"""Meetings M23–M31: Weeks 9–11 — experimental causal research (nb08),
share-the-research-and-attack-the-analysis (nb09), and poster criticism through
the terminal poster lock (nb10). Fridays are studios; the M31 lock is terminal
(poster submitted for printing by 5:00 PM, no revision). v2 rebuild — SRL fields
carried on the four Mon/Wed lectures; Gemini is the in-class AI, GenAI Studio
appears only at the M27 multi-model lesson and the M28 required-role reviews."""

MEETINGS_P3 = [
    # ------------------------------------------------------------------ M23
    {
        "meeting": 23, "date": "2026-10-19", "day": "Mon", "modality": "in-person",
        "unit": "Week 9 — Experimental causal research",
        "title": "Experimental causal research I: potential outcomes, random assignment, and what an experiment actually estimates",
        "driving_question": "If you could run the world twice — once with the treatment, once without — what would you compare, and why does randomizing let you fake that comparison?",
        "secondary_questions": "What are the potential outcomes Y(1) and Y(0), and why can you never see both for one unit? What exactly does random assignment buy you? What is an average treatment effect, and how does randomization inference put an interval around it? When is a study too small to detect the effect it is looking for?",
        "inquiry": "CAUSAL — causal kind (experimental design)",
        "srl_slot": "SRL slot 13 — rotation seat C",
        "srl_focus": "Puzzle: a get-out-the-vote canvass reached some households and not others, and the canvassed ones voted more — but what has to be true about WHO got canvassed before that gap is the effect of canvassing?",
        "claim_permitted": "\"Because assignment was randomized and I checked balance, the difference in means estimates the average treatment effect, reported with a randomization-inference interval.\"",
        "claim_not_permitted": "\"The treated group did better, so the treatment worked\" — with no check that assignment, not the kind of people in each group, produced the gap.",
        "rdss_reading": "RDSS ch. 18 'Experimental: causal' (book.declaredesign.org); declaration_18.1 (two-arm trial)",
        "cb_reading": "",
        "other_material": "nb08 student notebook (experimental causal research), §1–3 (Colab); Gemini in Colab as the in-class research partner",
        "provenance": "RDSS ch.18 + declaration_18.1.R + rdss foos_etal | experimental causal design | two-arm trial, difference-in-means, and randomization inference translated to the course's Python helpers | translated (R→Python)",
        "concepts": "potential outcomes Y(1)/Y(0) and the fundamental problem of causal inference; random assignment as the counterfactual-maker; treatment and control conditions; the average treatment effect (ATE); randomization inference; statistical power and the minimum detectable effect",
        "python_r_dependency": "numpy/pandas (difference-in-means + randomization-inference interval on foos_etal); matplotlib (the sharp-null reference distribution, provided)",
        "dataset_simulation": "foos_etal.csv (real get-out-the-vote field experiment) + inline seeded simulation of a two-arm trial for the power demonstration",
        "minute_dynamic": "0–9 SRL-led research puzzle: the lead stands the canvassing gap and presses the class — is this the effect of canvassing, or the effect of who happens to answer the door?; 9–31 guided Gemini research-partner investigation in the notebook: nb08 defines Y(1)/Y(0) on a toy world, then analyzes the real foos_etal experiment (balance check, difference in means, randomization-inference interval) with Gemini proposing each step and the class inspecting its output; 31–43 human verification + instructor formalization: recompute the interval against the helper, name the ATE the number estimates, and run the power / minimum-detectable-effect cell to see when a true effect would go undetected; 43–50 decision & defense: ledger entry (what Gemini proposed, how it was verified) + Claim Ticket.",
        "hands_on_activity": "Analyze a real randomized field experiment end to end — balance, ATE, randomization-inference interval — and read a power curve to find the smallest effect the design could have caught.",
        "practice": "📝 nb08 practice: for three described studies, write Y(1) and Y(0) for one unit and mark which is observed; then say whether each study is powered to detect a small, medium, or only a large effect.",
        "discussion_prompt": "You get a p-value below 0.05 from twelve participants. Why should a randomization-inference interval, not the p-value alone, decide whether you believe the effect?",
        "project_connection": "Every project that declared an experimental (or experiment-like) pathway begins its M8 minimum viable analysis here; projects on other pathways run the branch their declaration named.",
        "milestone_developed": "M8 — Minimum viable analysis",
        "milestone_work_time": "8 min (start your branch's first computed estimate)",
        "milestone_presentation_review": "none (lecture day)",
        "student_prep": "RDSS ch. 18 read; your declared analysis protocol (M7) at hand so you know which branch your M8 runs.",
        "student_artifact": "Analyzed foos_etal experiment + first computed estimate started on your own project's branch",
        "exit_ticket": "Claim Ticket #23: \"The number my M8 will report is an average treatment effect only because assignment was random — and here is the balance check that earns me the word.\"",
        "homework_next_milestone": "Finish nb08's potential-outcomes and power practice cells; Wednesday we take on what breaks a clean experiment — attrition, noncompliance, spillovers — and keep building M8.",
        "instructor_prep": "Verify foos_etal loads and the ATE + randomization-inference interval reproduce; pre-run the power cell so the curve renders fast; brief the SRL on the canvassing puzzle.",
        "risks_contingency": "Randomization inference feels abstract → the toy two-unit world grounds it first, and the helper does the resampling; students choose the outcome column and read the interval, they do not code the loop.",
    },
    # ------------------------------------------------------------------ M24
    {
        "meeting": 24, "date": "2026-10-21", "day": "Wed", "modality": "in-person",
        "unit": "Week 9 — Experimental causal research",
        "title": "Experimental causal research II: blocking, clusters, factorials, and the things that break a clean experiment",
        "driving_question": "Your randomization was perfect on paper — then a third of participants dropped out and neighbors talked to each other. What did you actually estimate?",
        "secondary_questions": "How do blocking and cluster randomization change what you can learn? What does a factorial design test at once? How do attrition, noncompliance, spillovers, and interference each bias or reinterpret the effect? When many outcomes are tested, why does at least one 'work' by chance — and what is a heterogeneous effect?",
        "inquiry": "CAUSAL — causal kind (experimental design, real-world threats)",
        "srl_slot": "SRL slot 14 — rotation seat D",
        "srl_focus": "Puzzle: the treatment 'worked' but a third of participants dropped out before the outcome was measured — what did we actually estimate, and for whom?",
        "claim_permitted": "\"After accounting for [attrition / noncompliance / clustering], my estimate is the effect for [this well-defined group], with its uncertainty and its limits stated.\"",
        "claim_not_permitted": "Reporting a clean average treatment effect while attrition, noncompliance, or spillovers silently changed which units and which quantity the number describes.",
        "rdss_reading": "RDSS ch. 18 'Experimental: causal' (continued — blocking, clustering, and the complications sections; book.declaredesign.org)",
        "cb_reading": "",
        "other_material": "nb08 student notebook (experimental causal research), §4–6 (Colab); Gemini in Colab as the applied-lab partner",
        "provenance": "RDSS ch.18 (blocking/cluster/factorial + attrition/noncompliance/spillover sections) + foos_etal | experimental causal complications | design variants and threat diagnostics translated to seeded Python simulations | translated (R→Python)",
        "concepts": "blocking; cluster randomization; factorial designs; attrition; noncompliance (and the local effect it leaves you); spillovers and interference; multiple-outcome testing; heterogeneous treatment effects; the ethical and practical limits of experimenting on people",
        "python_r_dependency": "numpy/pandas (seeded simulations of attrition and spillover on the two-arm world; subgroup estimates for heterogeneity)",
        "dataset_simulation": "foos_etal.csv (subgroup / heterogeneity reading) + inline seeded simulations that inject attrition, noncompliance, and spillover to show each threat's footprint",
        "minute_dynamic": "0–7 SRL-led retrieval & challenge: the lead replays yesterday's clean estimate, then breaks it — a third of units vanish before measurement — and challenges the class to say what the number now means; 7–30 intensive applied AI laboratory: in nb08, use Gemini to simulate blocking and clustering (does the interval tighten or widen?), run a factorial cell, then inject attrition, noncompliance, and spillover and watch the estimate move — inspecting and correcting every Gemini step; 30–42 peer defense + adversarial questioning: in pairs, each student defends 'my M8 estimate survives these threats because…' while the partner plays the spillover-and-attrition skeptic; 42–50 transfer to your own project + ledger + Claim Ticket.",
        "hands_on_activity": "Simulate blocking, clustering, and a factorial design, then inject attrition, noncompliance, and spillover into the same experiment and report how each one changes the effect you can honestly claim.",
        "practice": "📝 nb08 practice: match four broken experiments to the threat that broke them (attrition / noncompliance / spillover / multiple-outcome fishing); for one, name the group your surviving estimate actually describes.",
        "discussion_prompt": "A study reports the one outcome out of twenty that reached significance. What did the other nineteen tests do to that claim, and how would an honest report show them?",
        "project_connection": "M8 advances: each project names the single threat nearest its own design and states how the minimum viable analysis handles or bounds it.",
        "milestone_developed": "M8 — Minimum viable analysis",
        "milestone_work_time": "16 min (run your branch's estimate + name and bound its nearest threat)",
        "milestone_presentation_review": "peer defense rounds (adversarial pairs; the 60-second pitches come at this Friday's M8-due studio)",
        "student_prep": "RDSS ch. 18 complications sections read; Monday's foos_etal analysis at hand; M8 branch running.",
        "student_artifact": "Threat-injected simulations + own M8 estimate with its nearest threat named and bounded",
        "exit_ticket": "Claim Ticket #24: \"My M8's biggest threat is [attrition / noncompliance / spillover / multiplicity], and here is the group and quantity my estimate honestly describes once I account for it.\"",
        "homework_next_milestone": "Finish your minimum viable analysis; it is due at this Friday's studio, where you pitch it in 60 seconds and kick off the poster draft (M9).",
        "instructor_prep": "Verify the attrition/noncompliance/spillover simulation cells run in seconds; prep the adversarial-pair prompt cards; brief the SRL on the drop-out puzzle.",
        "risks_contingency": "The complication list overwhelms → the lab commits to attrition + spillover as the two everyone simulates; blocking, clustering, and factorial run as read-and-inspect demos, with nb08 carrying the depth.",
    },
    # ------------------------------------------------------------------ M25
    {
        "meeting": 25, "date": "2026-10-23", "day": "Fri", "modality": "in-person",
        "unit": "Week 9 — Experimental causal research",
        "title": "Studio Friday — minimum viable analysis due: first real evidence, and the poster draft begins",
        "driving_question": "You have your first computed estimate on your own question. Can you say what it shows, what it cannot, and pitch it in 60 seconds?",
        "secondary_questions": "What makes a minimum viable analysis 'viable' rather than final? What does the M9 poster draft + research audit ask of your compass position? Where does your poster's headline claim start?",
        "inquiry": "all positions (first computed evidence → communication)",
        "srl_slot": "",
        "srl_focus": "",
        "claim_permitted": "\"Here is my first real estimate, the check that makes me trust it, and the boundary my compass position puts on what it means.\"",
        "claim_not_permitted": "A pitch of a result with no verification and no stated limit — a number is not yet evidence until you have checked it and bounded it.",
        "rdss_reading": "(no new reading — studio Friday; bring your executed minimum viable analysis)",
        "cb_reading": "",
        "other_material": "nb08 student notebook (experimental causal) for the recap; M9 Brightspace brief (poster draft 1 + research audit); project/poster/storyboard_protocol.md (headline-claim preview); 60-second pitch timer",
        "provenance": "week's nb08 material + M9 Brightspace brief + project/poster/storyboard_protocol.md | studio Friday | 60-second evidence pitch + poster-draft kickoff | fresh",
        "concepts": "the minimum viable analysis as first honest evidence; verifying before believing your own output; the poster draft as the week ahead; the research audit that will attack it",
        "python_r_dependency": "none required (analysis helpers stay open for consults)",
        "dataset_simulation": "each student's own project data (M8 estimate)",
        "minute_dynamic": "0–6 research stand-up: each student's one-line status on their minimum viable analysis (what ran, what is shaky); 6–29 milestone kickoff + AI-supported sprint: present the M9 brief on Brightspace — poster draft 1 plus a research audit — then a supported sprint to finalize the M8 estimate and verify it, Gemini on call for the stubborn cell; 29–41 peer + AI red-team review: 60-second evidence pitches (my estimate, my check, my boundary) on a hard timer, peers and a Gemini skeptic each naming the one thing they do not yet believe; 41–50 revise, log the ledger, submit M8 tonight + Claim Ticket.",
        "hands_on_activity": "Deliver your 60-second evidence pitch with its verification and boundary, take the red-team's one hit, and submit your minimum viable analysis.",
        "practice": "📝 during consults: write the poster headline claim your M8 evidence could support today — ≤ 15 words, inside your compass position's boundary.",
        "discussion_prompt": "Which classmate's estimate did you most want to believe but could not yet — and what one check would have won you over?",
        "project_connection": "M8 submits tonight; every project leaves with a headline-claim seed and a locked plan for the M9 poster draft + research audit.",
        "milestone_developed": "M8 — Minimum viable analysis (due tonight) → M9 — Poster draft 1 and research audit (kickoff)",
        "milestone_work_time": "30 min studio block",
        "milestone_presentation_review": "M8 presented: 60-second evidence pitches with peer + AI red-team hits",
        "student_prep": "Minimum viable analysis executed (any state of polish); pitch rehearsed once; verification note ready.",
        "student_artifact": "Delivered pitch + red-team hit logged + submitted M8",
        "exit_ticket": "Claim Ticket #25: \"My poster's headline claim starts as [≤ 15 words], and my M8 evidence backs exactly that much — no more.\"",
        "homework_next_milestone": "Submit M8 tonight on Brightspace. Monday begins the attack on your own analysis — robustness and sensitivity before the poster; bring your estimate and your worst worry about it.",
        "instructor_prep": "Pitch timer; consult order; M9 brief staged on Brightspace; keep the analysis helpers loadable; storyboard preview ready.",
        "risks_contingency": "An analysis is not done → the pitch still happens on what runs (the submission deadline is tonight, not the pitch); overflow verification moves to office hours.",
    },
    # ------------------------------------------------------------------ M26
    {
        "meeting": 26, "date": "2026-10-26", "day": "Mon", "modality": "in-person",
        "unit": "Week 10 — Share the research and attack the analysis",
        "title": "Attack the analysis I: robustness, sensitivity, and the line between them and p-hacking",
        "driving_question": "If your result only holds one way of slicing the data, is it a finding — or an accident you went looking for?",
        "secondary_questions": "What is a robustness check versus a sensitivity check? What do placebo, falsification, and negative tests each try to break? How do alternative samples, measurements, specifications, and metrics stress a claim? What separates honest robustness from specification searching?",
        "inquiry": "all positions (attacking your own analysis)",
        "srl_slot": "SRL slot 15 — rotation seat E",
        "srl_focus": "Puzzle: our headline result is significant under one specification and vanishes under another — is the result fragile, or did we just find the one specification that worked?",
        "claim_permitted": "\"My claim survives these pre-listed robustness and placebo checks; where it moves, I report by how much and why.\"",
        "claim_not_permitted": "Reporting the one specification that 'worked' after quietly trying many, without disclosing the search — the definition of specification searching.",
        "rdss_reading": "(no new RDSS chapter — attack-the-analysis week; the readings are the robustness/red-team protocols and your own declared analysis protocol)",
        "cb_reading": "optional: callingbullshit.org — a 'the result vanished under reanalysis' case",
        "other_material": "nb09 student notebook (attack the analysis), §1–3 (Colab); Gemini in Colab as the robustness-lab partner; project/poster/redteam_review_protocol.md (the four-audit vocabulary, previewed)",
        "provenance": "fresh (robustness/sensitivity protocol) + course honest-analysis discipline | attack-the-analysis unit | placebo/falsification/negative tests + alternative-specification grid built as seeded Python cells | fresh",
        "concepts": "robustness vs sensitivity; placebo tests; falsification tests; negative tests; alternative samples, measurements, specifications, and metrics; outlier and influence analysis; robustness vs specification searching (the pre-listed-checks discipline)",
        "python_r_dependency": "numpy/pandas (rerun the estimate across a pre-listed robustness grid; leave-one-out influence cells); matplotlib (the specification curve, provided)",
        "dataset_simulation": "each student's own M8 estimate rerun under alternative specifications + a shared demonstration dataset with one influential outlier",
        "minute_dynamic": "0–9 SRL-led research puzzle: the lead shows one result that lives or dies by a single specification choice and asks the class to rule fragile vs cherry-picked; 9–31 guided Gemini research-partner investigation in the notebook: nb09 pre-lists the checks first, then reruns the estimate across alternative samples, measurements, specifications, and metrics, adds placebo and leave-one-out influence cells, and reads the specification curve — Gemini proposing checks, the class inspecting each; 31–43 human verification + instructor formalization: separate the checks that were pre-committed from the ones that would be fishing, and name the honest headline the surviving evidence supports; 43–50 decision & defense: ledger entry + Claim Ticket.",
        "hands_on_activity": "Pre-list your robustness checks, then rerun your own estimate across alternative specifications, run placebo and influence tests, and report where the claim holds and where it moves.",
        "practice": "📝 nb09 practice: label six analyses as robustness check or specification search; for the shared outlier dataset, find the one point whose removal flips the result.",
        "discussion_prompt": "You ran ten specifications and report the one that is significant. Write the sentence that turns that from p-hacking into honest robustness — what would you have had to do first?",
        "project_connection": "M9 poster draft + research audit begins: each project pre-lists its robustness checks and runs the first ones against its own M8 estimate.",
        "milestone_developed": "M9 — Poster draft 1 and research audit",
        "milestone_work_time": "10 min (pre-list your checks + run the first robustness rerun)",
        "milestone_presentation_review": "none (lecture day)",
        "student_prep": "M8 submitted; the estimate you most want to stress-test at hand.",
        "student_artifact": "Pre-listed robustness checks + first alternative-specification rerun of own estimate",
        "exit_ticket": "Claim Ticket #26: \"My result holds or moves under my pre-listed checks; the one that stresses it most is [check], and here is what it did.\"",
        "homework_next_milestone": "Run the rest of your pre-listed checks in nb09; Wednesday you turn AI reviewers loose on your own analysis and compare what they catch.",
        "instructor_prep": "Verify the robustness-grid and influence cells run fast; build the shared one-outlier dataset; brief the SRL on the fragile-specification puzzle.",
        "risks_contingency": "The specification grid balloons → students commit to three pre-listed checks maximum for class, the rest as homework; the pre-listing rule is the point, not the count.",
    },
    # ------------------------------------------------------------------ M27
    {
        "meeting": 27, "date": "2026-10-28", "day": "Wed", "modality": "in-person",
        "unit": "Week 10 — Share the research and attack the analysis",
        "title": "Attack the analysis II: human versus AI reviewers, and adversarial review of your own work",
        "driving_question": "When a human reviewer, one AI, and a panel of AIs read the same analysis, who catches what — and would you have caught it yourself?",
        "secondary_questions": "How does AI reviewer feedback differ from a peer's? What does a multi-model comparison reveal that a single model hides? How do you run an adversarial-reviewer role against your own analysis without letting it write your conclusions? Where do AI reviewers confidently mislead?",
        "inquiry": "all positions (adversarial review)",
        "srl_slot": "SRL slot 16 — rotation seat A",
        "srl_focus": "Puzzle: three AI reviewers named three different 'most serious flaws' in our analysis — which one is real, and how would we tell without just trusting the most confident one?",
        "claim_permitted": "\"I ran my analysis past a human reviewer and a multi-model AI panel, verified their hits against the data, and folded the real ones into my audit — with a note on what they got wrong.\"",
        "claim_not_permitted": "Accepting an AI reviewer's verdict as authority (or blaming it for a miss) — the reviewer proposes, you verify; a flaw is real only if the data show it.",
        "rdss_reading": "(no new RDSS chapter — attack-the-analysis week; the readings are the red-team protocol and your AI Research Ledger)",
        "cb_reading": "",
        "other_material": "nb09 student notebook (attack the analysis), §4–5 (Colab); Purdue GenAI Studio — the multi-model comparison + an adversarial-reviewer role (today's designated GenAI Studio touchpoint); AI Research Ledger template",
        "provenance": "fresh + GenAI Studio reviewer bench | attack-the-analysis unit | multi-model reviewer comparison + adversarial-reviewer role protocol | fresh",
        "concepts": "human vs AI reviewer feedback; multi-model comparison (agreement, disagreement, and confident error); the adversarial-reviewer role; verifying AI-flagged issues against the data; documenting AI review in the ledger",
        "python_r_dependency": "none new (GenAI Studio runs alongside; every flagged issue is re-checked in the student's own notebook)",
        "dataset_simulation": "each student's own analysis + its written summary, submitted to the reviewers",
        "minute_dynamic": "0–7 SRL-led retrieval & challenge: the lead recaps yesterday's honest-robustness line and challenges the class — can an AI reviewer tell robustness from p-hacking?; 7–30 intensive applied AI laboratory: in GenAI Studio, run your analysis summary through a single reviewer, then a multi-model panel, then an adversarial-reviewer role instructed to find its worst flaw — logging every hit and disagreement in the ledger; 30–42 peer defense + adversarial questioning: pair up, trade the AI panels' verdicts, and defend which flags are real (checked against your data) versus confident nonsense; 42–50 transfer to your project + ledger + Claim Ticket.",
        "hands_on_activity": "Run your own analysis through a human reviewer and a GenAI Studio multi-model panel plus an adversarial-reviewer role, then verify each flagged issue against your data and record which were real.",
        "practice": "📝 nb09 practice: given three AI reviewers' conflicting 'top flaws' on a sample analysis, design the one data check that would confirm or kill each.",
        "discussion_prompt": "An AI reviewer flagged a flaw your human reviewer missed — and invented one that is not there. What does that pattern tell you about how to use it?",
        "project_connection": "M9 research audit takes shape: each project's audit now carries verified human + multi-model AI review, with the real hits triaged and the false ones noted.",
        "milestone_developed": "M9 — Poster draft 1 and research audit",
        "milestone_work_time": "16 min (run the multi-model + adversarial review on your own analysis, log it)",
        "milestone_presentation_review": "peer defense rounds (real-vs-confident-nonsense triage; the studio pitches come at this Friday's M9-due studio)",
        "student_prep": "Robustness checks from Monday run; a one-paragraph written summary of your analysis ready to hand a reviewer.",
        "student_artifact": "Human + multi-model AI review logged in the ledger, each hit verified real or refuted",
        "exit_ticket": "Claim Ticket #27: \"The realest flaw any reviewer found in my analysis is [flaw]; I confirmed it with [check]; the most confident wrong flag was [x].\"",
        "homework_next_milestone": "Fold the verified hits into your poster draft and research audit; both are due at this Friday's studio, where you present the draft and log the required GenAI Studio Poster Critic and Robustness reviews.",
        "instructor_prep": "Confirm GenAI Studio access and that the adversarial-reviewer and multi-model roles are live; verify the RCAC endpoint; prep the conflicting-reviewers practice case; brief the SRL.",
        "risks_contingency": "GenAI Studio access fails → the multi-model comparison runs on provided saved transcripts of three models reviewing a sample analysis; the lesson (compare, then verify) survives without live access.",
    },
    # ------------------------------------------------------------------ M28
    {
        "meeting": 28, "date": "2026-10-30", "day": "Fri", "modality": "in-person",
        "unit": "Week 10 — Share the research and attack the analysis",
        "title": "Studio Friday — poster draft 1 and research audit due: your analysis, attacked and defended",
        "driving_question": "Your poster draft is on screen and your analysis has been audited. What survived the attack, and what did you change?",
        "secondary_questions": "What does a completed research audit contain? What do the GenAI Studio Poster Critic and Robustness reviewers add to it? What will next week's poster criticism demand of this draft?",
        "inquiry": "all positions (draft + audit)",
        "srl_slot": "",
        "srl_focus": "",
        "claim_permitted": "\"Here is my poster draft, the audit that stress-tested it, and the two things the AI critics changed my mind about — verified, not just accepted.\"",
        "claim_not_permitted": "Submitting a draft whose research audit is a formality — an audit with no hits either was not run honestly or was not run at all.",
        "rdss_reading": "(no new reading — studio Friday; bring your poster draft and your robustness results)",
        "cb_reading": "",
        "other_material": "nb09 student notebook (attack the analysis) for the recap; M10 Brightspace brief (final poster lock); Purdue GenAI Studio — REQUIRED Poster Critic + Robustness & Sensitivity Reviewer roles, logged in the ledger; project/poster/redteam_review_protocol.md (four-audit slip); AI Research Ledger template",
        "provenance": "week's nb09 material + M10 Brightspace brief + GenAI Studio reviewer bench + project/poster/redteam_review_protocol.md | studio Friday | poster-draft review + required-role AI audit + poster-lock kickoff | fresh",
        "concepts": "the research audit as a graded artifact; required GenAI Studio Poster Critic + Robustness reviews; verifying AI critique before acting on it; the four-audit peer red-team; the poster-criticism and lock week ahead",
        "python_r_dependency": "none required (robustness results carried from the week)",
        "dataset_simulation": "each student's own poster draft + audited analysis",
        "minute_dynamic": "0–6 research stand-up: each student's one-line status on their poster draft and audit; 6–29 milestone kickoff + AI-supported sprint: present the M10 brief on Brightspace — the final poster lock and the criticism week that leads to it — then a sprint where every student runs the REQUIRED GenAI Studio Poster Critic and Robustness & Sensitivity Reviewer roles against their own draft and logs both in the ledger; 29–41 peer + AI red-team review: trade drafts, apply the four-audit red-team slip (claim boundary, figure honesty, read path, uncertainty), and compare what the peer caught against what the AI roles caught; 41–50 revise, log the ledger, submit M9 tonight + Claim Ticket.",
        "hands_on_activity": "Run the required GenAI Studio Poster Critic and Robustness reviews on your own draft, log them, then red-team a peer's draft with the four-audit slip and submit your poster draft plus research audit.",
        "practice": "📝 during the sprint: for each required AI reviewer, write one hit you verified and acted on, and one you checked and rejected.",
        "discussion_prompt": "Where did the GenAI Studio Poster Critic and your human peer disagree about your draft — and whose hit did the data side with?",
        "project_connection": "M9 submits tonight; every project enters poster-criticism week with an audited draft and a documented, verified AI review trail.",
        "milestone_developed": "M9 — Poster draft 1 and research audit (due tonight) → M10 — Final poster lock (kickoff)",
        "milestone_work_time": "30 min studio block",
        "milestone_presentation_review": "M9 review: four-audit peer red-team + required GenAI Studio Poster Critic and Robustness reviews logged",
        "student_prep": "Poster draft built and on screen; robustness and AI-review results from the week at hand.",
        "student_artifact": "Submitted poster draft + research audit + logged GenAI Studio Poster Critic and Robustness reviews + one peer red-team slip",
        "exit_ticket": "Claim Ticket #28: \"The one change the required AI reviews made to my poster — and the check that convinced me it was right, not just confident.\"",
        "homework_next_milestone": "Submit M9 tonight on Brightspace. Monday begins poster criticism — bring your draft ready to be walked, questioned, and defended before the Friday lock.",
        "instructor_prep": "Confirm the GenAI Studio Poster Critic + Robustness roles are provisioned; print the four-audit red-team slips; M10 brief staged on Brightspace; consult order.",
        "risks_contingency": "GenAI Studio is down → the required reviews use each student's own draft run through saved role transcripts prepared in advance, and the live run is rescheduled to office hours; the ledger records the substitution.",
    },
    # ------------------------------------------------------------------ M29
    {
        "meeting": 29, "date": "2026-11-02", "day": "Mon", "modality": "in-person",
        "unit": "Week 11 — Poster criticism and final poster lock",
        "title": "Poster criticism I: the gallery walk — audit every poster's questions, claims, evidence, uncertainty, and accessibility",
        "driving_question": "Walking the room as a stranger would, does each poster's evidence actually earn its headline — and can everyone read it?",
        "secondary_questions": "What does a gallery-walk audit check: the research question, the claims, the evidence hierarchy, the visible uncertainty, the visual design, the accessibility? Where do posters most often overclaim or exclude a reader? How do AI-generated skeptic questions sharpen a human critique?",
        "inquiry": "all positions (poster criticism)",
        "srl_slot": "SRL slot 17 — rotation seat B",
        "srl_focus": "Puzzle: this poster's figure looks convincing from across the room, but does its impression match its number — and would a color-blind reader or a screen-reader user get the same message?",
        "claim_permitted": "\"On this poster, the headline is inside or outside its evidence, the uncertainty is visible or buried, and the design reaches or excludes these readers — here is the specific hit.\"",
        "claim_not_permitted": "A gallery-walk 'looks great' with no named hit — politeness is not a review, and a criticism round with no findings failed the poster, not spared it.",
        "rdss_reading": "Course book chapter 28 'Poster Criticism' — the gallery-walk audit plus accessibility; also project/poster/redteam_review_protocol.md (the four audits + accessibility) and the milestone_10 poster rubric",
        "cb_reading": "",
        "other_material": "nb10 student notebook (poster criticism and final lock), §1–2 (Colab); project/poster/redteam_review_protocol.md (four-audit + accessibility slip); the milestone_10 poster rubric (the five graded rows, incl. the AI Research Ledger); Gemini for AI-generated skeptic questions per poster",
        "provenance": "project/poster/redteam_review_protocol.md + milestone_10 poster rubric + fresh gallery-walk method | poster-criticism unit | four-audit + accessibility gallery walk with AI-generated skeptic prompts | fresh",
        "concepts": "the gallery-walk audit; the four audits (claim boundary, figure honesty, read path, uncertainty) plus visual design and accessibility; impression-versus-number; accessibility as a claim reaching every reader; AI-generated skeptic questions as a critique aid",
        "python_r_dependency": "none required (figure re-checks optional, matplotlib)",
        "dataset_simulation": "the class's own five poster drafts on display",
        "minute_dynamic": "0–9 SRL-led research puzzle: the lead opens with one poster's figure and presses the room — does the visual impression match the actual number, and who cannot read it?; 9–31 structured gallery walk (the investigation block): every poster on display, each student walks all five with the four-audit slip plus a visual-design and accessibility check, and pastes Gemini-generated skeptic questions beside each to sharpen the critique; 31–43 human verification + instructor formalization: the room consolidates the hits per poster, separating real evidence-and-access problems from stylistic quibbles and checking each AI-generated question against the poster; 43–50 decision & defense: ledger entry + Claim Ticket.",
        "hands_on_activity": "Run a full gallery-walk audit of all five posters — claims, evidence, uncertainty, visual design, accessibility — sharpened by AI-generated skeptic questions you verify against each poster.",
        "practice": "📝 nb10 practice: on a sample poster with planted flaws, catch at least one claim-boundary, one figure-honesty, and one accessibility problem; mark which AI-generated skeptic question would have surfaced each.",
        "discussion_prompt": "Which accessibility problem did the gallery walk catch that a fast reader never would — and how many strangers at the Expo would it have lost?",
        "project_connection": "M10 final poster lock advances: each project leaves with a consolidated list of audited hits and the AI-generated hard questions its poster must answer.",
        "milestone_developed": "M10 — Final poster lock",
        "milestone_work_time": "8 min (log the audited hits your own poster received)",
        "milestone_presentation_review": "gallery-walk audit (structured peer criticism of every poster)",
        "student_prep": "M9 poster draft on display; four-audit slip and rubric reviewed.",
        "student_artifact": "Completed gallery-walk audit slips given + the consolidated hit list for your own poster",
        "exit_ticket": "Claim Ticket #29: \"The gallery walk's most serious hit on my poster is [hit]; it threatens my claim boundary, uncertainty, or accessibility, and my fix is [x].\"",
        "homework_next_milestone": "Apply the gallery-walk hits to your poster; Wednesday you defend it out loud against interdisciplinary, methods, and skeptical-reviewer questions before Friday's lock.",
        "instructor_prep": "Mount all five drafts for the walk; print the four-audit + accessibility slips; verify the Gemini skeptic-question prompts produce usable output; brief the SRL on the impression-vs-number puzzle.",
        "risks_contingency": "A draft is not display-ready → that student audits others (the obligation stands) and posts their storyboard grid in its place for critique.",
    },
    # ------------------------------------------------------------------ M30
    {
        "meeting": 30, "date": "2026-11-04", "day": "Wed", "modality": "in-person",
        "unit": "Week 11 — Poster criticism and final poster lock",
        "title": "Poster criticism II: the oral defense — face interdisciplinary, methods, and skeptical-reviewer questions",
        "driving_question": "Standing at your poster, can you answer the outsider, the methodologist, and the skeptic — and concede gracefully where you must?",
        "secondary_questions": "How does an interdisciplinary question differ from a methods question or a skeptic's? What does a strong 'I don't know' contain? When do you defend and when do you concede? How does the oral defense expose gaps the written poster hid?",
        "inquiry": "all positions (oral poster defense)",
        "srl_slot": "SRL slot 18 — rotation seat C",
        "srl_focus": "Puzzle: a skeptic asks 'couldn't something else explain this?' and a methods reviewer asks 'why this specification?' — do they take the same answer, or do they need different defenses?",
        "claim_permitted": "\"Asked as an outsider, a methodologist, and a skeptic, I defended what my evidence licenses and conceded what it does not — on the record, at the poster.\"",
        "claim_not_permitted": "Bluffing an answer you do not have or upgrading the claim under pressure — the spoken defense must stay inside the poster's written boundary.",
        "rdss_reading": "Course book chapter 28 'Poster Criticism', the oral-defense section; also project/poster/redteam_review_protocol.md and a three-lens question deck for the interdisciplinary, methods, and skeptic lenses",
        "cb_reading": "",
        "other_material": "nb10 student notebook (poster criticism and final lock), §3 (Colab); project/poster/redteam_review_protocol.md; a three-lens question deck (interdisciplinary / methods / skeptic); Gemini for generating additional hard questions per poster",
        "provenance": "project/poster/redteam_review_protocol.md (oral-defense adaptation) + fresh three-lens question protocol | poster-criticism unit | oral defense rounds with interdisciplinary/methods/skeptic questioning | fresh",
        "concepts": "oral poster defense; interdisciplinary vs methods vs skeptical questions; the honest-don't-know formula; defend-versus-concede judgment; the spoken claim boundary",
        "python_r_dependency": "none required (defender may open the notebook if a number is probed)",
        "dataset_simulation": "each student's own poster (defended live)",
        "minute_dynamic": "0–7 SRL-led retrieval & challenge: the lead sorts three sample questions into interdisciplinary, methods, and skeptic, and challenges the class on which needs which kind of answer; 7–30 intensive oral-defense rounds: each presenter stands their poster for a timed round of questions drawn from all three lenses (peers, instructor, and Gemini-generated skeptic prompts), practicing the honest-don't-know formula; 30–42 peer defense + adversarial questioning: in pairs, drill the hardest unanswered question from each defense and rehearse the defend-or-concede call; 42–50 transfer to Friday's lock + ledger + Claim Ticket.",
        "hands_on_activity": "Defend your poster live against interdisciplinary, methods, and skeptical questions, then drill the hardest question each defense exposed and decide where to defend and where to concede.",
        "practice": "📝 nb10 practice: classify six audience questions by lens (interdisciplinary / methods / skeptic) and draft the honest-don't-know answer for the one you would least like to get.",
        "discussion_prompt": "Which classmate's concession made their project MORE credible, not less — and what exactly did they concede?",
        "project_connection": "M10 nears lock: every project has faced live questioning across three lenses and knows the exact claims it must soften before Friday.",
        "milestone_developed": "M10 — Final poster lock",
        "milestone_work_time": "16 min (revise the claims your oral defense exposed as too strong)",
        "milestone_presentation_review": "oral poster defense rounds (three-lens questioning)",
        "student_prep": "Gallery-walk hits applied; poster ready to stand and defend; question bank started.",
        "student_artifact": "Delivered oral defense + logged hardest questions + the list of claims to soften before the lock",
        "exit_ticket": "Claim Ticket #30: \"The question I could not fully answer today is [q]; before Friday's lock I will answer it or soften the claim it exposed.\"",
        "homework_next_milestone": "Make every claim-softening your defense exposed; Friday is the terminal production studio — arrive with a print-ready file, because the poster locks and goes for printing that day, with no revision after.",
        "instructor_prep": "Assemble the three-lens question deck per project; timer; verify the Gemini hard-question prompts; brief the SRL on the two-kinds-of-question puzzle.",
        "risks_contingency": "A defense stalls → the instructor steps in as question-asker-of-record, slows the cadence, and the presenter gets a second short round after watching a peer model a save.",
    },
    # ------------------------------------------------------------------ M31
    {
        "meeting": 31, "date": "2026-11-06", "day": "Fri", "modality": "in-person",
        "unit": "Week 11 — Poster criticism and final poster lock",
        "title": "Studio Friday — final production and poster lock: citations verified, claims traced, submitted for printing by 5:00 PM",
        "driving_question": "Is every claim on this poster one you can defend to a stranger at the Expo, every number traced to a cell, every source real — with no 'after' to fix it?",
        "secondary_questions": "Does every citation resolve to a real, retrievable source? Does every claim trace to its evidence and sit inside its boundary? Is the AI-use disclosure block complete? Is the file print-ready to URC spec?",
        "inquiry": "all positions (production and lock)",
        "srl_slot": "",
        "srl_focus": "",
        "claim_permitted": "\"Locked: every number traces to a notebook cell, every citation resolves to a real source, every claim sits inside its boundary, and the AI-use disclosure is on the record.\"",
        "claim_not_permitted": "\"I'll fix it after submission\" — there is no after; the poster is terminal and the Expo audience reads the submitted version.",
        "rdss_reading": "(no new reading — studio Friday; bring your print-ready poster file and your notebook, runnable)",
        "cb_reading": "",
        "other_material": "nb10 student notebook (poster criticism and final lock), §4 final checklist (Colab); project/poster/production_checklist.md; the milestone_10 poster rubric (self-score against the five graded rows); the course citation-verification discipline (every source retrieved and confirmed); URC poster spec + submission instructions on Brightspace",
        "provenance": "project/poster/production_checklist.md + milestone_10 poster rubric + course evidence-integrity discipline | studio Friday (terminal) | final production checklist + citation/claim/disclosure audit + poster lock | fresh",
        "concepts": "citation verification (every source real and retrievable); claim–evidence traceability (every number to a cell); the AI-use disclosure block; print-spec compliance; the terminal lock",
        "python_r_dependency": "none required (figure re-exports at print resolution as needed)",
        "dataset_simulation": "each student's own final poster + runnable notebook",
        "minute_dynamic": "0–6 research stand-up: each student's one-line readiness call (what is left before the file locks); 6–29 final production sprint: silent studio with rotating instructor checklist consults — print-spec, figure resolution, uncertainty visible, headline inside its boundary — while each student runs the citation-verification pass (every source retrieved and confirmed) and completes the AI-use disclosure block; 29–41 final-lock checklist audit pairs: partners trade posters and run three audits — citation verification, claim–evidence traceability (one number shown to its notebook cell), and disclosure-block completeness — initialing each; 41–50 lock, submit for printing, close the ledger + Claim Ticket. The deadline is today, 5:00 PM.",
        "hands_on_activity": "Run the final checklist, verify every citation resolves to a real source, trace one number to its cell under a partner's eyes, complete the AI-use disclosure, and submit the poster for printing.",
        "practice": "📝 (embedded in the checklist) verify: fonts ≥ minimum size at print scale; every figure carries its uncertainty or caveat; every citation opens to the source it names.",
        "discussion_prompt": "(brief, during consults) Which audit almost caught you — a citation that did not resolve, a number that did not trace, or a claim that outran its evidence?",
        "project_connection": "M10 final poster LOCKED and submitted for printing — the URC artifact is terminal; everything after this is delivery and depth (M11 kicks off Monday).",
        "milestone_developed": "M10 — Final poster lock (LOCKED + submitted for printing by 5:00 PM, terminal — no revision)",
        "milestone_work_time": "30 min studio block (production sprint + audit pairs)",
        "milestone_presentation_review": "instructor checklist consults + pair citation/claim/disclosure audit",
        "student_prep": "All oral-defense claim-softenings applied; print-ready file staged; notebook runnable.",
        "student_artifact": "Locked poster submitted for printing + signed production checklist + citation-verification + claim-traceability + disclosure audit",
        "exit_ticket": "Claim Ticket #31: \"One claim I softened before the lock, and why the softer version is the one I can defend at the Expo.\"",
        "homework_next_milestone": "Rest this weekend — the poster is locked. Monday begins poster delivery: the pitches, spoken uncertainty, and hard questions that turn this poster into a performance (M11).",
        "instructor_prep": "Confirm the printing/portal submission mechanics; consult-rotation timer; backup PDF-to-Brightspace plan; the M11 delivery brief staged for Monday.",
        "risks_contingency": "Printing or the portal fails → the PDF submitted to Brightspace timestamps the 5:00 PM deadline; physical printing resolves next week before the Expo. A citation will not resolve → the claim it supports is cut or re-sourced before the lock, never shipped unverified.",
    },
]
