"""Meetings M12–M22 (Sep 21 – Oct 16): rest of Phase 2 (measurement,
description deep dive) and Phase 3 (data & answer strategies, generalization)."""

MEETINGS_P2 = [
    # ------------------------------------------------------------------ M12
    {
        "meeting": 12, "date": "2026-09-21", "day": "Mon", "modality": "in-person",
        "unit": "Phase 2 — Literature, model, inquiry, measurement",
        "title": "Measurement II: error, and what bad measures do to good questions",
        "driving_question": "What happens to your answer when your measure is a little bit wrong?",
        "secondary_questions": "What do random vs systematic measurement error do differently? How do you argue a measure is good enough?",
        "inquiry": "description + generalization (measurement)",
        "claim_permitted": "\"With measurement error of the kind I simulated, my conclusion would move by roughly this much.\"",
        "claim_not_permitted": "\"My measure is imperfect, so nothing can be learned\" — or its twin, \"the measure is what it is, so ignore the error.\"",
        "rdss_reading": "RDSS ch. 8 measurement sections (continued)",
        "cb_reading": "",
        "other_material": "nb05 §3–4 (Colab)",
        "provenance": "RDSS ch.8 | measurement within data strategy | error simulation newly built on the concept | newly-constructed-from-source-concept",
        "concepts": "random vs systematic error; attenuation intuition; robustness of a claim to error; documenting measurement decisions",
        "python_r_dependency": "numpy (inject seeded noise/bias into a measure), matplotlib (before/after picture)",
        "dataset_simulation": "inline simulation: true construct + noisy indicator (seed 464); bonilla_tillery items for realism",
        "minute_dynamic": "0–5 ladder headlines from the weekend M04 drafts; 5–12 mini-lesson: two ways to be wrong (noise vs bias) with one picture each; 12–20 pause-and-predict: we add noise to the indicator — what happens to the observed group difference? commit; 20–33 hands-on: run the nb05 error simulation, compare to your prediction, then flip noise→bias and rerun; 33–45 studio: write the measurement-error paragraph of YOUR M04 plan (which error type threatens you, and how much would it take to change your story); 45–50 exit ticket.",
        "hands_on_activity": "Inject random then systematic error into a simulated indicator and watch what each does to the observed pattern.",
        "practice": "📝 nb05 practice: for each of 3 measures, predict whether its main threat is noise or bias, and defend the call.",
        "discussion_prompt": "Bias of just 2 points in one direction beat noise of 10 points in our simulation. Why does that asymmetry matter for your project?",
        "project_connection": "The measurement-error paragraph drafted today completes each student's M04 plan.",
        "milestone_developed": "M04 — Measurement & Operationalization Plan",
        "milestone_work_time": "12 min (error paragraph for own plan)",
        "milestone_presentation_review": "none (studio day)",
        "student_prep": "Full M04 draft from the weekend; nb05 §1–2 complete.",
        "student_artifact": "Executed error simulation + own measurement-error paragraph",
        "exit_ticket": "Claim Ticket #12: the error type that most threatens my measure, and one design move that would reduce it.",
        "homework_next_milestone": "Polish M04 (present Friday, submit Friday night). Read RDSS ch. 15 opener on descriptive designs for Wednesday.",
        "instructor_prep": "Verify both simulation cells run < 5s in Colab; queue the noise-vs-bias board picture.",
        "risks_contingency": "Simulation intuition doesn't land → rerun with exaggerated parameters (huge bias) so the effect is unmissable, then dial back.",
    },
    # ------------------------------------------------------------------ M13
    {
        "meeting": 13, "date": "2026-09-23", "day": "Wed", "modality": "in-person",
        "unit": "Phase 2 — Literature, model, inquiry, measurement",
        "title": "Description deep dive I: honest summaries of real data",
        "driving_question": "What is actually IN your data — and how do you summarize it without lying?",
        "secondary_questions": "Which summary fits which variable type? What do distributions show that averages hide? What is a descriptive inquiry, formally?",
        "inquiry": "DESCRIPTION — descriptive · data at hand (deep dive)",
        "claim_permitted": "\"In these 10,000 resampled LAPOP Brazil interviews, X% report Y; the distribution looks like Z.\"",
        "claim_not_permitted": "\"Brazilians believe Y\" (generalization) or \"Y because of Z\" (causation) — description stops at the data's edge.",
        "rdss_reading": "RDSS ch. 15 'Observational: descriptive' (book.declaredesign.org)",
        "cb_reading": "",
        "other_material": "nb06 §1–2 (Colab)",
        "provenance": "RDSS ch.15 + rdss lapop_brazil | observational descriptive designs | dataset shipped as CSV (MIT, attributed); 10k resample caveat taught | adapted",
        "concepts": "variable types; distributions; center + spread; group summaries; the descriptive claim boundary; the explore → declare → confirm loop (EDA anchor — an exploratory finding is not yet a confirmed claim); the lapop_brazil resampling caveat",
        "python_r_dependency": "pandas (describe, groupby), matplotlib (hist, bar)",
        "dataset_simulation": "lapop_brazil.csv (10,000-row resample — planning use only, taught as a provenance lesson)",
        "minute_dynamic": "0–5 M04 pulse + why description comes first on the compass; 5–12 mini-lesson: summaries as compressions that must not distort — one variable summarized three ways; 12–18 pause-and-predict: sketch the shape of the trust-in-government distribution before plotting; 18–33 hands-on: nb06 explore lapop_brazil — types, distributions, one group comparison — then name the loop just performed: explore → declare → confirm, and mark which findings are still exploratory; 33–41 claim clinic: write 3 descriptive claims from your output, then tighten each to exactly what the data permit; 41–47 project transfer: what would an honest descriptive table of YOUR future data contain?; 47–50 exit ticket.",
        "hands_on_activity": "Explore lapop_brazil: variable types, distributions, one honest group comparison — and state each result's claim.",
        "practice": "📝 nb06 practice: three flawed descriptive claims about lapop_brazil — repair each to what the data actually permit.",
        "discussion_prompt": "The file is a 10,000-row RESAMPLE of the real survey. What is it good for, and what would be dishonest to do with it?",
        "project_connection": "Each student drafts the skeleton of their project's future 'Table 1'.",
        "milestone_developed": "M04 → M05 — Data Strategy (transition)",
        "milestone_work_time": "6 min (own Table-1 skeleton)",
        "milestone_presentation_review": "none",
        "student_prep": "RDSS ch. 15 opener; M04 near-final (presents Friday).",
        "student_artifact": "Executed lapop_brazil exploration + 3 tightened descriptive claims",
        "exit_ticket": "Claim Ticket #13: my best descriptive claim from today's data, worded to stop exactly at the data's edge.",
        "homework_next_milestone": "Rehearse the 3-minute M04 walkthrough for Friday; finish nb06 §1–2.",
        "instructor_prep": "Confirm lapop_brazil.csv raw-URL load; pre-run the distribution shapes to anticipate the predict-then-plot reveals.",
        "risks_contingency": "Dataset load fails in class → nb06 carries an inline fallback sample (500 rows embedded) so every cell still runs.",
    },
    # ------------------------------------------------------------------ M14
    {
        "meeting": 14, "date": "2026-09-25", "day": "Fri", "modality": "in-person",
        "unit": "Phase 2 — Literature, model, inquiry, measurement",
        "title": "Description deep dive II: visualization that tells the truth — and the M04 walkthroughs",
        "driving_question": "When does a chart clarify, and when does it deceive?",
        "secondary_questions": "What are the classic distortions (truncated axes, cherry-picked bins, 3-D junk)? What makes a visualization defensible?",
        "inquiry": "DESCRIPTION — descriptive · data at hand (deep dive)",
        "claim_permitted": "\"This chart shows the pattern AND its context (scale, base, missing cases) — a reader could re-draw it from my description.\"",
        "claim_not_permitted": "A chart whose visual impression says more than the numbers do (the impression IS a claim, and it must be permitted too).",
        "rdss_reading": "RDSS ch. 15 (continued; descriptive design figures)",
        "cb_reading": "optional: callingbullshit.org — misleading axes / dataviz tools case",
        "other_material": "nb06 §3–4 (Colab)",
        "provenance": "RDSS ch.15 + fresh honest-viz checklist; optional CB public case | ch.15 | axis/bin distortion rebuilds | extended",
        "concepts": "honest visualization checklist; axis/bin/aspect distortions; same-data-two-stories; visualization as claim-making",
        "python_r_dependency": "matplotlib (two versions of the same chart)",
        "dataset_simulation": "lapop_brazil.csv (same variable, honest vs distorted renderings)",
        "minute_dynamic": "0–4 settle + walkthrough order; 4–10 mini-lesson: one dataset, two stories — the same lapop variable drawn honestly and deceptively; 10–20 hands-on: in nb06, un-distort a rigged chart (fix axis, bins, framing) and write what changed; 20–40 M04 WALKTHROUGHS: five 3-minute measurement-plan walkthroughs, listeners fill a two-line review (best rung / weakest rung); 40–47 revise plan from reviews; 47–50 exit ticket + M04 submission reminder.",
        "hands_on_activity": "Repair a deliberately distorted chart of lapop_brazil data and document each repair as a truth-telling decision.",
        "practice": "📝 nb06 practice: find (or recall) one real-world chart that overstates its data; name the distortion mechanism.",
        "discussion_prompt": "Is a technically-accurate but misleading chart a lie? Who is responsible — the maker or the reader?",
        "project_connection": "The honest-viz checklist becomes a standing rubric row for the poster (M10–M12).",
        "milestone_developed": "M04 — Measurement & Operationalization Plan (presented + submitted)",
        "milestone_work_time": "20 min (walkthroughs) + 7 min (revision)",
        "milestone_presentation_review": "M04 presented: 3-minute walkthrough + written two-line peer reviews",
        "student_prep": "M04 walkthrough rehearsed; nb06 §1–2 done.",
        "student_artifact": "Repaired chart + delivered walkthrough + revision notes",
        "exit_ticket": "Claim Ticket #14: one distortion I will actively avoid in my own project figures, and how.",
        "homework_next_milestone": "Submit M04 tonight 11:59 PM. Weekend read: RDSS ch. 8 'Crafting a data strategy' §sampling (8.1) — Monday we ask WHO gets into your data.",
        "instructor_prep": "Build the rigged chart variants; print two-line review slips; timer.",
        "risks_contingency": "Walkthroughs overrun → reviews go silent-written-only and the revision block moves to homework.",
    },
    # ------------------------------------------------------------------ M15
    {
        "meeting": 15, "date": "2026-09-28", "day": "Mon", "modality": "in-person",
        "unit": "Phase 3 — Data & answer strategies",
        "title": "Data strategy I (MIDA II): sampling — who gets into your data?",
        "driving_question": "Who is in your data, who is not, and who decided?",
        "secondary_questions": "What is a sampling procedure? What do random and convenience samples each license? What is selection, and why is it the quiet killer of claims?",
        "inquiry": "generalization (data strategy)",
        "claim_permitted": "\"My data strategy samples [units] by [procedure], so results speak to [population] with stated uncertainty.\"",
        "claim_not_permitted": "Convenience-sample results narrated as population facts (\"students in my dorm\" ≠ \"college students\").",
        "rdss_reading": "RDSS ch. 8 'Crafting a data strategy' §8.1 sampling (book.declaredesign.org); declaration_2.1",
        "cb_reading": "",
        "other_material": "nb07 §1–2 (Colab)",
        "provenance": "RDSS ch.8 §8.1 + declaration_2.1.R | sampling within data strategy | simple random sampling sim translated | translated (R→Python)",
        "concepts": "sampling procedures (simple random, convenience); sampling frame; selection; representativeness; D of MIDA begins",
        "python_r_dependency": "numpy/pandas (draw repeated samples from la_voter_file; compare to frame)",
        "dataset_simulation": "la_voter_file.csv (the frame) + seeded repeated sampling from it",
        "minute_dynamic": "0–5 weekend-reading pulse: what is a data strategy in one sentence?; 5–13 mini-lesson: the frame vs the sample vs the population, drawn as nested boxes; 13–20 pause-and-predict: 10 random samples of 100 voters — how much will their mean ages disagree? commit a range; 20–34 hands-on: nb07 draw the samples, plot the spread, then draw one CONVENIENCE sample (first 100 rows) and see the lie; 34–45 studio: draft the sampling paragraph of YOUR M05 data strategy (who, how, from what frame, who is missed); 45–50 exit ticket.",
        "hands_on_activity": "Draw repeated random samples vs one convenience sample from a real voter file and compare what each would have you believe.",
        "practice": "📝 nb07 practice: for 3 studies, name the frame, the sample, and the population each claim silently invokes.",
        "discussion_prompt": "Your project's most convenient sample — who exactly does it exclude, and does the exclusion correlate with your outcome?",
        "project_connection": "The sampling paragraph drafted today anchors M05 (Data Strategy + Feasibility & Ethics).",
        "milestone_developed": "M05 — Data Strategy + Feasibility & Ethics Checkpoint",
        "milestone_work_time": "11 min (own sampling paragraph)",
        "milestone_presentation_review": "none (studio day)",
        "student_prep": "RDSS ch. 8 §8.1 read; M04 submitted.",
        "student_artifact": "Sampling-spread plot + convenience-sample comparison + own sampling paragraph",
        "exit_ticket": "Claim Ticket #15: the population my project claims to speak about, and the frame I can actually reach.",
        "homework_next_milestone": "Read RDSS ch. 8 §assignment sections; Wednesday: who gets the treatment, and ethics.",
        "instructor_prep": "Verify la_voter_file.csv loads; pre-seed the sampling cells so the spread picture is reliably instructive.",
        "risks_contingency": "File too large/slow in Colab → nb07 subsamples on load (seeded) with the full-file path documented.",
    },
    # ------------------------------------------------------------------ M16
    {
        "meeting": 16, "date": "2026-09-30", "day": "Wed", "modality": "in-person",
        "unit": "Phase 3 — Data & answer strategies",
        "title": "Data strategy II: assignment, feasibility, and the ethics checkpoint",
        "driving_question": "If your design touches people, what do you owe them?",
        "secondary_questions": "What is treatment assignment (vs sampling)? What makes a design feasible for ONE undergraduate semester? What ethical review does student research need?",
        "inquiry": "causal + generalization (data strategy)",
        "claim_permitted": "\"My design is feasible by [date] with [resources], and its human-subjects footprint is [none / minimal-risk, handled by X].\"",
        "claim_not_permitted": "\"It's just a class project, so ethics review doesn't apply\" — or a design whose data cannot exist by November.",
        "rdss_reading": "RDSS ch. 8 §assignment sections (book.declaredesign.org)",
        "cb_reading": "",
        "other_material": "nb07 §3–4 (Colab); Purdue IRB student-research guidance (linked)",
        "provenance": "RDSS ch.8 §assignment + fresh feasibility/ethics checkpoint | ch.8 | assignment sim + honors-scale feasibility rubric | extended",
        "concepts": "random assignment vs random sampling (the two randomizations); feasibility triage; minimal risk; secondary data as the honors-scale default",
        "python_r_dependency": "numpy (complete random assignment demo)",
        "dataset_simulation": "inline 100-unit assignment simulation (seed 464)",
        "minute_dynamic": "0–5 recap duel: sampling vs assignment — two students each explain one, class spots the difference; 5–12 mini-lesson: the two randomizations do different jobs (who we SEE vs what they GET); 12–22 hands-on: nb07 assign treatment three ways (coin flips, complete, none) and check balance; 22–30 feasibility triage: score YOUR design on the 4-question feasibility rubric (data by when? skills? cost? consent?); 30–42 ethics checkpoint: walk the decision tree (secondary data / surveys / interventions) and write your project's ethics paragraph; 42–48 rotating consults: instructor visits each student while others finish M05 sections; 48–50 exit ticket.",
        "hands_on_activity": "Run three assignment procedures on the same 100 units and check covariate balance under each.",
        "practice": "📝 nb07 practice: two randomizations quiz — for 4 designs, which randomization (if either) is present, and what does it buy?",
        "discussion_prompt": "A classmate wants to test whether skipping breakfast hurts exam scores — on friends. Walk the ethics tree together: what changes the answer?",
        "project_connection": "Feasibility + ethics paragraphs complete the M05 draft; async M17 stress-tests it.",
        "milestone_developed": "M05 — Data Strategy + Feasibility & Ethics Checkpoint",
        "milestone_work_time": "20 min (feasibility triage + ethics paragraph + consults)",
        "milestone_presentation_review": "rotating instructor consults (5 × ~2 min)",
        "student_prep": "RDSS ch. 8 assignment sections; sampling paragraph from Monday.",
        "student_artifact": "Balance-check output + feasibility score + ethics paragraph",
        "exit_ticket": "Claim Ticket #16: my project's ethics classification and the one feasibility risk that most worries me.",
        "homework_next_milestone": "Friday is ASYNC (nb08): complete the misleading-claim diagnosis module by Sunday 11:59 PM. M05 full draft due with it.",
        "instructor_prep": "Update the IRB-guidance links; prepare the feasibility rubric; plan consult order.",
        "risks_contingency": "A project genuinely needs IRB review → escalate to office hours immediately and pre-plan the secondary-data pivot.",
    },
    # ------------------------------------------------------------------ M17
    {
        "meeting": 17, "date": "2026-10-02", "day": "Fri", "modality": "async-online",
        "unit": "Phase 3 — Data & answer strategies",
        "title": "ASYNC — Diagnose a misleading claim (and preview the answer strategy)",
        "driving_question": "A published claim crossed your feed. How do you take it apart — kindly, and with evidence?",
        "secondary_questions": "Where on the compass was the claim operating — what kind, what reach? What would the claim need to be true? What can still be learned from a flawed study?",
        "inquiry": "generalization (claim diagnosis)",
        "claim_permitted": "\"The claim as stated needs [design]; the study ran [design]; therefore what stands is the weaker claim X.\"",
        "claim_not_permitted": "Reflexive debunking (\"this study is trash\") with no statement of what evidence WOULD settle the question.",
        "rdss_reading": "RDSS ch. 9 'Choosing an answer strategy' — opening sections (preview for Monday)",
        "cb_reading": "optional: one callingbullshit.org case study of your choice (linked menu in nb08)",
        "other_material": "nb08 — fully self-contained async module (Colab)",
        "provenance": "brief §12 P3 + fresh claim-diagnosis protocol; optional CB public cases | async module | compass diagnosis worksheet | newly-constructed-from-source-concept",
        "concepts": "claim anatomy (claim/evidence/warrant); compass classification in the wild; charitable reconstruction; the diagnosis habit",
        "python_r_dependency": "pandas (one small recompute of the claim's own numbers)",
        "dataset_simulation": "embedded mini-table reproducing the case's published numbers",
        "minute_dynamic": "ASYNC (~50 min self-paced): 0–8 watch/read the case setup in nb08; 8–15 place the claim on the compass (kind + reach) and write the claim it NEEDED to make vs the claim it MADE; 15–30 recompute the case's central number from its own table, check the arithmetic and the framing; 30–42 write the structured diagnosis (what stands, what falls, what evidence would settle it); 42–50 answer-strategy preview cells + submit the module artifact.",
        "hands_on_activity": "Recompute a published claim's central number from its own data table; verify or correct it.",
        "practice": "📝 nb08 practice: classify 3 headlines by kind + reach and by the claim each would be permitted to make.",
        "discussion_prompt": "(async board post) Post your diagnosis's single most surprising line; reply to one classmate's with a steel-man.",
        "project_connection": "The diagnosis protocol practiced here is exactly what M08 will do to YOUR OWN design.",
        "milestone_developed": "M05 — Data Strategy (async development: full draft assembled)",
        "milestone_work_time": "module includes a 10-min M05 assembly block (sampling + assignment + feasibility + ethics into one document)",
        "milestone_presentation_review": "async board: one steel-man reply to a classmate's diagnosis",
        "student_prep": "nb07 complete; M05 sections drafted M15–M16.",
        "student_artifact": "Completed nb08 module: diagnosis memo + recompute cell + board post",
        "exit_ticket": "(embedded in module) Claim Ticket #17: the weaker-but-true claim the case study could honestly have made.",
        "homework_next_milestone": "Submit nb08 artifact + full M05 draft by Sunday 11:59 PM. Read RDSS ch. 9 opening for Monday.",
        "instructor_prep": "Final-check nb08 runs unattended end-to-end; seed the discussion board; confirm case links are live.",
        "risks_contingency": "Students stuck alone → nb08 embeds hints behind expandable cells + office-hours booking link; the board is monitored Friday afternoon.",
    },
    # ------------------------------------------------------------------ M18
    {
        "meeting": 18, "date": "2026-10-05", "day": "Mon", "modality": "in-person",
        "unit": "Phase 3 — Data & answer strategies",
        "title": "Answer strategy I (MIDA III): estimators — how data become an answer",
        "driving_question": "By what exact procedure will your data be turned into your answer?",
        "secondary_questions": "What is an estimator vs an estimate vs an estimand? Why is difference-in-means an answer strategy? What makes a strategy match an inquiry?",
        "inquiry": "generalization + causal (answer strategy)",
        "claim_permitted": "\"My answer strategy is [procedure]; applied to my data it yields [estimate] of my declared inquiry.\"",
        "claim_not_permitted": "Reporting a number with no named procedure behind it (\"the analysis shows…\" — WHICH analysis?).",
        "rdss_reading": "RDSS ch. 9 'Choosing an answer strategy' (book.declaredesign.org); declaration_9.1",
        "cb_reading": "",
        "other_material": "nb09 §1–2 (Colab); M05 feedback returned",
        "provenance": "RDSS ch.9 + declaration_9.1.R | choosing an answer strategy | estimator declaration translated | translated (R→Python)",
        "concepts": "estimand / estimator / estimate triad; difference-in-means; matching strategy to inquiry; A of MIDA begins; the answer strategy is the WHOLE procedure (RDSS §9.1.3 — exploration that influenced the choice is part of A)",
        "python_r_dependency": "numpy/pandas (hand-rolled difference-in-means on simulated data)",
        "dataset_simulation": "inline simulated experiment (seed 464) with known truth from the nb04 world",
        "minute_dynamic": "0–5 async-week debrief: best diagnosis lines read aloud; 5–13 mini-lesson: the triad (estimand/estimator/estimate) — the genie's number, the recipe, the dish; 13–20 pause-and-predict: our recipe on 500 simulated units — how close to the hidden truth will it land? commit; 20–34 hands-on: nb09 compute difference-in-means by hand-rolled pandas, unhide the nb04 truth, measure the miss; 34–44 M05 mini-presentations: each student states sampling + assignment in 90 seconds, class names the matching answer strategy (and whether any exploratory peeking must be declared inside it); 44–48 revise M05 from what you heard; 48–50 exit ticket.",
        "hands_on_activity": "Hand-roll difference-in-means on a simulated experiment, then reveal the true estimand and measure your estimator's miss.",
        "practice": "📝 nb09 practice: pair 4 inquiries with the answer strategy each demands; flag the one mismatch.",
        "discussion_prompt": "Two different estimators give two different answers on the same data. What does that mean — and what does it NOT mean?",
        "project_connection": "Each project names its candidate answer strategy — the last MIDA letter falls into place.",
        "milestone_developed": "M05 — Data Strategy (presented) → M06 — Answer Strategy Declaration",
        "milestone_work_time": "10 min (mini-presentations) + 4 min (revision)",
        "milestone_presentation_review": "M05 presented: 90-second data-strategy statements + class strategy-matching",
        "student_prep": "nb08 + M05 draft submitted Sunday; RDSS ch. 9 opening read.",
        "student_artifact": "Executed estimator cells + M05 revision notes + candidate answer strategy named",
        "exit_ticket": "Claim Ticket #18: my inquiry, my candidate answer strategy, and why they match — one sentence each.",
        "homework_next_milestone": "Finalize M05 (submit Wed Oct 7, 11:59 PM). Read RDSS ch. 9 regression sections.",
        "instructor_prep": "Grade nb08 diagnoses over the weekend; select the best lines; verify the truth-unhiding mechanic.",
        "risks_contingency": "The triad confuses → run the cooking analogy hard (recipe/dish/the-dish-the-genie-would-serve) and re-anchor each term to a cell in the notebook.",
    },
    # ------------------------------------------------------------------ M19
    {
        "meeting": 19, "date": "2026-10-07", "day": "Wed", "modality": "in-person",
        "unit": "Phase 3 — Data & answer strategies",
        "title": "Answer strategy II: regression as an estimator (not an oracle)",
        "driving_question": "What is regression actually doing for you — and what is it quietly assuming?",
        "secondary_questions": "How is regression 'difference-in-means with adjustment'? What do coefficients mean under a descriptive vs causal reading? What are robust standard errors, intuitively?",
        "inquiry": "generalization + causal (answer strategy)",
        "claim_permitted": "\"Adjusting for the variables I named, the association between X and Y is [estimate ± uncertainty].\"",
        "claim_not_permitted": "Reading a regression coefficient as a causal effect because covariates were 'controlled for.'",
        "rdss_reading": "RDSS ch. 9 regression/estimator sections (book.declaredesign.org)",
        "cb_reading": "",
        "other_material": "nb09 §3–4 (Colab); statsmodels docs (linked)",
        "provenance": "RDSS ch.9 (lm_robust workflow) | answer strategies | estimatr::lm_robust → statsmodels OLS + HC2 | translated (R→Python)",
        "concepts": "regression as adjusted comparison; coefficient readings by compass position; robust (HC2) standard errors; 'controlling for' ≠ identifying",
        "python_r_dependency": "statsmodels (OLS with HC2 robust SEs), pandas",
        "dataset_simulation": "lapop_brazil.csv (one adjusted association, descriptive reading)",
        "minute_dynamic": "0–5 M05 final-call + triad flash quiz; 5–13 mini-lesson: regression rebuilt from difference-in-means, one adjustment at a time on the board; 13–27 hands-on: nb09 fit the same model twice (classical vs robust SEs), read the coefficient aloud in DESCRIPTIVE language, then write the forbidden causal sentence and cross it out; 27–37 lab: sketch the regression YOUR project would run (outcome, key regressor, 2 honest covariates) in the M06 template; 37–46 peer check: partner reads your coefficient sentence — is it inside the claim boundary?; 46–50 exit ticket.",
        "hands_on_activity": "Fit an adjusted association in lapop_brazil, read it strictly descriptively, and physically cross out the causal overread.",
        "practice": "📝 nb09 practice: 4 coefficient sentences — mark each as permitted (descriptive), permitted (causal, IF identified), or forbidden.",
        "discussion_prompt": "'We controlled for everything we could think of.' Why is that sentence a confession, not a defense?",
        "project_connection": "Each project's M06 answer-strategy declaration takes concrete shape (model, estimator, uncertainty plan).",
        "milestone_developed": "M06 — Answer Strategy Declaration",
        "milestone_work_time": "10 min (own regression sketch in the M06 template)",
        "milestone_presentation_review": "peer boundary-check of the coefficient sentence",
        "student_prep": "M05 final due tonight 11:59 PM; RDSS ch. 9 regression sections read.",
        "student_artifact": "Twice-fit model output + crossed-out forbidden sentence + own M06 sketch",
        "exit_ticket": "Claim Ticket #19: my coefficient sentence, worded inside my compass position's boundary.",
        "homework_next_milestone": "Draft the URC abstract (150–250 words) using the abstract template — internal gate FRIDAY Oct 9. M06 continues Monday.",
        "instructor_prep": "Pre-fit the lapop model; prepare the board build-up from difference-in-means; abstract template posted.",
        "risks_contingency": "statsmodels output overwhelms → nb09 wraps the fit in a helper that prints only the three numbers that matter today.",
    },
    # ------------------------------------------------------------------ M20
    {
        "meeting": 20, "date": "2026-10-09", "day": "Fri", "modality": "in-person",
        "unit": "Phase 3 — Data & answer strategies",
        "title": "Generalization deep dive I: uncertainty — and the URC abstract gate",
        "driving_question": "How wrong could you be, and can you say so with a straight face?",
        "secondary_questions": "Where does sampling variability come from? What does a confidence interval actually promise? Why must the abstract already carry uncertainty language?",
        "inquiry": "GENERALIZATION — descriptive · population (deep dive)",
        "claim_permitted": "\"My estimate is X; under my design, estimates this far from truth happen rarely — here is the interval.\"",
        "claim_not_permitted": "A bare point estimate narrated as the truth (\"the effect IS 4.2\") — uncertainty deleted is certainty invented.",
        "rdss_reading": "RDSS ch. 9–10 uncertainty sections (book.declaredesign.org)",
        "cb_reading": "",
        "other_material": "nb10 §1–2 (Colab); URC abstract template",
        "provenance": "RDSS ch.9–10 | uncertainty via simulation | sampling-distribution sim built on the source concept | newly-constructed-from-source-concept",
        "concepts": "sampling distribution (by simulation); standard error; confidence interval as a procedure property; uncertainty-first writing",
        "python_r_dependency": "numpy (replicate the design 1,000×), matplotlib (sampling distribution)",
        "dataset_simulation": "seeded 1,000-replication simulation of each student's simplified design",
        "minute_dynamic": "0–5 abstract-gate roll call (drafts open on screens); 5–13 mini-lesson: run the SAME design 1,000 times — the histogram of answers IS your uncertainty; 13–20 pause-and-predict: will a sample of 400 halve the spread of a sample of 100? commit; 20–33 hands-on: nb10 replicate the design at n=100 vs n=400, compare spreads, extract the interval; 33–45 ABSTRACT WORKSHOP: apply the uncertainty-language checklist to your URC abstract, partner swap, final edits; 45–50 submit the abstract (internal gate) + exit ticket.",
        "hands_on_activity": "Replicate your simplified design 1,000 times at two sample sizes; watch uncertainty shrink by √n, not by wishing.",
        "practice": "📝 nb10 practice: rewrite 3 overcertain sentences into interval-bearing sentences without burying the finding.",
        "discussion_prompt": "A reader skims only your abstract. What single uncertainty phrase most protects them from over-believing you?",
        "project_connection": "URC abstract (M07 part 1) clears its internal gate today — the project is now publicly committed.",
        "milestone_developed": "M07 — URC Abstract (internal gate TODAY) + Full Design Declaration",
        "milestone_work_time": "12 min (abstract workshop) + submission",
        "milestone_presentation_review": "partner abstract swap with uncertainty-language checklist",
        "student_prep": "URC abstract drafted (Wednesday's homework); nb09 complete.",
        "student_artifact": "Submitted URC abstract + two-sample-size uncertainty comparison",
        "exit_ticket": "Claim Ticket #20: my headline finding-to-be, stated WITH its uncertainty, in ≤25 words.",
        "homework_next_milestone": "Fall break Monday — no class. For Wed Oct 14: RDSS ch. 10 'Diagnosing designs' opening; M06 declaration due Wed night.",
        "instructor_prep": "Abstract checklist copies; confirm the URC submission mechanics/deadline status (external date still TBD — internal gate binds today).",
        "risks_contingency": "External URC portal/deadline shifts → internal gate stands regardless; abstracts are submitted to Brightspace and forwarded when the portal opens.",
    },
    # ------------------------------------------------------------------ M21
    {
        "meeting": 21, "date": "2026-10-14", "day": "Wed", "modality": "in-person",
        "unit": "Phase 3 — Data & answer strategies",
        "title": "Generalization deep dive II: how far the answer reaches — and the association-is-not-causation boundary",
        "driving_question": "Your sample shows a pattern. To whom does it apply — and what may you NOT say about why?",
        "secondary_questions": "What breaks generalization (selection, attrition, non-response)? Why does adjusting not equal identifying? What does an honest inferential claim look like end-to-end?",
        "inquiry": "GENERALIZATION — descriptive · population (deep dive)",
        "claim_permitted": "\"In the population my frame reaches, X and Y are associated by [estimate ± interval], robust to [checks].\"",
        "claim_not_permitted": "The silent upgrade: association → 'link' → 'impact' → 'effect' across paragraphs — each word a claim your design didn't buy.",
        "rdss_reading": "RDSS ch. 15–16 (observational descriptive → causal boundary; book.declaredesign.org)",
        "cb_reading": "optional: callingbullshit.org 'correlation ≠ causation' case",
        "other_material": "nb10 §3–4 (Colab)",
        "provenance": "RDSS ch.15–16 + rdss lapop_brazil | observational designs | selection stress-test built fresh on the concept | extended",
        "concepts": "generalization threats; non-response; the language ladder of overclaiming; end-to-end inferential claim anatomy",
        "python_r_dependency": "pandas/numpy (simulate non-response biasing the lapop estimate)",
        "dataset_simulation": "lapop_brazil.csv + seeded non-response filter",
        "minute_dynamic": "0–5 fall-break re-entry + M06 status pulse; 5–12 mini-lesson: the language ladder of overclaiming, climbed on the board with a real headline; 12–19 pause-and-predict: delete the least-trusting 20% of respondents — which way does mean trust move? commit; 19–32 hands-on: nb10 apply the non-response filter, measure the bias, write the now-honest generalization sentence; 32–44 M06 clinic: apply the full claim-anatomy checklist to your own declaration, rotating instructor consults; 44–48 pair proof-read of each other's permitted/not-permitted lines; 48–50 exit ticket.",
        "hands_on_activity": "Simulate non-response in lapop_brazil and measure exactly how far it moves the estimate you would have reported.",
        "practice": "📝 nb10 practice: climb-down drill — take 3 overclaimed sentences down the ladder to what the design bought.",
        "discussion_prompt": "Find the exact sentence in a real abstract where association quietly became causation. What word did the smuggling?",
        "project_connection": "M06 declarations get their final clinic before tonight's deadline.",
        "milestone_developed": "M06 — Answer Strategy Declaration (submitted tonight)",
        "milestone_work_time": "12 min (M06 clinic with consults)",
        "milestone_presentation_review": "rotating instructor consults + pair proof-read",
        "student_prep": "M06 near-final; RDSS ch. 15–16 boundary sections skimmed.",
        "student_artifact": "Bias measurement + honest generalization sentence + final M06",
        "exit_ticket": "Claim Ticket #21: the word I am most tempted to smuggle into my claims, and its honest replacement.",
        "homework_next_milestone": "Submit M06 tonight 11:59 PM. Friday: assemble the FULL design declaration (M07 part 2) — bring all MIDA pieces.",
        "instructor_prep": "Real-headline ladder example; consult order; check M06 drafts midweek.",
        "risks_contingency": "Post-break fog → open with the 3-minute whole-course-so-far recap slide before the mini-lesson.",
    },
    # ------------------------------------------------------------------ M22
    {
        "meeting": 22, "date": "2026-10-16", "day": "Fri", "modality": "in-person",
        "unit": "Phase 3 — Data & answer strategies",
        "title": "Generalization deep dive III: power — and assembling the full design declaration",
        "driving_question": "Could your design even detect the thing you are looking for?",
        "secondary_questions": "What is statistical power, by simulation? What kills power (n, noise, effect size)? What does a complete MIDA declaration look like on one page?",
        "inquiry": "GENERALIZATION — descriptive · population (deep dive)",
        "claim_permitted": "\"At my n and plausible effect sizes, my design finds a real effect [P]% of the time — I checked before collecting data.\"",
        "claim_not_permitted": "\"We found nothing, so there is nothing\" from a design that could barely have found anything (absence of evidence, underpowered edition).",
        "rdss_reading": "RDSS ch. 10 'Diagnosing designs' §power (book.declaredesign.org); problem set 1 (concepts)",
        "cb_reading": "",
        "other_material": "nb10 §5 (Colab); M07 one-page declaration template",
        "provenance": "rdss-problem-set-1.Rmd + RDSS ch.10 | power analysis with design diagnosis | PS1 power simulation translated | translated (R→Python)",
        "concepts": "power by simulation; the power triangle (n, noise, effect); minimum detectable effect intuition; the one-page MIDA declaration",
        "python_r_dependency": "numpy (power simulation loop), matplotlib (power curve)",
        "dataset_simulation": "seeded power simulation over a grid of n and effect sizes",
        "minute_dynamic": "0–5 pop quiz: the four MIDA letters, each in five words; 5–12 mini-lesson: power as a batting average you compute BEFORE the season; 12–19 pause-and-predict: at n=50 and a small effect, how often does our design 'find it'? commit a percentage; 19–32 hands-on: nb10 run the power grid, find YOUR design's approximate power, locate the n that would double it; 32–45 DECLARATION ASSEMBLY: compile Model+Inquiry+Data+Answer into the one-page M07 declaration, rotating consults; 45–50 declarations submitted + exit ticket.",
        "hands_on_activity": "Run a power grid and locate your own design on it; find what change would most raise your power.",
        "practice": "📝 nb10 practice: rank 4 design tweaks by how much each raises power, then verify by simulation.",
        "discussion_prompt": "Your power is 30%. Is running the study anyway unethical, merely risky, or defensible with the right framing?",
        "project_connection": "M07 (full design declaration) submits today — the complete MIDA blueprint every later milestone builds on.",
        "milestone_developed": "M07 — Full Design Declaration (submitted TODAY)",
        "milestone_work_time": "13 min (assembly + consults)",
        "milestone_presentation_review": "rotating instructor consults during assembly",
        "student_prep": "All MIDA pieces (M03–M06) at hand; RDSS ch. 10 §power skimmed.",
        "student_artifact": "Power-grid location for own design + submitted one-page M07 declaration",
        "exit_ticket": "Claim Ticket #22: my design's approximate power and the single change that would raise it most.",
        "homework_next_milestone": "Weekend: rest — the declaration is in. Monday begins the diagnosis engine (RDSS ch. 10 in full).",
        "instructor_prep": "Verify power-grid cells run <30s; print declaration templates; consult order.",
        "risks_contingency": "Power simulation too slow live → pre-computed grid ships in the notebook, students interpolate their design instead of re-running.",
    },
]
