"""Meetings M1–M11: Phase 1 (curiosity → question) and Phase 2 (compass,
sources, model & measurement); Fridays are studios."""

MEETINGS_P1 = [
    # ------------------------------------------------------------------ M1
    {
        "meeting": 1, "date": "2026-08-24", "day": "Mon", "modality": "in-person",
        "unit": "Phase 1 — Curiosity, gaps, answerable questions",
        "title": "Launchpad: How do we know? Course map, Colab, and the Ask → Verify → Document policy",
        "driving_question": "How do we come to know something well enough to defend it?",
        "secondary_questions": "What will you build this semester? What does the AI policy require of every deliverable? How does a lecture-plus-studio seminar week work?",
        "inquiry": "all positions (framing)",
        "claim_permitted": "\"I can state what evidence WOULD be needed to support a claim\" — the course's opening move.",
        "claim_not_permitted": "Any empirical claim without a stated evidence base — including claims an AI tool produced.",
        "rdss_reading": "RDSS ch. 1 (Preface) + ch. 2 'What is a research design?' — skim before Wednesday (book.declaredesign.org)",
        "cb_reading": "",
        "other_material": "nb00 (Colab); course website; syllabus; Brightspace orientation",
        "provenance": "brief §3 + RDSS ch.2 | course framing | MIDA overview (concept only) | newly-constructed-from-source-concept",
        "concepts": "evidence-driven research; the inquiry compass (preview); MIDA (preview); Ask → Verify → Document; claim ledger; the weekly rhythm (lectures + Friday studio)",
        "python_r_dependency": "Colab basics only (run a cell, save a copy)",
        "dataset_simulation": "none (one toy claim-check cell)",
        "minute_dynamic": "0–5 welcome + names + one-line curiosities; 5–13 the course promise: from curiosity to a defensible claim (map on board, including the Friday-studio rhythm); 13–20 live demo: an AI tool fabricates a citation, we catch it (Ask → Verify → Document); 20–35 hands-on: open nb00 in Colab, run the readiness cells, save a copy to Drive; 35–45 pair task: swap one claim you believe and name the evidence behind it; 45–50 M00 kickoff brief + Claim Ticket exit.",
        "hands_on_activity": "Open nb00 in Colab, run all readiness cells, and catch the planted fabricated citation using the verification checklist.",
        "practice": "📝 nb00 practice: classify three everyday claims by the evidence that would be needed to support each.",
        "discussion_prompt": "What is something you believed that turned out to be wrong — and what evidence changed your mind?",
        "project_connection": "The semester project starts today: every student leaves with the M00 Curiosity Map assignment.",
        "milestone_developed": "M00 — Kickoff: Curiosity Map + tool readiness",
        "milestone_work_time": "5 min (M00 brief + first curiosity jotting)",
        "milestone_presentation_review": "none (kickoff)",
        "student_prep": "Bring a laptop; be able to log into Google (Colab) and Brightspace.",
        "student_artifact": "Executed nb00 readiness cells + first Claim Ticket",
        "exit_ticket": "Claim Ticket #1: one claim you encountered this week + what evidence would be needed to defend it.",
        "homework_next_milestone": "Start M00 (Curiosity Map: 3 curiosities + tool readiness screenshot) — due at this Friday's studio, where you will pitch one curiosity in 30 seconds.",
        "instructor_prep": "Verify Colab loads nb00 from the public repo; test the planted-citation demo; print/roster the 5 students.",
        "risks_contingency": "Colab/account issues → pair students on one laptop and finish readiness at home; keep the demo offline-safe (screenshots of the AI output as backup).",
    },
    # ------------------------------------------------------------------ M2
    {
        "meeting": 2, "date": "2026-08-26", "day": "Wed", "modality": "in-person",
        "unit": "Phase 1 — Curiosity, gaps, answerable questions",
        "title": "From curiosity to a topic, and the gap worth filling",
        "driving_question": "What makes a curiosity worth a semester of your life, and where is the hole in what is known?",
        "secondary_questions": "How do researchers move from 'interesting' to 'studyable'? What is the difference between a topic and a question? What kinds of gaps exist (evidence, population, measurement, method, contradiction)?",
        "inquiry": "all positions (framing)",
        "claim_permitted": "\"Based on the sources I examined, X has not been established for population/context Y\" — a bounded gap claim.",
        "claim_not_permitted": "\"Nothing is known about my topic.\" (An absolute absence claim you cannot verify.)",
        "rdss_reading": "RDSS ch. 2 'What is a research design?' + ch. 3 'Research design principles' (book.declaredesign.org)",
        "cb_reading": "",
        "other_material": "nb01 §1–3 (Colab)",
        "provenance": "RDSS ch.2–3 + fresh gap typology | research designs + design principles | funnel and gap typology for honors non-quant audience | extended",
        "concepts": "curiosity vs topic vs question; studyability; the curiosity → topic → question funnel; gap typology: evidence, population, measurement, method, contradiction gaps; bounded vs absolute absence claims",
        "python_r_dependency": "none beyond running markdown/code cells",
        "dataset_simulation": "none (five mini-abstract cards for gap matching)",
        "minute_dynamic": "0–5 Claim Ticket callbacks (two volunteers read theirs); 5–14 mini-lesson: the curiosity → topic → question funnel, with one worked path narrated start to finish; 14–22 hands-on: in nb01, write your curiosity, narrow it to a topic, and draft a first candidate question; 22–30 mini-lesson: the five gap types with real examples; 30–40 hands-on: match five mini-abstracts to the gap type each leaves open, then draft two candidate bounded gap claims for your own topic; 40–47 pairs exchange one 'so what?' challenge and one gap-type check; 47–50 exit ticket + reminder that M00 pitches happen at this Friday's studio.",
        "hands_on_activity": "Run your curiosity through the nb01 funnel (curiosity → topic → first question), then match five mini-abstracts to gap types and draft two bounded gap claims for your own topic.",
        "practice": "📝 nb01 practice: sort 6 given statements into curiosity / topic / question; then match 5 mini-abstracts to the gap type each leaves open.",
        "discussion_prompt": "When is 'nobody has studied this' a good sign, and when is it a warning sign?",
        "project_connection": "The funnel and the candidate gaps drafted today become the spine of the M00 pitch and the M01 research-question work.",
        "milestone_developed": "M00 — Kickoff: Curiosity Map + tool readiness (dev)",
        "milestone_work_time": "13 min (funnel + candidate gap claims on own project)",
        "milestone_presentation_review": "none (pitches at this Friday's studio)",
        "student_prep": "M00 in progress (Curiosity Map draft started); RDSS ch. 1–2 skimmed; laptop ready.",
        "student_artifact": "Funnel cells + two candidate bounded gap claims in nb01",
        "exit_ticket": "Claim Ticket #2: my strongest curiosity, restated as a topic, plus my best candidate gap in one bounded sentence.",
        "homework_next_milestone": "Finish M00 (Curiosity Map: 3 curiosities + tool readiness screenshot) and rehearse the 30-second curiosity pitch for this Friday's studio.",
        "instructor_prep": "Prepare 5 mini-abstract cards for the gap matching; queue the worked funnel example; review any M00 drafts that arrive early.",
        "risks_contingency": "A student has no viable curiosity → offer the curated fallback-topic menu (in the instructor notebook) and schedule an office-hours consult.",
    },
    # ------------------------------------------------------------------ M3
    {
        "meeting": 3, "date": "2026-08-28", "day": "Fri", "modality": "in-person",
        "unit": "Phase 1 — Curiosity, gaps, answerable questions",
        "title": "Studio Friday — Curiosity pitches: M00 due, M01 kickoff",
        "driving_question": "Can you pitch your curiosity in 30 seconds and leave with a research-question plan?",
        "secondary_questions": "What does a compelling curiosity pitch sound like? What does the M01 brief ask for, and how will it be graded?",
        "inquiry": "all positions (studio)",
        "claim_permitted": "\"My curiosity narrows to topic T, and the gap I suspect is G\" — the M00 pitch claim.",
        "claim_not_permitted": "\"My topic matters, so any question about it is a research question.\" (Topics are not questions.)",
        "rdss_reading": "(no new reading — studio Friday; bring your M00 Curiosity Map and pitch)",
        "cb_reading": "",
        "other_material": "nb01 student notebook (curiosity → question) — recap reference (Colab); M01 Brightspace brief",
        "provenance": "course design (studio format) | weekly Friday studio | recap + milestone brief + supervised work | newly-constructed-from-source-concept",
        "concepts": "pitching a curiosity; warm feedback norms; the M01 deliverable (gap → problem → question); supervised project work",
        "python_r_dependency": "none new (own milestone work)",
        "dataset_simulation": "student's own project materials",
        "minute_dynamic": "0–10 recap: the curiosity → topic → gap funnel in one pass; 10–20 milestone brief (Brightspace): present M01 deliverable + rubric; 20–50 studio work: 30-second curiosity pitches with one strength + one question each, then supervised M01 start (turn your best gap into a problem statement) with rotating consults.",
        "hands_on_activity": "Deliver the 30-second M00 curiosity pitch, then start M01: draft the problem statement your best gap points to.",
        "practice": "📝 studio log: record one decision you made about your project today and the reason behind it.",
        "discussion_prompt": "Whose 30-second pitch would you fund, and what single question would you ask them first?",
        "project_connection": "M00 closes today; the problem statement drafted in the work block opens the M01 pipeline.",
        "milestone_developed": "M00 — Kickoff: Curiosity Map + tool readiness (presented + due); M01 — Research Question Pitch (kickoff)",
        "milestone_work_time": "30 min studio block",
        "milestone_presentation_review": "M00 presented: 30-second curiosity pitch, whole-class warm feedback (one strength + one question each)",
        "student_prep": "M00 complete; 30-second pitch rehearsed; laptop ready.",
        "student_artifact": "Delivered pitch + a first M01 problem-statement draft",
        "exit_ticket": "Claim Ticket #3: my gap, restated as a problem statement, in one sentence.",
        "homework_next_milestone": "Submit M00 tonight (11:59 PM). Weekend: skim RDSS ch. 4; turn your best gap into one written problem statement (bring Monday).",
        "instructor_prep": "Queue the pitch order; warm-feedback norms poster; M01 Brightspace brief on screen; consult rotation list.",
        "risks_contingency": "Pitches run long → cap feedback at one strength each and pass remaining questions as written notes; protect the supervised work block.",
    },
    # ------------------------------------------------------------------ M4
    {
        "meeting": 4, "date": "2026-08-31", "day": "Mon", "modality": "in-person",
        "unit": "Phase 1 — Curiosity, gaps, answerable questions",
        "title": "From problem to an answerable question",
        "driving_question": "What separates a question evidence can answer from one it cannot?",
        "secondary_questions": "What are the marks of answerability (defined units, defined comparison, observable outcomes, bounded scope)? How specific is too specific?",
        "inquiry": "all positions (framing)",
        "claim_permitted": "\"My question names its units, outcome, comparison, and scope — evidence could in principle answer it.\"",
        "claim_not_permitted": "\"Is X good or bad?\" posed as a research question (a values question is not answerable by evidence alone).",
        "rdss_reading": "RDSS ch. 4 'Getting started' (book.declaredesign.org)",
        "cb_reading": "",
        "other_material": "nb01 §4 answerability rubric (Colab)",
        "provenance": "RDSS ch.4 + fresh answerability rubric | getting started | question-formulation guidance | extended",
        "concepts": "answerability: units, outcomes, comparisons, scope; empirical vs normative questions; question quality rubric",
        "python_r_dependency": "none (rubric applied in markdown cells)",
        "dataset_simulation": "none",
        "minute_dynamic": "0–5 problem statements read-around (from weekend homework); 5–13 mini-lesson: the answerability rubric, with one question upgraded live; 13–28 hands-on: run 4 sample questions through the rubric in nb01, then your own; 28–38 peer clinic: partner scores your question on the rubric, you defend or revise; 38–47 project work: finalize the question wording for your M01 pitch; 47–50 exit ticket.",
        "hands_on_activity": "Score 4 sample questions + your own on the answerability rubric in nb01; rewrite yours until it passes.",
        "practice": "📝 nb01 practice: rewrite 3 unanswerable questions (one normative, one boundless, one unit-free) into answerable form.",
        "discussion_prompt": "Which is the worse failure — a question too broad to answer, or one so narrow the answer is trivial?",
        "project_connection": "The question finalized today is the centerpiece of this Friday's M01 pitch.",
        "milestone_developed": "M01 — Research Question Pitch (dev)",
        "milestone_work_time": "9 min (finalize own question wording)",
        "milestone_presentation_review": "peer clinic: partner rubric-scores your question",
        "student_prep": "Bring your written problem statement (weekend homework); RDSS ch. 4 skimmed.",
        "student_artifact": "Rubric-scored, revised research question in nb01",
        "exit_ticket": "Claim Ticket #4: my question, final wording, + the rubric criterion it is still weakest on.",
        "homework_next_milestone": "Draft the full M01 pitch (gap → problem → question, 2 minutes); pitch day is this Friday's studio. Skim the opening of RDSS ch. 7 before Wednesday.",
        "instructor_prep": "Select 4 sample questions spanning the rubric failure modes; prep the live-upgrade example.",
        "risks_contingency": "Questions converge on unmeasurable outcomes → pull the measurement-preview card forward from nb05 and flag it as coming attractions.",
    },
    # ------------------------------------------------------------------ M5
    {
        "meeting": 5, "date": "2026-09-02", "day": "Wed", "modality": "in-person",
        "unit": "Phase 2 — Compass, sources, model & measurement",
        "title": "The inquiry compass: kind (descriptive vs causal) × reach (data, population, unseen)",
        "driving_question": "What kind of answer does your question actually ask for?",
        "secondary_questions": "What can a description establish, and where does it stop? What licenses a claim about a population beyond the data? Why does predicting well not require understanding? Why does 'what if we intervened?' demand different evidence entirely?",
        "inquiry": "all four compass positions (the compass skill)",
        "claim_permitted": "Description: \"in these data, X.\" Generalization: \"in the population my frame reaches, plausibly X, with stated uncertainty.\" Prediction: \"for new cases, expect Ŷ, judged against a baseline.\" Causal: \"the intervention changes Y under a stated identification argument.\"",
        "claim_not_permitted": "Treating a pattern in the data at hand as if it automatically holds beyond the sample, or as if it were causal; \"the model predicts well, so X causes Y.\"",
        "rdss_reading": "RDSS ch. 7 'Defining the inquiry' (descriptive vs causal inquiries) + Part III opener (design library; book.declaredesign.org)",
        "cb_reading": "optional: callingbullshit.org 'Criminal machine learning' case study (prediction ≠ understanding)",
        "other_material": "nb02 §1–4 (Colab)",
        "provenance": "RDSS ch.7 + Part III framing | descriptive vs causal inquiries | classification recast as the compass skill (kind × reach); prediction column built fresh | extended",
        "concepts": "the compass: kind (descriptive vs causal) × reach (data at hand / population / unseen); four named positions: description, generalization, prediction, causal reasoning; baseline; counterfactuals (first exposure); identification (first exposure); claim boundaries",
        "python_r_dependency": "pandas (read a CSV, value_counts, mean) — first real code",
        "dataset_simulation": "lapop_brazil.csv (first look: one variable, sample vs population framing)",
        "minute_dynamic": "0–4 pitch-prep pulse check + one Claim Ticket callback; 4–16 mini-lesson: the compass, kind (descriptive vs causal) × reach (data at hand / population / unseen), and its four named positions with one example each; 16–28 hands-on: in nb02 compute one honest descriptive summary of lapop_brazil, write the exact claim it permits, then write the population claim that would OVERREACH it; 28–40 classification drill: sort question cards across the whole compass, naming the giveaway word in each; 40–46 project transfer: classify YOUR question by kind and reach and note the classification in your pitch draft; 46–50 exit ticket.",
        "hands_on_activity": "Compute a descriptive summary of one lapop_brazil variable, write the exact claim it permits, and drill the whole compass on question cards.",
        "practice": "📝 nb02 practice: for 8 question cards, name the kind + reach AND the claim that would overreach each.",
        "discussion_prompt": "Why is 'most people in this survey…' a different claim from 'most Brazilians…', and what would license the second?",
        "project_connection": "First-pass compass classification of each student's own M01 question, noted in the pitch draft.",
        "milestone_developed": "M01 — Research Question Pitch (compass candidate added)",
        "milestone_work_time": "6 min (classify own question by kind + reach; note it in the pitch draft)",
        "milestone_presentation_review": "none (drill + prep day; pitches at this Friday's studio)",
        "student_prep": "M01 pitch drafted; RDSS ch. 7 opening skimmed; laptop ready for first real pandas work.",
        "student_artifact": "One executed descriptive summary + own question classified by kind and reach in nb02",
        "exit_ticket": "Claim Ticket #5: my question is (for now) a ___ inquiry reaching ___, because the answer it wants is ___.",
        "homework_next_milestone": "Rehearse the 2-minute M01 pitch for this Friday's studio; finish any nb02 cells not completed in class.",
        "instructor_prep": "Print question cards spanning all four compass positions; verify lapop_brazil.csv loads from the repo raw URL in Colab; queue the optional CB case link.",
        "risks_contingency": "pandas friction dominates → shrink the hands-on to the provided one-liner cells and let the card drill carry the concept; unfinished cells complete as homework.",
    },
    # ------------------------------------------------------------------ M6
    {
        "meeting": 6, "date": "2026-09-04", "day": "Fri", "modality": "in-person",
        "unit": "Phase 2 — Compass, sources, model & measurement",
        "title": "Studio Friday — Question pitches: M01 due, M02 kickoff",
        "driving_question": "Can you pitch your research question in 2 minutes and defend its compass position?",
        "secondary_questions": "What makes a pitch land? What does the M02 brief ask for (verified sources + claim map), and how will it be graded?",
        "inquiry": "all four compass positions (studio)",
        "claim_permitted": "\"My question is Q, filling gap G, and the compass position it wants is P\" — the M01 pitch claim.",
        "claim_not_permitted": "A pitch whose compass position no listener can identify (if the class cannot place it, the question is not yet scoped).",
        "rdss_reading": "(no new reading — studio Friday; bring your rehearsed M01 pitch)",
        "cb_reading": "",
        "other_material": "nb02 student notebook (the inquiry compass) — recap reference (Colab); M02 Brightspace brief",
        "provenance": "course design (studio format) | weekly Friday studio | recap + milestone brief + pitch session | newly-constructed-from-source-concept",
        "concepts": "pitch delivery; compass-vote as structured peer review; the M02 deliverable (verified source ledger + claim map)",
        "python_r_dependency": "none new (own milestone work)",
        "dataset_simulation": "student's own project materials",
        "minute_dynamic": "0–10 recap: the compass (kind × reach) and its four positions in one pass; 10–20 milestone brief (Brightspace): present M02 deliverable + rubric; 20–50 studio work: 2-minute M01 pitches, each followed by a class compass-vote plus one named risk, then post-pitch self-revision notes with rotating consults.",
        "hands_on_activity": "Deliver the 2-minute M01 pitch; after each classmate's pitch, vote the compass position the question wants and name one risk.",
        "practice": "📝 studio log: record the compass position the class voted for your question and one revision you will make in response.",
        "discussion_prompt": "Which pitch today had the clearest compass position, and what wording made it so easy to place?",
        "project_connection": "Every project leaves with a class-voted compass hypothesis to test against the coming units; the source ledger assigned today feeds M02.",
        "milestone_developed": "M01 — Research Question Pitch (presented + due); M02 — Literature & Claim Map (kickoff)",
        "milestone_work_time": "30 min studio block",
        "milestone_presentation_review": "M01 presented: 2-minute pitch + structured class compass-vote and risk feedback",
        "student_prep": "2-minute M01 pitch rehearsed; nb02 cells complete.",
        "student_artifact": "Delivered pitch + annotated revision notes",
        "exit_ticket": "Claim Ticket #6: the compass position my classmates voted for my question, and whether I agree (one reason).",
        "homework_next_milestone": "Submit M01 (pitch notes + question + gap + compass position) tonight (11:59 PM). Weekend: read RDSS ch. 4 on situating a design in a literature; confirm your Purdue Libraries login works before Wednesday.",
        "instructor_prep": "Timer + pitch rubric sheets; compass-vote cards; M02 Brightspace brief on screen; consult rotation list.",
        "risks_contingency": "Pitches run long → cap responses at the compass vote plus one written risk passed to the presenter; protect the self-revision minutes.",
    },
    # ------------------------------------------------------------------ M7
    {
        "meeting": 7, "date": "2026-09-09", "day": "Wed", "modality": "in-person",
        "unit": "Phase 2 — Compass, sources, model & measurement",
        "title": "Sources with integrity: search, verify, and map what a field actually claims",
        "driving_question": "How do you find what is actually known, verify it is real, and draw the argument of a literature?",
        "secondary_questions": "Where do scholarly claims live (journals, working papers, reports, data)? Why must every citation be retrieved and checked before it is used? How do you extract a source's central claim and place your gap on the map?",
        "inquiry": "description + generalization (appraising and mapping evidence claims)",
        "claim_permitted": "\"Source S exists, I retrieved it, and it claims X on the basis of evidence E.\"",
        "claim_not_permitted": "Citing any source you have not personally retrieved and checked — however plausible an AI summary of it sounds.",
        "rdss_reading": "RDSS ch. 4 'Getting started' (situating a design in a literature; book.declaredesign.org)",
        "cb_reading": "",
        "other_material": "nb03 §1–4 (Colab); Purdue Libraries database portal; Google Scholar",
        "provenance": "fresh (AI-era source verification + claim-map method) + RDSS ch.4 | getting started | retrieval-verification loop + claim-map builder | newly-constructed-from-source-concept",
        "concepts": "source types + hierarchy; search strings; snowballing; the retrieval-verification loop (every citation retrieved and checked); source ledger; claim extraction; evidence typing (descriptive/inferential/predictive/causal); agreement/contradiction edges; gap placement",
        "python_r_dependency": "provided networkx cell (fill a claims table; the graph draws itself)",
        "dataset_simulation": "none (student-retrieved real sources; own source ledger)",
        "minute_dynamic": "0–5 M01 feedback headlines returned; 5–14 mini-lesson: where claims live + the retrieval-verification loop (retrieve it, confirm it exists, log how you checked); 14–28 hands-on: run one AI-assisted search and one database search for YOUR question, retrieve the sources they surface, verify each is real, and log citation, retrieval point, and central claim in the nb03 source ledger; 28–38 mini-lesson: from ledger to claim map, one worked example (claims, evidence types, agreement/contradiction edges, gap placement); 38–47 project work: start your claims table and place a provisional gap on the map; 47–50 exit ticket.",
        "hands_on_activity": "Run paired AI-assisted and database searches for your own question, verify that every source you keep is real and retrievable, and log each in the source ledger with its central claim.",
        "practice": "📝 nb03 practice: turn your research question into two search strings — one for a database, one for an AI tool — and predict how their failure modes will differ.",
        "discussion_prompt": "An AI summary cites a perfect-sounding study you cannot find. What are the three possible explanations, and what do you do next?",
        "project_connection": "The verified source ledger and claims table started today are the backbone of M02 (Literature & Claim Map), due at this Friday's studio.",
        "milestone_developed": "M02 — Literature & Claim Map (dev)",
        "milestone_work_time": "23 min (own-question searches + ledger + claims table)",
        "milestone_presentation_review": "none (gallery walk at this Friday's studio)",
        "student_prep": "M01 submitted; Purdue Libraries login working; laptop ready.",
        "student_artifact": "Source ledger with ≥2 verified entries + a started claims table in nb03",
        "exit_ticket": "Claim Ticket #7: one verified source for my question — full citation + where I retrieved it.",
        "homework_next_milestone": "Grow the source ledger to ≥6 verified sources, note each source's central claim, and build the claim map with your gap placed; M02 presents at this Friday's studio.",
        "instructor_prep": "Verify library portal access from a student view; queue the worked claim-map example; test the networkx graph cell in Colab.",
        "risks_contingency": "Library portal outage → Google Scholar + open-access fallbacks are pre-listed in nb03; thin in-class search results → snowball from one seed source and finish the ledger as homework.",
    },
    # ------------------------------------------------------------------ M8
    {
        "meeting": 8, "date": "2026-09-11", "day": "Fri", "modality": "in-person",
        "unit": "Phase 2 — Compass, sources, model & measurement",
        "title": "Studio Friday — Claim-map gallery: M02 due, M03 kickoff",
        "driving_question": "Does your claim map survive a room full of readers, and is the gap you placed real?",
        "secondary_questions": "What does disagreement between sources look like on a map? What does the M03 brief ask for (model + inquiry declaration), and how will it be graded?",
        "inquiry": "description + generalization (studio)",
        "claim_permitted": "\"Across my verified sources, claims cluster as A vs B, and none address C — my gap.\"",
        "claim_not_permitted": "\"The literature proves…\" (a map of claims is not itself proof, and unread sources count for nothing).",
        "rdss_reading": "(no new reading — studio Friday; bring your finished claim map)",
        "cb_reading": "",
        "other_material": "nb03 student notebook (sources + claim map) — recap reference (Colab); M03 Brightspace brief",
        "provenance": "course design (studio format) | weekly Friday studio | recap + milestone brief + gallery walk | newly-constructed-from-source-concept",
        "concepts": "gallery-walk peer review; sticky-note challenges; incorporating criticism; the M03 deliverable (model + inquiry declaration)",
        "python_r_dependency": "none new (own milestone work)",
        "dataset_simulation": "student's own project materials (verified source ledgers)",
        "minute_dynamic": "0–10 recap: the retrieval-verification loop and the claim map in one pass; 10–20 milestone brief (Brightspace): present M03 deliverable + rubric; 20–50 studio work: claim-map gallery walk with sticky-note peer challenges, incorporate one challenge on the spot, then supervised M03 start (sketch your project's world) with rotating consults.",
        "hands_on_activity": "Walk the gallery: challenge two classmates' maps with sticky-note questions, then defend or revise your own gap placement.",
        "practice": "📝 studio log: record the sticky-note challenge you incorporated and what changed on your map because of it.",
        "discussion_prompt": "On your neighbor's map: is the gap they placed real, or does one of their own sources already cover it?",
        "project_connection": "M02 closes today; the world-sketch from the work block seeds the M03 Model & Inquiry Declaration.",
        "milestone_developed": "M02 — Literature & Claim Map (presented + due); M03 — Model & Inquiry Declaration (kickoff)",
        "milestone_work_time": "30 min studio block",
        "milestone_presentation_review": "M02 presented: gallery walk with sticky-note peer challenges",
        "student_prep": "Claim map built from ≥6 verified sources; ledger up to date; laptop ready.",
        "student_artifact": "Claim map with placed gap + one incorporated revision",
        "exit_ticket": "Claim Ticket #8: the strongest claim in my map that argues AGAINST my project's premise.",
        "homework_next_milestone": "Submit M02 tonight (11:59 PM). Weekend: read the opening of RDSS ch. 6 'Specifying the model'; Monday we build worlds.",
        "instructor_prep": "Sticky notes; screens arranged for the gallery; M03 Brightspace brief on screen; midweek ledger-check notes in hand.",
        "risks_contingency": "Ledgers too thin for maps → pair students to co-map the stronger ledger; the thin-ledger student owes the gap placement and finishes their own map over the weekend.",
    },
    # ------------------------------------------------------------------ M9
    {
        "meeting": 9, "date": "2026-09-14", "day": "Mon", "modality": "in-person",
        "unit": "Phase 2 — Compass, sources, model & measurement",
        "title": "Model & Inquiry (MIDA I): the world your question lives in, and the exact quantity you seek",
        "driving_question": "What must the world be like for your question to have an answer — and if a genie handed you the truth, what NUMBER or PATTERN would it hand you?",
        "secondary_questions": "What is a model in the MIDA sense? What are potential outcomes, and how does a DAG say 'I believe X could affect Y'? What is an inquiry/estimand, and why must it be defined before data arrive?",
        "inquiry": "causal + generalization (model-building and estimand thinking)",
        "claim_permitted": "\"Under my stated model of the world, my inquiry is [quantity], defined over [units] — stated before seeing outcome data.\"",
        "claim_not_permitted": "Choosing the quantity AFTER browsing results (inquiry shopping), or any claim that smuggles in a model you never stated.",
        "rdss_reading": "RDSS ch. 6 'Specifying the model' + ch. 7 'Defining the inquiry' (book.declaredesign.org); declaration_7.1",
        "cb_reading": "",
        "other_material": "nb04 §1–4 (Colab); make_dag_df utility (translated)",
        "provenance": "RDSS ch.6–7 + declaration_7.1.R + utilities/make_dag_df.R | specifying the model + defining the inquiry | potential outcomes, DAG helper, inquiry declaration pattern | translated (R→Python)",
        "concepts": "MIDA: Model + Inquiry; possible worlds; potential outcomes Y(1), Y(0); DAG nodes/edges; the genie test; inquiry/estimand; ATE vs share vs difference; inquiry precedes data; EDA upstream as model calibration (preview)",
        "python_r_dependency": "numpy (simulate a tiny world), networkx (draw a 3-node DAG), pandas (compute the true estimand)",
        "dataset_simulation": "inline simulated world (seeded, 100 units, one cause one outcome; true ATE computed then hidden)",
        "minute_dynamic": "0–5 weekend-reading pulse + one M02 map highlight; 5–15 mini-lesson: a model is a claim about how the world could be (potential outcomes on the board with a 4-unit toy, the fundamental problem named); 15–24 mini-lesson: the genie test (inquiry as the quantity the genie would hand you, descriptive and causal versions, declared before data arrive); 24–36 hands-on: in nb04 simulate a 100-unit world, reveal only one potential outcome per unit, then compute the TRUE inquiry value and hide it (it becomes the answer key for later units); 36–46 project lab: draw YOUR project's 3-node DAG (cause, outcome, one lurking third variable) and write your inquiry in one sentence; 46–50 pair swap: challenge one arrow in your partner's DAG + exit ticket.",
        "hands_on_activity": "Simulate a world with both potential outcomes, reveal only one per unit, then compute the true estimand in a world you control and hide it as the future answer key.",
        "practice": "📝 nb04 practice: for 3 scenarios, write the potential-outcomes pair the question implicitly compares; for 2 more, write the inquiry in words AND as a formula over potential outcomes or population values.",
        "discussion_prompt": "Your DAG has an arrow your partner's doesn't. What evidence, even in principle, could settle whose world is closer to true?",
        "project_connection": "Each project leaves with a first DAG and a one-sentence inquiry — the two halves of the M03 declaration.",
        "milestone_developed": "M03 — Model & Inquiry Declaration (dev)",
        "milestone_work_time": "10 min (own-project DAG + inquiry sentence)",
        "milestone_presentation_review": "pair DAG challenge",
        "student_prep": "RDSS ch. 6 opening skimmed; M02 feedback reviewed.",
        "student_artifact": "Executed potential-outcomes simulation + own-project DAG + one-sentence inquiry",
        "exit_ticket": "Claim Ticket #9: my inquiry in ONE sentence a non-researcher could repeat back.",
        "homework_next_milestone": "Refine your DAG with one more node if the world demands it; read RDSS ch. 8 measurement sections before Wednesday; start drafting the 3-minute M03 declaration for this Friday's studio.",
        "instructor_prep": "Board-ready 4-unit potential-outcomes table; test the networkx DAG cell and the hidden-estimand cell mechanics in Colab.",
        "risks_contingency": "Potential outcomes land abstract → fall back to the concrete scholarship-letter example scripted in the instructor notebook and re-run the toy table with numbers the class suggests.",
    },
    # ------------------------------------------------------------------ M10
    {
        "meeting": 10, "date": "2026-09-16", "day": "Wed", "modality": "in-person",
        "unit": "Phase 2 — Compass, sources, model & measurement",
        "title": "Measurement & operationalization: from concept to indicator, and what error does to answers",
        "driving_question": "How does an abstract idea become a number without losing its soul — and what happens when the number is a little bit wrong?",
        "secondary_questions": "What are concept, construct, indicator? What are validity and reliability, intuitively? What do random vs systematic measurement error do differently to a conclusion?",
        "inquiry": "description + generalization (measurement)",
        "claim_permitted": "\"Indicator I measures construct C for concept X, the mapping is defensible, and error of the kind I simulated would move my conclusion by roughly this much.\"",
        "claim_not_permitted": "\"My variable measures happiness\" (naming a column after a concept does not make it the concept) — and its twin, \"my measure is imperfect, so nothing can be learned.\"",
        "rdss_reading": "RDSS ch. 8 'Crafting a data strategy' — measurement sections (book.declaredesign.org)",
        "cb_reading": "",
        "other_material": "nb05 §1–4 (Colab)",
        "provenance": "RDSS ch.8 + fresh concept→construct→indicator ladder | measurement within data strategy | ladder framing + error simulation built on the concept | extended",
        "concepts": "concept → construct → indicator ladder; validity; reliability; operationalization; random vs systematic error; attenuation intuition; robustness of a claim to error; measurement inside D of MIDA",
        "python_r_dependency": "pandas (inspect real survey items), numpy (inject seeded noise/bias), matplotlib (before/after picture)",
        "dataset_simulation": "bonilla_tillery.csv (survey items as measurement examples) + inline error simulation (seed 464)",
        "minute_dynamic": "0–5 M03 declaration pulse + inquiry restated from memory (spot check); 5–14 mini-lesson: the ladder, climbed twice (trust in government, food insecurity), with validity and reliability named on each rung; 14–24 hands-on: open bonilla_tillery items in nb05 and rate which construct each item is reaching for; 24–34 hands-on: two ways to be wrong (noise vs bias): predict what added noise does to an observed group difference, run the nb05 error simulation, compare, then flip noise to bias and rerun; 34–45 project lab: climb the ladder for YOUR key concept (2 candidate indicators) and note which error type threatens you most; 45–50 exit ticket.",
        "hands_on_activity": "Rate real survey items on construct reach, then inject random and systematic error into a simulated indicator and watch what each does to the observed pattern.",
        "practice": "📝 nb05 practice: propose two DIFFERENT indicators for the same construct and state what each would miss; for each, call whether its main threat is noise or bias.",
        "discussion_prompt": "Give an example where a measure is highly reliable and badly invalid. Why is that combination so dangerous?",
        "project_connection": "The ladder and error-threat note drafted today seed the M04 plan, which kicks off at this Friday's studio.",
        "milestone_developed": "M03 — Model & Inquiry Declaration (dev); M04 — Measurement & Operationalization Plan (seeded)",
        "milestone_work_time": "11 min (own-concept ladder + error-threat note)",
        "milestone_presentation_review": "none (declarations at this Friday's studio)",
        "student_prep": "RDSS ch. 8 measurement sections skimmed; M03 declaration drafting underway.",
        "student_artifact": "Rated item set + executed error simulation + own-concept ladder draft with 2 candidate indicators",
        "exit_ticket": "Claim Ticket #10: my key concept, my best indicator, the biggest thing it misses, and the error type that most threatens it.",
        "homework_next_milestone": "Finalize and rehearse the 3-minute M03 declaration (world, DAG, genie quantity) for this Friday's studio; finish nb05 cells.",
        "instructor_prep": "Select 4 bonilla_tillery items for the rating task; verify both simulation cells run under 5 seconds in Colab; queue the noise-vs-bias board picture.",
        "risks_contingency": "Simulation intuition doesn't land → rerun with exaggerated parameters (huge bias) so the effect is unmissable, then dial back; concepts too abstract to ladder → climb the shared fallback concept (student stress) collectively.",
    },
    # ------------------------------------------------------------------ M11
    {
        "meeting": 11, "date": "2026-09-18", "day": "Fri", "modality": "in-person",
        "unit": "Phase 2 — Compass, sources, model & measurement",
        "title": "Studio Friday — Model & Inquiry declarations: M03 due, M04 kickoff",
        "driving_question": "Can you declare your world, your DAG, and your genie quantity in 3 minutes — and take a question on each?",
        "secondary_questions": "What makes a declaration clear enough to challenge? What does the M04 brief ask for (measurement & operationalization plan), and how will it be graded?",
        "inquiry": "causal + generalization (studio)",
        "claim_permitted": "\"My world is W, my DAG asserts A, and my inquiry is [quantity] — declared before data.\"",
        "claim_not_permitted": "A declaration whose inquiry no listener can restate (if the class cannot repeat the quantity back, it is not yet declared).",
        "rdss_reading": "(no new reading — studio Friday; bring your rehearsed M03 declaration)",
        "cb_reading": "",
        "other_material": "nb04 student notebook (model & inquiry) + nb05 student notebook (measurement) — recap reference (Colab); M04 Brightspace brief",
        "provenance": "course design (studio format) | weekly Friday studio | recap + milestone brief + declaration session | newly-constructed-from-source-concept",
        "concepts": "declaring in public; clarifying questions as peer review; the M04 deliverable (concept, construct, ≥2 indicators, validity threats, error paragraph)",
        "python_r_dependency": "none new (own milestone work)",
        "dataset_simulation": "student's own project materials",
        "minute_dynamic": "0–10 recap: the M-I half of MIDA (world, potential outcomes, DAG, genie quantity) and the measurement ladder in one pass; 10–20 milestone brief (Brightspace): present M04 deliverable + rubric; 20–50 studio work: 3-minute M03 declarations with one clarifying question per listener, quick revision notes, then supervised M04 start (ladder + error paragraph for your key concept) with rotating consults.",
        "hands_on_activity": "Deliver the 3-minute M03 declaration (world, DAG, genie quantity), collect one clarifying question per listener, then start the M04 ladder for your own key concept.",
        "practice": "📝 studio log: record the clarifying question that stung most and how your declaration will change because of it.",
        "discussion_prompt": "Which declaration today could you repeat back word for word, and what made it so repeatable?",
        "project_connection": "M03 closes today; the ladder work in the studio block opens the M04 measurement plan.",
        "milestone_developed": "M03 — Model & Inquiry Declaration (presented + due); M04 — Measurement & Operationalization Plan (kickoff)",
        "milestone_work_time": "30 min studio block",
        "milestone_presentation_review": "M03 presented: 3-minute declaration + one clarifying question per listener",
        "student_prep": "3-minute M03 declaration rehearsed; nb04 and nb05 cells complete.",
        "student_artifact": "Delivered declaration + revision notes + a started M04 ladder",
        "exit_ticket": "Claim Ticket #11: my inquiry, restated after feedback, in one sentence a non-researcher could repeat back.",
        "homework_next_milestone": "Submit M03 tonight (11:59 PM). Weekend: draft the full M04 plan (concept, construct, ≥2 indicators, validity threats, error paragraph); next week the description deep dive begins.",
        "instructor_prep": "Timer; declaration order; clarifying-question norms card; M04 Brightspace brief on screen; consult rotation list.",
        "risks_contingency": "Declarations exceed time → move the final declaration to the top of the work block and protect the M04 start; questions drift into debate → enforce the one-clarifying-question norm.",
    },
]
