"""Meetings M23–M31: Weeks 9–11 — the D41 studio-first arc. Week 9 = Studio 8
stress-test and adjudicate (nb09, M8 robustness audit); Week 10 = Studio 9
write, bound, and disclose (nb10, M9 bounded research-note v0); Week 11 =
Studio 10 poster adaptation + the two blocking release gates — author
self-reproduction and the release preflight — through the terminal M10 lock
(nb11; poster submitted for printing by 5:00 PM Fri Nov 6, no revision).
Fridays are quiz-first studios. SRL slots 13–18 on the six Mon/Wed lectures;
each Studio week opens Monday with the colleague puzzle and runs its scored
colleague audit in the Wednesday lab. AI is the in-class AI assistant; GenAI
Studio appears at the m24 adversarial-review lab and the designated M8
(Robustness & Sensitivity Reviewer) and M10 (Poster Critic) reviewer roles."""

MEETINGS_P3 = [
    # ------------------------------------------------------------------ M23
    {
        "meeting": 23, "date": "2026-10-19", "day": "Mon", "modality": "in-person",
        "unit": "Week 9 — Studio 8: Stress-test and adjudicate",
        "title": "Stress-test I: pre-list your checks before you run them — the robustness grid and commensurable panels",
        "driving_question": "If your result only holds under one way of slicing the data, is it a finding — or an accident you went looking for?",
        "secondary_questions": "What is a robustness check versus a sensitivity check? Why must every check be pre-listed, with its prediction written, before any of them run? What makes two specifications commensurable, and why is a span reported within a panel, never across panels? What separates honest robustness from specification searching?",
        "inquiry": "all routes (stress-testing your own verified result)",
        "srl_slot": "SRL slot 13 (randomly assigned at semester start)",
        "srl_focus": "Colleague puzzle: a colleague's robustness section lists five checks that all flatter the finding — and the file history shows the checks were chosen after the results ran. What would an honest, pre-listed grid have contained?",
        "claim_permitted": "\"My claim survives the checks I pre-listed before running any of them; where it moves, I report the direction and the size of the move.\"",
        "claim_not_permitted": "Reporting the one specification that 'worked' after quietly trying many, or quoting a span across panels that estimate different quantities — both are specification searching wearing robustness's clothes.",
        "rdss_reading": "Required EDR|AI: the robustness-and-sensitivity lesson (pre-listing, the grid, commensurable panels); start the false-confidence lesson for Wednesday. Recommended RDSS: revisit ch. 10 'Diagnosing designs' (book.declaredesign.org)",
        "cb_reading": "optional: callingbullshit.org — a 'the result vanished under reanalysis' case",
        "other_material": "nb09 student notebook (stress-test and adjudicate), §Lecture 1 (Colab); your frozen clean-restart verified analysis (M7); M8 Brightspace brief; the Studio 8 colleague artifact (course platform)",
        "provenance": "crosswalk M8 + BOOK_STATIONS stress-test steps 1–2 + the course robustness-grid and specification-curve cells | stress-test and adjudicate | pre-registration card + same-estimand specification panels on the LAPOP teaching resample | reused + fresh",
        "concepts": "robustness vs sensitivity; pre-listing before running, and committing to report all of it; the robustness grid; commensurable panels (a span is read within a panel that estimates one quantity, never across panels); the specification curve; the choice-sensitivity verdict; robustness vs specification searching; specification spread measures your choices — it is not an uncertainty interval",
        "python_r_dependency": "numpy/pandas (rerun the estimate across a pre-listed grid); matplotlib (the same-estimand specification curve, provided)",
        "dataset_simulation": "lapop_brazil.csv teaching resample for the shared grid demonstration (no substantive claims from the resample) + each student's own verified result",
        "minute_dynamic": "0–9 SRL-led colleague puzzle: the colleague's flattering five-check robustness section on screen — the class reconstructs what an honest, pre-listed grid would have contained; 9–31 guided AI research-partner investigation in nb09: write the pre-registration card FIRST (every check, its prediction, and the commitment to report all of them), then run the grid on the shared example and read the specification curve panel by panel — your AI assistant proposes candidate checks and you rule each in or out before anything runs; 31–43 human verification + instructor formalization: the instructor formalizes commensurable panels (a span within a panel that estimates one quantity, never across panels) and the class separates pre-committed checks from after-the-fact fishing; 43–50 decision & defense: pre-list your own project's grid + ledger + Claim Ticket.",
        "hands_on_activity": "Write your pre-registration card before any check runs, then execute the pre-listed grid on the shared example and read its specification curve within each commensurable panel.",
        "practice": "📝 nb09 practice: label six analyses as robustness check or specification search; then sort eight specifications into commensurable panels and mark the one span it would be dishonest to report.",
        "discussion_prompt": "You ran ten specifications and report the one that is significant. Write the sentence that turns that from p-hacking into honest robustness — what would you have had to do first?",
        "project_connection": "The M8 robustness audit begins: your pre-registration card — every check named and predicted before it runs — is the audit's spine.",
        "milestone_developed": "M8 — Robustness audit, Book Milestone 8 v1 (dev)",
        "milestone_work_time": "7 min (pre-list your own grid + write one prediction per check)",
        "milestone_presentation_review": "none (lecture day)",
        "student_prep": "M7 submitted; your frozen verified result at hand; the stress test you pre-listed over the weekend, still unrun.",
        "student_artifact": "Your pre-registration card (checks + predictions, committed before running) + the shared grid executed with its panel-by-panel reading",
        "exit_ticket": "Claim Ticket #23: \"The check most likely to hurt my finding is [check]; my written prediction is [x]; I commit to reporting it whatever it shows.\"",
        "homework_next_milestone": "Run your pre-listed grid on your own result before Wednesday, recording every move with its direction and size; Wednesday adds negative tests, adversarial reviewers, and your adjudication of every flag.",
        "instructor_prep": "Verify the shared grid and specification-curve cells run fast in Colab; release the Studio 8 colleague artifacts (one seeded flaw each, keys held privately); brief the SRL on the flattering-five-checks puzzle.",
        "risks_contingency": "The grid balloons → three pre-listed checks maximum in class, the rest as project work; the pre-listing rule is the point, not the count. A student's own result is not runnable → they pre-list on the shared example and run their own grid at the Friday studio.",
    },
    # ------------------------------------------------------------------ M24
    {
        "meeting": 24, "date": "2026-10-21", "day": "Wed", "modality": "in-person",
        "unit": "Week 9 — Studio 8: Stress-test and adjudicate",
        "title": "Stress-test II: negative tests, adversarial reviewers, and adjudicating every flag against the data",
        "driving_question": "Three confident reviewers — one human, two AI — name three different fatal flaws in your analysis. Which one is real, and how do you tell without trusting the loudest?",
        "secondary_questions": "What does a negative test check, and why is its prediction written before the run? Why is the licensed null check read against a reference spread, not exact zero? What does a multi-model AI panel reveal that a single reviewer hides? What turns a reviewer's flag into evidence?",
        "inquiry": "all routes (negative tests + adversarial adjudication)",
        "srl_slot": "SRL slot 14 (randomly assigned at semester start)",
        "srl_focus": "Challenge: three confident reviewers disagree about a finding's worst flaw — the lead presses the class on what could settle it, and why confidence settles nothing.",
        "claim_permitted": "\"I predicted each negative test before running it, commissioned adversarial review, and confirmed or refuted every flag with a data check — here is what survived.\"",
        "claim_not_permitted": "Accepting (or dismissing) a reviewer's verdict on its confidence — a flag becomes real only when a check confirms it, and an AI review is another critique, never independent verification.",
        "rdss_reading": "Required EDR|AI: the negative-tests, ai-adversarial-reviewer, and false-confidence lessons",
        "cb_reading": "",
        "other_material": "nb09 student notebook (stress-test and adjudicate), §Lecture 2 (Colab); Purdue GenAI Studio — the multi-model comparison + adversarial-reviewer bench; the Studio 8 colleague artifact (scored audit); AI Research Ledger template",
        "provenance": "crosswalk M8 + BOOK_STATIONS stress-test steps 3–5 + the course adversarial-review adjudication cells | stress-test and adjudicate | negative tests with pre-written predictions + null-reference spread + multi-model flag adjudication | reused + fresh",
        "concepts": "negative tests with predictions written before the run; the licensed null check and its reference spread (not exact zero); placebo and falsification logic; human vs AI reviewer flags; multi-model comparison (agreement, disagreement, confident error); adjudication — confirm or refute each flag with a data check; the confidence audit (where belief in the headline number actually comes from)",
        "python_r_dependency": "numpy/pandas (negative-test and null-spread cells on the shared example); matplotlib (the null reference distribution, provided)",
        "dataset_simulation": "lapop_brazil.csv teaching resample for the shared negative test + each student's own gridded result and its reviewer flags",
        "minute_dynamic": "0–7 SRL-led retrieval & challenge: the lead replays Monday's pre-listing rule, then stands three confident, conflicting reviewer verdicts on one finding and asks what could settle them; 7–30 intensive applied AI laboratory: in nb09, write your negative-test prediction, run the test and the licensed null check (reading the reference as a spread, not exact zero), commission the GenAI Studio adversarial reviewers on your own finding, and open the scored colleague audit — the colleague's robustness audit hides one seeded flaw, and every flag, theirs and yours, must be adjudicated against a data check; 30–38 peer defense + adversarial questioning: each student defends one confirmed flag and one refuted flag while the partner presses \"what check makes you sure?\"; 38–42 SRL synthesis + instructor accuracy lock: the lead states the room's conclusion and its uncertainty, and the instructor corrects any claim that survived challenge but is wrong before it can enter a ledger; 42–50 transfer to your own project: draft the adjudication — what survived, what did not, what you still cannot rule out — + ledger + Claim Ticket.",
        "hands_on_activity": "Predict, then run, your negative test and licensed null check; commission adversarial review on your own finding; and adjudicate every flag — yours and the colleague's seeded one — against a data check.",
        "practice": "📝 nb09 practice: given three conflicting 'top flaws' from three reviewers on a sample analysis, design the one data check that would confirm or kill each — then mark the flag no check can reach.",
        "discussion_prompt": "An AI reviewer flagged a flaw your human reviewer missed — and invented one that is not there. What does that pattern tell you about how to use it?",
        "project_connection": "M8 advances: the audit now carries your negative tests with their pre-written predictions and an adversarial-review record with every flag adjudicated.",
        "milestone_developed": "M8 — Robustness audit, Book Milestone 8 v1 (dev; adjudication drafted)",
        "milestone_work_time": "8 min (draft the adjudication: survived / did not survive / cannot yet rule out)",
        "milestone_presentation_review": "peer defense rounds (one confirmed + one refuted flag each); scored colleague audit filed",
        "student_prep": "Your pre-listed grid run on your own result; Monday's pre-registration card at hand; GenAI Studio access confirmed.",
        "student_artifact": "Negative test + null check with pre-written predictions, an adversarial-review record, the scored colleague-audit sheet, and a drafted adjudication",
        "exit_ticket": "Claim Ticket #24: \"The realest flag on my finding is [flaw], confirmed by [check]; the most confident wrong flag was [x], refuted by [check].\"",
        "homework_next_milestone": "Finish the adjudication and the confidence audit (where does belief in your headline number come from?); M8 is due at this Friday's studio, where you walk the room through your robustness audit.",
        "instructor_prep": "Confirm the GenAI Studio adversarial-reviewer bench is live; verify the null-spread cells; hold the colleague keys for the accuracy lock; brief the SRL on the three-reviewers challenge.",
        "risks_contingency": "GenAI Studio access fails → saved transcripts of three models reviewing a sample analysis carry the comparison and live reviews move to the Friday studio; the lesson (compare, then verify) survives without live access.",
    },
    # ------------------------------------------------------------------ M25
    {
        "meeting": 25, "date": "2026-10-23", "day": "Fri", "modality": "in-person",
        "unit": "Week 9 — Studio 8: Stress-test and adjudicate",
        "title": "Studio Friday — robustness audits due: what survived, what did not, and the bounded note begins",
        "driving_question": "You attacked your own result the way a hostile reviewer would. Can you walk the room through what survived, what did not, and what you still cannot rule out?",
        "secondary_questions": "What does a complete robustness audit contain? What does the designated Robustness & Sensitivity Reviewer add before submission? What does the M9 brief ask for (a bounded research-note v0), and why does the note precede the poster?",
        "inquiry": "all routes (robustness-audit studio)",
        "srl_slot": "",
        "srl_focus": "",
        "claim_permitted": "\"Here is my pre-listed grid with every result reported, my negative tests with their written predictions, and my adjudication — the checks that hurt my finding reported as fully as the ones that helped.\"",
        "claim_not_permitted": "An audit with no hits — either it was not run honestly, or it was not run at all; and a span quoted across panels that estimate different quantities.",
        "rdss_reading": "(no new reading — studio Friday; bring your executed robustness audit)",
        "cb_reading": "",
        "other_material": "week09 quiz (printed); nb09 student notebook (stress-test and adjudicate) for the recap; M9 Brightspace brief (bounded research-note v0); Purdue GenAI Studio — designated Robustness & Sensitivity Reviewer role, logged in the ledger",
        "provenance": "crosswalk M8 checkpoint (robustness-audit-v1) + M9 Brightspace brief + GenAI Studio reviewer bench | studio Friday | audit walkthrough + designated-role review + note-v0 kickoff | fresh",
        "concepts": "the robustness audit as a graded artifact; the audit walkthrough; the designated Robustness & Sensitivity Reviewer, adjudicated before submission; what survives licenses what ships — the note writes only the claims this audit supports, at the strength it supports them",
        "python_r_dependency": "none required (the audit cells stay open for consults)",
        "dataset_simulation": "each student's own audited result",
        "minute_dynamic": "0–10 weekly topic quiz: five multiple-choice questions on the week's topic, answered solo on paper and handed in; 10–15 research stand-up: each student's one-line audit status (what survived, what is still open); 15–45 milestone kickoff + AI-supported sprint: present the M9 brief on Brightspace — the bounded research-note v0 that writes down only what the audit licenses — then each student walks the room through their audit in two minutes, runs the designated GenAI Studio Robustness & Sensitivity Reviewer on their audit table, and adjudicates its flags before submission; 45–50 revise, log the ledger, submit M8 tonight + Claim Ticket.",
        "hands_on_activity": "Deliver your two-minute robustness-audit walkthrough, run the designated Robustness & Sensitivity Reviewer, adjudicate its flags, and submit your audit.",
        "practice": "📝 during the sprint: write the one sentence your audit now licenses that Monday's you would have overclaimed — and the check that changed it.",
        "discussion_prompt": "Whose audit reported a check that clearly hurt their finding — and did reporting it make you trust the finding less, or more?",
        "project_connection": "M8 submits tonight; every project enters the writing week knowing exactly which claims its audit licenses and at what strength.",
        "milestone_developed": "M8 — Robustness audit, Book Milestone 8 v1 (worked + due); M9 — Bounded research-note v0, Book Milestone 9 v1 (kickoff)",
        "milestone_work_time": "30 min studio block",
        "milestone_presentation_review": "M8 worked at the studio and submitted; robustness-audit walkthrough; designated GenAI Studio Robustness & Sensitivity Reviewer review",
        "student_prep": "Robustness audit executed (grid results, negative tests, drafted adjudication); walkthrough rehearsed once.",
        "student_artifact": "Delivered walkthrough + adjudicated designated-role review + submitted M8",
        "exit_ticket": "Claim Ticket #25: \"What survived my audit is [claim, at strength]; what I still cannot rule out is [x] — and my note will say both.\"",
        "homework_next_milestone": "Submit M8 tonight on Brightspace. Weekend: read the results-to-claims and claim-evidence-tables lessons; Monday you write the sentence your evidence can actually carry.",
        "instructor_prep": "Print the week09 quiz; walkthrough order + timer; confirm the Robustness & Sensitivity Reviewer role is provisioned; stage the M9 brief on Brightspace.",
        "risks_contingency": "An audit is incomplete → the walkthrough still happens on what ran (submission is tonight, not the walkthrough); the designated review runs on the strongest section and the rest is logged from home.",
    },
    # ------------------------------------------------------------------ M26
    {
        "meeting": 26, "date": "2026-10-26", "day": "Mon", "modality": "in-person",
        "unit": "Week 10 — Studio 9: Write, bound, and disclose",
        "title": "Write and bound I: from audited result to the claim your evidence can carry",
        "driving_question": "What sentence can your design and your surviving checks actually support?",
        "secondary_questions": "Which claim verbs overstate your route? Why must the boundary live in the same sentence as the claim? Where do population, uncertainty, and limitation lines belong? When is 'causal, currently unidentified' the honest label?",
        "inquiry": "all routes (results to bounded claims)",
        "srl_slot": "SRL slot 15 (randomly assigned at semester start)",
        "srl_focus": "Colleague puzzle: a colleague's note upgrades a robust association into a causal conclusion — every check passed, so what exactly is still missing?",
        "claim_permitted": "\"A bounded claim: estimate, population, route boundary, and uncertainty in one sentence — at the strength my audit licenses and no more.\"",
        "claim_not_permitted": "A claim strengthened by precision, significance, or reviewer confidence alone — surviving robustness checks makes an association sturdy, not causal.",
        "rdss_reading": "Required EDR|AI: the results-to-claims and claim-evidence-tables lessons",
        "cb_reading": "",
        "other_material": "nb10 student notebook (write, bound, and disclose), §Lecture 1 (Colab); M9 brief; your M8 robustness audit; the Studio 9 colleague artifact (course platform)",
        "provenance": "crosswalk M9 + BOOK_STATIONS write-bound-disclose steps 1–3 + the course claim-boundary discipline | write, bound, and disclose | claim-verb ladder + boundary-in-the-sentence + LAPOP instructional example | fresh",
        "concepts": "claim verbs and what each one requires; the bounded claim (boundary attached in the same sentence); population and uncertainty limits; limitations in a reader's words; the claim ladder — downgrade the verb until the design and audit license it; 'causal, currently unidentified' as the honest label (a causal question with weak identification is never relabeled descriptive)",
        "python_r_dependency": "pandas only (the bounded-claim teaching example; no new modeling)",
        "dataset_simulation": "lapop_brazil.csv instructional example (teaching resample, no substantive claims) + each student's own audited result",
        "minute_dynamic": "0–9 SRL-led colleague puzzle: the colleague's association-to-causation upgrade on screen — every check passed, and the class must name what is still missing; 9–31 guided AI research-partner investigation in nb10: work the claim ladder on four overclaims, downgrading each verb until the design and audit license it, with your AI assistant proposing alternative phrasings you accept or reject against the evidence; 31–43 human verification + instructor formalization: the instructor formalizes the bounded claim (boundary in the same sentence) and the kind rule — a causal question with weak identification stays causal, currently unidentified, never quietly descriptive; 43–50 decision & defense: draft your own headline bounded claim + ledger + Claim Ticket.",
        "hands_on_activity": "Downgrade four overclaims until each matches its design and evidence, then write your own headline claim with estimate, population, route boundary, and uncertainty in one sentence.",
        "practice": "📝 nb10 practice: for six claim sentences, circle the verb, name what it would require, and rewrite the two your own audit could not license.",
        "discussion_prompt": "Which word in your current claim carries the largest evidentiary burden?",
        "project_connection": "The headline bounded claim drafted today is the sentence everything else in note v0 exists to support.",
        "milestone_developed": "M9 — Bounded research-note v0, Book Milestone 9 v1 (dev)",
        "milestone_work_time": "7 min (headline bounded-claim transfer)",
        "milestone_presentation_review": "one oral claim defense during the close",
        "student_prep": "M8 submitted; your audit's adjudication at hand; the results-to-claims lesson read.",
        "student_artifact": "Bounded headline claim + claim-verb audit of four overclaims + ledger row",
        "exit_ticket": "Claim Ticket #26: \"I changed [verb] to [verb] because my design establishes [x] — and my boundary now lives in the same sentence.\"",
        "homework_next_milestone": "Bring the bounded claim and its evidence trace Wednesday; read the ai-disclosure and poster-to-note lessons — the note's spine and disclosure come next.",
        "instructor_prep": "Prepare the claim ladder and one real-output LAPOP teaching example with its caveat visible; release the Studio 9 colleague artifacts; brief the SRL on the upgrade puzzle.",
        "risks_contingency": "No result survived M8 → the defensible note reports that outcome — a survived-nothing note with honest boundaries beats an invented claim, and the project returns to the owning studio for its next cycle.",
    },
    # ------------------------------------------------------------------ M27
    {
        "meeting": 27, "date": "2026-10-28", "day": "Wed", "modality": "in-person",
        "unit": "Week 10 — Studio 9: Write, bound, and disclose",
        "title": "Write and bound II: the claim-evidence table, the ledger-derived disclosure, and the note spine",
        "driving_question": "Can every sentence in your note name its evidence, its verification, and its boundary?",
        "secondary_questions": "What goes in a claim-evidence row, and why does a claim with no row not ship? What did AI receive and return, and which suggestions remain unresolved? Why is the disclosure written from the ledger, not from memory? What orders the note spine?",
        "inquiry": "all routes (bounded writing and disclosure)",
        "srl_slot": "SRL slot 16 (randomly assigned at semester start)",
        "srl_focus": "Challenge: a colleague's note cites a plausible source that was never retrieved — the lead asks how the claim-evidence table would have caught it before a reader did.",
        "claim_permitted": "\"Every claim in my note has a complete evidence row — claim, output, check — and my disclosure is derived from the ledger, including what I did not verify.\"",
        "claim_not_permitted": "A citation or factual claim supported only by an AI suggestion — an unretrieved source is an unresolved suggestion, not evidence, however plausible it reads.",
        "rdss_reading": "Required EDR|AI: the ai-disclosure and poster-to-note lessons",
        "cb_reading": "",
        "other_material": "nb10 student notebook (write, bound, and disclose), §Lecture 2 (Colab); M9 brief; your AI Research Ledger; the Studio 9 colleague artifact (scored audit)",
        "provenance": "crosswalk M9 + BOOK_STATIONS write-bound-disclose steps 2–4 + the D16 evidence-integrity rule | write, bound, and disclose | claim-evidence table + ledger-derived disclosure + note spine | fresh",
        "concepts": "the claim-evidence table (one row per claim: claim, output, trace, boundary); a claim with no row does not ship; unresolved suggestions vs verified citations; the AI disclosure written from the ledger — including what was sent to tools and what was never verified; the note spine: problem, gap, question, findings ordered by support, headline claim with its boundary inside",
        "python_r_dependency": "none required beyond opening your verified outputs",
        "dataset_simulation": "each student's own verified outputs and evidence registry",
        "minute_dynamic": "0–7 SRL-led retrieval & challenge: yesterday's bounded claim recited from memory, then the colleague's plausible-but-never-retrieved source — how would the table have caught it?; 7–30 intensive applied AI laboratory: in nb10, build a claim-evidence row for every candidate claim in your note and cut any claim that cannot complete its row, then convert your ledger into a disclosure draft — while the scored colleague audit hunts the seeded flaw in the colleague's note; 30–38 peer defense + adversarial questioning: partners each verify one claim-evidence row and one disclosure sentence against the actual output and ledger; 38–42 SRL synthesis + instructor accuracy lock: the lead states the room's conclusion and its uncertainty, and the instructor corrects any claim that survived challenge but is wrong before it can enter a ledger; 42–50 transfer: assemble problem, gap, question, findings, boundary, and disclosure into your note spine + ledger + Claim Ticket.",
        "hands_on_activity": "Build a claim-evidence row for every candidate claim, cut the claims that cannot complete a row, and write your disclosure from the ledger — not from memory.",
        "practice": "📝 nb10 practice: convert one ledger entry into a precise disclosure sentence; then label three source-claims as verified, mischaracterized, or unresolved.",
        "discussion_prompt": "What belongs in your disclosure even when no AI wording survives in the note?",
        "project_connection": "Note v0 takes shape: spine assembled, every surviving claim traced, disclosure drafted — due at this Friday's studio.",
        "milestone_developed": "M9 — Bounded research-note v0, Book Milestone 9 v1 (dev; spine + table assembled)",
        "milestone_work_time": "8 min (note-spine transfer)",
        "milestone_presentation_review": "peer defense (one evidence row + one disclosure sentence verified each); scored colleague audit filed",
        "student_prep": "Bounded headline claim from Monday; evidence registry and AI Research Ledger current; the ai-disclosure lesson read.",
        "student_artifact": "Claim-evidence table + note spine + ledger-derived disclosure draft + scored colleague-audit sheet",
        "exit_ticket": "Claim Ticket #27: \"One sentence I cut or marked unresolved was [x], because its evidence row could not be completed.\"",
        "homework_next_milestone": "Complete note v0 (spine, table, disclosure); it is due at this Friday's studio, where the note is red-teamed and the poster week is briefed.",
        "instructor_prep": "Supply only retrieved real-source examples or explicitly unresolved suggestions — never a fabricated citation (D16); hold the colleague keys; brief the SRL on the never-retrieved-source challenge.",
        "risks_contingency": "A source cannot be retrieved in class → it keeps its unresolved status and leaves the evidence table; the claim it supported is cut or re-scoped, never shipped on the suggestion.",
    },
    # ------------------------------------------------------------------ M28
    {
        "meeting": 28, "date": "2026-10-30", "day": "Fri", "modality": "in-person",
        "unit": "Week 10 — Studio 9: Write, bound, and disclose",
        "title": "Studio Friday — bounded research-note v0 due: the note red-team, and the poster week is briefed",
        "driving_question": "Does your note stand alone — every claim traced, bounded, and disclosed — before a single poster pixel exists?",
        "secondary_questions": "What does the note red-team check? Why does the note lock before poster adaptation begins? What do the M10 gates — author self-reproduction and the release preflight — demand next week?",
        "inquiry": "all routes (bounded-note studio)",
        "srl_slot": "",
        "srl_focus": "",
        "claim_permitted": "\"A stand-alone note v0: headline claim bounded in-sentence, every claim with a complete evidence row, disclosure from the ledger — the only source the poster may draw from.\"",
        "claim_not_permitted": "A poster-first claim — anything appearing on next week's poster that is absent from tonight's note; and an unresolved source presented as evidence.",
        "rdss_reading": "(no new reading — studio Friday; bring your complete note v0)",
        "cb_reading": "",
        "other_material": "week10 quiz (printed); nb10 student notebook (write, bound, and disclose) for the recap; M10 Brightspace brief (final poster lock + the two gates); note-v0 checklist",
        "provenance": "crosswalk M9 checkpoint (bounded-claims-v1; the note precedes the poster) + M10 Brightspace brief | studio Friday | note red-team + poster content brief + gates preview | fresh",
        "concepts": "the note red-team; note-before-poster (the poster adapts the note, never the reverse); the M10 gate preview — author self-reproduction and the release preflight, both blocking before the lock; the terminal lock ahead",
        "python_r_dependency": "none required (verified outputs open for the red-team's checks)",
        "dataset_simulation": "each student's own note v0 and evidence registry",
        "minute_dynamic": "0–10 weekly topic quiz: five multiple-choice questions on the week's topic, answered solo on paper and handed in; 10–15 research stand-up: each student reads their headline claim and its boundary aloud; 15–45 milestone kickoff + AI-supported sprint: present the M10 brief on Brightspace — the final poster lock, its criticism week, and the two blocking gates (author self-reproduction + release preflight) — then the note red-team: pairs attack each other's claim-evidence tables and disclosures, and each student patches what the attack found; 45–50 revise, log the ledger, submit M9 tonight + Claim Ticket.",
        "hands_on_activity": "Run the note-v0 checklist, take a partner's red-team on your claim-evidence table and disclosure, patch the real hits, and submit your note.",
        "practice": "📝 during the sprint: record one red-team hit you patched and one you rejected — with the check that decided each.",
        "discussion_prompt": "Which note sentence would be most dangerous to carry unchanged onto a poster?",
        "project_connection": "M9 submits tonight; the note is the poster's only source — next week adapts it, criticizes it, gates it, and locks it.",
        "milestone_developed": "M9 — Bounded research-note v0, Book Milestone 9 v1 (worked + due); M10 — Final poster lock, Book Milestone 10 v1 (kickoff)",
        "milestone_work_time": "30 min studio block",
        "milestone_presentation_review": "M9 worked at the studio and submitted; note red-team in pairs; poster content brief presented",
        "student_prep": "Note v0 complete (spine, claim-evidence table, disclosure); headline claim ready to read aloud.",
        "student_artifact": "Submitted M9 note v0 + red-team slip given and received + ledger row",
        "exit_ticket": "Claim Ticket #28: \"The claim now safe to adapt to the poster is [claim] — and nothing outside my note will appear on it.\"",
        "homework_next_milestone": "Submit M9 tonight on Brightspace. Weekend: read the research-posters lesson; Monday you decide what your claim must lose to fit a poster — and begin the one-figure draft.",
        "instructor_prep": "Print the week10 quiz; stage the M10 brief with the two gate definitions; red-team pairing plan; note-v0 checklist copies.",
        "risks_contingency": "A note is thin → the red-team runs on what exists and the submission stands tonight (M9 is revisable; M10 is not); a missing evidence row removes its claim rather than becoming a Friday research task.",
    },
    # ------------------------------------------------------------------ M29
    {
        "meeting": 29, "date": "2026-11-02", "day": "Mon", "modality": "in-person",
        "unit": "Week 11 — Studio 10: Adapt the poster and pass the release gates",
        "title": "Poster adaptation and criticism I: what the claim must lose, the one-figure draft, and the gallery walk",
        "driving_question": "A poster gives your claim one figure and thirty seconds of a stranger's attention — what must it lose, and what may it never lose?",
        "secondary_questions": "What does adapting a bounded claim to the poster genre drop, and what must survive (the boundary, the uncertainty, the preliminary label)? Does the figure's impression match its number? What does the gallery-walk audit check — claims, evidence, uncertainty, visual design, accessibility?",
        "inquiry": "all routes (genre adaptation + poster criticism)",
        "srl_slot": "SRL slot 17 (randomly assigned at semester start)",
        "srl_focus": "Colleague puzzle: two figures of the same colleague result — the more dramatic one changes what the finding appears to say. Which one is honest, and how do you tell?",
        "claim_permitted": "\"My poster says less than my note and claims nothing my note does not — headline verbed to my boundary, intervals drawn, preliminary label on.\"",
        "claim_not_permitted": "An adaptation that drops the limitations — that is not a shorter version of the claim, it is a different claim; and a figure whose impression outruns its number.",
        "rdss_reading": "Required EDR|AI: the research-posters lesson (the one-figure adaptation)",
        "cb_reading": "",
        "other_material": "nb11 student notebook (poster adaptation and release gates), §Lecture 1 (Colab); your M9 note; project/poster/redteam_review_protocol.md (four-audit + accessibility slip); the Studio 10 colleague artifact (course platform)",
        "provenance": "crosswalk M10 + BOOK_STATIONS adapt-and-defend steps 1–2 + the course gallery-walk method | poster adaptation and criticism | one-figure adaptation + visual-honesty audit + four-audit gallery walk | reused + fresh",
        "concepts": "genre adaptation — what the claim must lose to fit, and what it may never lose; the one-figure draft with labeled values and intervals drawn; visual honesty (impression versus number); the preliminary-edition label; the gallery-walk audit (claim boundary, figure honesty, read path, uncertainty) plus visual design and accessibility",
        "python_r_dependency": "matplotlib (re-export your note's key figure at poster scale; provided cell)",
        "dataset_simulation": "each student's own note v0 and its verified outputs (+ the colleague pair of figures for the puzzle)",
        "minute_dynamic": "0–9 SRL-led colleague puzzle: the two figures of one colleague result side by side — the class rules which is honest and names what the dramatic one changed; 9–31 guided AI research-partner investigation in nb11: name what your claim must lose to fit the genre (and what it may never lose), then build the one-figure draft from your note — labeled values, intervals drawn, headline verbed to your boundary, preliminary label on — with your AI assistant proposing layouts you accept or reject against the note; 31–43 human verification + gallery walk: drafts up, every student walks all of them with the four-audit + accessibility slip, and the room consolidates the real hits per poster, separating evidence problems from stylistic quibbles; 43–50 decision & defense: log your draft's ranked hits + ledger + Claim Ticket.",
        "hands_on_activity": "Build the one-figure poster draft from your note, then walk the gallery and audit every draft — claim boundary, figure honesty, read path, uncertainty, accessibility.",
        "practice": "📝 nb11 practice: on a sample poster with planted flaws, catch one claim-boundary, one figure-honesty, and one accessibility problem — then name what its dramatic figure changed about the apparent finding.",
        "discussion_prompt": "Which accessibility problem did the gallery walk catch that a fast reader never would — and how many strangers at the Expo would it have lost?",
        "project_connection": "M10 advances: each project leaves with a preliminary-labeled one-figure draft and its consolidated, ranked hit list.",
        "milestone_developed": "M10 — Final poster lock, Book Milestone 10 v1 (dev)",
        "milestone_work_time": "8 min (log and rank the audited hits your own draft received)",
        "milestone_presentation_review": "gallery-walk audit (structured peer criticism of every draft)",
        "student_prep": "M9 note submitted and at hand; the research-posters lesson read; a draft or storyboard started over the weekend.",
        "student_artifact": "One-figure preliminary-labeled draft + gallery-walk slips given + your own draft's ranked hit list",
        "exit_ticket": "Claim Ticket #29: \"The gallery's most serious hit on my draft is [hit]; my fix is [x] — and the fix changes my figure, not my claim.\"",
        "homework_next_milestone": "Fix your draft once against the ranked hits; Wednesday you defend it aloud, then prove its numbers reproduce from a clean start and pass the release preflight — both gates block Friday's lock.",
        "instructor_prep": "Verify the poster-scale figure cell; print the four-audit + accessibility slips; prepare the colleague figure pair with its key; brief the SRL on the two-figures puzzle.",
        "risks_contingency": "A draft is not display-ready → that student audits others (the obligation stands) and posts the one-figure storyboard in its place; the fix log still opens from the walk's hits.",
    },
    # ------------------------------------------------------------------ M30
    {
        "meeting": 30, "date": "2026-11-04", "day": "Wed", "modality": "in-person",
        "unit": "Week 11 — Studio 10: Adapt the poster and pass the release gates",
        "title": "Poster criticism II: the oral defense, the author self-reproduction, and the release preflight",
        "driving_question": "Your poster looks ready and defends well — but do its numbers reproduce from a clean start, and would it survive a release audit? Both gates block Friday's lock.",
        "secondary_questions": "How do interdisciplinary, methods, and skeptic questions each test the poster? What does author self-reproduction prove — and what can it never prove (it is not independent verification)? What do the four preflight checks cover — permissions, disclosure, reproducibility, claim boundary?",
        "inquiry": "all routes (oral defense + release gates)",
        "srl_slot": "SRL slot 18 (randomly assigned at semester start)",
        "srl_focus": "Challenge: a colleague's poster looks finished and answers questions well — but its headline number does not reproduce from a clean start. What may Friday's lock do with it?",
        "claim_permitted": "\"Defended across three lenses, fixed once against the log, self-reproduced from a clean start, and preflight-passed — my poster has earned Friday's lock.\"",
        "claim_not_permitted": "\"It reproduced on my machine, so it is verified\" — author self-reproduction is a gate you must pass, not independent verification; and bluffing an answer under questioning upgrades no claim.",
        "rdss_reading": "Required EDR|AI: the poster-criticism lesson (the defense and the gates)",
        "cb_reading": "",
        "other_material": "nb11 student notebook (poster adaptation and release gates), §Lecture 2 (Colab); the three-lens question deck (interdisciplinary / methods / skeptic); the reproduction-log and release-preflight templates; the Studio 10 colleague artifact (scored audit)",
        "provenance": "crosswalk M10 gates (reproduce-before-publish + release-preflight-before-publish, both blocking) + BOOK_STATIONS adapt-and-defend steps 3–4 + the course three-lens defense | poster criticism and release gates | oral defense + fix log + author self-reproduction + four-check preflight | reused + fresh",
        "concepts": "the three-lens defense (interdisciplinary, methods, skeptic) and the honest don't-know; defend-versus-concede judgment; the fix log — fixed once, then the lock call; author self-reproduction from a clean start (a blocking gate, and not independent verification); the release preflight (permissions, disclosure, reproducibility, claim boundary); gate evidence: the reproduction log and the preflight log",
        "python_r_dependency": "your own notebook, restarted clean (run-all for the self-reproduction gate)",
        "dataset_simulation": "each student's own poster draft + runnable notebook (+ the colleague's non-reproducing poster for the audit)",
        "minute_dynamic": "0–7 SRL-led retrieval & challenge: the colleague's finished-looking poster whose headline number will not reproduce from a clean start — the class rules what Friday's lock may do with it; 7–30 intensive applied AI laboratory: timed defense rounds against the three-lens deck (peers, instructor, and AI-generated skeptic questions), each defender logging fixes — then every student restarts clean, runs all, and checks the poster's numbers against the fresh outputs (the reproduction log), while the scored colleague audit traces where the colleague's number diverged; 30–38 peer defense + adversarial questioning: pairs drill the hardest unanswered question and run each other's release preflight — permissions, disclosure, reproducibility, claim boundary; 38–42 SRL synthesis + instructor accuracy lock: the lead states the room's conclusion and its uncertainty, and the instructor corrects any claim that survived challenge but is wrong before it can enter a ledger; 42–50 transfer to Friday's lock: record gate status (pass / blocked, with the evidence) + ledger + Claim Ticket.",
        "hands_on_activity": "Defend your poster across three lenses, fix once against the log, self-reproduce its numbers from a clean restart, and run the four-check release preflight — recording both gate logs.",
        "practice": "📝 nb11 practice: classify six audience questions by lens and draft the honest don't-know for the one you least want; then mark which preflight check would catch a dropped limitation.",
        "discussion_prompt": "Which classmate's concession made their project MORE credible, not less — and what exactly did they concede?",
        "project_connection": "M10 nears lock: every project holds a defense record, a fix log, and its two gate logs — pass, or blocked with a named repair.",
        "milestone_developed": "M10 — Final poster lock, Book Milestone 10 v1 (dev; self-reproduction + release-preflight gates run)",
        "milestone_work_time": "8 min (record gate status + the claims your defense exposed as too strong)",
        "milestone_presentation_review": "oral defense rounds (three-lens questioning); scored colleague audit filed",
        "student_prep": "Draft fixed once against Monday's hits; notebook runnable for the clean restart; gallery hit list at hand.",
        "student_artifact": "Defense record + fix log + reproduction log + release-preflight log (both gates dated)",
        "exit_ticket": "Claim Ticket #30: \"My gates read [pass / blocked]: the number that had to reproduce was [x], and the preflight check closest to failing was [y].\"",
        "homework_next_milestone": "Close any blocked gate before Friday — a blocked gate blocks the lock, no exceptions; arrive with a print-ready file, because the poster locks and goes for printing at 5:00 PM, with no revision after.",
        "instructor_prep": "Assemble the three-lens deck per project; timer; verify a clean Colab runtime reproduces the shared example; hold the colleague key (where the number diverges); brief the SRL on the will-not-reproduce challenge.",
        "risks_contingency": "A clean run will not finish in class → the gate runs to completion in a hosted runtime after class and the log is filed before Friday's lock; a defense stalls → the instructor steps in as question-asker-of-record and the presenter gets a second short round.",
    },
    # ------------------------------------------------------------------ M31
    {
        "meeting": 31, "date": "2026-11-06", "day": "Fri", "modality": "in-person",
        "unit": "Week 11 — Studio 10: Adapt the poster and pass the release gates",
        "title": "Studio Friday — final production and the terminal poster lock: gates green, citations verified, submitted for printing by 5:00 PM",
        "driving_question": "Is every claim on this poster one you can defend to a stranger at the Expo, every number traced and freshly reproduced, every source real — with no 'after' to fix it?",
        "secondary_questions": "Are both gate logs green — author self-reproduction and the release preflight? Does every citation resolve to a real, retrievable source? Does every claim trace to its evidence and sit inside its boundary? Are the preliminary label and the AI-use disclosure block on, and is the file print-ready to URC spec?",
        "inquiry": "all routes (terminal lock studio)",
        "srl_slot": "",
        "srl_focus": "",
        "claim_permitted": "\"Locked: gates green, every number freshly reproduced and traced to a cell, every citation resolving, every claim inside its boundary, the preliminary label and disclosure on the record.\"",
        "claim_not_permitted": "\"I'll fix it after submission\" — there is no after; a blocked gate, an unresolved citation, or an untraceable number blocks the lock, and the Expo audience reads the submitted version.",
        "rdss_reading": "(no new reading — studio Friday; bring your print-ready file, both gate logs, and your runnable notebook)",
        "cb_reading": "",
        "other_material": "week11 quiz (printed); nb11 student notebook (poster adaptation and release gates), final checklist (Colab); project/poster/production_checklist.md; Purdue GenAI Studio — designated Poster Critic role, logged in the ledger; URC poster spec + submission instructions on Brightspace",
        "provenance": "crosswalk M10 checkpoint (defense-ready-v1, poster edition labeled preliminary; both gates blocking) + project/poster/production_checklist.md + the course evidence-integrity discipline | studio Friday (terminal) | final production + gate check + citation/claim/disclosure audit + poster lock | reused + fresh",
        "concepts": "the terminal lock; gate evidence checked at the door (reproduction log + preflight log); citation verification (every source real and retrievable); claim-evidence traceability (every number to a cell); the preliminary-edition label; the AI-use disclosure block; print-spec compliance",
        "python_r_dependency": "none required (figure re-exports at print resolution as needed)",
        "dataset_simulation": "each student's own final poster + runnable notebook",
        "minute_dynamic": "0–10 weekly topic quiz: five multiple-choice questions on the week's topic, answered solo on paper and handed in; 10–15 research stand-up: each student's readiness call — gate status and what is left before the file locks; 15–45 final production sprint: gate logs checked at the door (a blocked gate goes to repair first), then silent studio with rotating instructor checklist consults — print spec, figure resolution, uncertainty visible, headline inside its boundary, preliminary label on — while each student runs the citation-verification pass, traces one number to its cell under a partner's eyes, runs the designated GenAI Studio Poster Critic and adjudicates its flags, and completes the AI-use disclosure block; 45–50 lock, submit for printing, close the ledger + Claim Ticket. The deadline is today, 5:00 PM.",
        "hands_on_activity": "Show both gate logs green, run the final checklist, verify every citation resolves to a real source, trace one number to its cell under a partner's eyes, adjudicate the designated Poster Critic's flags, and submit the poster for printing.",
        "practice": "📝 (embedded in the checklist) verify: fonts ≥ minimum size at print scale; every figure carries its uncertainty or caveat; every citation opens to the source it names; the preliminary label is on the print file.",
        "discussion_prompt": "(brief, during consults) Which audit almost caught you — a gate, a citation that did not resolve, a number that did not trace, or a claim that outran its evidence?",
        "project_connection": "M10 final poster LOCKED and submitted for printing — the Expo artifact is terminal; next week turns the locked poster into a rehearsed defense (M11 kicks off Monday).",
        "milestone_developed": "M10 — Final poster lock, Book Milestone 10 v1 — poster edition, labeled preliminary (LOCKED + submitted for printing by 5:00 PM, terminal — no revision)",
        "milestone_work_time": "30 min studio block (production sprint + audit pairs)",
        "milestone_presentation_review": "gate-log check + instructor checklist consults + pair citation/claim/disclosure audit + designated GenAI Studio Poster Critic review",
        "student_prep": "Both gate logs green (or the repair done); all defense claim-softenings applied; print-ready file staged; notebook runnable.",
        "student_artifact": "Locked poster submitted for printing + signed production checklist + both gate logs + citation-verification, traceability, and disclosure audit",
        "exit_ticket": "Claim Ticket #31: \"One claim I softened before the lock, and why the softer version is the one I can defend at the Expo.\"",
        "homework_next_milestone": "Rest this weekend — the poster is locked. Monday begins the defense rehearsal: pitch layers, hard questions, and spoken uncertainty (M11 kicks off Monday of conference-prep week).",
        "instructor_prep": "Print the week11 quiz; confirm the printing/portal submission mechanics; confirm the Poster Critic role is provisioned; consult-rotation timer; backup PDF-to-Brightspace plan; the M11 brief staged for Monday.",
        "risks_contingency": "Printing or the portal fails → the PDF submitted to Brightspace timestamps the 5:00 PM deadline, and physical printing resolves next week before the Expo. A gate is still blocked at the studio → the repair happens first, in the sprint, and the lock waits for the log — never for a better result. A citation will not resolve → the claim it supports is cut or re-sourced before the lock, never shipped unverified.",
    },
]
