"""Meetings M12–M22: Weeks 5–8 — the D41 studio-first arc. Week 5 is the
route hub (Studio 5: each student reads their OWN pathway lesson plus one
instructor-assigned contrast; five-route jigsaw with advocate roles independent
of project routes). Week 6 governs data and measurement (Studio 6: acquisition
routes, provenance, permission; construct -> indicator, reliability, validity;
the D40 Contract-operationalization revisit, settled and versioned at the
studio). Weeks 7–8 are Studio 7's two halves: build the first executable
analysis (W7), then verify it from a clean restart (W8, single Wednesday
lecture — no class Mon Oct 12, October Break). Mon/Wed lectures are SRL-led;
several open on the week's Synthetic Colleague artifact (scored audits in the
Studio weeks; the W7 pipeline preview is unscored — its scored S7 audit runs in
W8 on the verification record). Fridays are quiz-first milestone studios: M4–M7
are worked and submitted, M8 kicks off; each course milestone presents its Book
Milestone version (M6 and M7 are versions 1 and 2 of Book Milestone 7). The
URC abstract internal gate is fixed at the Friday Oct 9 studio (m20)."""

MEETINGS_P2 = [
    # ------------------------------------------------------------------ M12
    {
        "meeting": 12, "date": "2026-09-21", "day": "Mon", "modality": "in-person",
        "unit": "Week 5 — Studio 5: Develop the pathway (route hub)",
        "title": "The route hub: five pathways, and the one your Contract licenses",
        "driving_question": "Which of the five research routes do your question and your license actually support — and what can that route never establish?",
        "secondary_questions": "What signals separate the five routes? Why does assigning conditions not make a question causal? Why does a causal question with weak data stay causal ('causal, currently unidentified') instead of quietly becoming descriptive?",
        "inquiry": "the five-route hub (design-library layer): observational descriptive, observational causal, experimental descriptive, experimental causal, prediction",
        "srl_slot": "SRL slot 06 (randomly assigned at semester start)",
        "srl_focus": "Colleague puzzle: your colleague picked the most sophisticated-looking method on the shelf, not the route their Contract licenses — what signal did they ignore?",
        "claim_permitted": "\"My route is [pathway] because my question asks [signal] and my data strategy is [observe / assign / forecast] — and here is what this route can never establish.\"",
        "claim_not_permitted": "A causal, predictive, or population claim licensed only by the topic's importance or the software used — a route is earned by the question and the license, never by the tool.",
        "rdss_reading": "Required EDR|AI: your project's route lesson (one of the five pathway lessons), read before today; the instructor-assigned contrast lesson is due Wednesday; the hybrid/complex-designs lesson binds only if your design has stages. Recommended RDSS: the design-library chapter matching your route (ch. 15–18, book.declaredesign.org; the prediction route's EDR|AI lesson stands alone).",
        "cb_reading": "optional: callingbullshit.org module on correlation and causation",
        "other_material": "nb05 §Lecture 1 (Colab); your Contract v0; the released colleague route artifact; M4 brief",
        "provenance": "EDR|AI Studio 5 (BOOK_STATIONS develop-the-pathway route guide) + crosswalk M4 route_selection + course datasets | the route hub | route-signal matrix over five shallow dataset cards + colleague route diagnosis | newly-constructed-from-source-concept",
        "concepts": "the five routes (observational descriptive, observational causal, experimental descriptive, experimental causal, prediction); route signals (what the question asks x what you are allowed to do); claim license and claim boundary; assignment does not imply a causal inquiry; a causal question that cannot yet be identified stays causal; the hybrid-stage overlay",
        "python_r_dependency": "pandas (open five shallow route cards; no model fitting)",
        "dataset_simulation": "shallow route cards drawn from the course datasets (lapop_brazil, cliningsmith_etal, bonilla_tillery, la_voter_file, foos_etal) — metadata and one summary each, no analysis",
        "minute_dynamic": "0–9 colleague research puzzle: the SRL opens the colleague's Contract next to its sophisticated-but-wrong method choice, and the class names the route signal the colleague ignored; 9–31 guided AI research-partner investigation in nb05: with AI as research partner, work the route-signal matrix across five shallow dataset cards — for each, what the question asks, what the researcher may do, and which route that licenses — asking AI to argue each call and verifying its reasons against the route guide; 31–43 human verification + instructor formalization: the instructor formalizes the five routes and the two cautions (assignment is not causality; an unidentified causal question stays causal), and the class settles the colleague diagnosis; 43–50 decision & defense: commit your provisional route with its warrant, log the Ledger entry, and write the Claim Ticket.",
        "hands_on_activity": "Complete the route-signal matrix across five dataset cards, then make and defend a provisional route call for your own Contract.",
        "practice": "📝 nb05 practice: for each of the five routes, complete the pair: this route estimates ___ and can never establish ___.",
        "discussion_prompt": "What would have to change in your Contract — the question, the data, or the permission — before a neighboring route became the defensible one?",
        "project_connection": "Your provisional route, its warrant, and its boundary sentence open the M4 pathway declaration due at this Friday's studio.",
        "milestone_developed": "M4 — Pathway declaration and mandated contrast, Book Milestone 5 v1 (dev)",
        "milestone_work_time": "7 min (provisional route + warrant sentence into M4)",
        "milestone_presentation_review": "one oral route defense during the closing block",
        "student_prep": "Read your route lesson; bring your Contract v0; know which contrast lesson the instructor assigned you.",
        "student_artifact": "Completed route-signal matrix + provisional route with warrant and boundary sentence + colleague diagnosis note",
        "exit_ticket": "Claim Ticket #12: my route is ___ because ___, and it can never establish ___.",
        "homework_next_milestone": "Read the instructor-assigned contrast lesson for Wednesday's jigsaw; draft the route section of M4.",
        "instructor_prep": "Release the week's colleague artifacts with keys filed; prepare the five route cards; assign contrast lessons so all five routes are covered; brief the SRL on the wrong-route puzzle.",
        "risks_contingency": "Route cards run long → protect the personal route decision and move the extra cards below the notebook's optional-depth line; a Contract fits two routes → declare the primary route and mark the hybrid overlay for Wednesday.",
    },
    # ------------------------------------------------------------------ M13
    {
        "meeting": 13, "date": "2026-09-23", "day": "Wed", "modality": "in-person",
        "unit": "Week 5 — Studio 5: Develop the pathway (route hub)",
        "title": "The route jigsaw: defend your pathway by ruling out its mandated contrast",
        "driving_question": "Why does your declared route fit your Contract better than the contrast the instructor assigned you to rule out?",
        "secondary_questions": "Which claim verbs change when the route changes? Does your design genuinely have stages, or does the hybrid overlay not apply? What evidence would force a route change rather than a robustness note?",
        "inquiry": "route comparison and pathway warrant (design-library layer)",
        "srl_slot": "SRL slot 07 (randomly assigned at semester start)",
        "srl_focus": "Colleague challenge: a fresh claim from your colleague quietly borrows the license of a neighboring route — find the borrowed verb.",
        "claim_permitted": "\"My route is [pathway]; the mandated contrast would answer [other question]; my Contract asks [my question], so the contrast is ruled out — and here is my claim boundary.\"",
        "claim_not_permitted": "A route declared from convenience, familiarity, or results already glimpsed — the declaration precedes the data, and the contrast must be genuinely engaged, never strawmanned.",
        "rdss_reading": "Required EDR|AI: the instructor-assigned contrast lesson (read before today); the hybrid/complex-designs lesson only when your design has stages. Recommended RDSS: skim the contrast route's design-library chapter (ch. 15–18, book.declaredesign.org).",
        "cb_reading": "",
        "other_material": "nb05 §Lecture 2 (Colab); the route-signal matrix from Monday; the colleague route artifact; M4 brief",
        "provenance": "crosswalk M4 route_selection (own-route-plus-one-contrast; five-route jigsaw, advocates independent of project routes) + EDR|AI Studio 5 | the route jigsaw | advocate rounds + mandated-contrast warrant + scored colleague audit | newly-constructed-from-source-concept",
        "concepts": "the mandated contrast; the five-route jigsaw (advocate roles independent of project routes); the pathway warrant; boundary verbs (the claim language each route licenses); the hybrid-stage decision; route change vs robustness check",
        "python_r_dependency": "none beyond Monday's loaded route cards",
        "dataset_simulation": "the same five route cards (no new analysis; the argument is the work)",
        "minute_dynamic": "0–7 SRL-led retrieval & challenge: name the five routes and their signals from memory, then the SRL opens the colleague claim with the borrowed verb; 7–30 intensive applied AI laboratory: the five-route jigsaw — each student advocates ONE route (assigned independent of their project) for a shared case, then turns to their own Contract to write the mandated-contrast warrant, and runs the colleague audit (find the seeded flaw, defend the decision that only looks wrong, repair with the smallest defensible correction), with AI pressed to argue the contrast side; 30–38 peer defense + adversarial questioning: partners attack each other's warrant — does the contrast get ruled out, or merely dismissed?; 38–42 SRL synthesis + instructor accuracy lock: the lead states the room's conclusion and its uncertainty, and the instructor corrects any claim that survived challenge but is wrong before it can enter a ledger; 42–50 transfer to the final project + Ledger + Claim Ticket: finalize the route declaration, contrast warrant, and hybrid decision for M4.",
        "hands_on_activity": "Advocate one route in the jigsaw, then write your own mandated-contrast warrant and hybrid-stage decision, with AI pressed to argue the other side.",
        "practice": "📝 nb05 practice: complete the pair for your own project: my contrast route would answer ___, but my Contract asks ___.",
        "discussion_prompt": "What evidence, arriving mid-semester, would force you to change routes rather than add a robustness check — and what would you owe your Contract if it did?",
        "project_connection": "The route declaration, contrast warrant, and hybrid decision finish the M4 draft you work and submit at this Friday's studio.",
        "milestone_developed": "M4 — Pathway declaration and mandated contrast, Book Milestone 5 v1 (dev; contrast warrant + hybrid decision)",
        "milestone_work_time": "8 min (contrast warrant + hybrid decision into M4)",
        "milestone_presentation_review": "peer defense of route, contrast, and boundary; colleague audit sheet due",
        "student_prep": "Read the assigned contrast lesson; bring Monday's route matrix and your provisional route.",
        "student_artifact": "Route declaration v1 + contrast warrant + hybrid decision + colleague audit sheet",
        "exit_ticket": "Claim Ticket #13: one tempting alternative route I ruled out, and the Contract sentence that ruled it out.",
        "homework_next_milestone": "Bring the complete M4 draft (route, warrant, contrast, boundary, hybrid decision) to Friday's studio.",
        "instructor_prep": "Assign jigsaw advocate roles so every route is represented; hold the colleague keys and the likely clean traps; brief the SRL on the borrowed-verb challenge.",
        "risks_contingency": "A project genuinely lacks the information to declare → allow a versioned provisional route with the missing decision named; the jigsaw overruns → the own-Contract warrant is protected and the shared case closes early.",
    },
    # ------------------------------------------------------------------ M14
    {
        "meeting": 14, "date": "2026-09-25", "day": "Fri", "modality": "in-person",
        "unit": "Week 5 — Studio 5: Develop the pathway (route hub)",
        "title": "Studio Friday — pathway declarations: M4 due, M5 kickoff",
        "driving_question": "Can you submit a pathway declaration whose warrant and claim boundary survive the mandated contrast?",
        "secondary_questions": "Are all the M4 pieces present — route, warrant, contrast, boundary, hybrid decision? What does the M5 brief ask for (a governed data and measurement record)?",
        "inquiry": "pathway declaration (studio)",
        "srl_slot": "",
        "srl_focus": "",
        "claim_permitted": "\"My pathway is declared: route, warrant, ruled-out contrast, claim boundary, and hybrid decision — versioned before any result exists.\"",
        "claim_not_permitted": "A route label without a Contract-based warrant, or a boundary sentence that quietly keeps verbs the route does not license.",
        "rdss_reading": "(no new reading — studio Friday; bring your complete M4 draft)",
        "cb_reading": "",
        "other_material": "week05 quiz (printed); nb05 student notebook (route hub) — recap reference (Colab); M5 Brightspace brief",
        "provenance": "course studio protocol + crosswalk M4 + M4/M5 Brightspace briefs + GenAI Studio reviewer bench | weekly Friday studio | pathway-declaration assembly + recommended Causal Identification Skeptic review + M5 kickoff | newly-constructed-from-source-concept",
        "concepts": "the pathway declaration as a versioned commitment; the M4 checklist (route, warrant, contrast, boundary, hybrid); the recommended GenAI Studio 'Causal Identification Skeptic' pass; the M5 deliverable (data + measurement governance); milestone hand-off (M4 -> M5)",
        "python_r_dependency": "none required (declaration assembly; nb05 open for reference)",
        "dataset_simulation": "student's own project materials (no shared dataset today)",
        "minute_dynamic": "0–10 weekly topic quiz: five multiple-choice questions on the week's topic, answered solo on paper and handed in; 10–15 research stand-up: each project states its route, its ruled-out contrast, and one unresolved risk; 15–45 milestone kickoff from the Brightspace brief + AI-supported sprint: present the M5 deliverable and rubric (how data reach you, provenance, permission, measurement), then work the M4 checklist — route, warrant, contrast, boundary, hybrid decision — and run the recommended GenAI Studio 'Causal Identification Skeptic' review on the declaration (the identification argument your route claims, or your defense that your language stays descriptive); 45–50 revise, update Ledger + dossier, submit M4 + Claim Ticket.",
        "hands_on_activity": "Apply the M4 checklist to your declaration, run the recommended Causal Identification Skeptic review, patch the weakest sentence, and submit M4.",
        "practice": "📝 studio log: record the one word in your boundary sentence the skeptic review attacked, and the verb you replaced it with.",
        "discussion_prompt": "Which sentence in your Contract did the most work in selecting your route — and what does that tell you about where your project's risk lives?",
        "project_connection": "M4 closes today; the declared pathway decides what the M5 governed-data record must cover, starting Monday with acquisition and provenance.",
        "milestone_developed": "M4 — Pathway declaration and mandated contrast, Book Milestone 5 v1 (worked + due); M5 — Data and measurement governance, Book Milestone 6 v1 (kickoff)",
        "milestone_work_time": "30 min studio block",
        "milestone_presentation_review": "M4 worked at the studio and submitted; recommended GenAI Studio 'Causal Identification Skeptic' review logged in the Ledger",
        "student_prep": "M4 draft complete (route, warrant, contrast, boundary, hybrid decision); current Contract in hand; laptop ready.",
        "student_artifact": "Submitted M4 + skeptic-review log + first M5 acquisition notes",
        "exit_ticket": "Claim Ticket #14: the one route boundary I will carry unchanged into analysis, however inconvenient it gets.",
        "homework_next_milestone": "Submit M4 tonight (11:59 PM). Weekend: read the data-provenance lesson — Week 6 governs how data reach you and what your measures mean.",
        "instructor_prep": "Print the week05 quiz and M4 rubric; stage the M5 Brightspace brief; confirm the Causal Identification Skeptic role is live; prepare route-specific coaching prompts; consult order.",
        "risks_contingency": "Route uncertainty threatens submission time → accept a marked provisional route with the missing evidence named; skeptic reviews queue → run the declarations closest to causal language first and log the rest after class.",
    },
    # ------------------------------------------------------------------ M15
    {
        "meeting": 15, "date": "2026-09-28", "day": "Mon", "modality": "in-person",
        "unit": "Week 6 — Studio 6: Govern data and measurement",
        "title": "How data reach you: acquisition routes, provenance, and permission",
        "driving_question": "Where do your numbers actually come from — and what are you allowed to do with them?",
        "secondary_questions": "Which acquisition route does your permission status put you on: cleared, pending, or no-permission? What must a provenance record document? Why can a simulated dataset demonstrate a method but never support a claim about the world?",
        "inquiry": "all routes (data governance: acquisition, provenance, permission)",
        "srl_slot": "SRL slot 08 (randomly assigned at semester start)",
        "srl_focus": "Colleague puzzle: your colleague's dataset arrived as a bare download link — the analysis is polished, but no one can say who produced the data, when, or under what terms.",
        "claim_permitted": "\"My data reached me by [route], produced by [source] under [terms], and here is the record that proves it\" — a provenance-backed acquisition claim.",
        "claim_not_permitted": "\"The data were on the internet, so they are fine to use\" — availability is not permission, and a dataset with no provenance record cannot underwrite any claim.",
        "rdss_reading": "Required EDR|AI: the data-provenance lesson (read before today). Recommended RDSS: the data-strategy discussion in your route's design-library chapter (ch. 15–18, book.declaredesign.org).",
        "cb_reading": "",
        "other_material": "nb06 §Lecture 1 (Colab); your Contract v0 permission determination (from M3); the released colleague acquisition artifact; M5 brief",
        "provenance": "EDR|AI Studio 6 (BOOK_STATIONS govern-data-measurement acquisition note) + crosswalk M5 + rdss lapop_brazil | acquisition routes, provenance, permission | acquisition-route decision + provenance interrogation of a real survey file + labeled-simulation contrast (seed 464) | newly-constructed-from-source-concept",
        "concepts": "the three acquisition routes (cleared or determination granted; pending; no authority to ask); sampling frame and non-response as design facts; provenance (who produced it, how, when, under what terms); permission recheck against the data as they actually arrived; the no-permission route (published aggregates, openly licensed data, labeled simulation); why simulated data demonstrate a method but cannot support a claim about the world",
        "python_r_dependency": "pandas (open the file and its documentation trail), numpy (labeled-simulation contrast, seed 464)",
        "dataset_simulation": "lapop_brazil.csv interrogated as an acquisition case (the 10,000-row resample caveat IS the provenance lesson); a small labeled simulation (seed 464) for the no-permission contrast",
        "minute_dynamic": "0–9 colleague research puzzle: the SRL opens the colleague's polished analysis sitting on a bare download link, and the class lists what a provenance record would have to say before any number is usable; 9–31 guided AI research-partner investigation in nb06: with AI as research partner, interrogate lapop_brazil's provenance — who produced it, how, when, under what terms, including the course resample caveat — then settle YOUR acquisition route from your permission status, asking AI what each route forbids and verifying its answers against the acquisition guidance; 31–43 human verification + instructor formalization: the instructor formalizes the three acquisition routes, the provenance record, and the simulation boundary, and the class settles the colleague diagnosis; 43–50 decision & defense: commit your acquisition route in writing, log the Ledger entry, and write the Claim Ticket.",
        "hands_on_activity": "Interrogate a real survey file's provenance end to end, then commit your own acquisition route in writing — cleared, pending, or no-permission — with the first row of your provenance record.",
        "practice": "📝 nb06 practice: for three arrival stories (an emailed spreadsheet, a scraped table, an openly licensed archive), write the provenance row each requires and name the one that cannot yet be used.",
        "discussion_prompt": "Your permission status is 'pending'. What can you honestly build this week without touching people — and what must wait?",
        "project_connection": "Your acquisition route and first provenance rows open the M5 governed-data record due at this Friday's studio.",
        "milestone_developed": "M5 — Data and measurement governance, Book Milestone 6 v1 (dev)",
        "milestone_work_time": "7 min (acquisition route + first provenance rows into M5)",
        "milestone_presentation_review": "none (lecture day)",
        "student_prep": "Read the data-provenance lesson; bring your M3 Contract v0 with its permission determination; know how your data are supposed to reach you.",
        "student_artifact": "Committed acquisition route + provenance record started + colleague diagnosis note",
        "exit_ticket": "Claim Ticket #15: my acquisition route, and the one provenance fact I still cannot document.",
        "homework_next_milestone": "Grow the provenance record to every source your project touches. For Wednesday, read the measurement lesson and bring the concept your project most needs to measure.",
        "instructor_prep": "Release the week's colleague artifacts at sprint start with keys filed; verify lapop_brazil.csv loads and its resample caveat is visible in nb06; brief the SRL on the download-link puzzle.",
        "risks_contingency": "A student's data have not arrived → the pending and no-permission routes are the lesson, not the exception: build against a labeled simulation and record the route; provenance search stalls → the instructor's worked lapop_brazil record is the fallback example.",
    },
    # ------------------------------------------------------------------ M16
    {
        "meeting": 16, "date": "2026-09-30", "day": "Wed", "modality": "in-person",
        "unit": "Week 6 — Studio 6: Govern data and measurement",
        "title": "Do your measures measure your concepts? Construct, indicator, reliability, validity — and a Contract version",
        "driving_question": "When you write a number next to a concept, what evidence says the number means what you claim it means?",
        "secondary_questions": "What separates a concept, a construct, and an indicator? What do reliability and validity each ask of your instrument? Why is any measurement change a Contract version?",
        "inquiry": "all routes (measurement: construct -> indicator, reliability, validity)",
        "srl_slot": "SRL slot 09 (randomly assigned at semester start)",
        "srl_focus": "Colleague challenge: your colleague measures 'trust in institutions' with a single yes/no question and reports the result to two decimals — what is actually wrong, and what only looks wrong?",
        "claim_permitted": "\"My indicator [X] operationalizes construct [Y]; here is the gap between them, the reliability evidence I have, and what my interpretation is licensed to say.\"",
        "claim_not_permitted": "\"The variable is named trust, so it measures trust\" — a column name is not an operationalization, and precision is not validity.",
        "rdss_reading": "Required EDR|AI: the measurement lesson (read before today). Recommended RDSS: the measurement discussion in your route's design-library chapter (ch. 15–18, book.declaredesign.org).",
        "cb_reading": "",
        "other_material": "nb06 §Lecture 2 (Colab); your Contract v0 operationalization; the colleague measurement artifact; M5 brief",
        "provenance": "EDR|AI Studio 6 (BOOK_STATIONS govern-data-measurement) + crosswalk M5 (the D40 Contract revisit) + rdss lapop_brazil | construct -> indicator, reliability, validity, measurement as a Contract version | trust-index build with an item-agreement check + seeded noisy-indicator simulation (seed 464) + scored colleague audit | newly-constructed-from-source-concept",
        "concepts": "concept vs construct vs indicator; operationalization and the construct-indicator gap; the meaning sentence for each number; reliability (do the items agree with each other); validity (does the interpretation and use hold up); measurement error as uncertainty alongside sampling uncertainty, not instead of it; any measurement change is a Contract version",
        "python_r_dependency": "pandas (build an index from items), numpy (seeded noisy-indicator simulation, seed 464), matplotlib (item-agreement picture)",
        "dataset_simulation": "lapop_brazil.csv trust items combined into an index with an item-agreement check; a seeded noisy-indicator simulation (seed 464) showing a reliable-but-invalid measure",
        "minute_dynamic": "0–7 SRL-led retrieval & challenge: name Monday's three acquisition routes from memory, then the SRL opens the colleague's one-item trust measure; 7–30 intensive applied AI laboratory: with AI as research partner, write your measurement specification (construct, indicator, and the gap between them), build the trust index from real items and check whether the items agree, then run the colleague audit — find the seeded measurement flaw, defend the decision that only looks wrong, and repair the flaw with the smallest defensible correction; 30–38 peer defense + adversarial questioning: partners attack each other's measurement specification at the construct-indicator gap; 38–42 SRL synthesis + instructor accuracy lock: the lead states the room's conclusion and its uncertainty, and the instructor corrects any claim that survived challenge but is wrong before it can enter a ledger; 42–50 transfer to the final project + Ledger + Claim Ticket: settle your Contract's provisional operationalization, mark the change as a Contract version, and log the Ledger entry.",
        "hands_on_activity": "Write your measurement specification, test a real multi-item index for item agreement, audit the colleague's seeded measurement flaw, and version your Contract's operationalization.",
        "practice": "📝 nb06 practice: for three indicator choices (a GPA for 'learning', a follower count for 'influence', a self-report for 'exercise'), write the meaning sentence and name the gap a skeptic would attack.",
        "discussion_prompt": "Your instrument is reliable — the items agree beautifully. What would it take for it still to be measuring the wrong thing?",
        "project_connection": "Your measurement specification and the versioned Contract operationalization complete the M5 governed-data record for this Friday's studio.",
        "milestone_developed": "M5 — Data and measurement governance, Book Milestone 6 v1 (dev; measurement specification + Contract revisit)",
        "milestone_work_time": "8 min (measurement specification + Contract version note into M5)",
        "milestone_presentation_review": "peer defense: partner attacks your construct-indicator gap; colleague audit sheet due",
        "student_prep": "Read the measurement lesson; bring Monday's acquisition route and provenance rows plus your Contract v0 operationalization.",
        "student_artifact": "Measurement specification + item-agreement check + colleague audit sheet + Contract version note",
        "exit_ticket": "Claim Ticket #16: my key indicator, the construct it claims to measure, and the gap I will disclose rather than hide.",
        "homework_next_milestone": "Assemble the full M5 governed-data record (acquisition route, provenance, measurement specification, permission recheck) for this Friday's studio.",
        "instructor_prep": "Verify the trust-item index cells run (seed 464); stage the item-agreement picture; hold the colleague keys for the audit debrief; brief the SRL on the one-item-trust challenge.",
        "risks_contingency": "Reliability intuition stalls → exaggerate the seeded noise until the item disagreement is unmissable, then dial back; the audit runs long → the repair step ships as a written fix and the debrief moves to Friday's stand-up.",
    },
    # ------------------------------------------------------------------ M17
    {
        "meeting": 17, "date": "2026-10-02", "day": "Fri", "modality": "in-person",
        "unit": "Week 6 — Studio 6: Govern data and measurement",
        "title": "Studio Friday — data and measurement governed: M5 due, M6 kickoff",
        "driving_question": "Can you show where every number came from, what it measures, and under what permission — before any analysis runs?",
        "secondary_questions": "Does your provenance record cover every source? Does your measurement specification survive a skeptic? What does the M6 brief ask for (a first executable analysis, with the URC abstract internal gate next Friday)?",
        "inquiry": "all routes (studio: the governed-data checkpoint + Contract revisit)",
        "srl_slot": "",
        "srl_focus": "",
        "claim_permitted": "\"My data are governed: acquisition route recorded, provenance documented, measures specified with their gaps named, permissions rechecked against the data as they arrived.\"",
        "claim_not_permitted": "\"The data are fine — I will document them later\" — a result computed on ungoverned data inherits every problem you declined to record.",
        "rdss_reading": "(no new reading — studio Friday; bring your complete M5 governed-data record)",
        "cb_reading": "",
        "other_material": "week06 quiz (printed); nb06 student notebook (data + measurement governance) — recap reference (Colab); M6 Brightspace brief",
        "provenance": "course studio protocol + crosswalk M5 (Contract revisit at the studio) + M5/M6 Brightspace briefs | weekly Friday studio | governed-data assembly + Contract versioning + M6 kickoff | newly-constructed-from-source-concept",
        "concepts": "the governed-data record as a submission; the Contract operationalization settled and versioned; the permission recheck; the M6 deliverable (first executable analysis + URC abstract internal gate); milestone hand-off (M5 -> M6)",
        "python_r_dependency": "none new (own milestone work; nb06 open for reference)",
        "dataset_simulation": "student's own governed data (or a labeled simulation on the no-permission route)",
        "minute_dynamic": "0–10 weekly topic quiz: five multiple-choice questions on the week's topic, answered solo on paper and handed in; 10–15 research stand-up: each project states its acquisition route, the provenance fact it is proudest of, and the measurement gap it is disclosing; 15–45 milestone kickoff from the Brightspace brief + AI-supported sprint: present the M6 deliverable and rubric (a first executable analysis, with the URC abstract internal gate at next Friday's studio), then assemble the M5 governed-data record — provenance rows completed, measurement specification attached, permissions rechecked, Contract version logged; 45–50 revise, update Ledger + dossier, submit M5 + Claim Ticket.",
        "hands_on_activity": "Assemble and submit the M5 governed-data record, settle the Contract operationalization as a logged version, and open your M6 analysis plan.",
        "practice": "📝 studio log: record the one provenance or measurement hole a partner found in your record, and how you closed or disclosed it.",
        "discussion_prompt": "Which classmate's provenance record would survive an audit by a stranger — and what does yours still assume the reader will take on faith?",
        "project_connection": "M5 closes today; the governed data it locks are what your M6 first executable analysis is licensed to run on.",
        "milestone_developed": "M5 — Data and measurement governance, Book Milestone 6 v1 (worked + due); M6 — First executable analysis + URC abstract internal gate, Book Milestone 7 v1 (kickoff)",
        "milestone_work_time": "30 min studio block",
        "milestone_presentation_review": "M5 worked at the studio and submitted; Contract v0 operationalization revisited and versioned",
        "student_prep": "M5 governed-data record complete (acquisition route, provenance, measurement specification, permission recheck); laptop ready.",
        "student_artifact": "Submitted M5 + logged Contract version + M6 analysis-plan notes",
        "exit_ticket": "Claim Ticket #17: the provenance fact or measurement gap I disclosed today that I was most tempted to leave out.",
        "homework_next_milestone": "Submit M5 tonight (11:59 PM). Weekend: read the AI-as-programmer lesson; for Monday, bring your Contract and governed-data record — Week 7 turns your declared analysis into running code.",
        "instructor_prep": "Print the week06 quiz and M5 rubric; stage the M6 Brightspace brief; prepare route-specific governance coaching prompts; consult order.",
        "risks_contingency": "A record is incomplete at close → submit with the gaps named as gaps (a disclosed hole beats a silent one) and book an office-hours repair; quiz or stand-up overruns → protect the 30-minute sprint block.",
    },
    # ------------------------------------------------------------------ M18
    {
        "meeting": 18, "date": "2026-10-05", "day": "Mon", "modality": "in-person",
        "unit": "Week 7 — Studio 7: Produce a reproducible first analysis (build)",
        "title": "From Contract to executable pipeline: does the code run YOUR analysis?",
        "driving_question": "Does each step of the code execute the analysis you declared — or a nearby analysis that merely runs?",
        "secondary_questions": "Where can delegated code silently change the inquiry, the data, or the answer? What belongs in a pipeline map? When is a coding correction also a Contract version?",
        "inquiry": "all routes (the declaration-to-execution trace)",
        "srl_slot": "SRL slot 10 (randomly assigned at semester start)",
        "srl_focus": "Colleague puzzle: your colleague's notebook runs top to bottom without an error — and estimates a quantity the Contract never declared.",
        "claim_permitted": "\"Each code block implements a named Contract field, and I inspected the delegated lines — my pipeline runs the analysis I declared.\"",
        "claim_not_permitted": "\"It executed cleanly, so it answers my question\" — successful execution proves the code runs, not that it runs YOUR analysis.",
        "rdss_reading": "Required EDR|AI: the AI-as-programmer lesson (read before today); revisit your route lesson as your analysis needs it. Recommended RDSS: revisit ch. 5 'Declaring designs' (book.declaredesign.org) if your declared analysis needs re-anchoring.",
        "cb_reading": "",
        "other_material": "nb07 §Lecture 1 (Colab); your Contract + M5 governed-data record; the colleague pipeline artifact (unscored preview); M6 brief",
        "provenance": "EDR|AI Studio 7 steps 1–2 (BOOK_STATIONS first-analysis) + crosswalk M6 + rdss foos_etal | Contract-to-pipeline mapping | annotate-every-block correspondence exercise on a real field experiment + colleague pipeline diagnosis | newly-constructed-from-source-concept",
        "concepts": "the pipeline (input -> transformation -> estimate); declared analysis vs nearby analysis; the pipeline map (each code block annotated with the Contract field it implements); delegated-code inspection; the execution record; a coding correction as a Contract version",
        "python_r_dependency": "pandas, numpy (seed 464); route-specific libraries only where already declared",
        "dataset_simulation": "foos_etal.csv as the common demonstration pipeline; the student's own governed data for the transfer",
        "minute_dynamic": "0–9 colleague research puzzle: the SRL runs the colleague's clean-running notebook next to its Contract, and the class hunts the line where the estimated quantity stops being the declared one; 9–31 guided AI research-partner investigation in nb07: with AI as research partner, walk the common foos_etal pipeline and annotate every code block with the Contract field it implements, asking AI to explain each delegated line and verifying the explanation against what the code actually does; 31–43 human verification + instructor formalization: the instructor formalizes the pipeline map and the execution record, and the class settles where the colleague's pipeline diverged; 43–50 decision & defense: draft your own pipeline map, log the Ledger entry, and write the Claim Ticket.",
        "hands_on_activity": "Annotate every block of a real pipeline with the Contract field it implements, then map your own declared analysis block by block.",
        "practice": "📝 nb07 practice: given four code steps, identify the first point where the estimand changes — and the annotation that would have caught it.",
        "discussion_prompt": "When is a coding correction just a bug fix, and when does it change what your estimand refers to — and so demand a Contract version?",
        "project_connection": "Your pipeline map is the skeleton of the M6 first executable analysis due at this Friday's studio.",
        "milestone_developed": "M6 — First executable analysis + URC abstract internal gate, Book Milestone 7 v1 (dev)",
        "milestone_work_time": "7 min (pipeline map for your declared analysis into M6)",
        "milestone_presentation_review": "one oral defense of your highest-risk code step",
        "student_prep": "Read the AI-as-programmer lesson; bring your Contract, your M5 governed-data record, and any analysis code you already have.",
        "student_artifact": "Annotated common pipeline + own pipeline map + first code scaffold + colleague diagnosis note",
        "exit_ticket": "Claim Ticket #18: the code step most likely to change my answer, and how I will inspect it.",
        "homework_next_milestone": "Bring a runnable first-analysis scaffold to Wednesday; keep every delegated block annotated as you build.",
        "instructor_prep": "Verify the foos_etal scaffold runs in Colab; prepare the contract-code mismatch with verified output; release the colleague pipeline preview (unscored — its scored S7 audit runs in Week 8); brief the SRL on the clean-but-wrong puzzle.",
        "risks_contingency": "Environments fail in class → the printed execution trace carries the mapping work and the code runs at home; annotation drags → annotate the three highest-risk blocks and mark the rest for the scaffold homework.",
    },
    # ------------------------------------------------------------------ M19
    {
        "meeting": 19, "date": "2026-10-07", "day": "Wed", "modality": "in-person",
        "unit": "Week 7 — Studio 7: Produce a reproducible first analysis (build)",
        "title": "Execute, attach uncertainty, and trace the result to its output",
        "driving_question": "What first result does your declared analysis produce — and where is its uncertainty?",
        "secondary_questions": "Can you verify a delegated number without re-deriving everything? What belongs in an environment record? How does a claim name the exact output that supports it?",
        "inquiry": "all routes (first result + uncertainty + claim-output trace)",
        "srl_slot": "SRL slot 11 (randomly assigned at semester start)",
        "srl_focus": "Puzzle: a polished first result reports one confident number — no uncertainty, no execution record. What, exactly, has been established?",
        "claim_permitted": "\"My first result is [estimate] with [uncertainty], produced by the declared pipeline, and this claim traces to output [X], which I verified by [check].\"",
        "claim_not_permitted": "A result claim inferred from fluent AI explanation or code appearance alone — a number nobody recomputed is a rumor with decimals.",
        "rdss_reading": "Required EDR|AI: the AI-as-programmer lesson's verification sections; revisit your route lesson for the uncertainty form your result takes.",
        "cb_reading": "",
        "other_material": "nb07 §Lecture 2 (Colab); your analysis scaffold; M6 brief",
        "provenance": "EDR|AI Studio 7 (BOOK_STATIONS first-analysis + the D16 verification rule) + crosswalk M6 + rdss foos_etal | execute, uncertainty, trace | predict-then-execute common run + claim-output row + environment record | newly-constructed-from-source-concept",
        "concepts": "the point estimate and its uncertainty statement; a result reported without uncertainty is not yet a result; expected-vs-actual output comparison; the environment record; the claim-output trace; verifying delegated numbers against the data",
        "python_r_dependency": "pandas, numpy (seed 464), matplotlib (the uncertainty picture)",
        "dataset_simulation": "foos_etal.csv common run (predict the output before executing); the student's own governed data for the transfer",
        "minute_dynamic": "0–7 SRL-led retrieval & challenge: name Monday's pipeline-map rule from memory, then the SRL opens the confident-number-with-no-uncertainty result; 7–30 intensive applied AI laboratory: with AI as research partner, predict the common run's output, execute, compare expected against actual, attach the uncertainty statement in your Contract's form, and build one claim-output row — verifying one delegated number by recomputing it against the data; 30–38 peer defense + adversarial questioning: partners each verify one of the other's delegated lines and one reported number; 38–42 SRL synthesis + instructor accuracy lock: the lead states the room's conclusion and its uncertainty, and the instructor corrects any claim that survived challenge but is wrong before it can enter a ledger; 42–50 transfer to the final project + Ledger + Claim Ticket: produce your own first result with uncertainty, environment record, and trace row.",
        "hands_on_activity": "Predict, execute, and verify the common run, then produce your own first result with its uncertainty statement, environment record, and claim-output row.",
        "practice": "📝 nb07 practice: write one result sentence containing all four parts — estimate, uncertainty, population, and design boundary — for your own project.",
        "discussion_prompt": "What would make an output real but unusable for your declared claim — and how would your trace row catch it?",
        "project_connection": "Today's result, environment record, and trace row are the core of the M6 package due at this Friday's studio, where the URC abstract also faces its internal gate.",
        "milestone_developed": "M6 — First executable analysis + URC abstract internal gate, Book Milestone 7 v1 (dev; first result + uncertainty + abstract draft)",
        "milestone_work_time": "8 min (own result + trace row into M6; first URC abstract lines)",
        "milestone_presentation_review": "peer verification: partner recomputes one delegated line and one reported number",
        "student_prep": "Bring your runnable scaffold and a written expected-output prediction; read the AI-as-programmer verification sections.",
        "student_artifact": "Executed result with uncertainty + environment record + claim-output row + verified-number note",
        "exit_ticket": "Claim Ticket #19: my first result traces to output ___, and I verified it by ___.",
        "homework_next_milestone": "Assemble the complete executable v1 package for Friday and draft the 150–250-word URC abstract — the internal gate is at the studio.",
        "instructor_prep": "Verify the common run reproduces in the supported environment; prepare no-tool fallback outputs; post the URC abstract template; brief the SRL on the no-uncertainty puzzle.",
        "risks_contingency": "A student's project code does not run → the diagnosed failure plus the verified common-run trace is the honest submission path — never invent a result; execution drags → the uncertainty attachment happens on the common run and the own-project result moves to Friday's sprint.",
    },
    # ------------------------------------------------------------------ M20
    {
        "meeting": 20, "date": "2026-10-09", "day": "Fri", "modality": "in-person",
        "unit": "Week 7 — Studio 7: Produce a reproducible first analysis (build)",
        "title": "Studio Friday — first executable analysis and the abstract gate: M6 due, M7 kickoff",
        "driving_question": "Do you have one executable result with uncertainty and a defensible trace — and an abstract that claims no more than it?",
        "secondary_questions": "Does every abstract sentence use only claims the current result licenses? What does the M7 brief ask for (a clean-restart verified analysis)?",
        "inquiry": "the first-analysis checkpoint (studio + URC abstract internal gate)",
        "srl_slot": "",
        "srl_focus": "",
        "claim_permitted": "\"My M6 package holds one executable result with uncertainty and a trace, and my abstract states the estimate, its uncertainty, and its reach — nothing more.\"",
        "claim_not_permitted": "A polished abstract that outruns the executed evidence — the gate reads the abstract against the result as it exists today, not as hoped.",
        "rdss_reading": "(no new reading — studio Friday; bring your executable package and your URC abstract draft)",
        "cb_reading": "",
        "other_material": "week07 quiz (printed); nb07 student notebook (first-analysis build) — recap reference (Colab); URC abstract internal-gate checklist; M7 Brightspace brief",
        "provenance": "course studio protocol + crosswalk M6 (the fixed Oct 9 internal gate) + M6/M7 Brightspace briefs | weekly Friday studio | M6 assembly + URC abstract internal gate + M7 kickoff | newly-constructed-from-source-concept",
        "concepts": "the executable-first-run checkpoint; the URC abstract as an uncertainty-bearing public commitment; the internal gate (every abstract claim traces to the current result); the M7 deliverable (clean-restart verification); milestone hand-off (M6 -> M7)",
        "python_r_dependency": "student's route-specific environment (one final run of the package; nb07 open for reference)",
        "dataset_simulation": "student's own governed data (or a labeled simulation on the no-permission route)",
        "minute_dynamic": "0–10 weekly topic quiz: five multiple-choice questions on the week's topic, answered solo on paper and handed in; 10–15 research stand-up: each project states its result, its uncertainty, and its blocker in one line each; 15–45 milestone kickoff from the Brightspace brief + AI-supported sprint: present the M7 deliverable and rubric (does the result survive a clean restart?), then run the M6 submission checklist from code input through abstract claim, reading each abstract verb against the result as it exists today; 45–50 revise, update Ledger + dossier, submit M6, pass or document the abstract gate + Claim Ticket.",
        "hands_on_activity": "Run the submission checklist from code input to abstract claim, verify every abstract sentence against the executed result, submit M6, and clear (or honestly document) the internal gate.",
        "practice": "📝 abstract drill: find the one sentence a skimming reader would over-believe in your abstract, and defuse it.",
        "discussion_prompt": "Which verb in your abstract is licensed by the result as it exists today — and which one is still a promise?",
        "project_connection": "M6 closes and the abstract clears its internal gate; the exact submitted package is frozen for Week 8's clean restart, which is what M7 will test.",
        "milestone_developed": "M6 — First executable analysis + URC abstract internal gate, Book Milestone 7 v1 (worked + due); M7 — Clean-restart verified analysis, Book Milestone 7 v2 (kickoff)",
        "milestone_work_time": "30 min studio block",
        "milestone_presentation_review": "M6 worked at the studio and submitted; URC abstract internal gate cleared or documented",
        "student_prep": "Runnable package with result and uncertainty; URC abstract drafted (150–250 words); nb07 finished.",
        "student_artifact": "Submitted M6 + abstract-gate record + M7 kickoff notes",
        "exit_ticket": "Claim Ticket #20: my gate status — pass / revise / not yet evidenced — and the sentence that decided it.",
        "homework_next_milestone": "Submit M6 tonight (11:59 PM) and preserve the EXACT submitted package untouched — Week 8 restarts it clean. No class Monday (October Break). For Wednesday, read the AI-as-analytical-assistant lesson.",
        "instructor_prep": "Print the week07 quiz and the internal-gate checklist; stage the M7 Brightspace brief; confirm the internal-gate mechanics (the gate binds today regardless of the external portal); consult order.",
        "risks_contingency": "External URC portal shifts → the internal gate stands and abstracts forward when the portal opens; a failed execution at the deadline → it is submitted as the diagnosed finding it is, never converted into a claimed result.",
    },
    # ------------------------------------------------------------------ M21
    {
        "meeting": 21, "date": "2026-10-14", "day": "Wed", "modality": "in-person",
        "unit": "Week 8 — Studio 7: Verify the first analysis (clean restart)",
        "title": "The clean restart: does your result survive, and does every claim still trace?",
        "driving_question": "Does the submitted result reappear from a clean state — and if a number moves, what is the finding?",
        "secondary_questions": "Which of your values can be independently rederived? What does a discrepancy diagnose — data, environment, order, code, or the claim trace? If your route is prediction, is your language backed by unseen-case evidence, or is a leak feeding the score?",
        "inquiry": "all routes (reproducibility + claim trace); the prediction route adds the leakage branch",
        "srl_slot": "SRL slot 12 (randomly assigned at semester start)",
        "srl_focus": "Colleague challenge: a fresh run of your colleague's frozen package changes the headline number — and the prediction branch is also quietly feeding the model information from the future.",
        "claim_permitted": "\"My result survived a clean restart: fresh run, matching outputs, two independently rederived numbers, every claim traced — or here is the discrepancy, diagnosed and owned as the finding.\"",
        "claim_not_permitted": "\"The earlier (or later) output is the right one\" argued from its order alone — a discrepancy is diagnosed, never adjudicated by preference.",
        "rdss_reading": "Required EDR|AI: the AI-as-analytical-assistant lesson (read before today); revisit the AI-as-programmer lesson's verification sections.",
        "cb_reading": "optional: callingbullshit.org module on big-data and algorithm hype",
        "other_material": "nb08 (Colab); your frozen M6 package + environment record; the colleague verification artifact (scored audit); M7 brief",
        "provenance": "EDR|AI Studio 7 steps 3–4 (BOOK_STATIONS first-analysis) + crosswalk M7 + rdss foos_etal + rdss la_voter_file | clean restart, rederivation, leakage | restart-and-run-all with output comparison + two independent rederivations + planted prediction leak (seed 464) + scored colleague audit | newly-constructed-from-source-concept",
        "concepts": "the clean restart (restart and run all from a fresh state); run history and the environment record; independent rederivation; the discrepancy taxonomy (data, environment, order, code, claim-trace); if the numbers move, the pipeline is the finding; data leakage as unseen-case dishonesty; the verified claim-output table",
        "python_r_dependency": "the same declared environment, recreated from its record; pandas, numpy (seed 464); scikit-learn on the prediction branch",
        "dataset_simulation": "foos_etal.csv common clean run; la_voter_file.csv prediction branch with a planted leak (seed 464); the student's frozen package",
        "minute_dynamic": "0–7 SRL-led retrieval & challenge: name the four parts of a result sentence from memory, then the SRL opens the colleague package whose fresh run changed the number; 7–30 intensive applied AI laboratory: with AI as research partner, restart the common package and run all, compare outputs against the frozen record, independently recompute two quantities, and run the scored colleague audit — diagnose the changed number, and on the prediction branch find the planted leak — classifying every discrepancy by its taxonomy; 30–38 peer defense + adversarial questioning: partners defend one discrepancy diagnosis and one independently recomputed number against attack; 38–42 SRL synthesis + instructor accuracy lock: the lead states the room's conclusion and its uncertainty, and the instructor corrects any claim that survived challenge but is wrong before it can enter a ledger; 42–50 transfer to the final project + Ledger + Claim Ticket: restart your own frozen package, log the run history, and start the M7 verification record.",
        "hands_on_activity": "Restart and run everything clean, compare against the frozen record, independently recompute two quantities, and diagnose every discrepancy — catching the planted leak if prediction is your route.",
        "practice": "📝 nb08 practice: classify five discrepancy stories as data, environment, order, code, or claim-trace failures — and name the one that is actually a finding.",
        "discussion_prompt": "When does a clean-restart difference stop being a bug and become the finding your project reports?",
        "project_connection": "Your clean-run log, rederivations, and discrepancy decisions are the M7 verification record due at this Friday's studio.",
        "milestone_developed": "M7 — Clean-restart verified analysis, Book Milestone 7 v2 (dev)",
        "milestone_work_time": "8 min (own-package restart started + run history into M7)",
        "milestone_presentation_review": "peer defense of one discrepancy diagnosis and one rederived number; colleague audit sheet due",
        "student_prep": "Bring the frozen M6 package and its environment record UNTOUCHED since submission; read the AI-as-analytical-assistant lesson.",
        "student_artifact": "Clean-run log + two independent rederivations + discrepancy diagnoses + colleague audit sheet",
        "exit_ticket": "Claim Ticket #21: my result did / did not survive the clean restart, because ___.",
        "homework_next_milestone": "Complete the M7 verification record (run history, rederivations, discrepancy decisions, verified claim-output table) for Friday's studio.",
        "instructor_prep": "Prepare the clean environment and the altered-output fallback; engineer the prediction leak (seed 464); release the scored colleague verification artifacts with keys filed; brief the SRL on the changed-number challenge.",
        "risks_contingency": "Local environments will not recreate → a fresh hosted runtime stands in and the environment change is recorded, never hidden; the leak is found too fast → the subtler second discrepancy in the colleague artifact extends the audit.",
    },
    # ------------------------------------------------------------------ M22
    {
        "meeting": 22, "date": "2026-10-16", "day": "Fri", "modality": "in-person",
        "unit": "Week 8 — Studio 7: Verify the first analysis (clean restart)",
        "title": "Studio Friday — the verified first result: M7 due, M8 kickoff",
        "driving_question": "Can another clean run recover your result and its uncertainty — and does your verification record prove it?",
        "secondary_questions": "Are your discrepancies resolved or honestly bounded? What does the M8 brief ask for (a robustness audit whose checks are pre-listed before any run)?",
        "inquiry": "the first-analysis revisit (studio: clean-restart verification)",
        "srl_slot": "",
        "srl_focus": "",
        "claim_permitted": "\"My verified result stands on a clean-run record: run history, two independent rederivations, discrepancies resolved or bounded, every claim traced to a verified output.\"",
        "claim_not_permitted": "A reproducibility claim without an execution record — 'it ran for me' is testimony, not verification.",
        "rdss_reading": "(no new reading — studio Friday; bring your complete M7 verification record)",
        "cb_reading": "",
        "other_material": "week08 quiz (printed); nb08 student notebook (clean-restart verification) — recap reference (Colab); GenAI Studio 'Prediction & Leakage Auditor' role; M8 Brightspace brief",
        "provenance": "course studio protocol + crosswalk M7 + GenAI Studio reviewer bench + M7/M8 Brightspace briefs | weekly Friday studio | verification-record assembly + recommended Prediction & Leakage Auditor review + M8 kickoff | newly-constructed-from-source-concept",
        "concepts": "the verification record as a submission; discrepancies resolved vs honestly bounded; the recommended GenAI Studio 'Prediction & Leakage Auditor' pass (out-of-sample and prediction claims); pre-listing stress tests before running them; milestone hand-off (M7 -> M8)",
        "python_r_dependency": "student's declared environment (final verification run; nb08 open for reference)",
        "dataset_simulation": "student's own frozen package and verification record",
        "minute_dynamic": "0–10 weekly topic quiz: five multiple-choice questions on the week's topic, answered solo on paper and handed in; 10–15 research stand-up: each project reports its clean-run status and one remaining concern; 15–45 milestone kickoff from the Brightspace brief + AI-supported sprint: present the M8 deliverable and rubric (a robustness audit whose checks are pre-listed before any run), then finish the M7 verification record — resolve or bound the last discrepancy, lock the claim-output table, and run the recommended GenAI Studio 'Prediction & Leakage Auditor' review on any out-of-sample or prediction claim; 45–50 revise, update Ledger + dossier, submit M7 + Claim Ticket.",
        "hands_on_activity": "Resolve or honestly bound your final discrepancy, lock the claim-output trace, run the recommended Prediction & Leakage Auditor review, and submit M7.",
        "practice": "📝 during the sprint: name the part of your result that remains least independently checked — and what one more check would cost.",
        "discussion_prompt": "What did the auditor — human or AI — catch in your verification record that you had stopped seeing, and why had you stopped seeing it?",
        "project_connection": "M7 closes the first-analysis arc as Book Milestone 7 v2; M8 opens the stress-test week, whose checks you pre-list before running anything.",
        "milestone_developed": "M7 — Clean-restart verified analysis, Book Milestone 7 v2 (worked + due); M8 — Robustness audit, Book Milestone 8 v1 (kickoff)",
        "milestone_work_time": "30 min studio block",
        "milestone_presentation_review": "M7 worked at the studio and submitted; recommended GenAI Studio 'Prediction & Leakage Auditor' review logged in the Ledger",
        "student_prep": "M7 verification record complete (run history, rederivations, discrepancy decisions, claim-output table); GenAI Studio access confirmed.",
        "student_artifact": "Submitted M7 + auditor-review log + first pre-listed stress tests",
        "exit_ticket": "Claim Ticket #22: the strongest evidence that my result is reproducible, and the discrepancy I bounded rather than resolved.",
        "homework_next_milestone": "Submit M7 tonight (11:59 PM). Weekend: pre-list your first proposed stress tests WITHOUT running any of them, and read the robustness and sensitivity lesson for Monday.",
        "instructor_prep": "Print the week08 quiz and M7 rubric; stage the M8 Brightspace brief; confirm the Prediction & Leakage Auditor role is live; consult order.",
        "risks_contingency": "GenAI Studio unavailable → a provided AI fallback auditor prompt stands in and the review is logged when the service returns; an unresolved discrepancy at the deadline → it is reported as unresolved and blocks stronger downstream claims, never papered over.",
    },
]
