"""Meetings M34–M44 (Nov 13 – Dec 11): end of Phase 6 (rehearsal), Phase 7
(reflection & redesign), Phase 8 (reproducibility, brief, Evidence Defense)."""

MEETINGS_P4 = [
    # ------------------------------------------------------------------ M34
    {
        "meeting": 34, "date": "2026-11-13", "day": "Fri", "modality": "in-person",
        "unit": "Phase 6 — Conference preparation",
        "title": "Delivery III: hard questions — building and drilling your question bank",
        "driving_question": "What is the hardest fair question a stranger could ask at your poster — and what will you say?",
        "secondary_questions": "What question types recur (method, alternative explanation, so-what, generalization, AI-use)? What does a good 'I don't know' contain? When do you defend vs concede?",
        "approach": "all (communication)",
        "claim_permitted": "\"I don't know — but here is what I do know that bears on it, and here is how one would find out.\"",
        "claim_not_permitted": "Bluffing an answer you don't have (the one move that can destroy a presenter's credibility entirely).",
        "rdss_reading": "(fresh unit)",
        "cb_reading": "",
        "other_material": "nb15 §4 (Colab); hard-question taxonomy; M14 due tonight",
        "provenance": "brief §12 P6 + fresh question taxonomy | conference unit | Q&A drill protocol | fresh",
        "concepts": "question taxonomy; the honest-don't-know formula; defend vs concede judgment; question banks as preparation",
        "python_r_dependency": "none",
        "dataset_simulation": "each student's own project",
        "minute_dynamic": "0–5 ULN redux (one volunteer, cold); 5–12 mini-lesson: the five question types with a real example of each + the honest-don't-know formula; 12–24 bank-building studio: write the 5 hardest fair questions for YOUR poster, one per type, with answer sketches (M14 bank); 24–44 HOT-SEAT ROUNDS: each student takes 3 minutes of rapid questions from the class (drawn from their bank + surprises), instructor models one save; 44–48 bank revision from what the hot seat exposed; 48–50 exit ticket + M14 due tonight.",
        "hands_on_activity": "Build your 5-question bank, then survive a 3-minute hot seat on it in front of the class.",
        "practice": "📝 nb15 practice: classify 6 sample audience questions by type; draft the don't-know answer for the worst one.",
        "discussion_prompt": "Which classmate's hot-seat save impressed you most — what exactly did they do?",
        "project_connection": "M14 completes tonight: statement + question bank = the intellectual armor for Nov 17.",
        "milestone_developed": "M14 — Uncertainty & Limitations Statement + Question Bank (submitted TONIGHT)",
        "milestone_work_time": "12 min (bank building) + 20 min (hot seats)",
        "milestone_presentation_review": "hot-seat rounds (this is the presentation/review)",
        "student_prep": "M14 statement drafted; poster content cold.",
        "student_artifact": "5-question bank with answer sketches + hot-seat performance",
        "exit_ticket": "Claim Ticket #34: the question I most fear on Nov 17, and my first sentence in reply.",
        "homework_next_milestone": "Submit M14 tonight 11:59 PM. Monday: full dress rehearsal — bring the poster (printed or full-screen) and both pitches.",
        "instructor_prep": "Surprise-question deck per project; timer; model-save planned.",
        "risks_contingency": "Hot seats run hot emotionally → instructor interposes as question-asker-of-record and slows cadence; the drill's purpose (safety through practice) is renamed aloud.",
    },
    # ------------------------------------------------------------------ M35
    {
        "meeting": 35, "date": "2026-11-16", "day": "Mon", "modality": "in-person",
        "unit": "Phase 6 — Conference preparation",
        "title": "Dress rehearsal: the full URC simulation — readiness audited",
        "driving_question": "Tomorrow is the real thing. Is every piece — poster, pitch, ULN, question bank, logistics — actually ready?",
        "secondary_questions": "Does the full 3-minute walk land inside time? Do transitions between pitch and Q&A feel natural? Is the logistics checklist (location, time, dress, materials) complete?",
        "approach": "all (communication)",
        "claim_permitted": "\"Readiness audit passed: rehearsed twice, question bank drilled, logistics confirmed — signed.\"",
        "claim_not_permitted": "\"I'll wing it tomorrow.\" (Rehearsal is the difference between nerves and panic.)",
        "rdss_reading": "(none — rehearsal day)",
        "cb_reading": "",
        "other_material": "nb15 §5 readiness audit (Colab); URC Expo logistics sheet",
        "provenance": "brief §12 P6 + fresh readiness audit | conference unit | full-dress simulation protocol | fresh",
        "concepts": "full-dress simulation; readiness auditing; pre-performance routine; logistics discipline",
        "python_r_dependency": "none",
        "dataset_simulation": "each student's own complete conference package",
        "minute_dynamic": "0–4 rehearsal norms: run it like it's real, notes after not during; 4–44 FULL SIMULATION: two 20-minute stations rounds — in each round, 2–3 posters are 'live' with presenters standing them while the rest of class + instructor rotate as conference visitors (1-min pitches, 3-min walks, hard questions, ULN moments all get exercised); 44–48 readiness audit: sign the M15 checklist (rehearsed / drilled / logistics / materials); 48–50 final word + tomorrow's call time.",
        "hands_on_activity": "Stand your poster through a full simulated conference round; visit others as a critical-but-kind stranger.",
        "practice": "📝 (embedded) the visitor role card: ask at least one question from each of the five types across your visits.",
        "discussion_prompt": "(post-simulation, 2 min) One thing you saw a classmate do that you're stealing for tomorrow.",
        "project_connection": "M15 readiness audit signed — the last gate before the real URC Expo tomorrow (Nov 17).",
        "milestone_developed": "M15 — Dress Rehearsal + Readiness Audit (completed TODAY) → M16 — URC Expo Presentation (tomorrow)",
        "milestone_work_time": "40 min (simulation) + 4 min (audit)",
        "milestone_presentation_review": "the full-dress simulation IS the presentation/review",
        "student_prep": "Poster ready (printed or presentable); both pitches cold; question bank internalized.",
        "student_artifact": "Signed readiness audit + rehearsal performance",
        "exit_ticket": "(on the audit sheet) The one thing I will do differently tomorrow because of today.",
        "homework_next_milestone": "URC EXPO TOMORROW (Tue Nov 17) — M16, required presentation. Wednesday: debrief; bring every question you were asked.",
        "instructor_prep": "Room setup for stations; visitor role cards; confirm Expo logistics (time/place/setup) and communicate call time.",
        "risks_contingency": "A poster's print failed → present full-screen today; emergency print run resolved before Tuesday (backup plan pre-arranged).",
    },
    # ------------------------------------------------------------------ M36
    {
        "meeting": 36, "date": "2026-11-18", "day": "Wed", "modality": "in-person",
        "unit": "Phase 7 — Reflection, feedback, redesign",
        "title": "Conference debrief: what the audience taught you",
        "driving_question": "What did strangers' questions reveal about your project that friends' questions never could?",
        "secondary_questions": "Which questions recurred? Where did the pitch work and where did it wobble? What feedback is signal vs noise?",
        "approach": "all (reflection)",
        "claim_permitted": "\"The audience data says: X landed, Y confused, Z was asked three times — here is what that evidences about my project.\"",
        "claim_not_permitted": "Treating applause as validation of the CLAIMS (a warm reception measures communication, not truth).",
        "rdss_reading": "(none — debrief day)",
        "cb_reading": "",
        "other_material": "nb16 §1–2 (Colab); M17 reflection template",
        "provenance": "brief §12 P7 + fresh debrief protocol | reflection unit | audience-data analysis | fresh",
        "concepts": "feedback as data; signal/noise triage; recurring-question analysis; the debrief discipline",
        "python_r_dependency": "none (a provided tally cell if wanted)",
        "dataset_simulation": "each student's collected conference questions/reactions",
        "minute_dynamic": "0–8 STORY ROUND: 90 seconds each — the single most surprising moment at your poster; 8–15 mini-lesson: feedback is data — code it like data (recurred? from whom? about claims or communication?); 15–32 coding studio: log every question you received into the nb16 tally (type, target, recurrence), find your pattern (M17 core); 32–44 pair analysis: swap tallies — what does your partner's pattern say that they can't see?; 44–48 reflection freewrite: the honest paragraph (what the conference changed in how I see my project); 48–50 exit ticket.",
        "hands_on_activity": "Code your conference questions like data and find the recurring pattern; read a partner's pattern back to them.",
        "practice": "📝 nb16 practice: classify 6 pieces of received feedback as claims-signal, communication-signal, or noise.",
        "discussion_prompt": "What question did you get that the class's hot seats never predicted — and why did we miss it?",
        "project_connection": "The coded audience data feeds M17 (reflection) tonight and M18 (redesign plan) Friday.",
        "milestone_developed": "M17 — Conference Reflection (submit tonight)",
        "milestone_work_time": "17 min (coding studio) + 12 min (pair analysis) + 4 min (freewrite)",
        "milestone_presentation_review": "story round + pair pattern-reading",
        "student_prep": "URC presented (M16 ✓); every question you were asked, captured.",
        "student_artifact": "Coded question tally + reflection paragraph (submitted as M17 tonight)",
        "exit_ticket": "Claim Ticket #36: the most repeated audience question, and what its repetition evidences.",
        "homework_next_milestone": "Submit M17 tonight 11:59 PM. Friday: feedback → redesign (bring your tally).",
        "instructor_prep": "Own observation notes from the Expo per student; tally template checked.",
        "risks_contingency": "A student missed the Expo (illness/emergency) → the documented make-up presentation is scheduled (department session or recorded defense), debrief uses rehearsal data meanwhile.",
    },
    # ------------------------------------------------------------------ M37
    {
        "meeting": 37, "date": "2026-11-20", "day": "Fri", "modality": "in-person",
        "unit": "Phase 7 — Reflection, feedback, redesign",
        "title": "Feedback → redesign: if you ran it again, what would you change — and what do you change NOW?",
        "driving_question": "Given everything the audience and the semester taught you, what is the honest redesign of your study?",
        "secondary_questions": "Which feedback maps to which MIDA letter? What is worth changing in the two weeks that remain vs in the imagined next study? How does redesign differ from regret?",
        "approach": "all (diagnosis + redesign, applied to one's own project)",
        "claim_permitted": "\"Feedback item F implicates my [M/I/D/A]; the redesign is R; diagnosed benefit: better [diagnosand].\"",
        "claim_not_permitted": "A redesign wish-list with no mapping to the design (\"more data, more time\" is a lament, not a redesign).",
        "rdss_reading": "RDSS ch. 11 'Redesigning' (revisited, now with real audience data)",
        "cb_reading": "",
        "other_material": "nb16 §3–4 (Colab); M18 redesign-plan template",
        "provenance": "RDSS ch.11 + brief §12 P7 | redesigning with realized feedback | feedback→MIDA mapping protocol | extended",
        "concepts": "feedback→MIDA mapping; now-vs-next triage; the redesign memo as scientific product; closing the declare→diagnose→redesign loop on oneself",
        "python_r_dependency": "optional: rerun one diagnosis cell with post-conference parameters",
        "dataset_simulation": "each student's coded tally + their nb11 design declaration",
        "minute_dynamic": "0–5 tally patterns recap (two headlines); 5–12 mini-lesson: mapping feedback onto MIDA — three worked examples (a question about generalization → D; about mechanism → M; about so-what → I); 12–30 redesign studio: map your top-3 feedback items to letters, propose the redesign for each, mark each NOW or NEXT (M18 core), rotating consults; 30–42 REDESIGN DECLARATIONS: 2 minutes each — my most important redesign, its letter, its diagnosed benefit; 42–48 lock the NOW items into your dossier task list; 48–50 exit ticket.",
        "hands_on_activity": "Map your three biggest feedback items onto MIDA letters and declare a redesign for each, triaged NOW vs NEXT.",
        "practice": "📝 nb16 practice: 4 feedback quotes — name the MIDA letter each implicates before proposing anything.",
        "discussion_prompt": "Which is harder to admit: a data-strategy flaw (D) or a question that wasn't worth asking (I)? Why?",
        "project_connection": "M18 redesign plan submits tonight; its NOW items become the dossier work plan (M19+).",
        "milestone_developed": "M18 — Feedback-to-Redesign Plan (submitted TONIGHT)",
        "milestone_work_time": "18 min (studio + consults)",
        "milestone_presentation_review": "M18 presented: 2-minute redesign declarations",
        "student_prep": "M17 submitted; coded tally in hand.",
        "student_artifact": "Feedback→MIDA map + triaged redesign plan (submitted tonight)",
        "exit_ticket": "Claim Ticket #37: my #1 redesign, its MIDA letter, and whether it is NOW or NEXT.",
        "homework_next_milestone": "Submit M18 tonight 11:59 PM. MONDAY IS ASYNC (nb17): the Poster-to-Dossier module — budget ~50 focused minutes before Thanksgiving; artifact due Mon Nov 30.",
        "instructor_prep": "Worked mapping examples; consult order; dossier task-list template staged for the async module.",
        "risks_contingency": "Post-conference deflation → the mini-lesson opens by naming it (every researcher's post-conference dip) and the studio's small wins reset momentum.",
    },
    # ------------------------------------------------------------------ M38
    {
        "meeting": 38, "date": "2026-11-23", "day": "Mon", "modality": "async-online",
        "unit": "Phase 7 — Reflection, feedback, redesign",
        "title": "ASYNC — Poster-to-Dossier module: robustness, sensitivity, and the claim ledger",
        "driving_question": "Your poster compressed the truth. The dossier must carry ALL of it — what does that require?",
        "secondary_questions": "What is a robustness/sensitivity check for YOUR approach? What is a claim ledger and why does every claim get a row? How does a methods section differ from a methods memory?",
        "approach": "project-specific (each student works in their own approach's branch)",
        "claim_permitted": "\"Claim C survives sensitivity checks S1–S2; its ledger row records claim, evidence, check, boundary.\"",
        "claim_not_permitted": "Porting poster claims into the dossier WITHOUT re-verification (the dossier's standard is higher, not equal).",
        "rdss_reading": "RDSS ch. 22 'Realization' (book.declaredesign.org) — reporting what actually happened",
        "cb_reading": "",
        "other_material": "nb17 — fully self-contained async module (Colab); claim-ledger template; M19 spec",
        "provenance": "brief §10 M19 + RDSS ch.22 | realization/reporting | claim-ledger method + approach-branched sensitivity menu | newly-constructed-from-source-concept",
        "concepts": "robustness/sensitivity by approach (description: alternative summaries/bins; inference: specification + non-response probes; prediction: split/metric perturbation; causal: assumption probes); the claim ledger; methods-section discipline",
        "python_r_dependency": "pandas/numpy (rerun own pilot under perturbations — approach-branched cells)",
        "dataset_simulation": "each student's own project data/pilot",
        "minute_dynamic": "ASYNC (~50 min self-paced): 0–8 module orientation + choose your approach branch; 8–25 run the branch's two sensitivity checks on your own pilot, record what moved; 25–38 build your claim ledger (every poster claim gets a row: claim, evidence, verification, boundary, survived-sensitivity?); 38–48 draft the dossier's methods+findings skeleton from the ledger; 48–50 submit checkpoint + (async board) post your ledger's most fragile row.",
        "hands_on_activity": "Run two approach-appropriate sensitivity checks on your own pilot and build the claim ledger from the results.",
        "practice": "📝 nb17 practice: one sample fragile claim — write its ledger row honestly, then its dossier sentence.",
        "discussion_prompt": "(async board) Your most fragile ledger row: post it, and reply to one classmate with a check that could shore theirs up.",
        "project_connection": "M19 = the dossier's analytical core; every December artifact builds on this module's output.",
        "milestone_developed": "M19 — Poster-to-Dossier Module (artifact due Mon Nov 30)",
        "milestone_work_time": "the whole module is milestone work (~50 min)",
        "milestone_presentation_review": "async board: fragile-row post + one shoring reply",
        "student_prep": "M18 submitted; own pilot notebook runnable.",
        "student_artifact": "Sensitivity outputs + claim ledger + methods/findings skeleton (due Nov 30)",
        "exit_ticket": "(embedded) Claim Ticket #38: my most fragile claim and what the sensitivity check did to it.",
        "homework_next_milestone": "Happy Thanksgiving. M19 artifact due Mon Nov 30, 11:59 PM (class resumes in person that day: reproducibility).",
        "instructor_prep": "Verify all four approach branches run end-to-end unattended; seed the board; holiday-proof the deadlines in Brightspace.",
        "risks_contingency": "Holiday-week attrition → module is doable in one sitting, deadline is AFTER break, and Wednesday-before-break reminder goes out with a progress checkpoint.",
    },
    # ------------------------------------------------------------------ M39
    {
        "meeting": 39, "date": "2026-11-30", "day": "Mon", "modality": "in-person",
        "unit": "Phase 8 — Reproducibility, brief, Evidence Defense",
        "title": "Reproducibility I: could a stranger rebuild your findings from what you hand them?",
        "driving_question": "If you vanished today, could a competent stranger reproduce every number in your dossier?",
        "secondary_questions": "What belongs in a reproducibility package (data provenance, environment, seed, decision log)? What is the AI-use ledger's role? Where do projects usually break?",
        "approach": "all (reproducibility)",
        "claim_permitted": "\"A classmate reproduced my headline number from my package alone — verified [date], discrepancies: none/listed.\"",
        "claim_not_permitted": "\"It works on my machine\" — reproducibility claimed but never exercised by another human.",
        "rdss_reading": "RDSS ch. 21 'Planning' + ch. 22 'Realization' (reproducibility threads; book.declaredesign.org)",
        "cb_reading": "",
        "other_material": "nb18 §1–2 (Colab); reproducibility-package checklist; M20 spec",
        "provenance": "brief §12 P8 + RDSS ch.21–22 | planning/realization | reproducibility-package protocol for Colab-scale projects | extended",
        "concepts": "reproducibility package anatomy; data provenance statements; seed + environment discipline; the decision log; AI-use ledger finalization",
        "python_r_dependency": "own notebook hygiene (restart-and-run-all)",
        "dataset_simulation": "each student's own project package",
        "minute_dynamic": "0–5 December map: three weeks, three artifacts (package, brief, defense) — then done; 5–12 mini-lesson: the package checklist walked on a real example, incl. where projects usually break (paths, seeds, undocumented by-hand steps); 12–30 package studio: assemble YOUR package — restart-and-run-all, fix breaks, write the provenance + decision log stubs (M20); 30–44 EXCHANGE ROUND 1: swap packages with a partner; partner attempts the headline-number reproduction cold while you watch silently; 44–48 log what broke; 48–50 exit ticket.",
        "hands_on_activity": "Restart-and-run-all your own notebook, then watch a partner try to reproduce your headline number from your package alone.",
        "practice": "📝 nb18 practice: 5 package sins (hard-coded path, missing seed, by-hand edit, undocumented exclusion, stale data) — find each in a sample package.",
        "discussion_prompt": "What broke first in the exchange — and would YOU have found it without a stranger's eyes?",
        "project_connection": "M20 reproducibility audit is underway; the partner exchange completes Wednesday.",
        "milestone_developed": "M20 — Reproducibility Audit",
        "milestone_work_time": "18 min (package studio) + 14 min (exchange)",
        "milestone_presentation_review": "partner reproduction attempt (round 1)",
        "student_prep": "M19 artifact submitted tonight 11:59 PM; own notebook runnable.",
        "student_artifact": "Assembled package + exchange breakage log",
        "exit_ticket": "Claim Ticket #39: the first thing that broke when a stranger ran my work, and my fix.",
        "homework_next_milestone": "Fix everything the exchange exposed; Wednesday: exchange round 2 (verification sign-off) + the research brief begins. M20 due Wed Dec 2.",
        "instructor_prep": "Sample sinful package built; pairing plan (rotate partners from red-team); checklist copies.",
        "risks_contingency": "A package is unreproducible in class time → document the failure honestly (that log IS audit evidence) and schedule the re-exchange for Wednesday.",
    },
    # ------------------------------------------------------------------ M40
    {
        "meeting": 40, "date": "2026-12-02", "day": "Wed", "modality": "in-person",
        "unit": "Phase 8 — Reproducibility, brief, Evidence Defense",
        "title": "Reproducibility II: sign-off — and the research brief begins",
        "driving_question": "Reproduction verified — now can you say what it all means on ONE page, to a decision-maker?",
        "secondary_questions": "What does a reproduction sign-off attest? What is a research brief (vs an abstract, vs a poster)? Who is your brief's reader and what do they need?",
        "approach": "all (reproducibility → communication)",
        "claim_permitted": "\"Reproduction verified by [name] on [date]\" — and, in the brief: claims sized for a reader who will never see the appendix.",
        "claim_not_permitted": "A brief that quietly restores the caveats-free claims the ledger already disciplined (the brief compresses, never un-verifies).",
        "rdss_reading": "RDSS ch. 22 (continued) + ch. 23 'Integration' opening (book.declaredesign.org)",
        "cb_reading": "",
        "other_material": "nb18 §3 (Colab); research-brief template; M20 due tonight, M21 spec",
        "provenance": "brief §12 P8 + RDSS ch.22–23 | realization/integration | one-page decision-maker brief format | extended",
        "concepts": "reproduction sign-off; the research brief genre (reader, question, finding, uncertainty, implication, one figure); compression under verification constraints",
        "python_r_dependency": "none new (final figure export)",
        "dataset_simulation": "each student's verified package + ledger",
        "minute_dynamic": "0–5 breakage-fix reports (round the room, one line each); 5–17 EXCHANGE ROUND 2: partner re-runs the fixed package and SIGNS the reproduction sign-off (or logs residuals) — M20 completes; 17–24 mini-lesson: the brief genre — one page, one reader, one figure, uncertainty on the page not in the appendix; 24–42 brief studio: draft your brief's four blocks (question/finding/uncertainty/implication) from the claim ledger, rotating consults; 42–48 read-aloud pairs: does your finding sentence survive being spoken?; 48–50 exit ticket + M20 due tonight.",
        "hands_on_activity": "Obtain a signed reproduction of your work from a partner, then draft the one-page brief from your verified ledger.",
        "practice": "📝 nb18 practice: compress a 3-sentence caveated finding into 1 sentence WITHOUT losing the caveat.",
        "discussion_prompt": "Your brief's reader has 90 seconds and decision power. What one uncertainty do they absolutely need on the page?",
        "project_connection": "M20 submits tonight with sign-off; M21 (brief) drafts today, workshops Friday.",
        "milestone_developed": "M20 (submitted TONIGHT) → M21 — Research Brief",
        "milestone_work_time": "12 min (sign-off exchange) + 18 min (brief studio)",
        "milestone_presentation_review": "reproduction sign-off + read-aloud pairs",
        "student_prep": "Package fixes applied from Monday's log.",
        "student_artifact": "Signed reproduction attestation + brief draft (4 blocks)",
        "exit_ticket": "Claim Ticket #40: my finding sentence, as compressed for the brief — caveat intact.",
        "homework_next_milestone": "Submit M20 tonight 11:59 PM. Polish the full brief for Friday's workshop; M21 due Fri Dec 4.",
        "instructor_prep": "Sign-off forms; brief exemplar (one page, annotated); consult order.",
        "risks_contingency": "Residual reproduction failures → the sign-off logs them as known residuals with cause; the audit grade weighs the honesty of the log, not just a clean pass.",
    },
    # ------------------------------------------------------------------ M41
    {
        "meeting": 41, "date": "2026-12-04", "day": "Fri", "modality": "in-person",
        "unit": "Phase 8 — Reproducibility, brief, Evidence Defense",
        "title": "The research brief workshop — and staging the Evidence Defense",
        "driving_question": "Does your one page do justice to fourteen weeks — and can you now defend it out loud?",
        "secondary_questions": "Where does the brief still overclaim or underclaim? What is the Evidence Defense format? What gets defended (the claims, the choices, the verification)?",
        "approach": "all (communication)",
        "claim_permitted": "\"Every sentence on this page traces to a ledger row\" — the brief as the dossier's honest ambassador.",
        "claim_not_permitted": "Brief-polish that drifts from the ledger (if the wording upgrades the claim, the ledger must be upgraded first — with evidence).",
        "rdss_reading": "(none new — workshop day)",
        "cb_reading": "",
        "other_material": "nb19 §1 defense format (Colab); M21 due tonight; defense schedule posted",
        "provenance": "brief §12 P8 + fresh defense protocol | synthesis unit | Evidence Defense format | fresh",
        "concepts": "ledger-traceable writing; the Evidence Defense format (10-min defense: claims, choices, verification + 5-min cross-examination); defense-order strategy",
        "python_r_dependency": "none",
        "dataset_simulation": "each student's brief + ledger",
        "minute_dynamic": "0–5 workshop norms + defense schedule draw (who defends Mon vs Wed); 5–22 BRIEF WORKSHOP: table read — each brief passes left, 3 minutes per read with the two-question margin note (sharpest sentence? weakest claim?), full rotation; 22–30 revise from margin notes; 30–40 mini-lesson: the Evidence Defense format walked on an example — what cross-examiners may probe (any ledger row, any decision, any verification); 40–48 defense prep: pick the 3 ledger rows you'd LEAST like probed and prep them first; 48–50 exit ticket + M21 due tonight.",
        "hands_on_activity": "Full-rotation table read of all five briefs with margin notes; revise; then prep your three weakest ledger rows for defense.",
        "practice": "📝 nb19 practice: for one sample brief sentence, trace it to its ledger row — or catch that it can't be.",
        "discussion_prompt": "Which classmate's brief taught you a compression move — what was it?",
        "project_connection": "M21 submits tonight; defense prep begins for M22 (Mon/Wed defenses).",
        "milestone_developed": "M21 — Research Brief (submitted TONIGHT) → M22 — Evidence Defense (prep)",
        "milestone_work_time": "17 min (workshop) + 8 min (revision) + 8 min (defense prep)",
        "milestone_presentation_review": "table-read margin notes (all-read-all)",
        "student_prep": "Full brief polished from Wednesday's draft.",
        "student_artifact": "Margin-annotated brief + revision + weakest-rows prep sheet",
        "exit_ticket": "Claim Ticket #41: the ledger row I least want probed Monday, and my first sentence about it.",
        "homework_next_milestone": "Submit M21 tonight 11:59 PM. Defense slots: Mon Dec 7 (2–3 students) and Wed Dec 9 (2–3 students) — full dossier draft supports you.",
        "instructor_prep": "Defense schedule; example defense walk; margin-note slips; cross-examination norms card.",
        "risks_contingency": "Briefs arrive rough → the table read doubles as triage; roughest briefs get first office-hours slots before Monday.",
    },
    # ------------------------------------------------------------------ M42
    {
        "meeting": 42, "date": "2026-12-07", "day": "Mon", "modality": "in-person",
        "unit": "Phase 8 — Reproducibility, brief, Evidence Defense",
        "title": "Evidence Defense I: defend your claims, your choices, and your verification",
        "driving_question": "Under cross-examination, does your evidence hold?",
        "secondary_questions": "Can you defend not just WHAT you claim but WHY your approach, data, and checks license it? Can you concede gracefully where the ledger says concede?",
        "approach": "all (synthesis — each defense exercises its project's approaches)",
        "claim_permitted": "Exactly what each defender's claim ledger permits — the defense IS the boundary, performed.",
        "claim_not_permitted": "New claims invented under pressure; concessions retracted without evidence; blame shifted to the AI tool (the researcher verified, or didn't).",
        "rdss_reading": "(none — defense day)",
        "cb_reading": "",
        "other_material": "nb19 §2 (Colab); defense rubric; cross-examination norms",
        "provenance": "brief §12 P8 | synthesis unit | Evidence Defense session 1 | fresh",
        "concepts": "claims-choices-verification defense; cross-examination; graceful concession; the ledger as shield",
        "python_r_dependency": "none (defender may open their notebook live if probed)",
        "dataset_simulation": "defenders' own dossier materials",
        "minute_dynamic": "0–4 defense norms: rigorous, respectful, ledger-grounded; 4–19 DEFENSE 1 (10-min defense + 5-min cross-examination from class + instructor); 19–34 DEFENSE 2 (same format); 34–46 DEFENSE 3 if scheduled, else extended cross-examination + panel feedback round; 46–50 defender self-assessments (2 lines: strongest moment, moment to redo) + exit ticket.",
        "hands_on_activity": "Defend (if scheduled today) or cross-examine: every non-defender must ask at least one ledger-grounded question.",
        "practice": "📝 (cross-examiner role) probe one claim, one choice, one verification across today's defenses.",
        "discussion_prompt": "(feedback round) The single most convincing moment of defense today — what made it convincing?",
        "project_connection": "M22 in progress: half the class defends today, half Wednesday; dossiers absorb what the defenses expose.",
        "milestone_developed": "M22 — Evidence Defense (session 1 of 2)",
        "milestone_work_time": "42 min (defenses + cross-examination)",
        "milestone_presentation_review": "the defenses ARE the presentation/review",
        "student_prep": "Defenders: full command of ledger + dossier draft. All: cross-examination questions prepared.",
        "student_artifact": "Delivered defense or logged cross-examination questions + self-assessment",
        "exit_ticket": "Claim Ticket #42: one probe from today I must answer inside my own dossier before Friday.",
        "homework_next_milestone": "Wednesday: remaining defenses. All: fold today's exposures into the dossier (due Fri Dec 11).",
        "instructor_prep": "Rubrics per defender; timer; balance the cross-examination airtime; note dossier-relevant exposures per student.",
        "risks_contingency": "A defense collapses → instructor converts to a supported walkthrough (rubric notes the support), student may elect a Wednesday redo slot.",
    },
    # ------------------------------------------------------------------ M43
    {
        "meeting": 43, "date": "2026-12-09", "day": "Wed", "modality": "in-person",
        "unit": "Phase 8 — Reproducibility, brief, Evidence Defense",
        "title": "Evidence Defense II: the remaining defenses — and the dossier's final checklist",
        "driving_question": "Same standard, remaining defenders: does the evidence hold?",
        "secondary_questions": "What did two days of cross-examination reveal about what 'defensible' means? What remains between each dossier and Friday's submission?",
        "approach": "all (synthesis)",
        "claim_permitted": "As Monday — each defender's ledger, performed. Plus: \"my dossier checklist has N open items and a plan for each.\"",
        "claim_not_permitted": "As Monday. Plus: declaring the dossier done without running its final checklist.",
        "rdss_reading": "(none — defense day)",
        "cb_reading": "",
        "other_material": "nb19 §3 (Colab); defense rubric; final-dossier checklist (M23)",
        "provenance": "brief §12 P8 | synthesis unit | Evidence Defense session 2 + dossier checklist | fresh",
        "concepts": "as M42 + dossier completeness auditing",
        "python_r_dependency": "none",
        "dataset_simulation": "defenders' own dossier materials",
        "minute_dynamic": "0–3 norms recap + order; 3–33 DEFENSES (remaining 2–3, same 10+5 format); 33–43 dossier checklist run: every student opens the M23 checklist against their draft, marks open items, writes the 48-hour plan; 43–48 cross-defense synthesis: what did the strongest defenses share? (board list, becomes Friday's opening); 48–50 exit ticket.",
        "hands_on_activity": "Defend or cross-examine; then run the final-dossier checklist against your own draft and commit a 48-hour plan.",
        "practice": "📝 (cross-examiner role continues) one claim, one choice, one verification probed.",
        "discussion_prompt": "Across all five defenses: what did the convincing ones share that the shaky moments lacked?",
        "project_connection": "M22 completes; every student leaves with a concrete 48-hour path to the M23 submission.",
        "milestone_developed": "M22 — Evidence Defense (completed) → M23 — Final Dossier (checklist run)",
        "milestone_work_time": "30 min (defenses) + 10 min (checklist)",
        "milestone_presentation_review": "the defenses ARE the presentation/review",
        "student_prep": "Defenders ready; all: dossier draft current.",
        "student_artifact": "Delivered defense/cross-examination + marked checklist + 48-hour plan",
        "exit_ticket": "Claim Ticket #43: my dossier's biggest open item and exactly when I will close it.",
        "homework_next_milestone": "Close the checklist. M23 FINAL DOSSIER due Fri Dec 11, 11:59 PM (submission in class Friday = synthesis + celebration).",
        "instructor_prep": "Rubrics; redo slot if invoked; compile the strongest-defenses board list for Friday.",
        "risks_contingency": "Checklist reveals a structural gap (e.g., missing sign-off) → triage in class; office hours Thursday held open as the safety valve.",
    },
    # ------------------------------------------------------------------ M44
    {
        "meeting": 44, "date": "2026-12-11", "day": "Fri", "modality": "in-person",
        "unit": "Phase 8 — Reproducibility, brief, Evidence Defense",
        "title": "Synthesis: the four approaches, one semester, and what a defensible claim is",
        "driving_question": "You began with a curiosity. You end with a defended, reproducible, honestly-bounded claim. What do you now know about knowing?",
        "secondary_questions": "How do the four approaches divide the world of questions? What will you do differently the next time a confident claim crosses your feed — or leaves your mouth?",
        "approach": "all (synthesis)",
        "claim_permitted": "\"I can classify a question, match it to an approach, state what the answer can and cannot establish, and verify before I believe.\" — the course's exit claim.",
        "claim_not_permitted": "\"Now I know the truth about my topic.\" (You know something better: exactly how much you know, and how you'd learn more.)",
        "rdss_reading": "RDSS ch. 24 'Epilogue' (book.declaredesign.org)",
        "cb_reading": "",
        "other_material": "nb19 §4 synthesis (Colab); course-reflection survey",
        "provenance": "brief §12 P8 + RDSS ch.24 | synthesis | four-approach retrospective + exit claim | newly-constructed-from-source-concept",
        "concepts": "the four approaches as a permanent lens; the claim ledger as a life habit; verification as identity; what transfers beyond research",
        "python_r_dependency": "none",
        "dataset_simulation": "the class's own 44-meeting claim-ticket archive (aggregated, anonymous)",
        "minute_dynamic": "0–5 the strongest-defenses list from Wednesday, read back; 5–15 synthesis exercise: the SAME question analyzed all four ways on the board, one student leading each approach — the course's signature skill, performed jointly; 15–25 claim-ticket archaeology: revisit YOUR Claim Ticket #1 vs #43 — write the two-sentence 'how my standards changed'; 25–35 round: each student reads their two sentences + names the habit they're keeping; 35–43 M23 submission ceremony (dossiers in, confirmed on screen) + course reflection survey; 43–50 instructor's closing: what you now owe the world as people who know how knowing works — and goodbyes.",
        "hands_on_activity": "Analyze one shared question through all four approaches jointly; excavate your own first-vs-last Claim Tickets.",
        "practice": "📝 (retrospective) the exit self-assessment: classify, match, bound, verify — rate yourself then vs now.",
        "discussion_prompt": "What claim did you believe in August that you would now demand evidence for — and what evidence would satisfy you?",
        "project_connection": "M23 Final Dossier submitted — the semester's complete, reproducible, defended research artifact.",
        "milestone_developed": "M23 — Final Research Dossier + Claim Ledger (SUBMITTED TODAY)",
        "milestone_work_time": "8 min (submission ceremony)",
        "milestone_presentation_review": "first-vs-last claim-ticket round",
        "student_prep": "M23 complete (due tonight 11:59 PM; ceremony confirms in class).",
        "student_artifact": "Submitted dossier + exit self-assessment + reflection survey",
        "exit_ticket": "Claim Ticket #44 (the last): one claim I will carry carefully for the rest of my life, and the evidence I hold it on.",
        "homework_next_milestone": "None. It is done. (Grades follow the posted rubric timeline.)",
        "instructor_prep": "Aggregate the claim-ticket arc; the shared four-way question chosen; survey link live; celebration logistics.",
        "risks_contingency": "A dossier misses the ceremony → the 11:59 PM deadline governs; late policy applies as published — the ceremony celebrates, the deadline grades.",
    },
]
