"""Meetings M32–M43 (Weeks 12–16): the delivery-to-defense arc.

Week 12 (nb11) — poster delivery: the 30-second, 90-second, and full pitch;
audience adaptation; explaining method without jargon; spoken uncertainty; the
five hard-question types; the honest-don't-know formula; the Friday mock poster
symposium. Week 13 (nb12, single Monday lecture) — final conference preparation:
the full dress rehearsal, then the Expo (Tuesday, a graded presentation +
evaluating >=3 colleagues' posters), then the Friday reflection studio (Expo
questions coded as data + criticism portfolio). Week 14 (nb13, ASYNC Thanksgiving
module) — AI-assisted replication + red-team of a peer's anonymized package, with
a required GenAI Studio 'Reproducibility Auditor' pass; the report is due Sunday
night. Week 15 (nb14) — from poster to research note: paper logic, the
problem-gap-question spine, results hierarchy, limitations, AI as a writing
critic without surrendering authorship, and the reproducibility capsule. Week 16
(nb15) — managing multiple AI agents: task decomposition, worker-critic
structures, conflicting outputs, false consensus, stopping rules, decisions that
stay human; the terminal Friday runs the final Evidence Defenses + submission
ceremony.

Fridays are studios (recap + milestone kickoff + AI-supported sprint / symposium
rounds, no new topic content). M37 is an asynchronous online module (no live
meeting; ordered self-paced segments). Milestones M11-M15 each open at one studio
and close at the next; M15 is terminal (final chapter + AI-management portfolio).
The Student Research Lead (SRL) rotation covers the seven Mon/Wed lectures here as
slots 19-25 (seats D, E, A, B, C, D, E); studios and the async module carry no
SRL slot.

RDSS chapter titles verified against book.declaredesign.org; never invent a
chapter — these weeks carry light-to-no new RDSS reading and lean on the course's
own conference and final-dossier protocols. AI tool named in activities is Gemini
(in and alongside Colab); GenAI Studio appears at the M13 'Reproducibility
Auditor' touchpoint and in the Week 16 sequential multi-role workflow. No
fabricated citations anywhere; every source a student cites is real and retrieved.
"""

MEETINGS_P4 = [
    # ------------------------------------------------------------------ M32
    {
        "meeting": 32, "date": "2026-11-09", "day": "Mon", "modality": "in-person",
        "unit": "Week 12 — Poster delivery",
        "title": "Poster delivery I: the 30-second, 90-second, and full pitch — compression without inflation",
        "driving_question": "A stranger gives you thirty seconds, then maybe three minutes. What do you say in each, and how do you keep every version honest?",
        "secondary_questions": "How do the 30-second, 90-second, and full pitches differ in job? How do you explain your method without jargon? Where does the claim boundary live when you are speaking, not writing?",
        "inquiry": "all positions (communication)",
        "srl_slot": "SRL slot 19 — rotation seat D",
        "srl_focus": "Puzzle: two visitors stop at the same poster for a few seconds each — one leaves intrigued, one leaves confused. What did the first ten words do differently?",
        "claim_permitted": "\"In my sample, X was associated with Y — spoken exactly as the poster says it, compressed but never upgraded.\"",
        "claim_not_permitted": "\"X causes Y\" said aloud at the poster when the poster only claims association (the excited-mouth upgrade).",
        "rdss_reading": "(no new reading — delivery unit; bring your final poster and your inquiry declaration boundary)",
        "cb_reading": "",
        "other_material": "nb11 student notebook (poster delivery) §1–2 (Colab); project/conference/presentation_plan_protocol.md; M11 brief on Brightspace",
        "provenance": "presentation_plan_protocol.md + fresh pitch architectures | delivery unit | 30-sec / 90-sec / full-pitch scripts + jargon audit | fresh",
        "concepts": "pitch architecture (hook, claim, evidence, boundary, invitation); the 30-second hook vs the 90-second walk vs the full 3-to-5-minute version; audience adaptation; explaining method without jargon; compression-never-inflation",
        "python_r_dependency": "none",
        "dataset_simulation": "each student's own poster",
        "minute_dynamic": "0–9 SRL-led research puzzle: the lead plays two visitors at one poster (a few-second stopper and a three-minute stayer) and the room names what the opening ten words must do differently for each; 9–31 guided Gemini research-partner investigation: draft your three pitch layers with Gemini as a rehearsal partner — the 30-second hook, the 90-second walk, the full pitch — then have Gemini flag every sentence that upgrades a claim or hides behind jargon; 31–43 human verification + instructor formalization: you check each Gemini flag against your poster's boundary yourself (Gemini proposes, you verify), and the instructor formalizes the pitch architecture — hook, claim, evidence, boundary, invitation — and the compression-never-inflation rule; 43–50 decision & defense: log the delivery decisions and their verification in the ledger and write the Claim Ticket.",
        "hands_on_activity": "Draft and deliver all three pitch layers (30-second, 90-second, full), and catch a partner's spoken claim-upgrades and jargon.",
        "practice": "📝 nb11 practice: compress one evidence block into a single spoken sentence at three lengths without inflating the claim; rewrite one jargon sentence in plain words a stranger outside your field would follow.",
        "discussion_prompt": "Where in a classmate's pitch did a technical word do real work, and where was it a wall a visitor could not climb?",
        "project_connection": "M11 (presentation package) begins: your three pitch layers are its first component, all sized to the poster you already locked.",
        "milestone_developed": "M11 — Presentation Package",
        "milestone_work_time": "15 min (scripting the three pitch layers)",
        "milestone_presentation_review": "partner delivery rounds with upgrade-and-jargon flagging",
        "student_prep": "Final poster content internalized; headline claim sayable cold; inquiry declaration boundary at hand.",
        "student_artifact": "Three drafted pitch layers with the boundary sentence marked + partner feedback",
        "exit_ticket": "Claim Ticket #32: my boundary sentence, exactly as I will say it out loud.",
        "homework_next_milestone": "Rehearse all three pitch layers aloud. Lecture 2 builds the harder half of delivery — spoken uncertainty and the difficult questions you fear.",
        "instructor_prep": "Rehearse the well-said / inflated pitch demo pair; print the pitch-architecture templates; stage the M11 brief on Brightspace.",
        "risks_contingency": "Stage fright surfaces → the two-attempt structure makes everyone's first delivery officially a draft, and solo rehearsal is offered in office hours.",
    },
    # ------------------------------------------------------------------ M33
    {
        "meeting": 33, "date": "2026-11-11", "day": "Wed", "modality": "in-person",
        "unit": "Week 12 — Poster delivery",
        "title": "Poster delivery II: uncertainty spoken like a scientist, and the hard question you fear",
        "driving_question": "Can you say what your study cannot show — and answer the hardest fair question — without either bluffing or apologizing your findings away?",
        "secondary_questions": "What does an honest 'I don't know' contain? How do you separate evidence from speculation out loud? When a visitor asks 'but does it CAUSE it?' about a noncausal project, what do you say?",
        "inquiry": "all positions (communication)",
        "srl_slot": "SRL slot 20 — rotation seat E",
        "srl_focus": "Puzzle: a stranger asks 'so does it CAUSE it?' about a study that only measured association — what is the one sentence that stays honest and still keeps them interested?",
        "claim_permitted": "\"I don't know — but here is what I do know that bears on it, and here is how one would find out.\"",
        "claim_not_permitted": "Bluffing an answer you do not have — the one move that can destroy a presenter's credibility on the spot.",
        "rdss_reading": "(no new reading — delivery unit; bring your uncertainty line and your poster's claim boundary)",
        "cb_reading": "",
        "other_material": "nb11 student notebook (poster delivery) §3–4 (Colab); project/conference/uncertainty_limitations_protocol.md; project/conference/hard_questions_protocol.md; M11 brief on Brightspace",
        "provenance": "uncertainty_limitations_protocol.md + hard_questions_protocol.md | delivery unit | ULN move + five-type question bank + honest-don't-know formula | fresh",
        "concepts": "the uncertainty-limitations-next-step (ULN) move; the five hard-question types (method, alternative explanation, so-what, generalization, AI-use); the honest-don't-know formula; separating evidence from speculation; defend-vs-concede judgment; professional conference interaction",
        "python_r_dependency": "none",
        "dataset_simulation": "each student's own findings, spoken",
        "minute_dynamic": "0–7 SRL-led retrieval & challenge: the lead fires a causal question at a deliberately noncausal finding ('so it CAUSES it?') and the room drafts the one sentence that stays honest and keeps the visitor interested; 7–30 intensive applied AI laboratory: build your five-question bank (one per type) with Gemini generating hostile-but-fair versions you did not think of, draft the ULN paragraph and the honest-don't-know answer for the worst one, then deliver your ULN to two partners in rotation; 30–42 peer defense + adversarial questioning: sit a 3-minute hot seat drawn from your bank plus surprises while classmates probe, defending from the ledger or conceding cleanly; 42–50 transfer + ledger + Claim Ticket: revise the bank from what the hot seat exposed, log the AI-use decision and its verification, and write the ticket.",
        "hands_on_activity": "Survive a 3-minute hot seat on your five-question bank, delivering the ULN move and at least one honest 'I don't know' without bluffing.",
        "practice": "📝 nb11 practice: convert three apology-spiral sentences into ULN form; for one causal question aimed at a noncausal finding, write the two-sentence honest reply.",
        "discussion_prompt": "Which classmate's hot-seat save impressed you most, and what exactly did they do to turn a stumble into a grounded answer?",
        "project_connection": "M11 completes its intellectual armor: the pitch layers plus the uncertainty statement and question bank are the package you carry to the Expo.",
        "milestone_developed": "M11 — Presentation Package (uncertainty statement + question bank)",
        "milestone_work_time": "15 min (bank-building + ULN drafting)",
        "milestone_presentation_review": "hot-seat rounds + ULN partner rounds with strength-not-apology scoring",
        "student_prep": "Pitch layers rehearsed from Lecture 1; findings and their limits at hand.",
        "student_artifact": "Five-question bank + ULN paragraph + hot-seat performance",
        "exit_ticket": "Claim Ticket #33: the question I most fear at the Expo, and my first sentence in reply.",
        "homework_next_milestone": "Finish M11 (three pitch layers + uncertainty statement + question bank) for Friday's studio, where the mock poster symposium drills it and M11 is due that night.",
        "instructor_prep": "Surprise-question deck per project; three ULN demos including a null finding; timer for the hot seats.",
        "risks_contingency": "A hot seat runs hot emotionally → the instructor becomes questioner-of-record and slows the cadence; the drill's purpose, safety through practice, is named aloud.",
    },
    # ------------------------------------------------------------------ M34
    {
        "meeting": 34, "date": "2026-11-13", "day": "Fri", "modality": "in-person",
        "unit": "Week 12 — Poster delivery",
        "title": "Studio Friday — the mock poster symposium: your package under live fire, M11 due",
        "driving_question": "Can your whole delivery package survive a room of strangers rotating through your poster — and is it ready to submit tonight?",
        "secondary_questions": "Does the full walk land inside time? Do the pitch, the ULN, and the question bank hold together under real traffic? What is still soft before the Expo (Tuesday)?",
        "inquiry": "all positions (communication)",
        "srl_slot": "",
        "srl_focus": "",
        "claim_permitted": "\"Every claim I spoke at my station matched what my poster shows — I compressed, I never upgraded.\"",
        "claim_not_permitted": "\"I'll figure out the hard questions live at the Expo\" (the symposium is the rehearsal that makes that unnecessary).",
        "rdss_reading": "(no new reading — studio Friday; bring your poster, all three pitches, and your question bank)",
        "cb_reading": "",
        "other_material": "nb11 student notebook (poster delivery) §5 symposium + visitor role cards (Colab); project/conference/dress_rehearsal_protocol.md (station-round format); M11 due tonight; M12 brief on Brightspace",
        "provenance": "presentation_plan_protocol.md + hard_questions_protocol.md + fresh symposium protocol | delivery unit | mock symposium station rounds with visitor role cards as the studio work block | fresh",
        "concepts": "the mock poster symposium; station-round format; the visitor role card (the five question types spread across visits); critical-but-kind feedback; delivery under live traffic",
        "python_r_dependency": "none",
        "dataset_simulation": "each student's own poster and package",
        "minute_dynamic": "0–6 research stand-up: one line each — the claim your package is built to defend and the one delivery move you are still unsure of; 6–29 milestone kickoff + symposium rounds: the instructor presents the M12 conference-reflection-and-portfolio brief (present at the Expo on Tuesday, plus evaluate at least three colleagues' posters), then the MOCK SYMPOSIUM runs as the work block — stations go live in rotation, presenters deliver the 30-second and full pitches while everyone else works the visitor role card across the five question types; 29–41 peer + AI red-team review: between rounds, revise your question bank from what surprised you and have Gemini stress-test your two weakest answers; 41–50 revise, ledger, submit + Claim Ticket: lock the package, log the verification, submit M11 tonight, and write the ticket.",
        "hands_on_activity": "Stand your poster through live symposium rounds and visit others as a critical-but-kind stranger, working all five question types across your visits.",
        "practice": "📝 (embedded) the visitor role card: ask at least one method, one alternative-explanation, one so-what, one generalization, and one AI-use question across your visits.",
        "discussion_prompt": "Which classmate's station made you stay longer than you meant to, and what specifically kept you there?",
        "project_connection": "M11 submits tonight; the package you drilled today is exactly what you carry to the Expo (Tuesday), where M12 begins.",
        "milestone_developed": "M11 — Presentation Package (due TONIGHT) → kickoff M12",
        "milestone_work_time": "30 min studio block (symposium rounds + bank revision)",
        "milestone_presentation_review": "the mock symposium IS the presentation/review",
        "student_prep": "M11 drafted from the week: three pitch layers, uncertainty statement, question bank.",
        "student_artifact": "Revised package + symposium performance + submitted M11",
        "exit_ticket": "Claim Ticket #34: the one delivery move I will do differently at the Expo because of today.",
        "homework_next_milestone": "Submit M11 tonight, 11:59 PM. Monday is final conference preparation; the Expo follows on Tuesday — carry a coding sheet and capture every question you are asked.",
        "instructor_prep": "Room set as stations; visitor role cards printed; timer; M12 brief staged on Brightspace; confirm Expo logistics to communicate.",
        "risks_contingency": "A poster's print is not ready → present full-screen today and trigger the backup print run so it is in hand before the Expo (Tuesday).",
    },
    # ------------------------------------------------------------------ M35
    {
        "meeting": 35, "date": "2026-11-16", "day": "Mon", "modality": "in-person",
        "unit": "Week 13 — Conference week",
        "title": "Conference week: final preparation and the full dress rehearsal",
        "driving_question": "The Expo is tomorrow. Is every piece — poster, pitches, question bank, logistics, and the coding sheet you will carry — actually ready?",
        "secondary_questions": "Does the full walk land inside time? What must be locked before tomorrow: location, call time, materials, backup file? What will you capture at the Expo so Friday's reflection has real data?",
        "inquiry": "all positions (communication)",
        "srl_slot": "SRL slot 21 — rotation seat A",
        "srl_focus": "Puzzle: everything is 'basically ready' — so why do half of rehearsed talks still run over time and freeze on question two? Find the piece that is not actually ready.",
        "claim_permitted": "\"Readiness audited: rehearsed twice inside time, question bank drilled, logistics confirmed, coding sheet in hand.\"",
        "claim_not_permitted": "\"I'll wing it tomorrow\" (rehearsal is the difference between nerves and panic).",
        "rdss_reading": "(no new reading — rehearsal day; bring your poster, all three pitches, and your question bank cold)",
        "cb_reading": "",
        "other_material": "nb12 student notebook (conference prep) §1 readiness audit + visitor role card (Colab); project/conference/dress_rehearsal_protocol.md; project/conference/conference_reflection_protocol.md (the capture method); audience-coding sheet; M12 brief on Brightspace",
        "provenance": "dress_rehearsal_protocol.md + conference_reflection_protocol.md capture method | conference unit | full-dress station simulation + readiness audit + Expo capture plan | fresh",
        "concepts": "full-dress simulation; readiness auditing; the visitor role card; capturing audience questions as data (the coding sheet); logistics discipline; professional conference interaction",
        "python_r_dependency": "none",
        "dataset_simulation": "each student's own complete conference package",
        "minute_dynamic": "0–9 SRL-led research puzzle: the lead surfaces the gap between 'basically ready' and actually ready — the room lists what freezes a rehearsed presenter on question two and names the piece that is usually not ready; 9–31 guided full dress-run rotation: two station rounds where posters go live in turn while everyone else plus the instructor rotate as conference visitors, exercising the short pitch, the full walk, hard questions from the bank, and the ULN moment under time; 31–43 human verification + instructor formalization: sign the readiness audit (rehearsed / drilled / logistics / materials), and the instructor formalizes the Expo capture plan — the coding sheet each presenter carries to log every question in the moment; 43–50 decision & defense: confirm call time and logistics, log the readiness decision in the ledger, and write the Claim Ticket.",
        "hands_on_activity": "Stand your poster through a full dress-run round, visit others with the five-type role card, and sign your readiness audit.",
        "practice": "📝 nb12 practice: fill the readiness audit honestly (an unchecked box is tonight's task, not a failure); write the one-line coding-sheet format you will use tomorrow.",
        "discussion_prompt": "One thing you saw a classmate do in the dress run that you are stealing for the Expo tomorrow?",
        "project_connection": "M12 begins here: the readiness audit is the last gate before the Expo (Tuesday), and the coding sheet you leave with captures the audience data M12's reflection needs.",
        "milestone_developed": "M12 — Conference Reflection and Poster-Criticism Portfolio (kickoff; the Expo presentation is a graded component)",
        "milestone_work_time": "22 min (full dress-run rotation) + 4 min (readiness audit)",
        "milestone_presentation_review": "the full dress-run rotation IS the presentation/review",
        "student_prep": "M11 submitted; poster ready (printed or presentable); all three pitches and question bank cold.",
        "student_artifact": "Signed readiness audit + dress-run performance + prepared coding sheet",
        "exit_ticket": "Claim Ticket #35: the one thing I will do differently at the Expo because of today's dress run.",
        "homework_next_milestone": "The Expo is tomorrow (Tuesday): present, and evaluate at least three colleagues' posters on the structured criticism forms. Carry your coding sheet and capture every question you are asked. There is no class Wednesday; Friday's studio is the structured reflection.",
        "instructor_prep": "Room set as stations; visitor role cards; audience-coding sheets and structured poster-criticism forms printed; confirm and communicate the Expo call time; M12 brief staged.",
        "risks_contingency": "A poster's print failed → present full-screen in the dress run today and resolve the emergency print before the Expo (Tuesday); the backup plan is pre-arranged.",
    },
    # ------------------------------------------------------------------ M36
    {
        "meeting": 36, "date": "2026-11-20", "day": "Fri", "modality": "in-person",
        "unit": "Week 13 — Conference week",
        "title": "Studio Friday — conference reflection: your Expo questions become data, M12 due",
        "driving_question": "What did strangers' questions at the Expo reveal about your project that friends' questions never could?",
        "secondary_questions": "Which questions recurred? Was the most repeated one about your claims or your clarity? What new research idea did the Expo hand you, and how honest are your self-evaluation and your portfolio of the three posters you evaluated?",
        "inquiry": "all positions (reflection, applied to your own project)",
        "srl_slot": "",
        "srl_focus": "",
        "claim_permitted": "\"The most repeated question at my poster was about my [claims / communication] — the count says so, not my mood.\"",
        "claim_not_permitted": "\"People liked it, so my findings held up\" (applause measures your communication, not the truth of your claims).",
        "rdss_reading": "(no new reading — studio Friday; bring your Expo coding sheet and your three completed poster-criticism forms)",
        "cb_reading": "",
        "other_material": "nb12 student notebook (conference prep) §2–3 reflection tally (Colab); project/conference/conference_reflection_protocol.md; M12 due tonight; M13 brief + the anonymized replication packages on Brightspace",
        "provenance": "conference_reflection_protocol.md + fresh studio protocol | conference unit | audience-question coding + criticism portfolio as the studio work block + M13 exchange kickoff | fresh",
        "concepts": "feedback as data; the claims-vs-communication split; recurring-question analysis; misunderstandings and weaknesses exposed; self-evaluation; the poster-criticism portfolio (three posters, structured); the anonymized replication-package exchange",
        "python_r_dependency": "none (a provided tally cell if wanted)",
        "dataset_simulation": "each student's collected Expo questions + the three posters they evaluated",
        "minute_dynamic": "0–6 research stand-up: the single most surprising moment at your poster, in one line each; 6–29 milestone kickoff + reflection sprint: the instructor kicks off M13 by handing out the ANONYMIZED replication packages for the Thanksgiving async exchange, then the reflection runs as the work block — code every Expo question into the tally (type, target: claims vs communication, recurrence), find your pattern, and assemble the criticism portfolio from the three posters you evaluated; 29–41 peer + AI red-team review: swap tallies with a partner who reads the pattern you are too close to see, and use Gemini to pressure-test whether your 'new research idea' actually follows from the feedback; 41–50 revise, ledger, submit + Claim Ticket: write the honest reflection paragraph, submit M12 tonight, and write the ticket.",
        "hands_on_activity": "Code your Expo questions like data, find the recurring pattern, and assemble your three-poster criticism portfolio.",
        "practice": "📝 nb12 practice: classify six received questions as claims-signal, communication-signal, or noise; name the one that recurred and what its repetition evidences.",
        "discussion_prompt": "What question did you get at the Expo that none of our hot seats predicted, and why did we miss it?",
        "project_connection": "M12 submits tonight (reflection + portfolio, with the Expo presentation graded); M13 launches now — over break you reproduce and red-team a classmate's anonymized package.",
        "milestone_developed": "M12 — Conference Reflection and Poster-Criticism Portfolio (due TONIGHT) → kickoff M13",
        "milestone_work_time": "30 min studio block (coding + portfolio assembly)",
        "milestone_presentation_review": "story round + partner tally-pattern read",
        "student_prep": "Expo presented; every question captured on the coding sheet; three poster-criticism forms completed at the Expo.",
        "student_artifact": "Coded question tally + criticism portfolio + reflection paragraph (submitted as M12) + assigned replication package",
        "exit_ticket": "Claim Ticket #36: the most repeated question at my poster, and whether it challenged my evidence or my clarity.",
        "homework_next_milestone": "Submit M12 tonight, 11:59 PM. Monday is asynchronous (Thanksgiving week): the replication and red-team module on the anonymized package assigned today; the report is due Sunday night.",
        "instructor_prep": "Own Expo observation notes per student; tally template checked; anonymize and assign the replication packages; M13 brief staged on Brightspace.",
        "risks_contingency": "A student missed the Expo for a documented reason → the make-up presentation path runs and the reflection uses dress-run data meanwhile. Post-conference deflation → the story round names it as every researcher's post-conference dip.",
    },
    # ------------------------------------------------------------------ M37
    {
        "meeting": 37, "date": "2026-11-23", "day": "Mon", "modality": "async-online",
        "unit": "Week 14 — Thanksgiving async: replication and red-team",
        "title": "ASYNC — Replication and red-team: rebuild a stranger's findings, then audit them",
        "driving_question": "Hand yourself a classmate's package: can you rebuild the headline number — and where does it quietly not hold?",
        "secondary_questions": "Does the notebook run end to end? Can you trace the data and code lineage? Do the poster's claims match what the computation actually shows? What hidden assumptions and AI-related weaknesses hide behind an illusion of completeness?",
        "inquiry": "all positions (replication + red-team, applied to a peer's project)",
        "srl_slot": "",
        "srl_focus": "",
        "claim_permitted": "\"I reproduced the headline number from the package alone, and here are the three weaknesses I ranked by how much they threaten the claim.\"",
        "claim_not_permitted": "\"It ran, so it's fine\" (a clean run is not agreement between the poster's claims and the computational evidence).",
        "rdss_reading": "(no new reading — self-contained async module; the reproducibility-audit protocol stands in for the reading)",
        "cb_reading": "",
        "other_material": "nb13 student notebook — fully self-contained async module (Colab); project/final_dossier/reproducibility_audit_protocol.md; the assigned anonymized replication package; GenAI Studio 'Reproducibility Auditor' role (genai.rcac.purdue.edu); async discussion board; M13 due Sunday night; M14 brief posted on Brightspace",
        "provenance": "reproducibility_audit_protocol.md + GenAI Studio Reproducibility Auditor touchpoint | replication + red-team unit | self-contained reproduce-and-audit module with a required GenAI Studio role pass | fresh",
        "concepts": "AI-assisted replication; restart-and-run-all execution; data and code lineage; alternative specifications; hidden assumptions; claims-vs-computation agreement; AI-related weaknesses; the illusion of completeness; prioritized (triaged) recommendations",
        "python_r_dependency": "pandas/numpy (execute the peer's package end to end); scikit-learn if the package uses it",
        "dataset_simulation": "a classmate's anonymized replication package",
        "minute_dynamic": "ASYNC (~50 min self-paced, no live meeting): 0–6 module orientation + open the assigned anonymized package; 6–20 cold reproduction — restart-and-run-all, trace the data and code lineage, and try to reproduce the headline number, logging every break; 20–32 red-team audit — check the poster's claims against what the computation actually shows, probe one alternative specification, and surface the hidden assumptions and AI-related weaknesses; 32–42 REQUIRED GenAI Studio pass — run the package summary through the 'Reproducibility Auditor' role, then verify its findings yourself and log the pass in your AI-use ledger (the role proposes, you confirm); 42–48 write the prioritized recommendations, ranked by threat to the claim, not by ease of fixing; 48–50 (async board) post the single weakness you ranked most threatening and reply to one classmate.",
        "hands_on_activity": "Reproduce a classmate's anonymized headline number, red-team it for hidden assumptions and AI weaknesses, and run the required GenAI Studio Reproducibility Auditor pass.",
        "practice": "📝 nb13 practice: for one sample package, list three ways a clean run can still hide a broken claim, then rank them by threat.",
        "discussion_prompt": "(async board) The weakness you ranked most threatening in your assigned package: post it, and reply to one classmate with a check that would confirm or dissolve theirs.",
        "project_connection": "M13 is a full red-team report on a peer's work — the skill you will want turned on your own dossier next; M14 (your research note) is posted today to read over break.",
        "milestone_developed": "M13 — Replication and Red-Team Report (due Sunday night)",
        "milestone_work_time": "the whole module is milestone work (~50 min self-paced)",
        "milestone_presentation_review": "async board: most-threatening-weakness post + one reply",
        "student_prep": "M12 submitted; the assigned anonymized package downloaded; GenAI Studio access confirmed.",
        "student_artifact": "Reproduction log + red-team audit + GenAI Studio Auditor pass (verified, ledgered) + prioritized recommendations",
        "exit_ticket": "(embedded) Claim Ticket #37: the weakness that most threatens my assigned package's headline claim, and the check that would settle it.",
        "homework_next_milestone": "Happy Thanksgiving. Submit M13 by Sunday night, 11:59 PM. Class resumes in person next Monday with the research-note unit (M14, posted today).",
        "instructor_prep": "Anonymize and assign packages so no one audits their own; verify each package runs unattended; confirm the GenAI Studio Reproducibility Auditor role is live; seed the discussion board; holiday-proof the Sunday deadline in Brightspace.",
        "risks_contingency": "Holiday-week attrition → the module is doable in one sitting, the deadline is Sunday, and a mid-week progress-checkpoint reminder goes out. A package will not run at all → that failure, documented with the exact break, IS valid red-team evidence.",
    },
    # ------------------------------------------------------------------ M38
    {
        "meeting": 38, "date": "2026-11-30", "day": "Mon", "modality": "in-person",
        "unit": "Week 15 — From poster to research note",
        "title": "From poster to research note I: paper logic, and the problem–gap–question spine",
        "driving_question": "Your poster said it in six boxes. What does a research note have to add that the poster was allowed to leave out?",
        "secondary_questions": "How does paper logic differ from poster logic? How do you build the problem–gap–question spine in prose? What does honest literature synthesis look like, and how dense should the evidence be?",
        "inquiry": "all positions (communication)",
        "srl_slot": "SRL slot 22 — rotation seat B",
        "srl_focus": "Puzzle: the poster said it in six boxes; the research note needs six pages. What does the note have to add that the poster was allowed to leave out?",
        "claim_permitted": "\"My note earns each claim in prose — problem, gap, question, design, evidence — with every source real and retrieved.\"",
        "claim_not_permitted": "\"As everyone knows…\" standing in for a literature synthesis that cites nothing a reader could retrieve.",
        "rdss_reading": "(no new reading — research-note unit; bring your poster, claim ledger, and evidence map)",
        "cb_reading": "",
        "other_material": "nb14 student notebook (poster to research note) §1–2 (Colab); project/final_dossier/research_brief_template.md (the compression cousin of the note); M14 brief on Brightspace",
        "provenance": "research_brief_template.md + fresh research-note method | research-note unit | poster-vs-paper logic + problem–gap–question spine + synthesis discipline | fresh",
        "concepts": "poster logic vs paper logic; the problem–gap–question spine; literature synthesis (real, retrievable sources only); explaining the research design in prose; evidence density",
        "python_r_dependency": "none",
        "dataset_simulation": "each student's own project and its verified sources",
        "minute_dynamic": "0–9 SRL-led research puzzle: the lead puts a poster box next to the paragraph it becomes and the room names what the paragraph must add — the reasoning the box only implied; 9–31 guided Gemini research-partner investigation: draft your problem–gap–question spine and a first literature-synthesis paragraph with Gemini, then make Gemini list every citation it produced so you can mark which ones you have actually retrieved and confirmed exist; 31–43 human verification + instructor formalization: you verify each source yourself before it stays in the note (Gemini proposes, you confirm the source is real), and the instructor formalizes paper logic, the problem–gap–question spine, and evidence density; 43–50 decision & defense: log the sourcing decisions and their verification in the ledger and write the Claim Ticket.",
        "hands_on_activity": "Draft the problem–gap–question spine and one synthesis paragraph, and verify every source in it is real and retrievable before it stays.",
        "practice": "📝 nb14 practice: turn one poster box into a paragraph that adds the reasoning the box left implicit; for one synthesis sentence, retrieve and confirm the source or cut the sentence.",
        "discussion_prompt": "Where did a classmate's note add reasoning the poster only gestured at, and where did it just restate the box in longer words?",
        "project_connection": "M14 (research-note draft + reproducibility capsule) begins: the spine and synthesis are its opening sections.",
        "milestone_developed": "M14 — Research-Note Draft and Reproducibility Capsule",
        "milestone_work_time": "15 min (spine + synthesis drafting)",
        "milestone_presentation_review": "none (lecture day; drafting studio sits inside the lab block)",
        "student_prep": "Poster and claim ledger in hand; source list ready to verify.",
        "student_artifact": "Problem–gap–question spine + one verified synthesis paragraph",
        "exit_ticket": "Claim Ticket #38: the one thing my note must argue that my poster was allowed to only imply.",
        "homework_next_milestone": "Extend the draft. Lecture 2 covers the results hierarchy, limitations, and using AI as a writing critic without surrendering authorship.",
        "instructor_prep": "A poster-box-to-paragraph example pair; a real-vs-fake citation demonstration; M14 brief staged on Brightspace.",
        "risks_contingency": "A student has thin literature → the synthesis narrows to the two or three sources genuinely adjacent to the gap, each verified, rather than padding with unretrieved names.",
    },
    # ------------------------------------------------------------------ M39
    {
        "meeting": 39, "date": "2026-12-02", "day": "Wed", "modality": "in-person",
        "unit": "Week 15 — From poster to research note",
        "title": "From poster to research note II: results hierarchy, limitations, and AI as critic (not author)",
        "driving_question": "Can you rank your results, own your limitations, and let an AI sharpen your prose — without letting it upgrade a single claim or take the pen?",
        "secondary_questions": "What earns the top of the results hierarchy? How do limitations and implications stay sized to the evidence? What does a reproducibility capsule contain? Where is the line between AI as critic and AI as author?",
        "inquiry": "all positions (communication)",
        "srl_slot": "SRL slot 23 — rotation seat C",
        "srl_focus": "Puzzle: an AI rewrite makes your discussion sound more confident and more publishable — and quietly upgrades one claim past its evidence. Which sentence, and how would a reader catch it?",
        "claim_permitted": "\"Every sentence in my discussion is sized to my evidence, and every AI edit I kept, I verified and own.\"",
        "claim_not_permitted": "\"The AI improved my conclusion\" when the improvement quietly upgraded a claim past its evidence (a sharper sentence is not a bigger finding).",
        "rdss_reading": "(no new reading — research-note unit; bring your draft and your reproducibility-capsule stub)",
        "cb_reading": "",
        "other_material": "nb14 student notebook (poster to research note) §3–4 reproducibility capsule (Colab); project/final_dossier/reproducibility_audit_protocol.md (the capsule anatomy); the course AI-use ledger; M14 due Friday; M15 brief on Brightspace",
        "provenance": "reproducibility_audit_protocol.md capsule anatomy + fresh discussion-craft method | research-note unit | results hierarchy + limitations discipline + AI-critic-not-author boundary | fresh",
        "concepts": "the results hierarchy; limitations and implications sized to evidence; avoiding inflated contributions; AI as a writing critic without surrendering authorship; the reproducibility capsule (runnable notebook, provenance, seed, decision log, AI-use ledger)",
        "python_r_dependency": "own notebook hygiene (restart-and-run-all for the capsule)",
        "dataset_simulation": "each student's own draft and project package",
        "minute_dynamic": "0–7 SRL-led retrieval & challenge: the lead shows an AI rewrite that sounds more publishable and upgrades one claim past its evidence — the room finds the sentence; 7–30 intensive applied AI laboratory: order your results into a hierarchy, draft limitations and implications sized to the evidence, then run your discussion through Gemini as a critic — keep the edits that sharpen, reject the ones that inflate, and assemble your reproducibility capsule with restart-and-run-all; 30–42 peer defense + adversarial questioning: a partner probes your discussion for any inflated contribution and any AI edit you cannot defend as your own; 42–50 transfer + ledger + Claim Ticket: log which AI edits you kept, changed, or rejected and why, and write the ticket.",
        "hands_on_activity": "Use Gemini to critique your discussion section, keep only the edits that sharpen without inflating, and pass restart-and-run-all on your reproducibility capsule.",
        "practice": "📝 nb14 practice: take three AI-suggested edits to one paragraph — accept the one that clarifies, reject the two that upgrade the claim, and say why for each.",
        "discussion_prompt": "What is the difference between an AI edit that makes your writing better and one that makes your claim bigger, and how did you tell them apart today?",
        "project_connection": "M14 nears completion: the note plus a runnable reproducibility capsule are due at Friday's studio.",
        "milestone_developed": "M14 — Research-Note Draft and Reproducibility Capsule",
        "milestone_work_time": "15 min (results/limitations drafting) + capsule restart-and-run-all",
        "milestone_presentation_review": "partner discussion-probe rounds",
        "student_prep": "Draft extended from Lecture 1; project notebook runnable.",
        "student_artifact": "Ranked results + limitations/implications + a reproducibility capsule that passes restart-and-run-all + AI-edit decision log",
        "exit_ticket": "Claim Ticket #39: one AI edit I rejected because it would have made my claim bigger than my evidence.",
        "homework_next_milestone": "Finish the research note and the reproducibility capsule for Friday's studio, where M14 is due and M15 (final chapter + AI-management portfolio) kicks off.",
        "instructor_prep": "An AI-rewrite-with-a-hidden-upgrade example; the reproducibility-capsule checklist; M15 brief staged on Brightspace.",
        "risks_contingency": "A capsule fails restart-and-run-all in class → the break is logged as capsule evidence and the fix routes to Friday's studio consults.",
    },
    # ------------------------------------------------------------------ M40
    {
        "meeting": 40, "date": "2026-12-04", "day": "Fri", "modality": "in-person",
        "unit": "Week 15 — From poster to research note",
        "title": "Studio Friday — research-note table read: every note sharpened, M14 due, M15 launched",
        "driving_question": "Does your research note do justice to the semester — and is its reproducibility capsule one a stranger could actually run?",
        "secondary_questions": "Where does the note still overclaim, underexplain, or lose the reader? Does the capsule pass a partner's restart-and-run-all? What does the final chapter and AI-management portfolio (M15) ask of you next week?",
        "inquiry": "all positions (communication)",
        "srl_slot": "",
        "srl_focus": "",
        "claim_permitted": "\"Every claim in my note traces to my ledger, and my capsule ran clean on a machine that was not mine.\"",
        "claim_not_permitted": "\"It runs for me\" offered as reproducibility no stranger ever exercised.",
        "rdss_reading": "(no new reading — studio Friday; bring your polished note and runnable capsule)",
        "cb_reading": "",
        "other_material": "nb14 student notebook (poster to research note) §5 table read (Colab); project/final_dossier/research_brief_template.md (the table-read margin-note procedure); M14 due tonight; M15 brief on Brightspace",
        "provenance": "research_brief_template.md table-read procedure + reproducibility_audit_protocol.md | research-note unit | note table read + partner capsule run as the studio work block + M15 kickoff + defense-order draw | fresh",
        "concepts": "the table read with two-question margin notes; ledger-traceable prose; a partner reproducibility check on the capsule; avoiding inflated contributions; the defense-order draw",
        "python_r_dependency": "partner runs your reproducibility capsule (restart-and-run-all)",
        "dataset_simulation": "each student's own note and capsule",
        "minute_dynamic": "0–6 research stand-up: your note's sharpest sentence and the claim you are least sure survives, one line each; 6–29 milestone kickoff + AI-supported sprint: the instructor presents the M15 brief (final research chapter + AI-management portfolio, staged for the multi-agent workflow next week) and draws the Evidence-Defense order for next week, then the TABLE READ runs as the work block — each note passes left, three minutes per read, a two-question margin note (sharpest sentence, weakest claim) on each, full rotation; 29–41 peer + AI red-team review: swap capsules and run your partner's restart-and-run-all cold, logging any break, then have Gemini flag any remaining inflated contribution in your discussion; 41–50 revise, ledger, submit + Claim Ticket: revise from the margin notes, submit M14 tonight, and write the ticket.",
        "hands_on_activity": "Run the full-rotation table read with margin notes, and reproduce a partner's capsule cold before signing that it ran.",
        "practice": "📝 nb14 practice: for one sample note sentence, trace it to a ledger row or catch that it cannot be traced.",
        "discussion_prompt": "Which classmate's note taught you a compression or framing move, and what exactly was it?",
        "project_connection": "M14 submits tonight; the note and capsule become the backbone the final chapter (M15) expands next week.",
        "milestone_developed": "M14 — Research-Note Draft and Reproducibility Capsule (due TONIGHT) → kickoff M15",
        "milestone_work_time": "30 min studio block (table read + capsule exchange + revision)",
        "milestone_presentation_review": "table-read margin notes (all-read-all) + partner capsule run",
        "student_prep": "Full note polished; reproducibility capsule assembled and runnable.",
        "student_artifact": "Margin-annotated note + partner capsule-run log + revision + submitted M14",
        "exit_ticket": "Claim Ticket #40: the claim a margin note flagged as weakest, and how I resized it.",
        "homework_next_milestone": "Submit M14 tonight, 11:59 PM. Monday begins the final unit — managing multiple AI agents to expand your note into the final research chapter.",
        "instructor_prep": "Margin-note slips; an annotated exemplar note; defense order-draw slips; confirm partner capsule-run pairings; M15 brief staged on Brightspace.",
        "risks_contingency": "A capsule will not run for the partner → the exact break is logged as reproducibility evidence and fixed in a consult; the note table read proceeds regardless.",
    },
    # ------------------------------------------------------------------ M41
    {
        "meeting": 41, "date": "2026-12-07", "day": "Mon", "modality": "in-person",
        "unit": "Week 16 — Managing multiple AI agents",
        "title": "Managing multiple AI agents I: decomposition, specialization, and the worker–critic workflow",
        "driving_question": "You have one chapter draft and several AI roles. Who works first, who works in parallel, and how do you keep them from all making the same mistake?",
        "secondary_questions": "How do you decompose a chapter task into roles? What does agent specialization and context allocation buy you? When is work parallel versus sequential, and what does a worker–critic structure add?",
        "inquiry": "all positions (AI-workflow management)",
        "srl_slot": "SRL slot 24 — rotation seat D",
        "srl_focus": "Puzzle: you have one chapter draft and four AI roles — reviewer, methodologist, skeptic, editor. Who works first, who works in parallel, and which output do you trust when two disagree?",
        "claim_permitted": "\"I assigned each AI role a scoped task and an independent reviewer, and I can name what each one did and did not touch.\"",
        "claim_not_permitted": "\"The agents handled it\" — a workflow whose outputs no human scoped, traced, or owned.",
        "rdss_reading": "(no new reading — AI-management unit; bring your research note as the chapter draft to expand)",
        "cb_reading": "",
        "other_material": "nb15 student notebook (managing AI agents) §1–2 (Colab); GenAI Studio sequential-workflow roles (genai.rcac.purdue.edu, Colab API or UI); the course AI-use ledger; M15 brief on Brightspace",
        "provenance": "GenAI Studio sequential-workflow capability + fresh multi-agent method | AI-management unit | task decomposition + worker–critic roles run against the student's own chapter | fresh",
        "concepts": "task decomposition; agent specialization; context allocation; parallel vs sequential work; dependencies; independent review; the worker–critic structure",
        "python_r_dependency": "GenAI Studio roles via the OpenAI-compatible API or UI (requests / provided client cells)",
        "dataset_simulation": "each student's own research note, being expanded into the final chapter",
        "minute_dynamic": "0–9 SRL-led research puzzle: the lead lays out one chapter draft and four AI roles (reviewer, methodologist, skeptic, editor) and the room decides the order, what runs in parallel, and which output wins when two disagree; 9–31 guided Gemini research-partner investigation: with Gemini, decompose your chapter task into scoped roles with allocated context and a dependency order, then stand up a real sequential worker–critic pass against your own note using GenAI Studio roles; 31–43 human verification + instructor formalization: you inspect each role's output for what it actually changed (the tool proposes, you verify), and the instructor formalizes decomposition, specialization, and the worker–critic structure; 43–50 decision & defense: log each role, its task, and your verification in the ledger and write the Claim Ticket.",
        "hands_on_activity": "Decompose your chapter into scoped AI roles and run a real sequential worker–critic pass against your own note using GenAI Studio.",
        "practice": "📝 nb15 practice: for one chapter section, assign three AI roles, set their order and dependencies, and mark which decision each is allowed to touch.",
        "discussion_prompt": "Where did specializing an AI role make its output sharper, and where did narrowing its context make it miss something a generalist would have caught?",
        "project_connection": "M15 (final research chapter + AI-management portfolio) begins: today's decomposition and role log are the portfolio's first entries.",
        "milestone_developed": "M15 — Final Research Chapter and AI-Management Portfolio",
        "milestone_work_time": "22 min (decomposition + first worker–critic pass)",
        "milestone_presentation_review": "none (lecture day; the workflow runs inside the lab block)",
        "student_prep": "Research note in hand as the chapter's starting draft; GenAI Studio access confirmed.",
        "student_artifact": "Task decomposition + role assignments + first sequential worker–critic pass, logged",
        "exit_ticket": "Claim Ticket #41: the one chapter decision I will keep human no matter how good the AI roles get, and why.",
        "homework_next_milestone": "Extend the chapter with your workflow. Lecture 2 confronts conflicting outputs, correlated errors, false consensus, and stopping rules — and stages the first defenses.",
        "instructor_prep": "Confirm the GenAI Studio sequential-workflow roles are live; the provided API/UI cells tested; M15 brief staged on Brightspace.",
        "risks_contingency": "GenAI Studio API friction → the UI path and the provided cells are the fallback, and the workflow logic is graded, not the plumbing.",
    },
    # ------------------------------------------------------------------ M42
    {
        "meeting": 42, "date": "2026-12-09", "day": "Wed", "modality": "in-person",
        "unit": "Week 16 — Managing multiple AI agents",
        "title": "Managing multiple AI agents II: conflicting outputs, false consensus, and staging the defense",
        "driving_question": "Three AI reviewers agree your chapter is fine. Is that three confirmations or one error repeated three times — and when do you overrule all of them?",
        "secondary_questions": "How do you reconcile conflicting outputs? What makes agreement false consensus (correlated errors)? What is your stopping rule, and which decisions should never be automated at all?",
        "inquiry": "all positions (synthesis — AI-workflow management + defense)",
        "srl_slot": "SRL slot 25 — rotation seat E",
        "srl_focus": "Puzzle: three AI reviewers agree your chapter is fine. Is that three independent confirmations or one correlated error repeated three times — and how would you tell?",
        "claim_permitted": "\"Where my AI roles conflicted, I made the call and can defend it; where they agreed, I checked the agreement was not one error repeated.\"",
        "claim_not_permitted": "\"All the agents agreed, so it must be right\" (correlated errors manufacture false consensus).",
        "rdss_reading": "(no new reading — AI-management unit; bring your chapter draft and your three weakest claim-ledger rows)",
        "cb_reading": "",
        "other_material": "nb15 student notebook (managing AI agents) §3–4 (Colab); project/final_dossier/evidence_defense_protocol.md (defense format + cross-examination norms); the course AI-use ledger; the defense order (drawn at Friday's M15 kickoff); M15 due Friday",
        "provenance": "GenAI Studio sequential-workflow + evidence_defense_protocol.md | AI-management unit | conflict reconciliation + false-consensus check + defense staging (first defenses) | fresh",
        "concepts": "reconciling conflicting outputs; correlated errors and false consensus; escalation to human judgment; human override; stopping rules; decisions that should never be automated; the Evidence Defense format (10-min defense + 5-min cross-examination)",
        "python_r_dependency": "GenAI Studio roles via the API or UI (reconcile conflicting role outputs)",
        "dataset_simulation": "each student's own chapter draft + claim ledger",
        "minute_dynamic": "0–7 SRL-led retrieval & challenge: the lead shows three AI reviews that agree and one that dissents on the same chapter — the room decides whether the agreement is confirmation or correlated error, and what would tell them apart; 7–30 intensive applied AI laboratory: run your multi-role workflow to the point of conflict, reconcile the disagreements yourself, test each agreement for false consensus, and mark your stopping rule and the decisions you refuse to automate (M15 portfolio); 30–42 peer defense + adversarial questioning: the first Evidence Defenses run here in compressed staging form (a tightened defense + rapid cross-examination) so all five defenders fit across the two meetings, with every non-defender asking at least one ledger-grounded question; 42–50 transfer + ledger + Claim Ticket: finalize the AI-management portfolio log and write the ticket.",
        "hands_on_activity": "Reconcile your AI roles' conflicting outputs, test their agreements for false consensus, and either defend (if staged today) or cross-examine a classmate's defense.",
        "practice": "📝 nb15 practice: given three agreeing AI outputs and one dissent, decide whether the agreement is confirmation or correlated error, and name the check that decides.",
        "discussion_prompt": "When did you overrule every AI role at once today, and what did you know that they did not?",
        "project_connection": "M15 advances and the defenses begin: today's conflict-reconciliation log is a core portfolio entry, and the first defenders perform in the drawn order.",
        "milestone_developed": "M15 — Final Research Chapter and AI-Management Portfolio (defense staging: first defenses)",
        "milestone_work_time": "23 min (conflict-reconciliation lab) + 12 min (first defenses)",
        "milestone_presentation_review": "first Evidence Defenses (compressed staging) + cross-examination",
        "student_prep": "Chapter workflow advanced; three weakest ledger rows prepped; defense order drawn.",
        "student_artifact": "Conflict-reconciliation + false-consensus log + delivered defense or logged cross-examination",
        "exit_ticket": "Claim Ticket #42: the moment my AI roles reached false consensus, and how I caught it.",
        "homework_next_milestone": "Finish the final chapter and AI-management portfolio. The remaining defenses and the submission ceremony are Friday, when M15 is due.",
        "instructor_prep": "Defense rubrics per defender; timer; the cross-examination norms card; confirm the drawn order; GenAI Studio roles live for the conflict lab.",
        "risks_contingency": "Five full 10+5 defenses do not fit two 50-minute meetings → defenses run in compressed staging form (a tightened defense + rapid cross-examination) split across today and Friday; any defense that needs the full length gets an office-hours overflow slot the rubric notes.",
    },
    # ------------------------------------------------------------------ M43
    {
        "meeting": 43, "date": "2026-12-11", "day": "Fri", "modality": "in-person",
        "unit": "Week 16 — Managing multiple AI agents",
        "title": "Studio Friday (terminal) — the final defenses and the submission ceremony, M15 due",
        "driving_question": "You began with a curiosity and end with a defended, reproducible, honestly-bounded chapter. Does the evidence hold, and is it in?",
        "secondary_questions": "Do the remaining defenses survive cross-examination? Is your AI-management portfolio honest about what you automated and what you kept human? Is every number in the chapter traceable before you submit?",
        "inquiry": "all positions (synthesis)",
        "srl_slot": "",
        "srl_focus": "",
        "claim_permitted": "\"I can classify my question, match it to a design, state what my answer can and cannot establish, and defend every claim from a verified ledger.\"",
        "claim_not_permitted": "\"The AI wrote my chapter\" (you directed, verified, and own it — or you did not, and the defense shows which).",
        "rdss_reading": "(no new reading — terminal studio; RDSS ch. 24 'Epilogue' offered as an optional send-off, not required; book.declaredesign.org)",
        "cb_reading": "",
        "other_material": "nb15 student notebook (managing AI agents) §5 synthesis (Colab); project/final_dossier/evidence_defense_protocol.md (final defenses + the submission checklist); course-reflection survey; M15 due tonight",
        "provenance": "evidence_defense_protocol.md + fresh ceremony protocol | AI-management + synthesis unit | remaining Evidence Defenses + submission ceremony as the terminal studio work block | fresh",
        "concepts": "the Evidence Defense under cross-examination; the AI-management portfolio (what was automated, escalated, and overridden); ledger-traceable claims; number-to-cell traceability; the submission ceremony; verification as a habit that outlasts the course",
        "python_r_dependency": "none (defenders may open the chapter's capsule live if probed)",
        "dataset_simulation": "each student's own chapter, ledger, and AI-management portfolio",
        "minute_dynamic": "0–6 research stand-up: the AI decision you are proudest of overruling, one line each; 6–29 milestone kickoff + defense rounds: the instructor runs the final-dossier checklist one last time, then the REMAINING EVIDENCE DEFENSES run as the work block in the drawn order (compressed 10+5 format so all five defenders fit across the two meetings), every non-defender asking at least one ledger-grounded question; 29–41 peer + AI red-team review: a last cross-defense synthesis (what did the strongest defenses share?) and a final traceability spot-check — one number in your chapter shown to its notebook cell; 41–50 revise, ledger, submit + Claim Ticket: submit M15 and confirm it on screen, take the reflection survey, and write the final Claim Ticket.",
        "hands_on_activity": "Deliver or cross-examine the final defenses, run a last traceability spot-check on your own chapter, and submit M15.",
        "practice": "📝 (retrospective) the exit self-assessment: classify, match, bound, verify — rate yourself at the start of the semester versus now.",
        "discussion_prompt": "What claim did you believe at the start of the semester that you would now demand evidence for, and what evidence would satisfy you?",
        "project_connection": "M15 — the final research chapter, claim ledger, and AI-management portfolio — is submitted; the semester's complete, defended, reproducible artifact is in.",
        "milestone_developed": "M15 — Final Research Chapter and AI-Management Portfolio (SUBMITTED TODAY)",
        "milestone_work_time": "30 min studio block (final defenses + submission ceremony)",
        "milestone_presentation_review": "the remaining Evidence Defenses ARE the presentation/review",
        "student_prep": "Chapter, ledger, and AI-management portfolio complete; capsule runnable; ready to defend or cross-examine.",
        "student_artifact": "Delivered defense or logged cross-examination + submitted M15 + exit self-assessment + reflection survey",
        "exit_ticket": "Claim Ticket #43 (the last): one claim I will carry carefully for the rest of my life, and the evidence I hold it on.",
        "homework_next_milestone": "None. It is done. (Grades follow the posted rubric timeline.)",
        "instructor_prep": "Rubrics per remaining defender; the overflow slot in reserve; the strongest-defenses synthesis list; survey link live; submission mechanics confirmed; celebration logistics.",
        "risks_contingency": "A chapter misses the ceremony → the tonight deadline governs and the published late policy applies; the ceremony celebrates, the deadline grades. A defense needs the full length → the office-hours overflow slot absorbs it before the deadline.",
    },
]
