"""Meetings M23–M33 (Oct 19 – Nov 11): Phase 4 (diagnosis, prediction, causal),
Phase 5 (poster), start of Phase 6 (conference prep)."""

MEETINGS_P3 = [
    # ------------------------------------------------------------------ M23
    {
        "meeting": 23, "date": "2026-10-19", "day": "Mon", "modality": "in-person",
        "unit": "Phase 4 — Pilot, diagnosis, redesign",
        "title": "The diagnosis engine I: declare your design in code and interrogate it",
        "driving_question": "Before trusting your study, can you simulate it — and catch it failing?",
        "secondary_questions": "What are diagnosands (bias, power, coverage)? How does declare→diagnose work as a loop? Why simulate a study you haven't run?",
        "approach": "all (diagnosis engine)",
        "claim_permitted": "\"Simulated 1,000 times, my design shows bias ≈ B and power ≈ P for my inquiry — measured, not assumed.\"",
        "claim_not_permitted": "\"My design is fine\" as a feeling. Untested designs have undiagnosed diseases.",
        "rdss_reading": "RDSS ch. 10 'Diagnosing designs' (book.declaredesign.org); declaration_10.1; ch. 13 'Designing in code'",
        "cb_reading": "",
        "other_material": "nb11 §1–2 (Colab)",
        "provenance": "RDSS ch.10 + declaration_10.1.R + diagnosis_10.1.R | diagnosing designs | declare/diagnose loop translated to a compact Python helper | translated (R→Python)",
        "concepts": "design declaration in code; diagnosands: bias, power, coverage; Monte-Carlo diagnosis; the declare→diagnose loop",
        "python_r_dependency": "numpy/pandas (the course's inline declare_design/diagnose helpers, introduced here)",
        "dataset_simulation": "seeded Monte-Carlo diagnosis (1,000 runs) of a two-group design",
        "minute_dynamic": "0–5 M07 declarations returned with first-pass notes; 5–13 mini-lesson: the flight simulator argument — crash in simulation, not in the field; the three diagnosands; 13–20 pause-and-predict: our textbook design — biased or just noisy? commit before diagnosing; 20–35 hands-on: nb11 declare the design with the course helpers, run the 1,000-run diagnosis, read the diagnosand table; 35–46 lab: declare a SIMPLIFIED version of your own design (provided skeleton) and start its diagnosis; 46–50 exit ticket.",
        "hands_on_activity": "Declare a design in code, run a 1,000-replication diagnosis, and read bias/power/coverage off the result.",
        "practice": "📝 nb11 practice: match 3 sick designs to their diseases (bias / low power / bad coverage) from their diagnosand tables.",
        "discussion_prompt": "Pilots train in simulators because crashes are cheap there. What is the research equivalent of a simulator crash — and of a real one?",
        "project_connection": "Each student's simplified own-design declaration enters the diagnosis engine (M08 begins).",
        "milestone_developed": "M08 — Design Diagnosis & Redesign Memo",
        "milestone_work_time": "11 min (own-design declaration skeleton)",
        "milestone_presentation_review": "none (engine day)",
        "student_prep": "RDSS ch. 10 read; M07 declaration at hand.",
        "student_artifact": "Executed diagnosis of the textbook design + own declaration skeleton started",
        "exit_ticket": "Claim Ticket #23: the diagnosand my design most needs checked, and why.",
        "homework_next_milestone": "Finish your own-design declaration cells; Wednesday we diagnose and REDESIGN it (RDSS ch. 11).",
        "instructor_prep": "Stress-test the inline declare/diagnose helpers; keep runs ≤30s; prep the sick-designs cards.",
        "risks_contingency": "Helper code intimidates → students only FILL parameters (n, effect, noise), never write the machinery; machinery is narrated, not authored.",
    },
    # ------------------------------------------------------------------ M24
    {
        "meeting": 24, "date": "2026-10-21", "day": "Wed", "modality": "in-person",
        "unit": "Phase 4 — Pilot, diagnosis, redesign",
        "title": "The diagnosis engine II: redesign — fix it before you run it",
        "driving_question": "Your diagnosis found a weakness. What is the CHEAPEST change that fixes it?",
        "secondary_questions": "What can you redesign (n, measures, assignment, estimator)? How do you compare designs on a diagnosand? When is a question itself the thing to redesign?",
        "approach": "all (diagnosis engine)",
        "claim_permitted": "\"Redesign R raises power from P1 to P2 at cost C — I compared designs, not vibes.\"",
        "claim_not_permitted": "Changing the QUESTION to whatever the weak design can answer, silently (that is a new declaration, not a redesign).",
        "rdss_reading": "RDSS ch. 11 'Redesigning' (book.declaredesign.org); declaration_11.1",
        "cb_reading": "",
        "other_material": "nb11 §3–4 (Colab)",
        "provenance": "RDSS ch.11 + declaration_11.1.R + diagnosis_11.x | redesigning | redesign-comparison loop translated | translated (R→Python)",
        "concepts": "redesign levers; design comparison tables; cost-aware improvement; honest vs silent redesign",
        "python_r_dependency": "numpy/pandas (rerun diagnosis across parameter grids)",
        "dataset_simulation": "seeded redesign grid over the M23 design + each student's own",
        "minute_dynamic": "0–5 diagnosand-table cold reads (two volunteers read a table aloud correctly); 5–12 mini-lesson: the four redesign levers, each with its price tag; 12–25 hands-on: nb11 rerun the textbook design across a redesign grid, build the comparison table, pick the cheapest fix; 25–40 M08 STUDIO: diagnose YOUR design, apply one redesign, record before/after diagnosands (rotating consults); 40–47 REDESIGN PITCHES: each student, 60 seconds — my weakness, my fix, my before/after numbers; 47–50 exit ticket.",
        "hands_on_activity": "Build a redesign comparison table and defend the cheapest fix with before/after diagnosands.",
        "practice": "📝 nb11 practice: given a fixed budget, choose between doubling n and halving measurement noise — verify your choice by simulation.",
        "discussion_prompt": "When is shrinking your question the honest redesign — and how would a reader know you did it?",
        "project_connection": "M08 memo takes form: each project now has diagnosed numbers and one committed redesign.",
        "milestone_developed": "M08 — Design Diagnosis & Redesign Memo (presented; submit Fri Oct 23)",
        "milestone_work_time": "15 min (own diagnose + redesign studio)",
        "milestone_presentation_review": "M08 presented: 60-second redesign pitches with before/after diagnosands",
        "student_prep": "Own-design declaration cells complete (Monday's homework); RDSS ch. 11 read.",
        "student_artifact": "Own before/after diagnosand table + delivered redesign pitch",
        "exit_ticket": "Claim Ticket #24: my design's diagnosed weakness and the fix I committed to, with numbers.",
        "homework_next_milestone": "Write up and submit the M08 memo (diagnosis + redesign, with tables) by Fri Oct 23, 11:59 PM. Friday: prediction begins.",
        "instructor_prep": "Consult order; verify grid runs stay fast; timer for pitches.",
        "risks_contingency": "A student's design resists the simple helpers → instructor pair-declares it live in the consult; the memo may use the simplified stand-in with the simplification documented.",
    },
    # ------------------------------------------------------------------ M25
    {
        "meeting": 25, "date": "2026-10-23", "day": "Fri", "modality": "in-person",
        "unit": "Phase 4 — Pilot, diagnosis, redesign",
        "title": "Prediction deep dive I: target, baseline, split — forecasting without fooling yourself",
        "driving_question": "Can you forecast new cases better than the dumbest honest rule?",
        "secondary_questions": "What is a prediction target? Why must a baseline come first? Why hold out data you never touch?",
        "approach": "PREDICTION (deep dive)",
        "claim_permitted": "\"On held-out cases, my model beats the baseline by [margin] on [metric].\"",
        "claim_not_permitted": "Any performance number computed on data the model already saw — and any 'the model shows X matters' explanation talk.",
        "rdss_reading": "(RDSS treats prediction lightly — this unit is built fresh; ch. 9 answer-strategy framing carries over)",
        "cb_reading": "optional: callingbullshit.org — big-data/algorithm hubris case",
        "other_material": "nb12 §1–2 (Colab); scikit-learn (linked docs)",
        "provenance": "fresh (scikit-learn) | prediction unit | target/baseline/split/metric protocol | fresh",
        "concepts": "prediction target; baseline rule; train/test split; metric choice; out-of-sample honesty",
        "python_r_dependency": "scikit-learn (train_test_split, DummyClassifier, LogisticRegression), pandas",
        "dataset_simulation": "la_voter_file.csv (predict turnout from voter-file fields)",
        "minute_dynamic": "0–5 M08 submission check + why prediction is its own column (recall the 2×2); 5–13 mini-lesson: the prediction contract — target, baseline, split, metric, in that order; 13–20 pause-and-predict: what accuracy does the always-votes baseline get on this file? commit; 20–35 hands-on: nb12 build the baseline, beat (or fail to beat) it with a simple model, all scoring on held-out rows; 35–45 lab: IF your project has a predictive angle, define its target+baseline+metric; if not, write why prediction is the wrong column for your question (both are M09 prep); 45–50 exit ticket.",
        "hands_on_activity": "Score a dumb baseline honestly on held-out data, then try to beat it — and feel how hard honest beats easy.",
        "practice": "📝 nb12 practice: choose the right metric for 3 targets (rare event, balanced classes, costly false negatives) and defend each.",
        "discussion_prompt": "The baseline got 78% and the fancy model got 80%. Write the honest headline — then the dishonest one you almost wrote.",
        "project_connection": "M09 pilot prep: each project confirms or rules out its predictive component with reasons.",
        "milestone_developed": "M09 — Pilot Analysis (approach-specific)",
        "milestone_work_time": "10 min (own prediction-angle decision memo)",
        "milestone_presentation_review": "none",
        "student_prep": "M08 due tonight 11:59 PM; nothing else new.",
        "student_artifact": "Baseline-vs-model held-out comparison + own prediction-angle memo",
        "exit_ticket": "Claim Ticket #25: my project's prediction verdict (has an angle / wrong column) in one defended sentence.",
        "homework_next_milestone": "Read the nb12 leakage preview cell; Monday: how prediction goes wrong (leakage) and prediction ≠ explanation.",
        "instructor_prep": "Verify la_voter_file predictive cells run fast; pre-compute the baseline so the reveal is snappy.",
        "risks_contingency": "sklearn friction → all model code is provided; students only choose the target column and read outputs.",
    },
    # ------------------------------------------------------------------ M26
    {
        "meeting": 26, "date": "2026-10-26", "day": "Mon", "modality": "in-person",
        "unit": "Phase 4 — Pilot, diagnosis, redesign",
        "title": "Prediction deep dive II: leakage, and why performance is not understanding",
        "driving_question": "Your model scores brilliantly. What are the two most likely explanations — and why is 'it understands the world' third?",
        "secondary_questions": "What is leakage and how does it sneak in? Why do good predictors make bad explainers? What does prediction contribute to a research argument?",
        "approach": "PREDICTION (deep dive)",
        "claim_permitted": "\"My model forecasts held-out cases at [level]; I checked the features for leakage; I make no causal reading of its weights.\"",
        "claim_not_permitted": "\"The model's top feature is X, so X drives the outcome\" — importance is not explanation, and leakage fakes importance.",
        "rdss_reading": "(fresh unit continues)",
        "cb_reading": "optional: callingbullshit.org — machine-bias / algorithm case",
        "other_material": "nb12 §3–4 (Colab)",
        "provenance": "fresh (scikit-learn) | prediction unit | leakage demonstration built for the course | fresh",
        "concepts": "leakage (target proxies, post-outcome features); the performance-understanding gap; prediction's honest role in research",
        "python_r_dependency": "scikit-learn, pandas (leaky vs clean feature sets)",
        "dataset_simulation": "la_voter_file.csv with one deliberately leaky feature engineered in",
        "minute_dynamic": "0–5 recap bet: guess the leaky feature hiding in today's feature list; 5–12 mini-lesson: leakage taxonomy with two war stories; 12–27 hands-on: nb12 train on the leaky set (spectacular score), find the leak, retrain clean (honest score), write the delta; 27–36 pause-and-reflect: what SHOULD a researcher do with a great predictor (triage, targeting, hypothesis generation — not explanation); 36–46 M09 studio: pilot-analysis plans drafted, approach branch confirmed (rotating consults); 46–50 exit ticket.",
        "hands_on_activity": "Train on a leaky feature set, catch the leak, retrain clean, and report both numbers side by side.",
        "practice": "📝 nb12 practice: 4 features for predicting hospital readmission — rank by leakage risk and justify.",
        "discussion_prompt": "An algorithm predicts who will miss probation appointments. List one legitimate use and one illegitimate use of exactly the same scores.",
        "project_connection": "M09 pilot plans locked: every student knows which approach branch their pilot runs.",
        "milestone_developed": "M09 — Pilot Analysis (approach-specific)",
        "milestone_work_time": "10 min (pilot plan studio + consults)",
        "milestone_presentation_review": "rotating instructor consults",
        "student_prep": "nb12 §1–2 complete; prediction-angle memo from Friday.",
        "student_artifact": "Leaky-vs-clean comparison + locked pilot plan",
        "exit_ticket": "Claim Ticket #26: the leakage risk nearest MY project's data, and my check for it.",
        "homework_next_milestone": "Read RDSS ch. 16 opener + skim declaration_18.1 context; Wednesday: causal reasoning proper.",
        "instructor_prep": "Engineer the leaky feature so discovery is satisfying (findable in ~10 min); prep war stories.",
        "risks_contingency": "Leak found too fast → the notebook's second, subtler leak (temporal) is the extension path.",
    },
    # ------------------------------------------------------------------ M27
    {
        "meeting": 27, "date": "2026-10-28", "day": "Wed", "modality": "in-person",
        "unit": "Phase 4 — Pilot, diagnosis, redesign",
        "title": "Causal reasoning deep dive I: counterfactuals, experiments, and what randomization buys",
        "driving_question": "What would have happened WITHOUT the intervention — and how can anyone know?",
        "secondary_questions": "Why is the counterfactual the heart of every causal claim? What exactly does randomization solve? What is an identification argument?",
        "approach": "CAUSAL (deep dive)",
        "claim_permitted": "\"Because assignment was randomized (checked), the difference in outcomes estimates the causal effect, with stated uncertainty.\"",
        "claim_not_permitted": "A causal claim whose counterfactual is imagined rather than identified (\"they improved after the program, so the program worked\").",
        "rdss_reading": "RDSS ch. 18 'Experimental: causal' (book.declaredesign.org); declaration_18.1 (two-arm trial)",
        "cb_reading": "",
        "other_material": "nb13 §1–2 (Colab)",
        "provenance": "RDSS ch.18 + declaration_18.1.R + rdss foos_etal | experimental causal designs | two-arm trial translated; real GOTV experiment replicated descriptively | translated (R→Python)",
        "concepts": "counterfactuals (return of Y(1),Y(0)); randomization as counterfactual-maker; identification argument; the two-arm trial",
        "python_r_dependency": "numpy/pandas (analyze the foos_etal experiment; difference-in-means + interval)",
        "dataset_simulation": "foos_etal.csv (real get-out-the-vote field experiment, MIT-licensed replication data)",
        "minute_dynamic": "0–5 the 2×2 completed ceremonially — the last column's deep dive begins; 5–13 mini-lesson: the counterfactual problem and randomization's trick, replayed on the nb04 world; 13–20 pause-and-predict: in the real foos_etal experiment, did contact raise turnout? by how much? commit; 20–35 hands-on: nb13 analyze the real experiment — balance check, effect estimate, interval — then write its identification argument in 3 sentences; 35–45 lab: write YOUR project's identification paragraph (or the honest 'no identification available — my claim stops at association'); 45–50 exit ticket.",
        "hands_on_activity": "Analyze a real randomized field experiment end-to-end and write its 3-sentence identification argument.",
        "practice": "📝 nb13 practice: 3 claims — write the counterfactual each silently asserts, then grade its plausibility.",
        "discussion_prompt": "'The patients who took the drug did better.' Give the two non-causal stories, then say what randomization would have done to them.",
        "project_connection": "Every project writes its identification paragraph — or its honest absence.",
        "milestone_developed": "M09 — Pilot Analysis (approach-specific)",
        "milestone_work_time": "10 min (own identification paragraph)",
        "milestone_presentation_review": "none",
        "student_prep": "RDSS ch. 16 opener + declaration_18.1 context skimmed; pilot plan locked.",
        "student_artifact": "Analyzed real experiment + own identification (or non-identification) paragraph",
        "exit_ticket": "Claim Ticket #27: my project's causal status in one sentence: identified by ___ / honestly not identified.",
        "homework_next_milestone": "Pilot analyses due FRIDAY (M09, walkthrough day). Read RDSS ch. 16 DiD/RDD intuition sections.",
        "instructor_prep": "Verify foos_etal loads + effect reproduces; prep the balance-check cell; office hours advertised for pilot crunch.",
        "risks_contingency": "Pilot crunch panic → Friday's walkthrough accepts work-in-progress pilots; the submission deadline carries the polish.",
    },
    # ------------------------------------------------------------------ M28
    {
        "meeting": 28, "date": "2026-10-30", "day": "Fri", "modality": "in-person",
        "unit": "Phase 4 — Pilot, diagnosis, redesign",
        "title": "Causal reasoning deep dive II: causal claims without experiments — and the M09 pilot walkthroughs",
        "driving_question": "When you cannot randomize, what earns you the word 'because'?",
        "secondary_questions": "What leverage do DiD, RDD, and IV each exploit (intuition only)? What assumptions does each buy its identification with? How do you present a pilot honestly?",
        "approach": "CAUSAL (deep dive)",
        "claim_permitted": "\"Under [parallel trends / threshold locality / instrument validity — stated and probed], the estimate carries a causal reading.\"",
        "claim_not_permitted": "Design-mimicry: DiD/RDD/IV vocabulary decorating a comparison whose assumptions were never argued.",
        "rdss_reading": "RDSS ch. 16 'Observational: causal' (book.declaredesign.org) — DiD/RDD/IV intuition sections",
        "cb_reading": "",
        "other_material": "nb13 §3–4 (Colab); cliningsmith_etal.csv (natural-experiment flavor)",
        "provenance": "RDSS ch.16 + rdss cliningsmith_etal | observational causal designs | DiD/RDD/IV intuition, no estimation machinery | adapted",
        "concepts": "difference-in-differences, regression discontinuity, instrumental variables — as identification ARGUMENTS; assumption probing",
        "python_r_dependency": "pandas/matplotlib (picture-first DiD and RDD illustrations, provided)",
        "dataset_simulation": "cliningsmith_etal.csv + two seeded illustrative simulations (parallel-trends world, threshold world)",
        "minute_dynamic": "0–5 settle + walkthrough order; 5–15 mini-lesson: three ways nature randomizes for you, one picture each (DiD's parallel lines, RDD's cliff, IV's nudge); 15–20 quick check: match 3 scenarios to their design; 20–42 M09 PILOT WALKTHROUGHS: five ~4-minute walkthroughs (what I ran, what came out, what surprised me), listeners log one verification question each; 42–48 revision notes + submission checklist; 48–50 exit ticket.",
        "hands_on_activity": "Match natural-experiment scenarios to their identification argument; probe one assumption per design.",
        "practice": "📝 nb13 practice: for each of DiD/RDD/IV, write the one sentence a skeptic would attack first.",
        "discussion_prompt": "On a classmate's pilot: what is the single verification step you most want them to run before believing their own output?",
        "project_connection": "M09 pilots presented and submitted — every project now has real preliminary evidence, honestly bounded.",
        "milestone_developed": "M09 — Pilot Analysis (presented + submitted TONIGHT)",
        "milestone_work_time": "22 min (walkthroughs) + 6 min (revision + checklist)",
        "milestone_presentation_review": "M09 presented: 4-minute pilot walkthroughs + logged verification questions",
        "student_prep": "Pilot analysis executed (any state of polish); walkthrough rehearsed.",
        "student_artifact": "Delivered walkthrough + verification-question log + submitted M09",
        "exit_ticket": "Claim Ticket #28: the verification question a classmate asked me, and how I will answer it before the poster.",
        "homework_next_milestone": "Submit M09 tonight 11:59 PM. Monday: POSTER PHASE — bring your best figure and your headline claim.",
        "instructor_prep": "Timer; walkthrough rubric; check the three intuition pictures render cleanly; verify cliningsmith_etal loads.",
        "risks_contingency": "A pilot collapsed during the week → its walkthrough presents the failure + diagnosis (explicitly graded as legitimate); redesign happens in office hours.",
    },
    # ------------------------------------------------------------------ M29
    {
        "meeting": 29, "date": "2026-11-02", "day": "Mon", "modality": "in-person",
        "unit": "Phase 5 — Poster construction & submission",
        "title": "Poster I: storyboard — one claim, one hierarchy of evidence",
        "driving_question": "If a stranger reads your poster for 90 seconds, what ONE defensible claim must survive?",
        "secondary_questions": "What is an evidence hierarchy on a poster? What earns the top-center slot? How does uncertainty live on a poster without killing it?",
        "approach": "all (communication)",
        "claim_permitted": "The poster's headline claim, worded to match its approach's boundary — description as description, association as association.",
        "claim_not_permitted": "A headline that outruns the pilot's evidence (the 90-second reader will never see your caveats footnote).",
        "rdss_reading": "(fresh unit; RDSS figure style referenced for honest graphics)",
        "cb_reading": "",
        "other_material": "nb14 §1–2 (Colab); URC poster specs; storyboard template",
        "provenance": "brief §12 P5 + fresh storyboard method + Purdue URC specs | poster unit | storyboard grid | fresh",
        "concepts": "storyboarding; claim hierarchy; the 90-second read path; poster real estate economics; uncertainty placement",
        "python_r_dependency": "none required (figure polish optional, matplotlib)",
        "dataset_simulation": "each student's own pilot outputs",
        "minute_dynamic": "0–5 poster-phase kickoff: the Nov 6 deadline is REAL (production, not buffer); 5–12 mini-lesson: the 90-second read path traced on two example posters (one strong, one lost); 12–30 studio: fill the storyboard grid — headline claim, 3 evidence blocks ranked, uncertainty line, read path arrows (M10); 30–42 STORYBOARD PITCHES: 90 seconds each — walk us down your read path; listeners mark where they got lost; 42–48 revise the grid from the lost-points; 48–50 exit ticket + M10 submission tonight.",
        "hands_on_activity": "Fill the storyboard grid for your own poster and walk a listener down its 90-second read path.",
        "practice": "📝 nb14 practice: rank your pilot's 5 outputs by evidence value for the headline claim; cut the bottom two.",
        "discussion_prompt": "What did the strong example poster REFUSE to include — and why did that refusal make it stronger?",
        "project_connection": "M10 storyboard submitted tonight; the draft build starts from it Wednesday.",
        "milestone_developed": "M10 — Poster Storyboard (presented + submitted TODAY)",
        "milestone_work_time": "18 min (grid studio) + 6 min (revision)",
        "milestone_presentation_review": "M10 presented: 90-second storyboard pitches with lost-point marking",
        "student_prep": "M09 submitted; best figure + headline claim in hand.",
        "student_artifact": "Completed storyboard grid + pitch + revision marks",
        "exit_ticket": "Claim Ticket #29: my headline claim, ≤15 words, inside my approach's boundary.",
        "homework_next_milestone": "Submit M10 tonight 11:59 PM; build the full draft poster for Wednesday's red-team (any tool: PowerPoint/Canva/Quarto).",
        "instructor_prep": "Two example posters chosen; storyboard grids printed; URC spec sheet distributed.",
        "risks_contingency": "Pilot results too thin for a poster → the storyboard pivots to 'design + preliminary evidence' framing (explicitly legitimate for URC undergraduate posters).",
    },
    # ------------------------------------------------------------------ M30
    {
        "meeting": 30, "date": "2026-11-04", "day": "Wed", "modality": "in-person",
        "unit": "Phase 5 — Poster construction & submission",
        "title": "Poster II: draft + red-team — attack your own poster before strangers do",
        "driving_question": "Where does your draft overclaim, underexplain, or lose the reader — and who will find it first?",
        "secondary_questions": "What does a red-team review look for (claim boundary, figure honesty, read path, uncertainty)? How do you take a hit and revise?",
        "approach": "all (communication)",
        "claim_permitted": "\"A hostile reader walked my poster and the headline survived — here are the three hits and my three fixes.\"",
        "claim_not_permitted": "Shipping a draft no adversarial eye has touched (peer-review is the course's quality gate, not a courtesy).",
        "rdss_reading": "(fresh unit)",
        "cb_reading": "",
        "other_material": "nb14 §3 red-team protocol (Colab); draft posters on screens; the M14 honest-viz checklist rides again",
        "provenance": "fresh (red-team protocol) + M14 honest-viz checklist | poster unit | adversarial review protocol | fresh",
        "concepts": "red-team review; claim-boundary audit; figure-honesty audit; read-path audit; revision triage",
        "python_r_dependency": "none",
        "dataset_simulation": "each student's own draft poster",
        "minute_dynamic": "0–5 red-team norms: hard on the poster, warm on the person; roles assigned (each student red-teams two posters); 5–10 protocol walkthrough: the four audits with the scoring slip; 10–34 RED-TEAM ROUNDS: two 12-minute rounds — reviewer walks the poster with the audit slip while the author listens silently, then 2 minutes of author questions; 34–46 revision triage: authors rank their hits, fix the top one NOW, plan the rest; 46–50 exit ticket + M11 submission tonight (draft + received reviews + triage plan).",
        "hands_on_activity": "Red-team two classmates' posters with the four-audit slip; triage and begin fixing your own hits.",
        "practice": "📝 nb14 practice: the four audits applied to a sample poster with 6 planted flaws — find at least 4.",
        "discussion_prompt": "Which audit found your poster's worst flaw — and why didn't YOU find it first?",
        "project_connection": "M11 (draft + red-team record) submits tonight; only production polish remains before Friday.",
        "milestone_developed": "M11 — Poster Draft + Red-Team Review (submitted TODAY)",
        "milestone_work_time": "24 min (red-team rounds) + 12 min (triage + first fix)",
        "milestone_presentation_review": "M11 review: structured red-team with written audit slips (this IS the presentation/review)",
        "student_prep": "Full draft poster ready on screen (Monday's homework).",
        "student_artifact": "Two completed audit slips given + own triage plan + first fix applied",
        "exit_ticket": "Claim Ticket #30: the hit I'm fixing first, and what the fixed version says instead.",
        "homework_next_milestone": "Apply the full triage plan; FINAL poster due Friday in class (production day) — submission Nov 6 is the real deadline.",
        "instructor_prep": "Print audit slips; assign the red-team rotation (5 students → each reviews 2, is reviewed by 2); sample flawed poster ready.",
        "risks_contingency": "A draft doesn't exist by class → that student red-teams others (obligation stands) and enters Friday's production day with the storyboard + instructor triage instead.",
    },
    # ------------------------------------------------------------------ M31
    {
        "meeting": 31, "date": "2026-11-06", "day": "Fri", "modality": "in-person",
        "unit": "Phase 5 — Poster construction & submission",
        "title": "Poster III: final production and SUBMISSION — the deadline is today",
        "driving_question": "Is every claim on this poster one you can defend to a stranger on Nov 17?",
        "secondary_questions": "Does the final pass the four audits? Are figures reproducible from your notebook? Is the file print-ready to URC spec?",
        "approach": "all (communication)",
        "claim_permitted": "\"Submitted: every number on this poster traces to a cell in my notebook, and every claim sits inside my approach's boundary.\"",
        "claim_not_permitted": "\"I'll fix it after submission.\" (There is no after — Nov 17 is a live audience, not a draft reader.)",
        "rdss_reading": "(fresh unit)",
        "cb_reading": "",
        "other_material": "nb14 §4 final checklist (Colab); URC submission portal/instructions",
        "provenance": "fresh + Purdue URC specs | poster unit | final production checklist | fresh",
        "concepts": "production checklist; number-to-notebook traceability; print specs; submission hygiene",
        "python_r_dependency": "none (figure re-exports as needed)",
        "dataset_simulation": "each student's own final poster",
        "minute_dynamic": "0–5 deadline briefing + checklist distributed; 5–35 PRODUCTION SPRINT: silent studio, instructor circulates on a fixed rotation (5 × ~5 min consults) running the final checklist on each poster; 35–45 traceability spot-check: for one number on your poster, show the notebook cell that produced it (pairs verify each other); 45–50 SUBMIT (Brightspace + URC channel as instructed) + exit ticket.",
        "hands_on_activity": "Final production sprint: run the checklist, verify one number's notebook traceability under a partner's eyes, submit.",
        "practice": "📝 (embedded in checklist) verify: fonts ≥ minimum size at print scale; every figure has its uncertainty or its caveat.",
        "discussion_prompt": "(brief, during consults) Which checklist line almost caught you?",
        "project_connection": "M12 FINAL POSTER submitted — the URC artifact is locked; everything after this is delivery and depth.",
        "milestone_developed": "M12 — Final Poster (SUBMITTED TODAY, Nov 6)",
        "milestone_work_time": "45 min (production + verification + submission)",
        "milestone_presentation_review": "instructor final-checklist consults + pair traceability check",
        "student_prep": "Triage plan fully applied; print-ready file staged.",
        "student_artifact": "Submitted final poster + signed checklist + traceability verification",
        "exit_ticket": "Claim Ticket #31: one claim I softened before submission, and why the softer version is stronger.",
        "homework_next_milestone": "Rest this weekend. Monday: from poster to PERFORMANCE — the 1-minute and 3-minute pitches.",
        "instructor_prep": "Confirm submission mechanics (portal/print shop); consult rotation timer; backup printing plan.",
        "risks_contingency": "Printing/portal failure → PDF submission to Brightspace timestamps the deadline; physical printing resolves next week (before Nov 17).",
    },
    # ------------------------------------------------------------------ M32
    {
        "meeting": 32, "date": "2026-11-09", "day": "Mon", "modality": "in-person",
        "unit": "Phase 6 — Conference preparation",
        "title": "Delivery I: the 1-minute and 3-minute pitch architectures",
        "driving_question": "A visitor stops at your poster. What do your first 60 seconds do?",
        "secondary_questions": "How do the 1-min and 3-min versions differ in job (hook vs walk)? Where does the claim boundary live in spoken form? What does a confident 'we don't know yet' sound like?",
        "approach": "all (communication)",
        "claim_permitted": "Spoken claims that match the poster's written boundary — the pitch may compress evidence, never inflate it.",
        "claim_not_permitted": "The excited-mouth upgrade: saying 'causes' at the poster after writing 'is associated with' on it.",
        "rdss_reading": "(fresh unit)",
        "cb_reading": "",
        "other_material": "nb15 §1–2 (Colab); pitch architecture templates",
        "provenance": "brief §12 P6 + fresh pitch architectures | conference unit | 1-min hook / 3-min walk scripts | fresh",
        "concepts": "pitch architecture (hook, claim, evidence, boundary, invitation); compression without inflation; spoken uncertainty",
        "python_r_dependency": "none",
        "dataset_simulation": "each student's own poster",
        "minute_dynamic": "0–5 poster-phase debrief + what Nov 17 actually looks like (logistics); 5–13 mini-lesson: the two architectures, demonstrated live by the instructor on a past poster (once well, once inflated — spot the upgrade); 13–28 drafting studio: script your 1-minute hook using the template, mark the boundary sentence (M13); 28–42 FIRST DELIVERY ROUND: everyone delivers the 1-minute to a partner twice (swap roles), partner flags any spoken upgrade; 42–48 revise scripts; 48–50 exit ticket.",
        "hands_on_activity": "Script and twice-deliver your 1-minute pitch; catch your partner's spoken claim-upgrades.",
        "practice": "📝 nb15 practice: compress your 3 evidence blocks into one spoken sentence each — no inflation allowed.",
        "discussion_prompt": "Where in the instructor's inflated demo did the claim outrun the poster — what exact word did it?",
        "project_connection": "M13 presentation plan begins: the 1-minute script is its first component.",
        "milestone_developed": "M13 — Presentation Plan (1-min + 3-min)",
        "milestone_work_time": "15 min (scripting) + 14 min (delivery rounds)",
        "milestone_presentation_review": "partner delivery rounds with upgrade-flagging",
        "student_prep": "Final poster content internalized; comfortable saying your headline claim aloud.",
        "student_artifact": "1-minute script with marked boundary sentence + delivery feedback",
        "exit_ticket": "Claim Ticket #32: my boundary sentence, exactly as I will SAY it.",
        "homework_next_milestone": "Draft the 3-minute walk script; M13 (both scripts + poster-walk map) due Wed Nov 11, 11:59 PM.",
        "instructor_prep": "Rehearse the well/inflated demo pair; print architecture templates; confirm URC-day logistics to brief.",
        "risks_contingency": "Stage fright surfaces → normalize with the two-attempt structure (everyone's first attempt is officially a draft) and offer office-hours solo rehearsal.",
    },
    # ------------------------------------------------------------------ M33
    {
        "meeting": 33, "date": "2026-11-11", "day": "Wed", "modality": "in-person",
        "unit": "Phase 6 — Conference preparation",
        "title": "Delivery II: uncertainty and limitations, spoken like a scientist",
        "driving_question": "Can you state what your study CANNOT show — and make it sound like strength?",
        "secondary_questions": "Why do limitations spoken first-person build credibility? What is the uncertainty-limitations-next-step (ULN) move? How do you avoid the apology spiral?",
        "approach": "all (communication)",
        "claim_permitted": "\"This is an association in a convenience frame; it cannot establish X; the design that could is Y\" — limitation as expertise.",
        "claim_not_permitted": "Either failure mode: hiding limitations, or drowning in them (\"this is probably all wrong\") — both misstate the evidence.",
        "rdss_reading": "(fresh unit; RDSS ch. 10 diagnosands vocabulary echoes in spoken form)",
        "cb_reading": "",
        "other_material": "nb15 §3 (Colab); ULN move template; M13 due tonight",
        "provenance": "brief §12 P6 + fresh ULN protocol | conference unit | spoken-limitations discipline | fresh",
        "concepts": "the ULN move (uncertainty → limitation → next step); credibility mechanics; the apology spiral and its antidote",
        "python_r_dependency": "none",
        "dataset_simulation": "each student's own findings",
        "minute_dynamic": "0–5 1-minute pitch pulse (one volunteer, warm notes); 5–12 mini-lesson: the ULN move, demonstrated on three findings including a null; 12–24 writing studio: draft YOUR ULN paragraph (M14 core) — the honest limitation, said with a straight spine; 24–40 ULN ROUNDS: deliver your ULN to two successive partners; partners score on the strength-not-apology scale; 40–47 whole-group: the best ULN heard, re-delivered for the room; 47–50 exit ticket + M13 due tonight reminder.",
        "hands_on_activity": "Draft and twice-deliver your uncertainty-limitations-next-step paragraph; score partners on strength-not-apology.",
        "practice": "📝 nb15 practice: convert 3 apology-spiral sentences into ULN form.",
        "discussion_prompt": "Why does 'here is what this study cannot show' make an expert MORE believable, not less?",
        "project_connection": "M14 (uncertainty & limitations statement) drafts its spoken core; written form completes Friday.",
        "milestone_developed": "M13 (submitted tonight) → M14 — Uncertainty & Limitations Statement",
        "milestone_work_time": "12 min (ULN drafting) + 16 min (delivery rounds)",
        "milestone_presentation_review": "ULN partner rounds with strength-not-apology scoring",
        "student_prep": "M13 scripts due tonight 11:59 PM; findings at hand.",
        "student_artifact": "ULN paragraph + delivery scores",
        "exit_ticket": "Claim Ticket #33: my single most important limitation, stated in ULN form, ≤30 words.",
        "homework_next_milestone": "Write the full M14 statement (uncertainty + limitations + hard-question bank starts Friday); due Fri Nov 13, 11:59 PM.",
        "instructor_prep": "Three ULN demos prepped (incl. the null finding); scoring slips printed.",
        "risks_contingency": "ULNs collapse into apology → pause rounds, re-demo the spine posture, restart with the sentence stems on screen.",
    },
]
