"""Meetings M12–M22: Weeks 5–8 — the design-library pathways (observational
descriptive, observational causal, experimental descriptive, prediction). Each
pathway week teaches its design family in the DeclareDesign library's
declare -> diagnose -> redesign frame with DAGs and simulations; Mon/Wed are
SRL-led AI-lab lectures, Fridays are milestone studios, and Week 6's Friday is
the async-online causal studio (instructor traveling)."""

MEETINGS_P2 = [
    # ------------------------------------------------------------------ M12
    {
        "meeting": 12, "date": "2026-09-21", "day": "Mon", "modality": "in-person",
        "unit": "Week 5 — Observational descriptive research",
        "title": "Observational descriptive designs: population, frame, sample — who your data can speak for",
        "driving_question": "When you can only observe, never intervene, what can a description honestly claim, and about whom?",
        "secondary_questions": "What separates the population you care about from the one your frame can reach? Where does selection quietly enter? How do you declare an observational descriptive design before collecting a single row?",
        "inquiry": "Description -> Generalization — descriptive kind · data-at-hand and population reach (observational pathway, Lecture 1)",
        "srl_slot": "SRL slot 06 — rotation seat A",
        "srl_focus": "Puzzle: a campus poll of dining-hall diners reports 'what Purdue students think' — name every gap between the diners observed and the students meant.",
        "claim_permitted": "\"In the units my sampling frame actually reaches, the share with characteristic X is [estimate], described exactly as observed.\"",
        "claim_not_permitted": "\"This describes the whole population\" when the frame misses part of it, or \"X causes Y\" from a description that never intervened.",
        "rdss_reading": "RDSS ch. 15 'Observational: descriptive' (book.declaredesign.org), population/frame/sample sections; the observational-descriptive entries in the DeclareDesign design library",
        "cb_reading": "optional: callingbullshit.org module on selection bias",
        "other_material": "nb04 student notebook (observational descriptive), §1–3 (Colab); la_voter_file attribution note",
        "provenance": "RDSS ch.15 + DeclareDesign library (observational descriptive) + rdss la_voter_file | population/frame/sample stack + declaring an observational design | frame-and-sample draw simulated from the voter file (seed 464) | translated (R→Python)",
        "concepts": "target population vs accessible population; sampling frame; sample; selection; coverage; the observational descriptive design declared as Model + Inquiry + Data strategy; a selection DAG (arrows into 'observed'); simulating a frame -> sample draw",
        "python_r_dependency": "pandas (read the voter file as a frame), numpy (seeded sampling, seed 464), matplotlib (frame vs sample comparison)",
        "dataset_simulation": "la_voter_file.csv used as a sampling frame (1,000 rows); seeded repeated draws from it (seed 464)",
        "minute_dynamic": "0–9 SRL-led research puzzle: the SRL hands the room a dining-hall poll claiming to speak for all Purdue students, and the class lists every gap between who was observed and who was meant; 9–31 guided Gemini research-partner investigation in the notebook: with Gemini as research partner, load la_voter_file as a frame, draw repeated seeded samples, and ask Gemini to name the population each draw can and cannot speak for while you check its answer against the data; 31–43 human verification + instructor formalization: the instructor formalizes target population vs accessible population vs frame vs sample and draws the selection DAG, and the class verifies Gemini's claims against what the draws actually show; 43–50 decision & defense: log the AI Research Ledger entry (what Gemini proposed, how you verified) and write the Claim Ticket.",
        "hands_on_activity": "With Gemini as research partner, use la_voter_file as a sampling frame, draw repeated seeded samples, and state for each the population it can honestly describe and the gap the frame leaves out.",
        "practice": "📝 nb04 practice: for four observational STEM settings (environmental monitoring, a biodiversity survey, materials characterization, app usage telemetry), name the target population, the accessible population, and the selection that separates them.",
        "discussion_prompt": "Think about the data you can actually get for your project. Who is in your reachable frame, who is silently left out, and does that gap line up with the people your question is really about?",
        "project_connection": "The population/frame/sample stack and first selection DAG you draft today become the spine of the M4 observational descriptive design audit.",
        "milestone_developed": "M4 — Observational descriptive design audit",
        "milestone_work_time": "7 min (draft your project's population/frame/sample stack + first selection DAG into the M4 audit)",
        "milestone_presentation_review": "none (lecture day)",
        "student_prep": "Read the RDSS ch. 15 opener on observational descriptive designs; bring the research question from your M3 declaration.",
        "student_artifact": "Executed frame-and-sample cells + your project's population/frame/sample stack + first selection DAG",
        "exit_ticket": "Claim Ticket #12: the population my project's frame can honestly describe, and the one it cannot reach.",
        "homework_next_milestone": "Finish nb04 §1–3 and keep building the M4 audit. For Wednesday, read the RDSS ch. 15 measurement and nonresponse sections.",
        "instructor_prep": "Confirm la_voter_file.csv loads from the raw URL; pre-seed the sampling draws (seed 464); prepare the selection DAG build; brief the SRL on the dining-hall puzzle.",
        "risks_contingency": "Voter file slow to load in Colab → nb04 subsamples on load (seeded) with the full-file path documented; the DAG discussion runs long → the measurement preview moves to Lecture 2.",
    },
    # ------------------------------------------------------------------ M13
    {
        "meeting": 13, "date": "2026-09-23", "day": "Wed", "modality": "in-person",
        "unit": "Week 5 — Observational descriptive research",
        "title": "Reading an observational description: measurement, missingness, and the generalization boundary",
        "driving_question": "Once the data are in, how do you summarize them honestly, and how far past your sample may the summary reach?",
        "secondary_questions": "How do nonresponse and missingness bend a description? What do distributions, relationships, and indices each reveal? When does a sample description become a population claim, and what licenses that crossing?",
        "inquiry": "Generalization — descriptive kind · population reach (observational pathway, Lecture 2)",
        "srl_slot": "SRL slot 07 — rotation seat B",
        "srl_focus": "Puzzle: a survey with 40% nonresponse reports a precise national estimate — what license is missing, and what would restore it?",
        "claim_permitted": "\"Given what my frame and response rate allow, the population estimate is [value] with stated uncertainty and named coverage limits.\"",
        "claim_not_permitted": "\"The average in my respondents is the population average\" when nonresponse is related to the very thing being measured.",
        "rdss_reading": "RDSS ch. 15 'Observational: descriptive' (book.declaredesign.org), measurement and nonresponse sections",
        "cb_reading": "",
        "other_material": "nb04 student notebook (observational descriptive), §4–6 (Colab); lapop_brazil attribution + resample-caveat note",
        "provenance": "RDSS ch.15 + rdss lapop_brazil | measurement, nonresponse, distributions/relationships/indices, the generalization boundary | sample-survey exploration + seeded nonresponse stress-test (seed 464) | adapted",
        "concepts": "measurement of a construct; coverage; nonresponse; missingness (and why it is rarely random); distributions; relationships between variables; indices as combined measures; generalization from sample to population; the lapop_brazil resample caveat; diagnose -> redesign the observational design",
        "python_r_dependency": "pandas (describe, groupby, missingness audit), numpy (seeded nonresponse filter, seed 464), matplotlib (distributions, an index)",
        "dataset_simulation": "lapop_brazil.csv as a sample survey (10,000-row resample, taught as a provenance lesson); seeded nonresponse filter (seed 464)",
        "minute_dynamic": "0–7 SRL-led retrieval & challenge: the SRL puts up a headline population estimate built on 40% nonresponse and asks the room what license is missing; 7–30 intensive applied AI laboratory: with Gemini as research partner, explore lapop_brazil (a distribution, one relationship, one index), then delete the least-trusting respondents and watch the estimate move, asking Gemini to draft the coverage caveat while you check it against the numbers; 30–42 peer defense + adversarial questioning: partners attack each other's generalization sentence — does the frame and response rate actually license it?; 42–50 transfer to the final project + ledger + Claim Ticket: write your project's measurement-and-coverage note, log the ledger entry, and write the Claim Ticket.",
        "hands_on_activity": "Explore lapop_brazil, build a distribution/relationship/index, then simulate nonresponse and measure how far it moves the estimate you would have reported.",
        "practice": "📝 nb04 practice: rewrite three sample-only summaries into population claims that name their coverage limits, or explain why the crossing is not licensed.",
        "discussion_prompt": "For your own project, what is the one measurement you most worry is missing not-at-random, and how would you even notice if it were?",
        "project_connection": "Your measurement-and-coverage note and the diagnosed nonresponse risk complete the M4 audit you present at this Friday's studio.",
        "milestone_developed": "M4 — Observational descriptive design audit (final development)",
        "milestone_work_time": "10 min (measurement-and-coverage note + diagnosed nonresponse risk added to the M4 audit)",
        "milestone_presentation_review": "none (lecture day)",
        "student_prep": "Read the RDSS ch. 15 measurement and nonresponse sections; bring your population/frame/sample stack from the previous lecture.",
        "student_artifact": "Executed lapop_brazil exploration + nonresponse stress-test + your measurement-and-coverage note",
        "exit_ticket": "Claim Ticket #13: my project's headline description, worded to stop exactly where my frame and response rate stop.",
        "homework_next_milestone": "Finish the M4 observational descriptive design audit and rehearse a 3-minute walkthrough for this Friday's studio.",
        "instructor_prep": "Verify lapop_brazil.csv loads; pre-seed the nonresponse filter (seed 464); prepare the index example; brief the SRL on the nonresponse puzzle.",
        "risks_contingency": "Two explorations crowd the lab → the index build ships as a provided cell and the nonresponse reveal stays live; load fails → nb04's embedded 500-row fallback carries the class.",
    },
    # ------------------------------------------------------------------ M14
    {
        "meeting": 14, "date": "2026-09-25", "day": "Fri", "modality": "in-person",
        "unit": "Week 5 — Observational descriptive research",
        "title": "Studio Friday — observational descriptive audits present; the causal question opens (M4 due, M5 kicks off)",
        "driving_question": "Can you walk a skeptic through your observational design and show exactly where its description must stop?",
        "secondary_questions": "What makes a population claim defensible out loud? Now that description is on the table, what does it take to ask a causal question honestly?",
        "inquiry": "Description + Generalization -> the causal turn (studio hand-off)",
        "srl_slot": "",
        "srl_focus": "",
        "claim_permitted": "\"Here is my population, my frame, my measurement, and the exact boundary past which my description cannot go.\"",
        "claim_not_permitted": "\"The design is standard, so it needs no audit\" — every observational description hides a selection and a coverage decision someone can question.",
        "rdss_reading": "(no new reading — studio Friday; bring your M4 audit and a 3-minute walkthrough)",
        "cb_reading": "",
        "other_material": "nb04 (observational descriptive) for the recap; M5 Brightspace brief (causal identification strategy or causal-language boundary)",
        "provenance": "course studio protocol + M4/M5 Brightspace briefs | studio Friday | 3-minute audit walkthrough + two-line peer review slips + causal-question kickoff | newly-constructed-from-source-concept",
        "concepts": "defending an observational description aloud; the selection/coverage audit; the descriptive-to-causal boundary; milestone hand-off (M4 -> M5)",
        "python_r_dependency": "none required (walkthroughs + peer review; nb04 open for reference)",
        "dataset_simulation": "student's own project data plans (no shared dataset today)",
        "minute_dynamic": "0–6 research stand-up: each project states its population, its frame, and the one coverage worry it could not shake this week; 6–29 milestone kickoff from the Brightspace brief + AI-supported sprint: present the M5 deliverable and rubric (a causal identification strategy or an honest causal-language boundary), then run five 3-minute M4 walkthroughs with Gemini-assisted note-taking; 29–41 peer + AI red-team review: two-line peer reviews (best boundary / weakest boundary) plus a Gemini pass that tries to find a population the audit overclaims; 41–50 revise, update ledger + dossier, submit + Claim Ticket: patch the weakest boundary, update the dossier and ledger, submit M4, and write the Claim Ticket.",
        "hands_on_activity": "Deliver a 3-minute M4 walkthrough, collect two-line peer reviews, run a Gemini overclaim-check, and open your M5 causal question.",
        "practice": "📝 while listening: for each walkthrough, note the strongest boundary line and the one place the description quietly overreaches.",
        "discussion_prompt": "Which classmate's coverage limit would you steal for your own project, and what does admitting it buy you?",
        "project_connection": "M4 presents and submits; M5 (a causal identification strategy or a defended causal-language boundary) kicks off from its Brightspace brief.",
        "milestone_developed": "M4 — Observational descriptive design audit (presented + submitted); M5 — Causal identification strategy or causal-language boundary (kickoff)",
        "milestone_work_time": "23-min kickoff + sprint within the studio block (M5 opens, M4 walkthroughs)",
        "milestone_presentation_review": "M4 presented: 3-minute walkthrough + written two-line peer reviews + Gemini overclaim-check",
        "student_prep": "M4 audit complete; 3-minute walkthrough rehearsed; nb04 finished.",
        "student_artifact": "Delivered walkthrough + peer reviews given/received + M5 causal question drafted",
        "exit_ticket": "Claim Ticket #14: one coverage limit I heard today that I will adopt, and the causal question I am tempted to ask next.",
        "homework_next_milestone": "Submit M4 tonight on Brightspace. For Monday, read the RDSS ch. 16 opener on observational causal designs and bring a candidate causal question.",
        "instructor_prep": "Print two-line review slips; stage the M5 Brightspace brief; timer; consult order; confirm the Gemini overclaim-check prompt is ready.",
        "risks_contingency": "Walkthroughs overrun → peer reviews go silent-written and the M5 kickoff moves to homework with the brief posted.",
    },
    # ------------------------------------------------------------------ M15
    {
        "meeting": 15, "date": "2026-09-28", "day": "Mon", "modality": "in-person",
        "unit": "Week 6 — Observational causal research",
        "title": "Observational causal designs: counterfactuals, confounding, and the DAG that earns 'because'",
        "driving_question": "Without an experiment, what would let you say an intervention caused an outcome, and what quietly forbids it?",
        "secondary_questions": "What is the counterfactual at the heart of every causal claim? What is a confounder, drawn as a DAG? When does adjusting for observed variables identify an effect, and when does it only pretend to?",
        "inquiry": "Causal reasoning — causal kind · observational pathway (Lecture 1)",
        "srl_slot": "SRL slot 08 — rotation seat C",
        "srl_focus": "Puzzle: coffee drinkers live longer in the data — draw the DAG that makes that correlation a trap, and the one that would make it a cause.",
        "claim_permitted": "\"Under the identification argument I stated and probed, the estimated effect of [treatment] on [outcome] is [value] with uncertainty.\"",
        "claim_not_permitted": "\"We controlled for everything, so this is the causal effect\" — adjustment on observed variables is not identification when an unobserved confounder remains.",
        "rdss_reading": "RDSS ch. 16 'Observational: causal' (book.declaredesign.org), counterfactuals, confounding, and selection-on-observables sections; the observational-causal entries in the DeclareDesign design library",
        "cb_reading": "optional: callingbullshit.org module on correlation and causation",
        "other_material": "nb05 student notebook (observational causal), §1–3 (Colab); cliningsmith_etal attribution note",
        "provenance": "RDSS ch.16 + DeclareDesign library (observational causal) + rdss cliningsmith_etal | counterfactuals, treatment/outcome/estimand, confounding, selection into treatment, DAGs, selection-on-observables | potential-outcomes simulation with a hidden confounder (seed 464) + a real natural experiment for context | translated (R→Python)",
        "concepts": "counterfactual reasoning (the outcome you cannot see); treatment; outcome; estimand (the effect you are after); confounding; selection into treatment; identification; causal diagrams (DAGs); selection on observables; why 'controlling for' is not identifying",
        "python_r_dependency": "numpy (potential-outcomes simulation with a hidden confounder, seed 464), pandas, networkx (draw the DAG)",
        "dataset_simulation": "inline potential-outcomes simulation with a planted confounder (seed 464) + cliningsmith_etal.csv (natural-experiment context)",
        "minute_dynamic": "0–9 SRL-led research puzzle: the SRL shows that coffee drinkers live longer in the data and asks the room to draw the DAG that makes the correlation a trap and the DAG that would make it a cause; 9–31 guided Gemini research-partner investigation in the notebook: with Gemini as research partner, simulate potential outcomes with a hidden confounder, watch a naive comparison miss the true estimand, then ask Gemini which variables would have to be observed to identify it and check its DAG reasoning against the simulation; 31–43 human verification + instructor formalization: the instructor formalizes counterfactuals, estimand, confounding, and selection-on-observables, and the class verifies where Gemini's identification story holds and where it breaks; 43–50 decision & defense: log the ledger entry and write the Claim Ticket.",
        "hands_on_activity": "Simulate a causal effect with a hidden confounder, show a naive comparison missing the estimand, and draw the DAG that says which variables identification would require.",
        "practice": "📝 nb05 practice: for three observational STEM claims (fertilizer and yield, exposure and disease, a policy and an outcome), draw the confounding DAG and name the variable whose absence breaks identification.",
        "discussion_prompt": "For your own project, if you cannot run an experiment, what is the one unobserved variable most likely to be confounding your comparison, and can you get it?",
        "project_connection": "Your project's causal DAG and candidate identification argument (or the honest note that none is available) begin the M5 deliverable.",
        "milestone_developed": "M5 — Causal identification strategy or causal-language boundary",
        "milestone_work_time": "8 min (draft your causal DAG + candidate identification argument into M5)",
        "milestone_presentation_review": "none (lecture day)",
        "student_prep": "Read the RDSS ch. 16 opener on observational causal designs; bring a candidate causal question.",
        "student_artifact": "Executed confounding simulation + your project's causal DAG + candidate identification argument",
        "exit_ticket": "Claim Ticket #15: the causal effect my project is after, and the one confounder that most threatens it.",
        "homework_next_milestone": "Continue the M5 identification strategy. For Wednesday, read the RDSS ch. 16 sections on difference-in-differences, instrumental variables, and regression discontinuity.",
        "instructor_prep": "Pre-seed the potential-outcomes simulation (seed 464); prepare the confounding DAG build in networkx; confirm cliningsmith_etal.csv loads; brief the SRL on the coffee puzzle.",
        "risks_contingency": "networkx DAG plotting fails in Colab → nb05 ships the DAGs as static images with the code shown but not required; the simulation runs long → the hidden-confounder reveal is pre-computed.",
    },
    # ------------------------------------------------------------------ M16
    {
        "meeting": 16, "date": "2026-09-30", "day": "Wed", "modality": "in-person",
        "unit": "Week 6 — Observational causal research",
        "title": "When nature assigns: difference-in-differences, IV, regression discontinuity, and the assumptions you cannot test",
        "driving_question": "When you cannot randomize, what does each natural-experiment design exploit, and what must you take on faith?",
        "secondary_questions": "What does difference-in-differences assume about trends? What does an instrument require? What does regression discontinuity buy near the cutoff? Which of these assumptions can data never confirm?",
        "inquiry": "Causal reasoning — causal kind · observational pathway, natural experiments (Lecture 2)",
        "srl_slot": "SRL slot 09 — rotation seat D",
        "srl_focus": "Puzzle: a lottery decides who gets a scarce opportunity — why is that luck a research gift, and what would ruin the as-if-random logic?",
        "claim_permitted": "\"Because [natural-experiment feature] plausibly assigns [treatment] as-if at random, the estimated effect is [value]; here is the assumption a skeptic would attack.\"",
        "claim_not_permitted": "A difference-in-differences, IV, or regression-discontinuity label decorating a comparison whose key assumption was never stated or probed.",
        "rdss_reading": "RDSS ch. 16 'Observational: causal' (book.declaredesign.org), difference-in-differences, instrumental-variables, and regression-discontinuity sections",
        "cb_reading": "",
        "other_material": "nb05 student notebook (observational causal), §4–6 (Colab); cliningsmith_etal attribution note",
        "provenance": "RDSS ch.16 + rdss cliningsmith_etal | difference-in-differences, instrumental variables, regression discontinuity, natural experiments, untestable assumptions, causal-language boundaries | the Hajj-lottery natural experiment analyzed as a difference-in-means; DiD/IV/RDD as intuition pictures | translated (R→Python)",
        "concepts": "difference-in-differences (and the parallel-trends assumption); instrumental variables (relevance + exclusion); regression discontinuity (as-if random near the cutoff); natural experiments; untestable assumptions; the causal-language boundary — what earns 'because' and what stops at 'associated with'",
        "python_r_dependency": "pandas, numpy (difference-in-means + interval on the lottery data, seed 464), matplotlib (parallel-trends and cutoff intuition pictures, provided)",
        "dataset_simulation": "cliningsmith_etal.csv (Hajj-lottery natural experiment) analyzed as a difference-in-means; provided DiD/RDD/IV intuition figures",
        "minute_dynamic": "0–7 SRL-led retrieval & challenge: the SRL asks why a lottery for a scarce opportunity is a research gift, and what would ruin the as-if-random logic; 7–30 intensive applied AI laboratory: with Gemini as research partner, analyze the real lottery natural experiment (balance check, effect estimate, interval), then for each of difference-in-differences, IV, and regression discontinuity ask Gemini to state the one untestable assumption and check whether it holds here; 30–42 peer defense + adversarial questioning: partners attack each other's identification argument at its weakest assumption; 42–50 transfer to the final project + ledger + Claim Ticket: write your project's identification paragraph or its honest causal-language boundary, log the ledger, and write the Claim Ticket.",
        "hands_on_activity": "Analyze a real lottery natural experiment end-to-end, then match difference-in-differences, IV, and regression discontinuity to the untestable assumption each would require.",
        "practice": "📝 nb05 practice: for each of difference-in-differences, IV, and regression discontinuity, write the one sentence a skeptic would attack first, and how you would probe it.",
        "discussion_prompt": "For your own project, is there any natural experiment hiding in how your treatment gets assigned — a lottery, a cutoff, a rule change — or must your claim stop at association?",
        "project_connection": "Today you write your project's identification paragraph or its honest causal-language boundary — the core of the M5 deliverable due at this Friday's async studio.",
        "milestone_developed": "M5 — Causal identification strategy or causal-language boundary (final development)",
        "milestone_work_time": "10 min (identification paragraph or causal-language boundary drafted into M5)",
        "milestone_presentation_review": "none (lecture day)",
        "student_prep": "Read the RDSS ch. 16 difference-in-differences, IV, and regression-discontinuity sections; bring your causal DAG from the previous lecture.",
        "student_artifact": "Analyzed lottery natural experiment + your identification paragraph (or honest causal-language boundary)",
        "exit_ticket": "Claim Ticket #16: my project's causal status in one sentence — identified by ___, or honestly stopping at association.",
        "homework_next_milestone": "This Friday runs asynchronously online: complete nb05, run the required GenAI Studio 'Causal Identification Skeptic' review, and submit M5 by the posted time. Budget about 50 minutes.",
        "instructor_prep": "Verify cliningsmith_etal.csv loads and the effect reproduces; check the DiD/RDD intuition figures render; brief the SRL on the lottery puzzle; confirm the async module and discussion board are staged.",
        "risks_contingency": "Intuition pictures crowd the lab → the DiD/RDD/IV block compresses to the three figures and nb05 carries the depth; content overruns → the identification paragraph moves into the async studio.",
    },
    # ------------------------------------------------------------------ M17
    {
        "meeting": 17, "date": "2026-10-02", "day": "Fri", "modality": "async-online",
        "unit": "Week 6 — Observational causal research",
        "title": "ASYNC — self-paced causal studio: the identification skeptic reviews your design (M5 submits, M6 brief posts)",
        "driving_question": "Can your causal claim survive a skeptic you cannot argue back to in real time?",
        "secondary_questions": "Does your identification argument state its untestable assumption plainly? Where would a hostile reviewer break it? If no identification is available, is your causal-language boundary honest and explicit?",
        "inquiry": "Causal reasoning — causal kind · observational pathway (async claim defense)",
        "srl_slot": "",
        "srl_focus": "",
        "claim_permitted": "\"My design identifies the effect by [argument]; the assumption it rests on is [X]; a skeptic's strongest objection is [Y], and here is my answer.\"",
        "claim_not_permitted": "A causal claim submitted without naming its untestable assumption, or a boundary that quietly keeps causal language it has not earned.",
        "rdss_reading": "RDSS ch. 16 'Observational: causal' (book.declaredesign.org), assumption-probing sections (read before Monday)",
        "cb_reading": "optional: one callingbullshit.org case of your choice from the module linked in nb05",
        "other_material": "nb05 — fully self-contained async module (Colab); GenAI Studio 'Causal Identification Skeptic' role; M6 Brightspace brief (posted today)",
        "provenance": "RDSS ch.16 + course async-studio protocol + GenAI Studio reviewer bench | self-contained causal claim defense | recorded stand-up + async red-team board exchange + required skeptic role review | newly-constructed-from-source-concept",
        "concepts": "stating an untestable assumption plainly; adversarial review of an identification argument; the required GenAI Studio 'Causal Identification Skeptic' pass; honest causal-language boundaries; asynchronous research defense",
        "python_r_dependency": "pandas (one small recompute of your own estimate); no live session",
        "dataset_simulation": "student's own project data plans + the nb05 lottery example for reference",
        "minute_dynamic": "ASYNC (~50 min self-paced, no live meeting): 0–8 record and post a 90-second research stand-up stating your causal question and candidate identification argument to the discussion board; 8–28 sprint: complete nb05 and assemble your M5 — the identification paragraph (or honest causal-language boundary), its untestable assumption, and one recompute of your own estimate; 28–40 asynchronous peer red-team exchange: post your identification argument and reply to one classmate's with the single assumption you would attack, then run the REQUIRED GenAI Studio 'Causal Identification Skeptic' review and patch the weakest point it finds; 40–50 submission: finalize M5, update the dossier and AI Research Ledger (including the skeptic-review pass), and submit with your Claim Ticket.",
        "hands_on_activity": "Complete the self-contained causal module: recompute your own estimate, run the required GenAI Studio 'Causal Identification Skeptic' review, exchange async red-team notes, and submit M5.",
        "practice": "📝 nb05 async practice: classify three published causal headlines by whether they name their identifying assumption, and rewrite one to stop at what it earns.",
        "discussion_prompt": "(async board post) Post your identification argument and its untestable assumption; reply to one classmate with the single assumption you would attack first, and why.",
        "project_connection": "M5 submits and the causal branch of your design is locked or honestly bounded; the M6 brief opens the experimental-measurement question.",
        "milestone_developed": "M5 — Causal identification strategy or causal-language boundary (submitted async); M6 — Experimental measurement or data-acquisition protocol (brief posted)",
        "milestone_work_time": "module includes a 20-min M5 assembly block + the required GenAI Studio skeptic review",
        "milestone_presentation_review": "async board: 90-second recorded stand-up + one red-team reply + required GenAI Studio 'Causal Identification Skeptic' review logged in the ledger",
        "student_prep": "nb05 lectures complete; identification paragraph (or causal-language boundary) drafted; GenAI Studio account access confirmed.",
        "student_artifact": "Completed nb05 async module: recompute cell + skeptic-review log + red-team exchange + submitted M5 + board stand-up",
        "exit_ticket": "(embedded in the module) Claim Ticket #17: the assumption the skeptic attacked hardest, and how I answered or conceded it.",
        "homework_next_milestone": "Submit M5 and the nb05 module by the posted time. For Monday, read the RDSS ch. 17 opener on experimental descriptive designs; the M6 brief is on Brightspace.",
        "instructor_prep": "Final-check nb05 runs unattended end-to-end; confirm the GenAI Studio 'Causal Identification Skeptic' role is live with its instructions in the module; post the M6 brief; seed and monitor the discussion board while traveling.",
        "risks_contingency": "A student is stuck alone → nb05 embeds hints behind expandable cells and an office-hours booking link; GenAI Studio unavailable → a provided Gemini fallback skeptic prompt stands in and the required review is logged when the service returns; the board is monitored remotely through the day.",
    },
    # ------------------------------------------------------------------ M18
    {
        "meeting": 18, "date": "2026-10-05", "day": "Mon", "modality": "in-person",
        "unit": "Week 7 — Experimental descriptive research",
        "title": "Experiments as measurement: when random assignment serves a descriptive question",
        "driving_question": "If you randomize a stimulus but only want to measure something, is your inquiry causal or descriptive, and why does the answer matter?",
        "secondary_questions": "How does an experiment become a measurement instrument for a latent characteristic? What do audit and list experiments measure that a survey cannot? Why does random assignment alone not make an inquiry causal?",
        "inquiry": "Description — descriptive kind · experimental pathway, measurement (Lecture 1)",
        "srl_slot": "SRL slot 10 — rotation seat E",
        "srl_focus": "Puzzle: a study randomizes résumé names to measure discrimination — the assignment is random, so why is the inquiry descriptive, not causal?",
        "claim_permitted": "\"Using randomized stimuli as a measurement instrument, the latent characteristic I estimate is [value], described for the units observed.\"",
        "claim_not_permitted": "\"We randomized, therefore we have a causal effect\" — random assignment can serve a purely descriptive measurement inquiry, and calling it causal misreads the question.",
        "rdss_reading": "RDSS ch. 17 'Experimental: descriptive' (book.declaredesign.org), measurement-experiment sections; the experimental-descriptive entries in the DeclareDesign design library",
        "cb_reading": "",
        "other_material": "nb06 student notebook (experimental descriptive), §1–3 (Colab); bonilla_tillery attribution note",
        "provenance": "RDSS ch.17 + DeclareDesign library (experimental descriptive) + rdss bonilla_tillery | experiments as measurement systems, latent characteristics, controlled stimuli, audit + list experiments, construct validity, assignment != causal inquiry | a real survey experiment analyzed as measurement + a seeded list-experiment simulation (seed 464) | translated (R→Python)",
        "concepts": "experiments used as measurement systems; experimental data strategy serving a descriptive inquiry; latent characteristics; controlled stimuli; audit experiments; list experiments; construct validity; why experimental assignment does not automatically imply a causal inquiry",
        "python_r_dependency": "pandas, numpy (list-experiment estimate + seeded simulation, seed 464), matplotlib",
        "dataset_simulation": "bonilla_tillery.csv (survey experiment, treatment Z) analyzed as a measurement instrument + a seeded list-experiment simulation (seed 464)",
        "minute_dynamic": "0–9 SRL-led research puzzle: the SRL presents a résumé-name audit study and asks why, though assignment is random, the inquiry is descriptive rather than causal; 9–31 guided Gemini research-partner investigation in the notebook: with Gemini as research partner, analyze the real survey experiment as a measurement of a latent attitude, then simulate a list experiment and ask Gemini to state what construct each design measures and what threatens its validity, checking against the data; 31–43 human verification + instructor formalization: the instructor formalizes experiments-as-measurement, latent characteristics, audit and list experiments, and the assignment-is-not-a-causal-inquiry point, and the class verifies Gemini's construct claims; 43–50 decision & defense: log the ledger entry and write the Claim Ticket.",
        "hands_on_activity": "Analyze a real survey experiment as a measurement instrument and simulate a list experiment, naming the latent characteristic each estimates and the validity threat each faces.",
        "practice": "📝 nb06 practice: for three randomized-stimulus studies, decide whether the inquiry is descriptive (measurement) or causal, and justify the call from the question's words.",
        "discussion_prompt": "Could an experiment measure something in your own project that a direct question never could, and would that make your inquiry descriptive or causal?",
        "project_connection": "You decide whether an experiment could serve a measurement need in your project, starting the M6 experimental-measurement or data-acquisition protocol.",
        "milestone_developed": "M6 — Experimental measurement or data-acquisition protocol",
        "milestone_work_time": "8 min (draft whether and how an experiment measures a construct in your project, into M6)",
        "milestone_presentation_review": "none (lecture day)",
        "student_prep": "Read the RDSS ch. 17 opener on experimental descriptive designs; bring one construct your project needs to measure.",
        "student_artifact": "Analyzed survey experiment + list-experiment simulation + your project's measurement-experiment note",
        "exit_ticket": "Claim Ticket #18: a construct my project must measure, and whether an experiment or a direct measure serves it better.",
        "homework_next_milestone": "Continue the M6 protocol. For Wednesday, read the RDSS ch. 17 sections on conjoint experiments and behavioral games, plus demand and instrument effects.",
        "instructor_prep": "Confirm bonilla_tillery.csv loads; pre-seed the list-experiment simulation (seed 464); prepare the audit-study example; brief the SRL on the résumé-name puzzle.",
        "risks_contingency": "Survey-experiment analysis confuses → nb06 wraps the estimate in a helper that prints only the measured quantity and its uncertainty; time short → the list-experiment simulation moves to homework.",
    },
    # ------------------------------------------------------------------ M19
    {
        "meeting": 19, "date": "2026-10-07", "day": "Wed", "modality": "in-person",
        "unit": "Week 7 — Experimental descriptive research",
        "title": "Conjoint, behavioral games, and calibration: designing a measurement experiment that survives its own artifacts",
        "driving_question": "How do you design an experiment whose measurement is not an artifact of demand effects or the instrument itself?",
        "secondary_questions": "What do conjoint experiments and behavioral games measure? How do calibration and A/B instrument tests work as measurement in STEM? What are demand effects and instrument effects, and how do you diagnose and redesign around them?",
        "inquiry": "Description — descriptive kind · experimental pathway, measurement design (Lecture 2)",
        "srl_slot": "SRL slot 11 — rotation seat A",
        "srl_focus": "Puzzle: two labs calibrate the same sensor and get different readings — is that the world, the instrument, or the design?",
        "claim_permitted": "\"My measurement experiment estimates [construct] while controlling for demand and instrument effects, verified by [check].\"",
        "claim_not_permitted": "A measurement number reported without checking whether participants guessed the hypothesis or the instrument itself moved the result.",
        "rdss_reading": "RDSS ch. 17 'Experimental: descriptive' (book.declaredesign.org), conjoint, behavioral-game, and validity-threat sections",
        "cb_reading": "",
        "other_material": "nb06 student notebook (experimental descriptive), §4–6 (Colab); bonilla_tillery attribution note",
        "provenance": "RDSS ch.17 + rdss bonilla_tillery | conjoint experiments, behavioral games, STEM measurement experiments (calibration, A/B instrument tests, psychophysics), demand effects, instrument effects, construct validity | seeded measurement simulation (seed 464) declared -> diagnosed -> redesigned | extended",
        "concepts": "conjoint experiments; behavioral games; STEM measurement experiments (calibration protocols, A/B instrument tests, psychophysics); demand effects; instrument effects; construct validity; declare -> diagnose -> redesign a measurement experiment",
        "python_r_dependency": "numpy (seeded conjoint/measurement simulation, seed 464), pandas, matplotlib",
        "dataset_simulation": "seeded measurement-experiment simulation (seed 464) with planted demand and instrument effects; bonilla_tillery.csv for reference",
        "minute_dynamic": "0–7 SRL-led retrieval & challenge: the SRL shows two labs calibrating one sensor to different readings and asks whether the gap is the world, the instrument, or the design; 7–30 intensive applied AI laboratory: with Gemini as research partner, declare a small measurement experiment, diagnose it under planted demand and instrument effects, and redesign to shrink the artifact, asking Gemini for candidate fixes and verifying each by simulation; 30–42 peer defense + adversarial questioning: partners attack each other's measurement design for the artifact it failed to rule out; 42–50 transfer to the final project + ledger + Claim Ticket: draft your project's measurement-experiment or data-acquisition protocol, log the ledger, and write the Claim Ticket.",
        "hands_on_activity": "Declare, diagnose, and redesign a measurement experiment under demand and instrument effects, verifying each redesign by simulation.",
        "practice": "📝 nb06 practice: for a calibration protocol, an A/B instrument test, and a conjoint task, name the demand or instrument effect most likely to fake the result and the redesign that defuses it.",
        "discussion_prompt": "For your own project, what is the one way your participants or your instrument could produce your result even if the real effect were zero?",
        "project_connection": "Your measurement-experiment or data-acquisition protocol completes the M6 deliverable, and your URC abstract draft begins for this Friday's internal gate.",
        "milestone_developed": "M6 — Experimental measurement or data-acquisition protocol (final development); URC abstract draft begun for the internal gate",
        "milestone_work_time": "10 min (measurement/data-acquisition protocol into M6 + first URC abstract lines)",
        "milestone_presentation_review": "none (lecture day)",
        "student_prep": "Read the RDSS ch. 17 conjoint and behavioral-game sections; bring your measurement-experiment note from the previous lecture.",
        "student_artifact": "Declare-diagnose-redesign measurement simulation + your M6 protocol + URC abstract draft started",
        "exit_ticket": "Claim Ticket #19: the artifact most likely to fake my project's measurement, and the design choice that guards against it.",
        "homework_next_milestone": "Finish the M6 protocol and draft the 150–250-word URC abstract — the internal gate is this Friday's studio. No new reading.",
        "instructor_prep": "Pre-seed the measurement simulation with demand/instrument effects (seed 464); prepare the calibration example; post the URC abstract template; brief the SRL on the sensor puzzle.",
        "risks_contingency": "Simulation too abstract → anchor every term to a cell and use the calibration example as the running case; time short → the redesign step ships as a provided comparison and the protocol drafting moves to homework.",
    },
    # ------------------------------------------------------------------ M20
    {
        "meeting": 20, "date": "2026-10-09", "day": "Fri", "modality": "in-person",
        "unit": "Week 7 — Experimental descriptive research",
        "title": "Studio Friday — measurement protocols present and the URC abstract clears its internal gate (M6 due, M7 kicks off)",
        "driving_question": "Is your measurement protocol defensible, and is your Expo abstract honest enough to submit?",
        "secondary_questions": "Does your protocol rule out its worst artifact? Does your abstract already carry uncertainty and reach? What does the declared analysis protocol (M7) ask of you next?",
        "inquiry": "Description (experimental measurement) -> declared analysis (studio hand-off)",
        "srl_slot": "",
        "srl_focus": "",
        "claim_permitted": "\"My protocol measures [construct] with named artifact controls, and my abstract states the estimate, its uncertainty, and its reach.\"",
        "claim_not_permitted": "An abstract that promises what the design cannot deliver, or a protocol whose worst artifact was never named.",
        "rdss_reading": "(no new reading — studio Friday; bring your M6 protocol and your URC abstract draft)",
        "cb_reading": "",
        "other_material": "nb06 (experimental descriptive) for the recap; URC abstract template + internal-gate checklist; M7 Brightspace brief (declared analysis protocol); URC Expo abstract specs",
        "provenance": "course studio protocol + URC abstract specs + M6/M7 Brightspace briefs | studio Friday | protocol clinic + URC abstract internal gate (draft, verify, submit internally) + M7 kickoff | newly-constructed-from-source-concept",
        "concepts": "defending a measurement protocol; the URC abstract as a public, uncertainty-bearing commitment; internal-gate verification (every claim traces to evidence); milestone hand-off (M6 -> M7)",
        "python_r_dependency": "none required (protocol clinic + abstract workshop; nb06 open for reference)",
        "dataset_simulation": "student's own project data plans (no shared dataset today)",
        "minute_dynamic": "0–6 research stand-up: each project states the construct it measures and the artifact it most fears; 6–29 milestone kickoff from the Brightspace brief + AI-supported sprint: present the M7 deliverable and rubric (a declared analysis protocol), then run the URC abstract workshop with Gemini-assisted tightening against the uncertainty-and-reach checklist; 29–41 peer + AI red-team review: partner abstract swap plus a Gemini pass hunting the one sentence a skimming reader would over-believe, and a protocol clinic on the worst unaddressed artifact; 41–50 revise, update ledger + dossier, submit + Claim Ticket: verify every abstract claim traces to evidence, submit M6, clear the abstract at the internal gate, update the ledger, and write the Claim Ticket.",
        "hands_on_activity": "Run the uncertainty-and-reach checklist on your URC abstract with a partner and Gemini, verify each claim traces to evidence, submit M6, and clear the abstract at the internal gate.",
        "practice": "📝 abstract drill: find the one sentence a skimming reader would over-believe in your abstract, and defuse it.",
        "discussion_prompt": "Read your partner's abstract cold — what did you believe that their design cannot actually deliver?",
        "project_connection": "M6 submits and the URC abstract clears its internal gate (drafted, verified, submitted internally); M7 (declared analysis protocol) kicks off from its Brightspace brief.",
        "milestone_developed": "M6 — Experimental measurement or data-acquisition protocol (presented + submitted) + URC abstract internal gate (cleared today); M7 — Declared analysis protocol (kickoff)",
        "milestone_work_time": "23-min kickoff + sprint within the studio block (M7 opens, URC abstract workshop)",
        "milestone_presentation_review": "M6 presented: protocol clinic + partner abstract swap with the uncertainty-and-reach checklist + Gemini overbelief-check",
        "student_prep": "M6 protocol complete; URC abstract drafted (150–250 words); nb06 finished.",
        "student_artifact": "Submitted M6 + abstract cleared at the internal gate + M7 declared-analysis kickoff notes",
        "exit_ticket": "Claim Ticket #20: the uncertainty phrase that now protects my abstract's reader, and the artifact control I am proudest of.",
        "homework_next_milestone": "Submit M6 tonight and confirm your abstract cleared the internal gate. No class Monday (October Break). For Wednesday, read the course-authored 'Observational: predictive' library entry and bring your analysis question.",
        "instructor_prep": "Stage the M7 Brightspace brief; print the uncertainty-and-reach checklist; confirm the URC internal-gate mechanics (the internal gate binds today regardless of the external portal); consult order.",
        "risks_contingency": "External URC portal shifts → the internal gate stands; abstracts go to Brightspace and are forwarded when the portal opens; the clinic overruns → the M7 kickoff brief is posted and read as homework.",
    },
    # ------------------------------------------------------------------ M21
    {
        "meeting": 21, "date": "2026-10-14", "day": "Wed", "modality": "in-person",
        "unit": "Week 8 — Prediction",
        "title": "Prediction: beat an honest baseline on unseen cases, and know when the win is fake",
        "driving_question": "Can you forecast new cases better than the dumbest honest rule, and would you notice if your score were leaking?",
        "secondary_questions": "How is prediction different from description, explanation, and causation? Why must a baseline and a held-out test come first? How do overfitting, leakage, and distribution shift each fake or break a score? When should you declare a model NOT useful?",
        "inquiry": "Prediction — descriptive kind · unseen-cases reach (course-authored observational-predictive pathway, single lecture)",
        "srl_slot": "SRL slot 12 — rotation seat B",
        "srl_focus": "Puzzle: a model scores 99% at predicting who already voted — impressive, or is a column of the answer hiding in the inputs?",
        "claim_permitted": "\"On held-out cases, my model beats the baseline by [margin] on [metric]; I checked for leakage; I make no causal reading of its weights.\"",
        "claim_not_permitted": "Any performance number computed on data the model already saw, or \"the top feature is X, so X drives the outcome\" — importance is not explanation, and leakage fakes importance.",
        "rdss_reading": "the course-authored 'Observational: predictive' library entry, written in the RDSS declare-diagnose-redesign format (modeled on the DeclareDesign design library at book.declaredesign.org/library); RDSS Part III stops before prediction, so its descriptive generalization logic carries over but no RDSS chapter covers this pathway",
        "cb_reading": "optional: callingbullshit.org module on big-data and algorithm hype",
        "other_material": "nb07 student notebook (prediction), §1–5 (Colab); scikit-learn (linked docs); the course-authored 'Observational: predictive' library entry",
        "provenance": "course-authored 'Observational: predictive' library entry (declare-diagnose-redesign format) + scikit-learn + rdss la_voter_file | prediction vs description/explanation/causation, baselines, train/validation/test, cross-validation, metrics, calibration, overfitting, leakage, distribution shift, subgroup performance, model-selection and not-useful rules | baseline-vs-model on held-out voter-file rows with a planted leaky feature (seed 464) | fresh",
        "concepts": "prediction distinguished from description, explanation, and causation; baseline rule; training/validation/test split; cross-validation; performance metrics; calibration; overfitting; data leakage as a data-strategy violation; generalization to unseen cases; distribution shift; interpretability vs explanation; subgroup performance; model-selection rules; criteria for declaring a model NOT useful",
        "python_r_dependency": "scikit-learn (train_test_split, DummyClassifier, LogisticRegression, cross_val_score, calibration), pandas, numpy (seed 464)",
        "dataset_simulation": "la_voter_file.csv (predict 2012 turnout from voter-file fields; one deliberately leaky feature engineered in; seed 464)",
        "minute_dynamic": "0–7 SRL-led retrieval & challenge: the SRL shows a model scoring 99% at predicting who already voted and asks whether a column of the answer is hiding in the inputs; 7–30 intensive applied AI laboratory: with Gemini as research partner, declare the prediction task, score an honest baseline on held-out voter-file rows, try to beat it with a simple model under cross-validation, then find the planted leak, retrain clean, and report the leaky-vs-clean delta while checking calibration and one subgroup; 30–42 peer defense + adversarial questioning: partners attack each other's score for leakage, overfitting, or a metric that flatters; 42–50 transfer to the final project + ledger + Claim Ticket: write your project's prediction verdict — a target, baseline, and metric, or the honest reason prediction is the wrong column — log the ledger, and write the Claim Ticket.",
        "hands_on_activity": "Beat (or fail to beat) an honest baseline on held-out cases under cross-validation, catch a planted leak, and report leaky-vs-clean numbers with a calibration and subgroup check.",
        "practice": "📝 nb07 practice: choose the right metric for three targets (a rare event, balanced classes, costly false negatives), and rank four candidate features by leakage risk.",
        "discussion_prompt": "The baseline got 78% and your model got 80%. Write the honest headline, then the dishonest one you almost wrote.",
        "project_connection": "You confirm or rule out your project's predictive component with reasons and name its nearest leakage risk — the spine of the M7 declared analysis protocol due at this Friday's studio.",
        "milestone_developed": "M7 — Declared analysis protocol",
        "milestone_work_time": "10 min (prediction verdict + target/baseline/metric or a reasoned no, into M7)",
        "milestone_presentation_review": "none (lecture day)",
        "student_prep": "Read the course-authored 'Observational: predictive' library entry; bring the analysis question your project needs to answer.",
        "student_artifact": "Baseline-vs-model held-out comparison + leaky-vs-clean delta + your project's prediction verdict",
        "exit_ticket": "Claim Ticket #21: my project's prediction verdict (has an angle / wrong column) and the leakage risk nearest my data.",
        "homework_next_milestone": "Finish nb07 and assemble the M7 declared analysis protocol for this Friday's studio, where it faces a prediction-and-leakage audit. No new reading.",
        "instructor_prep": "Verify la_voter_file predictive cells run fast; pre-compute the baseline for a snappy reveal; engineer the leaky feature so discovery takes about ten minutes; brief the SRL on the turnout-leak puzzle.",
        "risks_contingency": "sklearn friction → all model code is provided and you choose the target column and read outputs; the leak found too fast → nb07's second, subtler temporal leak is the extension path.",
    },
    # ------------------------------------------------------------------ M22
    {
        "meeting": 22, "date": "2026-10-16", "day": "Fri", "modality": "in-person",
        "unit": "Week 8 — Prediction",
        "title": "Studio Friday — declared analysis protocols audited by the prediction-and-leakage reviewer (M7 due, M8 kicks off)",
        "driving_question": "Does your declared analysis protocol survive an auditor built to hunt leakage and overclaiming?",
        "secondary_questions": "Is every analysis step declared before the data are touched? Where could leakage or a flattering metric sneak in? What does the minimum viable analysis (M8) ask you to actually run?",
        "inquiry": "Prediction + all positions (declared-analysis studio)",
        "srl_slot": "",
        "srl_focus": "",
        "claim_permitted": "\"My analysis is declared in full before I touch the data; here is the auditor's hardest hit and my fix.\"",
        "claim_not_permitted": "A protocol declared loosely enough to let leakage or a favorable metric slip in after seeing the results.",
        "rdss_reading": "(no new reading — studio Friday; bring your declared analysis protocol)",
        "cb_reading": "",
        "other_material": "nb07 (prediction) for the recap; GenAI Studio 'Prediction & Leakage Auditor' role; M7 declared-analysis template; M8 Brightspace brief (minimum viable analysis)",
        "provenance": "course studio protocol + GenAI Studio reviewer bench + M7/M8 Brightspace briefs | studio Friday | declared-analysis assembly + required Prediction & Leakage Auditor review + M8 kickoff | newly-constructed-from-source-concept",
        "concepts": "declaring an analysis before touching data; the GenAI Studio 'Prediction & Leakage Auditor' review; leakage and overclaiming audit; milestone hand-off (M7 -> M8)",
        "python_r_dependency": "none required (assembly + auditor review; nb07 open for reference)",
        "dataset_simulation": "student's own project data plans (no shared dataset today)",
        "minute_dynamic": "0–6 research stand-up: each project states its analysis question and the one place leakage could enter; 6–29 milestone kickoff from the Brightspace brief + AI-supported sprint: present the M8 deliverable and rubric (a minimum viable analysis), then assemble the declared analysis protocol from the template; 29–41 peer + AI red-team review: run the required GenAI Studio 'Prediction & Leakage Auditor' review on each protocol and exchange peer red-team notes on the hit each auditor found; 41–50 revise, update ledger + dossier, submit + Claim Ticket: patch the auditor's hardest hit, log the review in the ledger, submit M7, and write the Claim Ticket.",
        "hands_on_activity": "Assemble your declared analysis protocol, run the required GenAI Studio 'Prediction & Leakage Auditor' review, patch its hardest hit, and submit M7.",
        "practice": "📝 during the sprint: for a partner's protocol, name the one step where leakage or an after-the-fact metric choice could still sneak in.",
        "discussion_prompt": "What did the Prediction & Leakage Auditor catch in your protocol that you had not seen, and why did you miss it?",
        "project_connection": "M7 (declared analysis protocol) submits after its auditor review; M8 (minimum viable analysis) kicks off from its Brightspace brief.",
        "milestone_developed": "M7 — Declared analysis protocol (presented + submitted, auditor-reviewed); M8 — Minimum viable analysis (kickoff)",
        "milestone_work_time": "23-min kickoff + sprint within the studio block (M8 opens, declared-analysis assembly)",
        "milestone_presentation_review": "M7 presented: required GenAI Studio 'Prediction & Leakage Auditor' review + peer red-team exchange",
        "student_prep": "Declared analysis protocol drafted; nb07 complete; GenAI Studio access confirmed.",
        "student_artifact": "Submitted M7 + logged Prediction & Leakage Auditor review + M8 kickoff notes",
        "exit_ticket": "Claim Ticket #22: the leakage or overclaim risk the auditor caught in my protocol, and how I closed it.",
        "homework_next_milestone": "Submit M7 tonight on Brightspace. Start the M8 minimum viable analysis this weekend; for Monday, bring your first executed analysis cell.",
        "instructor_prep": "Confirm the GenAI Studio 'Prediction & Leakage Auditor' role is live with its rubric; stage the M8 Brightspace brief; print the declared-analysis template; consult order.",
        "risks_contingency": "GenAI Studio unavailable → a provided Gemini fallback auditor prompt stands in and the required review is logged when the service returns; assembly overruns → the auditor review runs on the strongest protocols live and the rest asynchronously, with submission tonight.",
    },
]

