"""Meetings M1–M11 (Weeks 1–4): the foundation arc.

Week 1 (nb00) — research in the age of AI: your arm and research assistant, not
your brain; automation bias; the AI Research Ledger; the SDIIVDD discipline
(everyday shorthand Ask -> Verify -> Document). Week 1's two lectures are
INSTRUCTOR-LED (no SRL slot). Week 2 (nb01) — curiosity to a research problem +
the inquiry compass (kind x reach). Week 3 (nb02, single Wednesday lecture) —
research builds on research: verified evidence and real gaps. Week 4 (nb03) —
the anatomy of a research design (MIDA + declare -> diagnose -> redesign).

Fridays are studios (recap + milestone kickoff + AI-supported sprint, no new
topic content). Milestones M0-M3 each open at one studio and close at the next.
The Student Research Lead (SRL) rotation begins at meeting 4 (seat A); seats A-E
map to SRL slots 01-05 across these weeks.

RDSS chapter titles verified against book.declaredesign.org (ch. 5 'Declaring
designs' confirmed 2026-07-23); never invent a chapter. AI tool named in
activities is Gemini (in and alongside Colab); GenAI Studio appears only as
Week 1 tool-readiness setup. No fabricated citations anywhere — the Week 1 demo
catches a LIVE Gemini hallucination, never a planted fake.
"""

MEETINGS_P1 = [
    # ------------------------------------------------------------------ M1
    {
        "meeting": 1, "date": "2026-08-24", "day": "Mon", "modality": "in-person",
        "unit": "Week 1 — Research in the age of AI",
        "title": "Your arm and your research assistant, not your brain: the course promise and a live citation-catch",
        "driving_question": "What does research even mean when an AI can generate the code and the prose for you?",
        "secondary_questions": "What will you build this semester? Where is the line between AI assistance and intellectual substitution? What does 'AI may propose, the researcher must verify' demand of you on day one?",
        "inquiry": "all positions (course framing)",
        "srl_slot": "",
        "srl_focus": "",
        "claim_permitted": "\"An AI tool generated this, and I confirmed the underlying source exists before I used it\" — the course's opening standard.",
        "claim_not_permitted": "\"The AI said so\" offered as evidence — a generated citation you have not retrieved and checked is not yet a source.",
        "rdss_reading": "RDSS ch. 1 (Preface) + ch. 2 'What is a research design?' — skim before Wednesday (book.declaredesign.org)",
        "cb_reading": "",
        "other_material": "nb00 (Colab); course website; syllabus; Brightspace orientation; genai.rcac.purdue.edu login",
        "provenance": "brief §Week1 + RDSS ch.2 | research in the age of AI | course promise + live Gemini citation-catch + Colab/GenAI Studio readiness | newly-constructed-from-source-concept",
        "concepts": "evidence-driven research; AI as arm and research assistant, not brain; assistance vs intellectual substitution; hallucination; the AI Research Ledger (preview); Ask -> Verify -> Document (the everyday form of SDIIVDD); the weekly rhythm (lectures + Friday studio)",
        "python_r_dependency": "Colab basics only (run a cell, save a copy to Drive)",
        "dataset_simulation": "none (one live AI-generated citation to verify)",
        "minute_dynamic": "0–9 instructor-led puzzle: what is left for a researcher to do once an AI can write the code and the prose? — the class maps the answer on the board; 9–31 guided Gemini research-partner investigation in nb00: ask Gemini for three sources on a shared question and open each one, watching one citation fail to resolve; 31–43 human verification + instructor formalization: run the failed citation through the verification checklist, name hallucination and the arm-not-brain principle, and set up the AI Research Ledger; 43–50 decision & defense: log the caught citation as the first Ledger entry + Claim Ticket.",
        "hands_on_activity": "Open nb00 in Colab, save a copy to Drive, ask Gemini for sources on a shared question, and catch the one citation that will not resolve using the verification checklist.",
        "practice": "📝 nb00 practice: for three AI-generated claims, mark which you could defend right now and which need a source you would have to retrieve first.",
        "discussion_prompt": "When has a confident answer, from a person or a tool, turned out to be wrong for you — and what would have caught it earlier?",
        "project_connection": "The semester project starts today: everyone leaves set up in Colab, logged into the course tools, and holding the M0 baseline assignment.",
        "milestone_developed": "M0 — Research and AI baseline (kickoff)",
        "milestone_work_time": "5 min (M0 brief walkthrough + first baseline-belief jotting)",
        "milestone_presentation_review": "none (kickoff)",
        "student_prep": "Bring a laptop; be able to log into Google (Colab), Brightspace, and genai.rcac.purdue.edu.",
        "student_artifact": "Executed nb00 readiness cells + first AI Research Ledger entry (the caught citation)",
        "exit_ticket": "Claim Ticket #1: one thing you assume AI is good at in research, and how you would check whether it actually is.",
        "homework_next_milestone": "Start M0 (baseline beliefs about AI, three curiosities, tool-readiness screenshots, first Ledger entries) — due at this Friday's studio, where you pitch one curiosity in 30 seconds. Skim RDSS ch. 1–2 before Wednesday.",
        "instructor_prep": "Verify nb00 loads in Colab from the public repo; rehearse the live Gemini citation-catch and keep an offline screenshot backup; confirm GenAI Studio logins work; roster the 5 students.",
        "risks_contingency": "Gemini returns only valid citations in the live demo → fall back to the saved transcript of a prior hallucination and have the class verify it; account/Colab issues → pair on one laptop and finish readiness at home.",
    },
    # ------------------------------------------------------------------ M2
    {
        "meeting": 2, "date": "2026-08-26", "day": "Wed", "modality": "in-person",
        "unit": "Week 1 — Research in the age of AI",
        "title": "Automation bias, false confidence, and the first full Ask -> Verify -> Document cycle",
        "driving_question": "Why do smart people trust a wrong machine, and what discipline keeps you from joining them?",
        "secondary_questions": "What is automation bias? How does fluent AI prose manufacture false confidence and the illusion of understanding? Which research decisions must stay human? What are the seven moves of Specify -> Delegate -> Interrogate -> Inspect -> Verify -> Document -> Defend?",
        "inquiry": "all positions (course framing)",
        "srl_slot": "",
        "srl_focus": "",
        "claim_permitted": "\"I delegated this step, interrogated the output, and verified it against a source I can point to\" — a claim that survives the full cycle.",
        "claim_not_permitted": "\"It sounded right and detailed, so I used it\" — fluency is not evidence, and detail is not verification.",
        "rdss_reading": "RDSS ch. 2 'What is a research design?' (finish; book.declaredesign.org)",
        "cb_reading": "",
        "other_material": "nb00 §Lecture 2 (Colab); the AI Research Ledger template",
        "provenance": "brief §Week1 + RDSS ch.2 | research in the age of AI | automation-bias framing + first full SDIIVDD cycle on a toy claim | newly-constructed-from-source-concept",
        "concepts": "automation bias; false confidence; the illusion of understanding; assistance vs substitution; research ownership + human decision authority; the never-delegate list; SDIIVDD (Specify -> Delegate -> Interrogate -> Inspect -> Verify -> Document -> Defend) and its shorthand Ask -> Verify -> Document; the AI Research Ledger fields",
        "python_r_dependency": "Colab (run provided cells; no new libraries)",
        "dataset_simulation": "none (one toy factual claim carried through the full cycle)",
        "minute_dynamic": "0–7 instructor-led retrieval & challenge: name yesterday's arm-not-brain principle and one decision an AI must never make for you; 7–30 intensive applied AI laboratory: take one toy claim through all seven SDIIVDD moves in nb00 — specify the task, delegate it to Gemini, interrogate and inspect the output, then verify it against a real source and document the Ledger row; 30–42 peer defense + adversarial questioning: partners try to break each other's verification (\"how do you KNOW the source says that?\"); 42–50 transfer to the final project + Ledger + Claim Ticket.",
        "hands_on_activity": "Run one toy claim through all seven SDIIVDD moves in nb00 and fill a complete AI Research Ledger row, ending with a source you personally opened.",
        "practice": "📝 nb00 practice: match five research tasks to 'safe to delegate', 'delegate then verify', or 'never delegate', and justify each in a phrase.",
        "discussion_prompt": "Describe a time a detailed, confident explanation made you stop checking. What would automation bias look like in your own project?",
        "project_connection": "The Ledger row you complete today is the template for every AI use you will document in the project dossier.",
        "milestone_developed": "M0 — Research and AI baseline (dev)",
        "milestone_work_time": "5 min (draft one real Ledger entry from your own AI use this week)",
        "milestone_presentation_review": "none (baseline is a studio submission)",
        "student_prep": "M0 in progress (baseline beliefs + curiosities started); RDSS ch. 2 skimmed; laptop ready.",
        "student_artifact": "One complete AI Research Ledger row (task, tool, prompt, output, decision, verification, remaining concern)",
        "exit_ticket": "Claim Ticket #2: one AI output you trusted this week, and the exact check that would confirm or break it.",
        "homework_next_milestone": "Finish M0 (baseline AI beliefs, three curiosities, tool-readiness screenshots, first Ledger entries) for this Friday's studio, where you pitch one curiosity in 30 seconds.",
        "instructor_prep": "Prepare the toy-claim cycle end-to-end in nb00; print the SDIIVDD and never-delegate cards; review any early M0 drafts.",
        "risks_contingency": "The cycle runs long → verify and document the toy claim together as a class and move peer defense to a written exchange; keep the never-delegate list visible as the anchor.",
    },
    # ------------------------------------------------------------------ M3
    {
        "meeting": 3, "date": "2026-08-28", "day": "Fri", "modality": "in-person",
        "unit": "Week 1 — Research in the age of AI",
        "title": "Studio Friday — AI baselines and first curiosities: M0 due, M1 kickoff",
        "driving_question": "Can you name what you assume about AI, pitch a curiosity in 30 seconds, and leave with a plan to map a research opportunity?",
        "secondary_questions": "What did your baseline reveal about where you over-trust AI? What does the M1 brief ask for (a research opportunity landscape), and how is it graded?",
        "inquiry": "all positions (studio)",
        "srl_slot": "",
        "srl_focus": "",
        "claim_permitted": "\"Here is a curiosity worth a semester, and here is what I assume AI can and cannot do for it\" — the M0 baseline claim.",
        "claim_not_permitted": "\"AI will just do the research for me\" — a baseline belief the whole course is built to correct.",
        "rdss_reading": "(no new reading — studio Friday; bring your completed M0 baseline and a 30-second curiosity)",
        "cb_reading": "",
        "other_material": "nb00 student notebook (research in the age of AI) — recap reference (Colab); M1 Brightspace brief",
        "provenance": "course design (Friday studio format) | weekly Friday studio | recap + M1 milestone brief + supervised sprint | newly-constructed-from-source-concept",
        "concepts": "surfacing AI-trust assumptions; the 30-second curiosity pitch; the M1 deliverable (research opportunity landscape); research stand-up norms; supervised project work",
        "python_r_dependency": "none new (own milestone work)",
        "dataset_simulation": "student's own baseline + curiosity materials",
        "minute_dynamic": "0–6 research stand-up: each student reports one change, one blocker, one decision, one thing delegated to AI, and one thing that still needs verification; 6–29 milestone kickoff from the Brightspace brief: present M1 (research opportunity landscape) + rubric, then an AI-supported sprint — 30-second curiosity pitches, then use Gemini to widen each curiosity into candidate problem areas while logging every prompt; 29–41 peer + AI red-team review: classmates and a Gemini skeptic pass each pitch back one 'so what?' and one place the AI over-promised; 41–50 revise, update the Ledger + dossier, submit M0 + Claim Ticket.",
        "hands_on_activity": "Deliver a 30-second curiosity pitch, then use Gemini to widen it into candidate problem areas, logging and verifying each suggestion in the Ledger.",
        "practice": "📝 studio log: record one AI suggestion you kept, one you rejected, and the reason for each.",
        "discussion_prompt": "Whose 30-second curiosity would you follow for a semester, and what is the first thing you would need to know to start?",
        "project_connection": "M0 closes today; the candidate problem areas widened in the sprint open the M1 opportunity landscape.",
        "milestone_developed": "M0 — Research and AI baseline (presented + due); M1 — Research opportunity landscape (kickoff)",
        "milestone_work_time": "23 min studio block",
        "milestone_presentation_review": "M0 presented: 30-second curiosity pitch + whole-class stand-up, each pitch gets one 'so what?' and one AI-overreach flag",
        "student_prep": "M0 complete (baseline, curiosities, tool-readiness screenshots, Ledger entries); 30-second pitch ready; laptop ready.",
        "student_artifact": "Delivered pitch + a first M1 candidate-problem-area list with a verified Ledger trail",
        "exit_ticket": "Claim Ticket #3: my strongest curiosity in one sentence, plus one thing I will NOT let AI decide about it.",
        "homework_next_milestone": "Submit M0 tonight (11:59 PM). Weekend: skim RDSS ch. 4 'Getting started'; grow your candidate problem areas toward the M1 opportunity landscape (due at next Friday's studio).",
        "instructor_prep": "Queue the stand-up and pitch order; M1 Brightspace brief on screen; warm-feedback + red-team norms posted; consult rotation list.",
        "risks_contingency": "Stand-ups run long → cap each at 45 seconds with a visible timer and protect the sprint block; a student has no viable curiosity → offer the curated fallback-topic menu and book an office-hours consult.",
    },
    # ------------------------------------------------------------------ M4
    {
        "meeting": 4, "date": "2026-08-31", "day": "Mon", "modality": "in-person",
        "unit": "Week 2 — From curiosity to a research problem",
        "title": "From curiosity to a research problem: the funnel, and what makes a problem worth doing",
        "driving_question": "How does a curiosity become a research problem someone would fund a semester of your life to study?",
        "secondary_questions": "What separates a topic from a research problem from a question? What do importance, feasibility, and contribution each demand? What are units of analysis, target populations, and outcomes?",
        "inquiry": "all positions (framing the problem)",
        "srl_slot": "SRL slot 01 — rotation seat A",
        "srl_focus": "Puzzle: two students bring the same broad interest but only one has a research problem — what did the second one add that the first did not?",
        "claim_permitted": "\"My problem names its units, its outcome, and the population it speaks to, and I can say why it matters and why it is doable this semester.\"",
        "claim_not_permitted": "\"My topic is important, so any question about it is a research problem\" — a topic is a subject, a problem is a specific gap someone could act on.",
        "rdss_reading": "RDSS ch. 4 'Getting started' (book.declaredesign.org)",
        "cb_reading": "",
        "other_material": "nb01 §Lecture 1 (Colab)",
        "provenance": "RDSS ch.4 + fresh curiosity->problem funnel | getting started | curiosity->topic->problem->question funnel + importance/feasibility/contribution + units/population/outcome scaffold | extended",
        "concepts": "curiosity vs topic vs research problem vs question; the funnel; importance, feasibility, contribution; units of analysis; target population; outcome and target; studyability",
        "python_r_dependency": "none beyond running markdown/code cells",
        "dataset_simulation": "none (worked funnel examples + own-topic cards)",
        "minute_dynamic": "0–9 SRL-led research puzzle: two students' broad interests side by side, only one already a research problem — the class names what the second added; 9–31 guided Gemini research-partner investigation in nb01: run your curiosity down the funnel, asking Gemini to surface candidate units, populations, and outcomes, then verify each suggestion against a real source; 31–43 human verification + instructor formalization: the instructor formalizes topic vs problem vs question and the importance/feasibility/contribution test, and the class corrects one over-eager AI suggestion; 43–50 decision & defense: log the funnel decisions in the Ledger + Claim Ticket.",
        "hands_on_activity": "Run your curiosity through the nb01 funnel to a candidate problem, using Gemini to propose units, populations, and outcomes and verifying each before you keep it.",
        "practice": "📝 nb01 practice: sort six statements into curiosity / topic / problem / question, then name the units, population, and outcome hiding in one of them.",
        "discussion_prompt": "When is 'this matters to everyone' a strength for a research problem, and when is it a warning that the problem is not yet specific?",
        "project_connection": "The funnel output — a candidate problem with units, population, and outcome — is the spine of the M1 opportunity landscape.",
        "milestone_developed": "M1 — Research opportunity landscape (dev)",
        "milestone_work_time": "7 min (funnel your own curiosity to a candidate problem)",
        "milestone_presentation_review": "SRL-led puzzle debrief (no formal presentation)",
        "student_prep": "M0 submitted; a curiosity in hand; RDSS ch. 4 skimmed; laptop ready.",
        "student_artifact": "Own curiosity funneled to a candidate problem with units, population, and outcome named in nb01",
        "exit_ticket": "Claim Ticket #4: my curiosity restated as a research problem, naming its units, its outcome, and who it is about.",
        "homework_next_milestone": "Grow the M1 opportunity landscape (candidate problems with importance/feasibility/contribution notes). Skim the opening of RDSS ch. 7 before Wednesday.",
        "instructor_prep": "Brief SRL seat A on the two-interest puzzle; queue the worked funnel example; verify nb01 loads in Colab; review M0 submissions.",
        "risks_contingency": "A student cannot narrow past a topic → co-run the funnel live on their topic as the shared example; SRL under-prepared → the instructor holds the puzzle and the SRL takes the transfer block.",
    },
    # ------------------------------------------------------------------ M5
    {
        "meeting": 5, "date": "2026-09-02", "day": "Wed", "modality": "in-person",
        "unit": "Week 2 — From curiosity to a research problem",
        "title": "The inquiry compass: descriptive, predictive, or causal — kind x reach",
        "driving_question": "What KIND of answer does your question ask for, and how far is it trying to reach?",
        "secondary_questions": "How do descriptive, predictive, and causal questions differ? Why is prediction a descriptive question about unseen cases, not a causal one? What goes wrong when a single question tries to do two jobs at once?",
        "inquiry": "all four compass positions (the compass skill)",
        "srl_slot": "SRL slot 02 — rotation seat B",
        "srl_focus": "Puzzle: one question secretly asks two things at once (what is happening AND what would fix it) — where does it split, and which half is which kind?",
        "claim_permitted": "\"My question is a ___ inquiry reaching ___ (data at hand / a population / unseen cases), because the answer it wants is ___.\"",
        "claim_not_permitted": "A question that fuses description and causation in one breath (\"how common is burnout and does remote work cause it?\") pretending to be a single answerable question.",
        "rdss_reading": "RDSS ch. 7 'Defining the inquiry' (descriptive vs causal inquiries; book.declaredesign.org)",
        "cb_reading": "optional: callingbullshit.org case on prediction vs understanding",
        "other_material": "nb01 §Lecture 2 (Colab)",
        "provenance": "RDSS ch.7 + fresh compass build | defining the inquiry | kind x reach compass with the prediction column authored fresh (descriptive about unseen cases) | extended",
        "concepts": "the inquiry compass: kind (descriptive vs causal) x reach (data at hand / population / unseen); the four positions — description, generalization, prediction, causal reasoning; prediction as descriptive questions about unseen cases; questions that improperly combine objectives; the giveaway words that place a question",
        "python_r_dependency": "none (classification in markdown cells)",
        "dataset_simulation": "none (question cards spanning the compass)",
        "minute_dynamic": "0–7 SRL-led retrieval & challenge: name the compass axes from memory, then the SRL reveals one question that secretly asks two things; 7–30 intensive applied AI laboratory: in nb01, classify a deck of question cards by kind and reach, then ask Gemini to classify the same cards and adjudicate every disagreement against the definitions; 30–42 peer defense + adversarial questioning: classify YOUR own question and defend its position while a partner tries to move it; 42–50 transfer to the final project + Ledger + Claim Ticket.",
        "hands_on_activity": "Classify a deck of question cards by kind and reach, pit your classification against Gemini's, and resolve every disagreement with the definitions — then place your own question.",
        "practice": "📝 nb01 practice: for eight questions, name the kind + reach AND rewrite the one that improperly combines two objectives into two clean questions.",
        "discussion_prompt": "Why is 'predicting who will drop out' a descriptive question about unseen cases and not a causal one, and what would make it causal?",
        "project_connection": "Each student leaves with a first compass position for their own question, recorded in the M1 landscape.",
        "milestone_developed": "M1 — Research opportunity landscape (dev; compass position added)",
        "milestone_work_time": "6 min (classify own question by kind + reach; note it in the landscape)",
        "milestone_presentation_review": "peer defense: partner tries to reclassify your question",
        "student_prep": "Candidate problem from Monday; RDSS ch. 7 opening skimmed; laptop ready.",
        "student_artifact": "A classified question deck + own question placed on the compass in nb01",
        "exit_ticket": "Claim Ticket #5: my question is (for now) a ___ inquiry reaching ___, and the giveaway word that places it there.",
        "homework_next_milestone": "Finish the M1 opportunity landscape (problems + compass positions + importance/feasibility/contribution) for this Friday's studio. Confirm your Purdue Libraries login works before next week.",
        "instructor_prep": "Brief SRL seat B on the double-barreled-question reveal; print the question-card deck spanning all four positions; queue the optional CB case.",
        "risks_contingency": "The compass lands abstract → anchor each position to one shared running example the class knows; AI classification agrees too easily → seed two deliberately ambiguous cards to force the adjudication.",
    },
    # ------------------------------------------------------------------ M6
    {
        "meeting": 6, "date": "2026-09-04", "day": "Fri", "modality": "in-person",
        "unit": "Week 2 — From curiosity to a research problem",
        "title": "Studio Friday — Opportunity landscapes: M1 due, M2 kickoff",
        "driving_question": "Does your research opportunity landscape hold up — real problems, honest feasibility, a clear compass position — and can you pitch the one you will pursue?",
        "secondary_questions": "Which of your candidate problems is most worth doing? What does the M2 brief ask for (verified evidence and a contribution map), and how is it graded?",
        "inquiry": "all four compass positions (studio)",
        "srl_slot": "",
        "srl_focus": "",
        "claim_permitted": "\"Across my candidate problems, this one is important, feasible, and a real contribution, and its compass position is ___.\"",
        "claim_not_permitted": "\"Every problem on my landscape is equally strong\" — a landscape with no ranking has not been appraised.",
        "rdss_reading": "(no new reading — studio Friday; bring your M1 opportunity landscape)",
        "cb_reading": "",
        "other_material": "nb01 student notebook (curiosity -> problem) — recap reference (Colab); M2 Brightspace brief",
        "provenance": "course design (Friday studio format) | weekly Friday studio | recap + M2 milestone brief + landscape review sprint | newly-constructed-from-source-concept",
        "concepts": "ranking candidate problems by importance/feasibility/contribution; committing to a lead problem; the M2 deliverable (verified evidence + contribution map); research stand-up; red-team review",
        "python_r_dependency": "none new (own milestone work)",
        "dataset_simulation": "student's own project materials",
        "minute_dynamic": "0–6 research stand-up: each student reports change, blocker, decision, delegation, and what still needs verification; 6–29 milestone kickoff from the Brightspace brief: present M2 (verified evidence + contribution map) + rubric, then an AI-supported sprint — pitch your landscape, pick a lead problem, and use Gemini to surface where evidence for it might live while logging each lead to verify next week; 29–41 peer + AI red-team review: the class and a Gemini skeptic challenge each lead problem's feasibility and compass position; 41–50 revise, update the Ledger + dossier, submit M1 + Claim Ticket.",
        "hands_on_activity": "Pitch your opportunity landscape, commit to a lead problem, and use Gemini to map where evidence for it might live — logging every lead as unverified until you retrieve it.",
        "practice": "📝 studio log: record the lead problem you committed to and the single feasibility risk that most threatens it.",
        "discussion_prompt": "Which classmate's lead problem would you switch your own project to, and what makes it feel doable in one semester?",
        "project_connection": "M1 closes today; the lead problem and evidence leads from the sprint open the M2 verified-evidence map.",
        "milestone_developed": "M1 — Research opportunity landscape (presented + due); M2 — Verified evidence and contribution map (kickoff)",
        "milestone_work_time": "23 min studio block",
        "milestone_presentation_review": "M1 presented: landscape pitch + class red-team on feasibility and compass position",
        "student_prep": "M1 opportunity landscape complete; Purdue Libraries login working; laptop ready.",
        "student_artifact": "Committed lead problem + a first list of evidence leads to verify, with a Ledger trail",
        "exit_ticket": "Claim Ticket #6: the one problem I am committing to, its compass position, and why it is doable this semester.",
        "homework_next_milestone": "Submit M1 tonight (11:59 PM). Next week has a single lecture — no class Monday for the holiday. Weekend: read RDSS ch. 4 on situating a design in a literature and confirm your Purdue Libraries access.",
        "instructor_prep": "Queue stand-up + pitch order; M2 Brightspace brief on screen; red-team norms posted; consult rotation.",
        "risks_contingency": "Landscapes are thin → pair students to pressure-test the stronger landscape and assign the thin one a fallback problem from the menu; pitches overrun → cap red-team responses at one written note each.",
    },
    # ------------------------------------------------------------------ M7
    {
        "meeting": 7, "date": "2026-09-09", "day": "Wed", "modality": "in-person",
        "unit": "Week 3 — Research builds on research",
        "title": "Research builds on research: verified evidence, citation chains, and real gaps",
        "driving_question": "How do you find what is actually known, prove each source is real, and tell a genuine gap from a search you simply gave up on?",
        "secondary_questions": "How is a field a cumulative conversation (replication, extension, synthesis, comparison, boundary conditions)? What are forward and backward citation searches? Why must every citation be retrieved and its claim checked before you use it?",
        "inquiry": "description + generalization (appraising and mapping evidence)",
        "srl_slot": "SRL slot 03 — rotation seat C",
        "srl_focus": "Puzzle: an AI hands you a perfect-sounding study you cannot find anywhere — is the gap real, or did the search just fail?",
        "claim_permitted": "\"Source S exists, I retrieved it, and it claims X on the basis of evidence E\" — and \"across the sources I checked, no one has addressed C.\"",
        "claim_not_permitted": "\"Nothing is known about my topic\" from a search that stopped early, or citing any source you have not personally opened — however fluent the AI summary.",
        "rdss_reading": "RDSS ch. 4 'Getting started' (situating a design in a literature; book.declaredesign.org) + course library-search guidance",
        "cb_reading": "",
        "other_material": "nb02 (Colab); Purdue Libraries database portal; Google Scholar",
        "provenance": "RDSS ch.4 + fresh AI-era source-verification method | getting started | retrieval-verification loop + citation-chain search + evidence map, tuned for an AI-assisted honors audience | newly-constructed-from-source-concept",
        "concepts": "research as cumulative conversation; replication, extension, synthesis, comparison, boundary conditions; backward and forward citation searches; the retrieval-verification loop (retrieve it, confirm it exists, log how you checked); claim–evidence–source alignment; citation hallucination; mischaracterized sources; genuine gap vs unsuccessful search; the evidence map",
        "python_r_dependency": "provided networkx cell (fill a claims table; the citation/evidence map draws itself)",
        "dataset_simulation": "none (student-retrieved real sources; own evidence map)",
        "minute_dynamic": "0–7 SRL-led retrieval & challenge: the SRL presents an AI-surfaced study nobody can locate and the class decides what that means; 7–30 intensive applied AI laboratory: for YOUR question, run one Gemini search and one library-database search, retrieve every source, verify each is real, log its central claim, and follow one backward and one forward citation link; 30–42 peer defense + adversarial questioning: swap evidence maps and challenge whether each placed gap is genuine or just an unfinished search; 42–50 transfer to the final project + Ledger + Claim Ticket.",
        "hands_on_activity": "Run paired Gemini and library-database searches for your own question, verify every source you keep is real and retrievable, log its central claim, and place a provisional gap on your evidence map.",
        "practice": "📝 nb02 practice: turn your question into two search strings (one database, one AI tool) and predict how their failure modes differ; then label three source-claims as aligned, mischaracterized, or unverifiable.",
        "discussion_prompt": "An AI summary cites a perfect study you cannot find. What are the three possible explanations, and what do you do next?",
        "project_connection": "The verified evidence and the provisional gap started today are the backbone of M2, due at this Friday's studio.",
        "milestone_developed": "M2 — Verified evidence and contribution map (dev)",
        "milestone_work_time": "23 min block (own-question searches + verified source log + evidence map)",
        "milestone_presentation_review": "peer defense: partner challenges your gap placement",
        "student_prep": "M1 submitted; Purdue Libraries login working; laptop ready.",
        "student_artifact": "A source log with ≥2 verified entries + a started evidence map with a provisional gap in nb02",
        "exit_ticket": "Claim Ticket #7: one verified source for my question — full citation, where I retrieved it, and its central claim in my own words.",
        "homework_next_milestone": "Grow the evidence map to ≥6 verified sources with claims, and mark whether your gap survives every one; M2 presents at this Friday's studio.",
        "instructor_prep": "Brief SRL seat C on the unfindable-study puzzle; verify library-portal access from a student view; test the networkx map cell in Colab.",
        "risks_contingency": "Library portal outage → Google Scholar and open-access fallbacks are pre-listed in nb02; thin in-class results → snowball from one seed source and finish the map as homework.",
    },
    # ------------------------------------------------------------------ M8
    {
        "meeting": 8, "date": "2026-09-11", "day": "Fri", "modality": "in-person",
        "unit": "Week 3 — Research builds on research",
        "title": "Studio Friday — Evidence-map gallery: M2 due, M3 kickoff",
        "driving_question": "Does your evidence map survive a room of skeptics, and is the gap you placed still real once every source is checked?",
        "secondary_questions": "Where do your sources agree and disagree? What does the M3 brief ask for (a research charter and MIDA declaration), and how is it graded?",
        "inquiry": "description + generalization (studio)",
        "srl_slot": "",
        "srl_focus": "",
        "claim_permitted": "\"Across my verified sources, claims cluster as A vs B, and none address C — my gap, and my contribution.\"",
        "claim_not_permitted": "\"The literature proves my point\" — a map of claims is not proof, and an unread source counts for nothing.",
        "rdss_reading": "(no new reading — studio Friday; bring your finished evidence and contribution map)",
        "cb_reading": "",
        "other_material": "nb02 student notebook (research builds on research) — recap reference (Colab); M3 Brightspace brief",
        "provenance": "course design (Friday studio format) | weekly Friday studio | recap + M3 milestone brief + evidence-map gallery walk | newly-constructed-from-source-concept",
        "concepts": "gallery-walk peer review; agreement/contradiction on an evidence map; contribution framing; the M3 deliverable (research charter + MIDA declaration); incorporating criticism",
        "python_r_dependency": "none new (own milestone work)",
        "dataset_simulation": "student's own project materials (verified source logs)",
        "minute_dynamic": "0–6 research stand-up: change, blocker, decision, delegation, verification-needed from each student; 6–29 milestone kickoff from the Brightspace brief: present M3 (research charter + MIDA declaration) + rubric, then an AI-supported sprint — gallery-walk the evidence maps, and use Gemini to stress-test each stated contribution while logging what you keep; 29–41 peer + AI red-team review: sticky-note challenges plus a Gemini skeptic ask whether each gap is already covered by one of the student's own sources; 41–50 revise, update the Ledger + dossier, submit M2 + Claim Ticket.",
        "hands_on_activity": "Walk the gallery, challenge two classmates' maps, use Gemini to test whether your own gap is already covered, and defend or revise your contribution.",
        "practice": "📝 studio log: record the challenge you incorporated and what changed on your map because of it.",
        "discussion_prompt": "On your neighbor's map: is the gap they placed real, or does one of their own verified sources already fill it?",
        "project_connection": "M2 closes today; the confirmed gap and contribution seed the M3 research charter and MIDA declaration.",
        "milestone_developed": "M2 — Verified evidence and contribution map (presented + due); M3 — Research charter and MIDA declaration (kickoff)",
        "milestone_work_time": "23 min studio block",
        "milestone_presentation_review": "M2 presented: evidence-map gallery walk with sticky-note peer challenges",
        "student_prep": "Evidence map built from ≥6 verified sources; source log current; laptop ready.",
        "student_artifact": "Evidence map with a defended gap + one incorporated revision",
        "exit_ticket": "Claim Ticket #8: the strongest verified claim in my map that argues AGAINST my project's premise.",
        "homework_next_milestone": "Submit M2 tonight (11:59 PM). Weekend: read RDSS ch. 2 'What is a research design?'; next week we build the anatomy of a design (MIDA).",
        "instructor_prep": "Sticky notes; screens arranged for the gallery; M3 Brightspace brief on screen; midweek source-log check notes in hand.",
        "risks_contingency": "Maps too thin for a gallery → pair students to co-present the stronger map; the thin-map student owes the gap defense and finishes over the weekend.",
    },
    # ------------------------------------------------------------------ M9
    {
        "meeting": 9, "date": "2026-09-14", "day": "Mon", "modality": "in-person",
        "unit": "Week 4 — The anatomy of a research design",
        "title": "The anatomy of a research design: MIDA — Model, Inquiry, Data strategy, Answer strategy",
        "driving_question": "What are the four parts every research design must have, and what must the world be like for your question to have an answer?",
        "secondary_questions": "What is a model, and how does a DAG say 'I believe X could affect Y'? What is an inquiry (estimand), and why must it be named before data arrive? What does it mean for the four MIDA parts to align?",
        "inquiry": "causal + generalization (design anatomy)",
        "srl_slot": "SRL slot 04 — rotation seat D",
        "srl_focus": "Puzzle: two designs share a question but disagree on one DAG arrow — what evidence, even in principle, could settle whose world is closer to true?",
        "claim_permitted": "\"Under my stated model, my inquiry is [quantity] over [units], and my data and answer strategies are built to reach exactly that quantity.\"",
        "claim_not_permitted": "Choosing the quantity after seeing results, or a design whose four parts do not point at the same inquiry.",
        "rdss_reading": "RDSS ch. 2 'What is a research design?' + ch. 5 'Declaring designs' (book.declaredesign.org)",
        "cb_reading": "",
        "other_material": "nb03 §Lecture 1 (Colab); make_dag DAG helper",
        "provenance": "RDSS ch.2 + ch.5 | what is a research design + declaring designs | MIDA anatomy, DAG helper, and the genie/estimand pattern for a non-quant audience | newly-constructed-from-source-concept",
        "concepts": "MIDA: Model, Inquiry, Data strategy, Answer strategy; a model as a claim about how the world could be; DAG nodes and edges; potential outcomes (first exposure); inquiry/estimand; the genie test; inquiry precedes data; alignment among the four parts",
        "python_r_dependency": "networkx (draw a 3-node DAG), numpy/pandas (name a toy estimand)",
        "dataset_simulation": "inline seeded toy world (seed 464): one cause, one outcome, one lurking variable",
        "minute_dynamic": "0–9 SRL-led research puzzle: two designs for one question disagree on a single DAG arrow — the class debates what could settle it; 9–31 guided Gemini research-partner investigation in nb03: sketch your project's 3-node DAG, ask Gemini to propose a lurking third variable and an estimand phrasing, then verify each against your own model rather than accepting it; 31–43 human verification + instructor formalization: the instructor formalizes MIDA, potential outcomes, and the genie test, and the class corrects one AI-proposed arrow that does not belong; 43–50 decision & defense: log your DAG + one-sentence inquiry in the Ledger + Claim Ticket.",
        "hands_on_activity": "Draw your project's 3-node DAG and write your inquiry in one sentence, using Gemini to propose a lurking variable and an estimand phrasing that you then verify against your own model.",
        "practice": "📝 nb03 practice: for three questions, write the potential-outcomes pair it implicitly compares; for two more, write the inquiry in words and name its units.",
        "discussion_prompt": "Your DAG has an arrow your partner's does not. What evidence, even in principle, could settle whose world is closer to true?",
        "project_connection": "Each project leaves with a first DAG and a one-sentence inquiry — the Model and Inquiry halves of the M3 declaration.",
        "milestone_developed": "M3 — Research charter and MIDA declaration (dev)",
        "milestone_work_time": "10 min (own-project DAG + inquiry sentence)",
        "milestone_presentation_review": "pair DAG challenge",
        "student_prep": "M2 submitted; RDSS ch. 2 read; laptop ready for the DAG cell.",
        "student_artifact": "Own-project 3-node DAG + one-sentence inquiry in nb03",
        "exit_ticket": "Claim Ticket #9: my inquiry in ONE sentence a non-researcher could repeat back, plus the units it is defined over.",
        "homework_next_milestone": "Refine your DAG and inquiry; read RDSS ch. 5 'Declaring designs' before Wednesday; start drafting the M3 research charter for this Friday's studio.",
        "instructor_prep": "Brief SRL seat D on the one-arrow-disagreement puzzle; test the networkx DAG cell in Colab; board-ready potential-outcomes toy table.",
        "risks_contingency": "Potential outcomes land abstract → fall back to a concrete two-world example the class suggests and rerun the toy table; SRL under-prepared → instructor holds the puzzle, SRL takes the transfer block.",
    },
    # ------------------------------------------------------------------ M10
    {
        "meeting": 10, "date": "2026-09-16", "day": "Wed", "modality": "in-person",
        "unit": "Week 4 — The anatomy of a research design",
        "title": "Declare, diagnose, redesign: assumptions, bias, variance, power, and threats to validity",
        "driving_question": "Once your design is declared, how do you find out whether it actually works before you spend a semester running it?",
        "secondary_questions": "What does it mean to declare a design in full? What is design diagnosis, and what do bias, variance, and power tell you? What threats to validity would a skeptic raise, and how does redesign answer them?",
        "inquiry": "causal + generalization (diagnosis + redesign)",
        "srl_slot": "SRL slot 05 — rotation seat E",
        "srl_focus": "Puzzle: a design looks airtight on paper but its diagnosis says it will miss the effect nine times out of ten — what single change rescues it?",
        "claim_permitted": "\"My declared design, diagnosed, has [bias/variance/power] properties X, so it can support claim Y and not claim Z; here is the redesign that improves it.\"",
        "claim_not_permitted": "\"The design is fine because it sounds rigorous\" — rigor is a diagnosed property, not a vibe, and an undiagnosed design makes no promises.",
        "rdss_reading": "RDSS ch. 5 'Declaring designs' + ch. 10 'Diagnosing designs' (book.declaredesign.org)",
        "cb_reading": "optional: callingbullshit.org case on an underpowered or invalid design",
        "other_material": "nb03 §Lecture 2 (Colab)",
        "provenance": "RDSS ch.5 + ch.10 (+ ch.11 'Redesigning' preview) | declaring + diagnosing designs | declare->diagnose->redesign loop with bias/variance/power/validity built for a non-quant audience | newly-constructed-from-source-concept",
        "concepts": "the declare -> diagnose -> redesign loop; assumptions made explicit; bias; variance; statistical power (intuition); threats to validity; redesign as a response to a diagnosis; a diagnosed design states what it can and cannot support",
        "python_r_dependency": "numpy (simulate the declared design many times; seed 464), matplotlib (spread of answers = variance; hit rate = power)",
        "dataset_simulation": "inline seeded simulation (seed 464): repeat a simple declared design to show bias, variance, and power",
        "minute_dynamic": "0–7 SRL-led retrieval & challenge: the SRL presents an airtight-looking design whose diagnosis says it will usually miss — the class guesses why; 7–30 intensive applied AI laboratory: in nb03, declare a simple design, simulate it many times to read its bias, variance, and power, then ask Gemini to name threats to validity and verify each against the simulation; 30–42 peer defense + adversarial questioning: run the same diagnosis on YOUR design draft and defend the one redesign you would make; 42–50 transfer to the final project + Ledger + Claim Ticket.",
        "hands_on_activity": "Declare a simple design, simulate it to read its bias, variance, and power, then use Gemini to list threats to validity and verify each against what the simulation actually shows.",
        "practice": "📝 nb03 practice: for three designs, label the biggest threat (bias, variance, or power) and name the one redesign that most reduces it.",
        "discussion_prompt": "Your diagnosis says the design will miss the effect most of the time. Is running it anyway unethical, merely risky, or defensible with the right framing?",
        "project_connection": "The diagnosis and redesign done today complete the M3 declaration — a design that states what it can and cannot support.",
        "milestone_developed": "M3 — Research charter and MIDA declaration (dev; diagnosis + redesign added)",
        "milestone_work_time": "11 min (diagnose own design draft + name one redesign)",
        "milestone_presentation_review": "peer defense: partner names one threat to your design; you answer with a redesign",
        "student_prep": "DAG + inquiry from Monday; RDSS ch. 5 read; laptop ready for the simulation cells.",
        "student_artifact": "Executed diagnosis simulation + own design's threats-to-validity note + one named redesign in nb03",
        "exit_ticket": "Claim Ticket #10: my design's biggest threat, what my diagnosis says it does to my answer, and the one redesign I will make.",
        "homework_next_milestone": "Finalize and rehearse the M3 research charter + MIDA declaration for this Friday's studio (world, DAG, inquiry, data + answer strategy, diagnosis, redesign); finish nb03 cells.",
        "instructor_prep": "Brief SRL seat E on the airtight-but-underpowered puzzle; verify the simulation cells run under 30 seconds in Colab; queue the bias/variance/power board picture.",
        "risks_contingency": "Simulation intuition doesn't land → rerun with exaggerated parameters so bias and low power are unmissable, then dial back; concepts too abstract → diagnose one shared fallback design collectively.",
    },
    # ------------------------------------------------------------------ M11
    {
        "meeting": 11, "date": "2026-09-18", "day": "Fri", "modality": "in-person",
        "unit": "Week 4 — The anatomy of a research design",
        "title": "Studio Friday — Research charter + MIDA declarations: M3 due, M4 kickoff",
        "driving_question": "Can you declare your whole design — model, inquiry, data strategy, answer strategy — in a few minutes, and take a question on each part?",
        "secondary_questions": "Do your four MIDA parts agree with each other? What does the M4 brief ask for (an observational descriptive design audit), and how is it graded?",
        "inquiry": "full MIDA (studio)",
        "srl_slot": "",
        "srl_focus": "",
        "claim_permitted": "\"My charter declares M, I, D, and A, each part consistent with the others, and my diagnosis says what it can and cannot support.\"",
        "claim_not_permitted": "A declaration whose parts quietly disagree — a population inquiry served by a convenience sample, or a causal claim with no design to identify it.",
        "rdss_reading": "(no new reading — studio Friday; bring your rehearsed M3 charter + declaration)",
        "cb_reading": "",
        "other_material": "nb03 student notebook (anatomy of a research design) — recap reference (Colab); M4 Brightspace brief",
        "provenance": "course design (Friday studio format) | weekly Friday studio | recap + M4 milestone brief + declaration session | newly-constructed-from-source-concept",
        "concepts": "declaring a full design in public; internal-consistency check across MIDA; clarifying questions as peer review; the M4 deliverable (observational descriptive design audit); hand-off to the design library",
        "python_r_dependency": "none new (own milestone work)",
        "dataset_simulation": "student's own project materials",
        "minute_dynamic": "0–6 research stand-up: change, blocker, decision, delegation, verification-needed from each student; 6–29 milestone kickoff from the Brightspace brief: present M4 (observational descriptive design audit) + rubric, then an AI-supported sprint — deliver 3-minute MIDA declarations, one clarifying question per listener, and use Gemini to probe internal consistency while logging what you accept; 29–41 peer + AI red-team review: partners plus a Gemini skeptic hunt for two MIDA parts that disagree; 41–50 revise, update the Ledger + dossier, submit M3 + Claim Ticket.",
        "hands_on_activity": "Deliver your 3-minute MIDA declaration, collect one clarifying question per listener, and use Gemini to test whether any two of your MIDA parts disagree.",
        "practice": "📝 studio log: record the clarifying question that stung most and how your declaration will change because of it.",
        "discussion_prompt": "Which classmate's declaration could you repeat back word for word, and what made its inquiry so easy to hold onto?",
        "project_connection": "M3 closes today; the declared design opens the design-library phase, beginning with the M4 observational descriptive audit.",
        "milestone_developed": "M3 — Research charter and MIDA declaration (presented + due); M4 — Observational descriptive design audit (kickoff)",
        "milestone_work_time": "23 min studio block",
        "milestone_presentation_review": "M3 presented: 3-minute MIDA declaration + one clarifying question per listener",
        "student_prep": "3-minute M3 declaration rehearsed; nb03 cells complete; laptop ready.",
        "student_artifact": "Delivered declaration + revision notes + a started M4 audit",
        "exit_ticket": "Claim Ticket #11: my inquiry, restated after feedback, in one sentence a non-researcher could repeat back.",
        "homework_next_milestone": "Submit M3 tonight (11:59 PM). Weekend: read RDSS ch. 15 'Observational: descriptive'; next week begins the observational descriptive design deep dive.",
        "instructor_prep": "Timer; declaration order; clarifying-question norms card; M4 Brightspace brief on screen; consult rotation.",
        "risks_contingency": "Declarations exceed time → move the last declaration to the top of the sprint and protect the M4 start; questions drift into debate → enforce the one-clarifying-question norm.",
    },
]
