"""Meetings M1–M11 (Aug 24 – Sep 18): Phase 1 (curiosity → question) and the
start of Phase 2 (literature, model & inquiry, measurement)."""

MEETINGS_P1 = [
    # ------------------------------------------------------------------ M1
    {
        "meeting": 1, "date": "2026-08-24", "day": "Mon", "modality": "in-person",
        "unit": "Phase 1 — Curiosity, gaps, answerable questions",
        "title": "Launchpad: How do we know? Course map, Colab, and the Ask → Verify → Document policy",
        "driving_question": "How do we come to know something well enough to defend it?",
        "secondary_questions": "What will you build this semester? What does the AI policy require of every deliverable? How does a notebook-driven MWF seminar work?",
        "approach": "all (framing)",
        "claim_permitted": "\"I can state what evidence WOULD be needed to support a claim\" — the course's opening move.",
        "claim_not_permitted": "Any empirical claim without a stated evidence base — including claims an AI tool produced.",
        "rdss_reading": "RDSS ch. 1 (Preface) + ch. 2 'What is a research design?' — skim before Wednesday (book.declaredesign.org)",
        "cb_reading": "",
        "other_material": "nb00 (Colab); course website; syllabus; Brightspace orientation",
        "provenance": "brief §3 + RDSS ch.2 | course framing | MIDA overview (concept only) | newly-constructed-from-source-concept",
        "concepts": "evidence-driven research; the four approaches (preview); MIDA (preview); Ask → Verify → Document; claim ledger",
        "python_r_dependency": "Colab basics only (run a cell, save a copy)",
        "dataset_simulation": "none (one toy claim-check cell)",
        "minute_dynamic": "0–5 welcome + names + one-line curiosities; 5–13 the course promise: from curiosity to a defensible claim (map on board); 13–20 live demo: an AI tool fabricates a citation, we catch it (Ask → Verify → Document); 20–35 hands-on: open nb00 in Colab, run the readiness cells, save a copy to Drive; 35–45 pair task: swap one claim you believe and name the evidence behind it; 45–50 M00 kickoff brief + Claim Ticket exit.",
        "hands_on_activity": "Open nb00 in Colab, run all readiness cells, and catch the planted fabricated citation using the verification checklist.",
        "practice": "📝 nb00 practice: classify three everyday claims by the evidence that would be needed to support each.",
        "discussion_prompt": "What is something you believed that turned out to be wrong — and what evidence changed your mind?",
        "project_connection": "The semester project starts today: every student leaves with the M00 Curiosity Map assignment.",
        "milestone_developed": "M00 — Kickoff: Curiosity Map + tool readiness",
        "milestone_work_time": "5 min (M00 brief + first curiosity jotting)",
        "milestone_presentation_review": "none (kickoff)",
        "student_prep": "Bring a laptop; be able to log into Google (Colab) and Brightspace.",
        "student_artifact": "Executed nb00 readiness cells + first Claim Ticket",
        "exit_ticket": "Claim Ticket #1: one claim you encountered this week + what evidence would be needed to defend it.",
        "homework_next_milestone": "Finish M00 (Curiosity Map: 3 curiosities + tool readiness screenshot) — due Wed Aug 26, 11:59 PM.",
        "instructor_prep": "Verify Colab loads nb00 from the public repo; test the planted-citation demo; print/roster the 5 students.",
        "risks_contingency": "Colab/account issues → pair students on one laptop and finish readiness at home; keep the demo offline-safe (screenshots of the AI output as backup).",
    },
    # ------------------------------------------------------------------ M2
    {
        "meeting": 2, "date": "2026-08-26", "day": "Wed", "modality": "in-person",
        "unit": "Phase 1 — Curiosity, gaps, answerable questions",
        "title": "From curiosity to a topic worth studying",
        "driving_question": "What makes a curiosity worth a semester of your life?",
        "secondary_questions": "How do researchers move from 'interesting' to 'studyable'? What is the difference between a topic and a question?",
        "approach": "all (framing)",
        "claim_permitted": "\"This topic is studyable because evidence about it can, in principle, be gathered.\"",
        "claim_not_permitted": "\"My topic matters, so any question about it is a research question.\" (Topics are not questions.)",
        "rdss_reading": "RDSS ch. 2 'What is a research design?' (book.declaredesign.org)",
        "cb_reading": "",
        "other_material": "nb01 §1–2 (Colab)",
        "provenance": "RDSS ch.2 | research designs as declarable objects | concept adapted to honors non-quant audience | adapted",
        "concepts": "curiosity vs topic vs question; studyability; the research pipeline; declared designs (first exposure)",
        "python_r_dependency": "none beyond running markdown/code cells (pandas preview optional)",
        "dataset_simulation": "none",
        "minute_dynamic": "0–5 Claim Ticket callbacks (two students read theirs); 5–12 mini-lesson: curiosity → topic → question funnel; 12–17 model: instructor narrates own curiosity→question path; 17–30 M00 presentations: each student gives a 30-second curiosity pitch (5 × ~2.5 min with transitions); 30–42 workshop in nb01: apply the funnel to your strongest curiosity; 42–48 pairs exchange one 'so what?' challenge; 48–50 exit ticket.",
        "hands_on_activity": "nb01 funnel worksheet cells: write your curiosity, narrow to a topic, and draft the first candidate question.",
        "practice": "📝 nb01 practice: sort 6 given statements into curiosity / topic / question.",
        "discussion_prompt": "Whose 30-second pitch would you fund, and what single question would you ask them first?",
        "project_connection": "The curiosity pitched today becomes the field for the M01 research-question pitch.",
        "milestone_developed": "M00 → M01 — Research Question Pitch",
        "milestone_work_time": "13 min (presentations) + 12 min (funnel workshop on own project)",
        "milestone_presentation_review": "M00 presented: 30-second curiosity pitch, whole-class warm feedback (one strength + one question each)",
        "student_prep": "M00 Curiosity Map due tonight 11:59 PM; be ready to pitch one curiosity in 30 seconds.",
        "student_artifact": "Funnel worksheet cells completed for own project",
        "exit_ticket": "Claim Ticket #2: my strongest curiosity, restated as a topic, in one sentence.",
        "homework_next_milestone": "Read RDSS ch. 3; bring one published study (any format) touching your topic to Friday's class.",
        "instructor_prep": "Queue the pitch order; prepare warm-feedback norms poster; review submitted M00 maps before class.",
        "risks_contingency": "A student has no viable curiosity → offer the curated fallback-topic menu (in the instructor notebook) and schedule an office-hours consult.",
    },
    # ------------------------------------------------------------------ M3
    {
        "meeting": 3, "date": "2026-08-28", "day": "Fri", "modality": "in-person",
        "unit": "Phase 1 — Curiosity, gaps, answerable questions",
        "title": "Gaps: what is actually missing from what we know?",
        "driving_question": "How do you find the hole in a field's knowledge — and how do you know it is real?",
        "secondary_questions": "What kinds of gaps exist (evidence, population, measurement, method, contradiction)? How is a gap different from 'nobody has done exactly this'?",
        "approach": "all (framing)",
        "claim_permitted": "\"Based on the sources I examined, X has not been established for population/context Y\" — a bounded gap claim.",
        "claim_not_permitted": "\"Nothing is known about my topic.\" (An absolute absence claim you cannot verify.)",
        "rdss_reading": "RDSS ch. 3 'Research design principles' (book.declaredesign.org)",
        "cb_reading": "",
        "other_material": "nb01 §3 gap typology (Colab)",
        "provenance": "fresh (gap typology) + RDSS ch.3 | design principles | principle framing | newly-constructed-from-source-concept",
        "concepts": "gap typology: evidence gap, population gap, measurement gap, method gap, contradiction gap; bounded vs absolute absence claims",
        "python_r_dependency": "none (text/argument work in notebook cells)",
        "dataset_simulation": "none",
        "minute_dynamic": "0–4 warm-up: name one thing your brought-in study does NOT answer; 4–12 mini-lesson: the five gap types with real examples; 12–24 hands-on: in nb01, classify the gap left by the study you brought (write the bounded gap claim); 24–34 gallery: each student states their gap type + bounded claim, class votes on the classification; 34–46 project work: draft 2 candidate gaps for your own topic; 46–50 exit ticket.",
        "hands_on_activity": "Classify the gap left by the study you brought and write it as a bounded gap claim in nb01.",
        "practice": "📝 nb01 practice: match 5 mini-abstracts to the gap type each leaves open.",
        "discussion_prompt": "When is 'nobody has studied this' a good sign — and when is it a warning sign?",
        "project_connection": "Candidate gaps drafted today feed directly into the M01 pitch (gap → problem → question).",
        "milestone_developed": "M01 — Research Question Pitch",
        "milestone_work_time": "12 min (candidate gaps for own topic)",
        "milestone_presentation_review": "informal: gap classification gallery with class voting",
        "student_prep": "Bring one published study touching your topic (from Wednesday's homework).",
        "student_artifact": "Two candidate bounded gap claims for own topic in nb01",
        "exit_ticket": "Claim Ticket #3: my best candidate gap, typed by kind, in one bounded sentence.",
        "homework_next_milestone": "Weekend: skim RDSS ch. 4; turn your best gap into one written problem statement (bring Monday).",
        "instructor_prep": "Prepare 5 mini-abstract cards for the matching practice; check every student brought a study (email reminder Thursday).",
        "risks_contingency": "Students bring op-eds instead of studies → run the matching practice first and use its abstracts as shared material.",
    },
    # ------------------------------------------------------------------ M4
    {
        "meeting": 4, "date": "2026-08-31", "day": "Mon", "modality": "in-person",
        "unit": "Phase 1 — Curiosity, gaps, answerable questions",
        "title": "From problem to an answerable question",
        "driving_question": "What separates a question evidence can answer from one it cannot?",
        "secondary_questions": "What are the marks of answerability (defined units, defined comparison, observable outcomes, bounded scope)? How specific is too specific?",
        "approach": "all (framing)",
        "claim_permitted": "\"My question names its units, outcome, comparison, and scope — evidence could in principle answer it.\"",
        "claim_not_permitted": "\"Is X good or bad?\" posed as a research question (a values question is not answerable by evidence alone).",
        "rdss_reading": "RDSS ch. 4 'Getting started' (book.declaredesign.org)",
        "cb_reading": "",
        "other_material": "nb01 §4 answerability rubric (Colab)",
        "provenance": "RDSS ch.4 + fresh answerability rubric | getting started | question-formulation guidance | extended",
        "concepts": "answerability: units, outcomes, comparisons, scope; empirical vs normative questions; question quality rubric",
        "python_r_dependency": "none (rubric applied in markdown cells)",
        "dataset_simulation": "none",
        "minute_dynamic": "0–5 problem statements read-around (from weekend homework); 5–13 mini-lesson: the answerability rubric, with one question upgraded live; 13–28 hands-on: run 4 sample questions through the rubric in nb01, then your own; 28–38 peer clinic: partner scores your question on the rubric, you defend or revise; 38–47 project work: finalize the question wording for your M01 pitch; 47–50 exit ticket.",
        "hands_on_activity": "Score 4 sample questions + your own on the answerability rubric in nb01; rewrite yours until it passes.",
        "practice": "📝 nb01 practice: rewrite 3 unanswerable questions (one normative, one boundless, one unit-free) into answerable form.",
        "discussion_prompt": "Which is the worse failure — a question too broad to answer, or one so narrow the answer is trivial?",
        "project_connection": "The question finalized today is the centerpiece of Friday's M01 pitch.",
        "milestone_developed": "M01 — Research Question Pitch",
        "milestone_work_time": "9 min (finalize own question wording)",
        "milestone_presentation_review": "peer clinic: partner rubric-scores your question",
        "student_prep": "Bring your written problem statement (weekend homework); RDSS ch. 4 skimmed.",
        "student_artifact": "Rubric-scored, revised research question in nb01",
        "exit_ticket": "Claim Ticket #4: my question, final wording, + the rubric criterion it is still weakest on.",
        "homework_next_milestone": "Draft the full M01 pitch (gap → problem → question, 2 minutes); pitch day is Friday Sep 4.",
        "instructor_prep": "Select 4 sample questions spanning the rubric failure modes; prep the live-upgrade example.",
        "risks_contingency": "Questions converge on unmeasurable outcomes → pull the measurement-preview card forward from nb05 and flag it as coming attractions.",
    },
    # ------------------------------------------------------------------ M5
    {
        "meeting": 5, "date": "2026-09-02", "day": "Wed", "modality": "in-person",
        "unit": "Phase 1 — Curiosity, gaps, answerable questions",
        "title": "The four approaches I: description and inference",
        "driving_question": "What kind of answer does your question actually ask for?",
        "secondary_questions": "What can a description establish, and where does it stop? What does it mean to generalize with uncertainty?",
        "approach": "description + inference (the classification skill)",
        "claim_permitted": "Description: \"in these data, X.\" Inference: \"in the population, plausibly X, with stated uncertainty.\"",
        "claim_not_permitted": "Treating a pattern in the data at hand as if it automatically holds beyond the sample — or as if it were causal.",
        "rdss_reading": "RDSS ch. 7 'Defining the inquiry' (descriptive vs causal inquiries; book.declaredesign.org)",
        "cb_reading": "",
        "other_material": "nb02 §1–2 (Colab)",
        "provenance": "RDSS ch.7 | descriptive inquiries vs causal inquiries | classification recast as the 4-approach skill | extended",
        "concepts": "approach classification; sample vs population; descriptive inquiry; uncertainty (preview); claim boundaries",
        "python_r_dependency": "pandas (read a CSV, value_counts, mean) — first real code",
        "dataset_simulation": "lapop_brazil.csv (first look: one variable, sample vs population framing)",
        "minute_dynamic": "0–5 pitch-prep pulse check + one Claim Ticket callback; 5–13 mini-lesson: the 2×2 of the four approaches, today the left column (description, inference); 13–25 hands-on: in nb02 compute one honest descriptive summary of lapop_brazil and write its claim; 25–33 pause-and-predict: will the sample pattern hold in the population? students commit in writing before the discussion; 33–43 classification drill rounds 1–2: sort question cards into description vs inference; 43–48 project transfer: which column does YOUR question live in (so far)?; 48–50 exit ticket.",
        "hands_on_activity": "Compute a descriptive summary of one lapop_brazil variable in nb02 and write the exact claim it permits.",
        "practice": "📝 nb02 practice: 8 question cards, sort into description vs inference and name the giveaway word in each.",
        "discussion_prompt": "Why is 'most people in this survey…' a different claim from 'most Brazilians…'? What would license the second?",
        "project_connection": "First-pass classification of each student's own M01 question.",
        "milestone_developed": "M01 — Research Question Pitch (approach candidate added)",
        "milestone_work_time": "5 min (classify own question + note the approach in the pitch draft)",
        "milestone_presentation_review": "none (drill + prep day)",
        "student_prep": "M01 pitch drafted; laptop ready for first real pandas work.",
        "student_artifact": "One executed descriptive summary + a committed pre-run prediction in nb02",
        "exit_ticket": "Claim Ticket #5: my question is (for now) a ___ question, because the answer it wants is ___.",
        "homework_next_milestone": "Rehearse the 2-minute M01 pitch for Friday; finish nb02 §1–2 cells if not done in class.",
        "instructor_prep": "Print two rounds of question cards; verify lapop_brazil.csv loads from the repo raw URL in Colab.",
        "risks_contingency": "pandas friction dominates → shrink the hands-on to the provided one-liner cells and move the second drill round to Friday.",
    },
    # ------------------------------------------------------------------ M6
    {
        "meeting": 6, "date": "2026-09-04", "day": "Fri", "modality": "in-person",
        "unit": "Phase 1 — Curiosity, gaps, answerable questions",
        "title": "The four approaches II: prediction and causation — and the M01 pitches",
        "driving_question": "Is your question asking to forecast the future, or to change it?",
        "secondary_questions": "Why does predicting well not require understanding? Why does 'what if we intervened?' demand a different kind of evidence entirely?",
        "approach": "prediction + causal (the classification skill)",
        "claim_permitted": "Prediction: \"for new cases, expect Ŷ, judged against a baseline.\" Causal: \"the intervention changes Y under a stated identification argument.\"",
        "claim_not_permitted": "\"The model predicts well, so X causes Y\" — or any causal claim with no identification argument.",
        "rdss_reading": "RDSS ch. 7 (continued) + Part III opener (design library: observational/experimental × descriptive/causal)",
        "cb_reading": "optional: callingbullshit.org 'Criminal machine learning' case study (prediction ≠ understanding)",
        "other_material": "nb02 §3–4 (Colab)",
        "provenance": "RDSS ch.7 + Part III framing | inquiry types | prediction column built fresh (RDSS treats it lightly) | extended",
        "concepts": "prediction vs explanation; baseline; counterfactuals (first exposure); identification (first exposure); the full 4-approach map",
        "python_r_dependency": "none new (one provided demo cell)",
        "dataset_simulation": "10-row toy forecast demo (inline, seeded)",
        "minute_dynamic": "0–4 settle + pitch order draw; 4–12 mini-lesson: the right column of the 2×2 (prediction, causal) with the criminal-ML cautionary case; 12–20 classification drill round 3: all four approaches now in play; 20–42 M01 PITCHES: five 2-minute pitches, each followed by 2 minutes of structured class response (the approach the class thinks the question wants + one risk); 42–48 self-revision: annotate your pitch with what you heard; 48–50 exit ticket + M01 submission reminder.",
        "hands_on_activity": "Classification drill with all four approaches; live approach-vote after each pitch.",
        "practice": "📝 nb02 practice: for 4 questions, name the approach AND the claim that would overreach it.",
        "discussion_prompt": "A model forecasts campus course demand almost perfectly. What can the registrar do with that — and what can't they conclude?",
        "project_connection": "Every project question gets a class-voted approach hypothesis to test against the coming units.",
        "milestone_developed": "M01 — Research Question Pitch (presented + submitted)",
        "milestone_work_time": "6 min (post-pitch self-revision)",
        "milestone_presentation_review": "M01 presented: 2-minute pitch + structured class approach-vote and risk feedback",
        "student_prep": "2-minute M01 pitch rehearsed; nb02 §1–2 complete.",
        "student_artifact": "Delivered pitch + annotated revision notes",
        "exit_ticket": "Claim Ticket #6: the approach my classmates voted for my question, and whether I agree (one reason).",
        "homework_next_milestone": "Submit M01 (pitch deck/notes + question + gap + candidate approach) tonight 11:59 PM. Read RDSS ch. 4 §literature; next week: sources and citation integrity.",
        "instructor_prep": "Timer + pitch rubric sheets; queue the optional CB case link; prepare approach-vote cards.",
        "risks_contingency": "Pitches run long → cap responses at one strength + the approach vote; move risk feedback to written notes passed to the presenter.",
    },
    # ------------------------------------------------------------------ M7
    {
        "meeting": 7, "date": "2026-09-09", "day": "Wed", "modality": "in-person",
        "unit": "Phase 2 — Literature, model, inquiry, measurement",
        "title": "Finding real sources: search, appraisal, and the AI hallucination problem",
        "driving_question": "How do you find what is actually known — and how do you know a citation is real?",
        "secondary_questions": "Where do scholarly claims live (journals, working papers, reports, data)? How does AI-assisted search fail, and how do you catch it?",
        "approach": "description + inference (appraising evidence claims)",
        "claim_permitted": "\"Source S exists, I retrieved it, and it claims X on the basis of evidence E.\"",
        "claim_not_permitted": "Citing any source you have not personally retrieved and checked — however plausible the AI's summary of it sounds.",
        "rdss_reading": "RDSS ch. 4 'Getting started' (situating a design in a literature)",
        "cb_reading": "",
        "other_material": "nb03 §1–2 (Colab); Purdue Libraries database portal; Google Scholar",
        "provenance": "fresh (AI-era source-finding workflow) + RDSS ch.4 | getting started | AI-policy instantiation | newly-constructed-from-source-concept",
        "concepts": "source types + hierarchy; search strings; snowballing; hallucinated citations; the retrieval-verification loop",
        "python_r_dependency": "none (browser + notebook log cells)",
        "dataset_simulation": "planted citation list (3 real, 2 fabricated) for the verification hunt",
        "minute_dynamic": "0–5 M01 feedback headlines returned; 5–12 mini-lesson: where claims live + the retrieval-verification loop; 12–27 hands-on hunt: nb03 gives 5 citations for a plausible topic — find the two fakes, log HOW you caught them; 27–35 debrief: what gave the fakes away; the verification checklist formalized; 35–47 project work: run one AI-assisted search + one database search for YOUR question, log both in the source ledger; 47–50 exit ticket.",
        "hands_on_activity": "Fabricated-citation hunt: verify 5 citations, catch the 2 fakes, document the tell in each.",
        "practice": "📝 nb03 practice: turn your research question into two search strings — one for a database, one for an AI tool — and predict how their failure modes will differ.",
        "discussion_prompt": "An AI summary cites a perfect-sounding study you cannot find. What are the three possible explanations, and what do you do next?",
        "project_connection": "The source ledger started today becomes the backbone of M02 (Literature & Claim Map).",
        "milestone_developed": "M02 — Literature & Claim Map",
        "milestone_work_time": "12 min (own-question searches + ledger start)",
        "milestone_presentation_review": "none (hunt debrief only)",
        "student_prep": "M01 submitted; Purdue Libraries login working.",
        "student_artifact": "Verification hunt log + source ledger with ≥2 verified entries",
        "exit_ticket": "Claim Ticket #7: one verified source for my question — full citation + where I retrieved it.",
        "homework_next_milestone": "Grow the source ledger to ≥6 verified sources before Friday; note each source's central claim.",
        "instructor_prep": "Refresh the planted-citation list (2 fabricated entries must remain plausible but unfindable); verify library portal access from a student view.",
        "risks_contingency": "Library portal outage → Google Scholar + open-access fallbacks are pre-listed in nb03.",
    },
    # ------------------------------------------------------------------ M8
    {
        "meeting": 8, "date": "2026-09-11", "day": "Fri", "modality": "in-person",
        "unit": "Phase 2 — Literature, model, inquiry, measurement",
        "title": "The claim map: what a field asserts, on what evidence — and where your gap sits",
        "driving_question": "Can you draw the argument of a literature — claims, evidence, and the hole your project fills?",
        "secondary_questions": "How do you extract a source's central claim and evidence type? What does disagreement between sources look like on a map?",
        "approach": "description + inference (mapping evidence claims)",
        "claim_permitted": "\"Across my verified sources, claims cluster as A vs B, and none address C — my gap.\"",
        "claim_not_permitted": "\"The literature proves…\" (a map of claims is not itself proof, and unread sources count for nothing).",
        "rdss_reading": "RDSS ch. 4 (continued)",
        "cb_reading": "",
        "other_material": "nb03 §3–4 claim-map builder (Colab)",
        "provenance": "fresh (claim-map method) | — | networkx-lite claim graph | newly-constructed-from-source-concept",
        "concepts": "claim extraction; evidence typing (descriptive/inferential/predictive/causal); agreement/contradiction edges; gap placement",
        "python_r_dependency": "provided networkx cell (students fill a table; the graph draws itself)",
        "dataset_simulation": "student source ledgers (own data)",
        "minute_dynamic": "0–5 ledger pulse check (count + best source aloud); 5–12 mini-lesson: from ledger to claim map, one worked example; 12–30 studio: build your claim map in nb03 (fill the claims table, run the graph cell, place your gap); 30–42 GALLERY WALK: maps on screens, class circulates with sticky-note questions (M02 review); 42–48 revise: incorporate one sticky-note challenge; 48–50 exit ticket + M02 submission reminder.",
        "hands_on_activity": "Build your own claim map from your verified ledger and place your gap on it.",
        "practice": "📝 nb03 practice: two sources disagree — list three design differences that could explain the contradiction without either being wrong.",
        "discussion_prompt": "On your neighbor's map: is the gap they placed real, or does one of their own sources already cover it?",
        "project_connection": "The claim map IS the M02 deliverable; today is its build-and-review studio.",
        "milestone_developed": "M02 — Literature & Claim Map (presented + submitted)",
        "milestone_work_time": "18 min (studio build) + 6 min (revision)",
        "milestone_presentation_review": "M02 presented: gallery walk with sticky-note peer challenges",
        "student_prep": "Source ledger with ≥6 verified sources (Wednesday's homework).",
        "student_artifact": "Claim map with placed gap + one incorporated revision",
        "exit_ticket": "Claim Ticket #8: the strongest claim in my map that argues AGAINST my project's premise.",
        "homework_next_milestone": "Submit M02 tonight 11:59 PM. Weekend read: RDSS ch. 6 'Specifying the model' §opening — next week we build worlds.",
        "instructor_prep": "Worked claim-map example ready; sticky notes; check each ledger midweek and nudge thin ones.",
        "risks_contingency": "Ledgers too thin for maps → pair students to co-map the stronger ledger, thin-ledger student owes the gap placement.",
    },
    # ------------------------------------------------------------------ M9
    {
        "meeting": 9, "date": "2026-09-14", "day": "Mon", "modality": "in-person",
        "unit": "Phase 2 — Literature, model, inquiry, measurement",
        "title": "Model (MIDA I): the world your question lives in — potential outcomes and DAGs",
        "driving_question": "What must the world be like for your question to have an answer?",
        "secondary_questions": "What is a model in the MIDA sense? What are potential outcomes? How does a DAG say 'I believe X could affect Y'?",
        "approach": "causal + inference (model-building)",
        "claim_permitted": "\"Under my stated model of the world, the quantity I want exists and is defined.\"",
        "claim_not_permitted": "Any claim that smuggles in a model you never stated (\"the effect of X\" with no world in which X varies).",
        "rdss_reading": "RDSS ch. 6 'Specifying the model' (book.declaredesign.org)",
        "cb_reading": "",
        "other_material": "nb04 §1–2 (Colab); make_dag_df utility (translated)",
        "provenance": "RDSS ch.6 + utilities/make_dag_df.R | specifying the model | potential outcomes + DAG helper | translated (R→Python)",
        "concepts": "MIDA: Model; possible worlds; potential outcomes Y(1), Y(0); DAG nodes/edges; what a model commits you to",
        "python_r_dependency": "numpy (simulate a tiny world), networkx (draw a 3-node DAG from an edge list)",
        "dataset_simulation": "inline simulated world (seeded, 100 units, one cause one outcome)",
        "minute_dynamic": "0–5 weekend-reading pulse + one M02 map highlight; 5–13 mini-lesson: a model is a claim about how the world could be — potential outcomes on the board with a 4-unit toy; 13–20 pause-and-predict: in the toy world, can we ever see both Y(1) and Y(0) for one unit? commit before reveal; 20–33 hands-on: nb04 simulate the world, reveal one potential outcome per unit, feel the fundamental problem; 33–43 DAG lab: draw YOUR project's 3-node DAG (cause, outcome, one lurking third variable); 43–48 pair swap: challenge one arrow in your partner's DAG; 48–50 exit ticket.",
        "hands_on_activity": "Simulate a 100-unit world with both potential outcomes, then reveal only one per unit — the fundamental problem of causal inference, executed.",
        "practice": "📝 nb04 practice: for 3 scenarios, write the potential-outcomes pair the question implicitly compares.",
        "discussion_prompt": "Your DAG has an arrow your partner's doesn't. What evidence — even in principle — could settle whose world is closer to true?",
        "project_connection": "Each student leaves with a first DAG of their own project's world — the seed of M03.",
        "milestone_developed": "M03 — Model & Inquiry Declaration",
        "milestone_work_time": "10 min (own-project DAG)",
        "milestone_presentation_review": "pair DAG challenge",
        "student_prep": "RDSS ch. 6 opening skimmed; M02 feedback reviewed.",
        "student_artifact": "Executed potential-outcomes simulation + own-project DAG",
        "exit_ticket": "Claim Ticket #9: one arrow in my DAG and the real-world mechanism it asserts.",
        "homework_next_milestone": "Read RDSS ch. 7 'Defining the inquiry'; refine your DAG with one more node if the world demands it.",
        "instructor_prep": "Board-ready 4-unit potential-outcomes table; test the networkx DAG cell renders in Colab.",
        "risks_contingency": "Potential outcomes land abstract → fall back to the concrete scholarship-letter example scripted in the instructor notebook and re-run the toy table with student-suggested numbers.",
    },
    # ------------------------------------------------------------------ M10
    {
        "meeting": 10, "date": "2026-09-16", "day": "Wed", "modality": "in-person",
        "unit": "Phase 2 — Literature, model, inquiry, measurement",
        "title": "Inquiry (MIDA I): the exact quantity you seek — and the M03 declarations",
        "driving_question": "If a genie handed you the truth, what NUMBER or PATTERN would it hand you?",
        "secondary_questions": "What is an inquiry/estimand? How do descriptive and causal inquiries differ? Why must the inquiry be defined before data arrive?",
        "approach": "causal + inference (estimand thinking)",
        "claim_permitted": "\"My inquiry is [quantity], defined over [units/world] — stated before seeing outcome data.\"",
        "claim_not_permitted": "Choosing the quantity AFTER browsing results (inquiry shopping), then presenting it as the question you always had.",
        "rdss_reading": "RDSS ch. 7 'Defining the inquiry' (book.declaredesign.org); declaration_7.1",
        "cb_reading": "",
        "other_material": "nb04 §3–4 (Colab)",
        "provenance": "RDSS ch.7 + declaration_7.1.R | defining the inquiry | inquiry declaration pattern | translated (R→Python)",
        "concepts": "inquiry/estimand; ATE vs share vs difference; inquiry precedes data; the M-I half of MIDA assembled",
        "python_r_dependency": "numpy/pandas (compute the true estimand inside the simulated world)",
        "dataset_simulation": "inline simulated world from M9, extended (true ATE computed then hidden)",
        "minute_dynamic": "0–4 DAG refinements shared (two volunteers); 4–12 mini-lesson: the genie test — inquiry as the quantity the genie hands you, descriptive and causal versions; 12–22 hands-on: in nb04 compute the TRUE inquiry value inside the simulated world, then hide it (it becomes the answer key for later units); 22–40 M03 DECLARATIONS: each student delivers a 3-minute Model + Inquiry declaration (world, DAG, genie quantity), class writes one clarifying question each; 40–47 revise declaration from the questions received; 47–50 exit ticket + M03 submission reminder.",
        "hands_on_activity": "Compute the true estimand in a world you control, hide it, and understand it as the future answer key.",
        "practice": "📝 nb04 practice: for 4 questions, write the inquiry in words AND as a formula over potential outcomes or population values.",
        "discussion_prompt": "Why does declaring the inquiry BEFORE data protect you from yourself?",
        "project_connection": "M03 declared aloud today: each project now has a stated world + stated quantity.",
        "milestone_developed": "M03 — Model & Inquiry Declaration (presented + submitted)",
        "milestone_work_time": "18 min (declarations) + 7 min (revision)",
        "milestone_presentation_review": "M03 presented: 3-minute declaration + one clarifying question per listener",
        "student_prep": "RDSS ch. 7 read; own DAG refined; 3-minute declaration drafted.",
        "student_artifact": "Delivered M03 declaration + revision notes; executed true-estimand cell",
        "exit_ticket": "Claim Ticket #10: my inquiry in ONE sentence a non-researcher could repeat back.",
        "homework_next_milestone": "Submit M03 tonight 11:59 PM. Read RDSS ch. 8 §measurement before Friday.",
        "instructor_prep": "Timer; declaration order; clarifying-question norms card; verify the hidden-estimand cell mechanics.",
        "risks_contingency": "Declarations exceed time → move the last student to Friday's opening and protect the revision block.",
    },
    # ------------------------------------------------------------------ M11
    {
        "meeting": 11, "date": "2026-09-18", "day": "Fri", "modality": "in-person",
        "unit": "Phase 2 — Literature, model, inquiry, measurement",
        "title": "Measurement I: from concept to construct to indicator",
        "driving_question": "How does an abstract idea become a number without losing its soul?",
        "secondary_questions": "What are concept, construct, indicator? What are validity and reliability, intuitively? Where does measurement live inside MIDA?",
        "approach": "description + inference (measurement)",
        "claim_permitted": "\"Indicator I measures construct C for concept X, and here is why the mapping is defensible.\"",
        "claim_not_permitted": "\"My variable measures happiness\" (naming a column after a concept does not make it the concept).",
        "rdss_reading": "RDSS ch. 8 'Crafting a data strategy' — measurement sections (book.declaredesign.org)",
        "cb_reading": "",
        "other_material": "nb05 §1–2 (Colab)",
        "provenance": "RDSS ch.8 (measurement within data strategy) + fresh concept→construct→indicator ladder | ch.8 | measurement framing | extended",
        "concepts": "concept → construct → indicator ladder; validity; reliability; operationalization; measurement inside D of MIDA",
        "python_r_dependency": "pandas (inspect real survey items)",
        "dataset_simulation": "bonilla_tillery.csv (survey-experiment items as measurement examples)",
        "minute_dynamic": "0–5 M03 submission debrief + inquiry restated from memory (spot check); 5–13 mini-lesson: the ladder, climbed twice (trust in government; food insecurity); 13–27 hands-on: open bonilla_tillery items in nb05 — which construct is each item reaching for? rate the reach; 27–38 lab: climb the ladder for YOUR project's key concept (draft 2 candidate indicators); 38–46 pair audit: partner attacks the weakest rung of your ladder; 46–50 exit ticket.",
        "hands_on_activity": "Rate real survey items on how well they reach their construct; climb the ladder for your own key concept.",
        "practice": "📝 nb05 practice: propose two DIFFERENT indicators for the same construct and state what each would miss.",
        "discussion_prompt": "Give an example where a measure is highly reliable and badly invalid. Why is that combination so dangerous?",
        "project_connection": "The measurement ladder for each project's central concept starts here (M04).",
        "milestone_developed": "M04 — Measurement & Operationalization Plan",
        "milestone_work_time": "11 min (own-concept ladder)",
        "milestone_presentation_review": "pair audit of the ladder's weakest rung",
        "student_prep": "RDSS ch. 8 measurement sections skimmed; M03 submitted.",
        "student_artifact": "Rated item set + own-concept ladder draft with 2 candidate indicators",
        "exit_ticket": "Claim Ticket #11: my key concept, my best indicator, and the biggest thing it misses.",
        "homework_next_milestone": "Weekend: draft the full M04 plan (concept, construct, ≥2 indicators, validity threats); Monday we stress-test it with simulated measurement error.",
        "instructor_prep": "Select 4 bonilla_tillery items for the rating task; two ladder walk-throughs prepped.",
        "risks_contingency": "Concepts too abstract to ladder in class → use the shared fallback concept (student stress) collectively, own ladders finish as homework.",
    },
]
