"""Meetings M32–M43 (Weeks 12–16): the public-test-to-release arc (D41 studio-first).

Week 12 (nb12) — Studio 10 continues: pitch and defense rehearsal. The
30-second and 3-minute pitch layers built boundary-first from the locked
preliminary poster; compression without inflation; the five hardest fair
questions, the ULN move, defend-or-concede; the Friday mock poster symposium
(M11, poster edition v2 — defense-rehearsed). Week 13 (nb13, single Monday
lecture) — Studio 10 closes with the public test: full dress rehearsal + the
Expo capture plan, then the Expo (Tuesday, a graded presentation + evaluating
>=3 colleagues' posters), then the Friday reflection studio where public
questions become data and the claim or its defense revises (M12, poster
edition v3 — publicly tested). Week 14 (nb14, ASYNC Thanksgiving module) —
Studio 11 PRACTICE: cold-run a peer's anonymized package without author help,
red-team it, run the required GenAI Studio 'Reproducibility Auditor' pass, and
write the repair handoff; the report is due Sunday night (M13, precedes Book
Milestone 11 v1). Week 15 (nb15) — Studios 9 and 11 close together: Monday
adjudicates the public test and the cold run into the bounded-note revision
(course note v1 = Book Milestone 9 v2); Wednesday repairs what the cold run
exposed and assembles reusable package v1 (Book Milestone 11 v1); Friday's
table read + partner cold check submit M14. Week 16 (nb16) — Studio 12,
release and the next cycle: the stale-run test, the five-part release audit,
the dossier manifest, conflicting agents and false consensus, the stopping
rule stated as a decision, the next-study agenda; the terminal Friday runs the
final Evidence Defenses + the release ceremony (M15, terminal).

Fridays are studios (weekly multiple-choice topic quiz + stand-up + milestone
kickoff + AI-supported work block, no new topic content). M37 is an
asynchronous online module (no live meeting; ordered self-paced segments).
Milestones M11–M15 each present a book Milestone version (the D41 bridge);
M15 is terminal (no revision window). The Student Research Lead (SRL) slots
cover the seven Mon/Wed lectures here as slots 19–25; studios and the async
module carry no SRL slot. Unscored Synthetic-Colleague continuation beats run
in W12 (defense), W13 (public-criticism revision), and W15 (repair), reusing
the S10/S11 artifacts — never on Fridays, never scored.

RDSS chapter titles verified against book.declaredesign.org; never invent a
chapter — these weeks lean on EDR|AI lessons (research-pitches,
difficult-questions, replication-reproduction, research-packages,
managing-ai-agents, conflicting-agents, final-portfolio) plus the course's
conference and final-dossier protocols. AI tool named in activities is the
student's AI assistant (in and alongside Colab); GenAI Studio appears at the
M13 'Reproducibility Auditor' touchpoint and in the Week 16 agent-workflow
lab. No fabricated citations anywhere; every source a student cites is real
and retrieved.
"""

MEETINGS_P4 = [
    # ------------------------------------------------------------------ M32
    {
        "meeting": 32, "date": "2026-11-09", "day": "Mon", "modality": "in-person",
        "unit": "Week 12 — Studio 10: Pitch and defense rehearsal",
        "title": "Pitch and defense I: the 30-second and 3-minute layers — compression without inflation",
        "driving_question": "A stranger gives you thirty seconds, then maybe three minutes. What do you say in each — and how do you keep every compressed version exactly as honest as the locked poster?",
        "secondary_questions": "How do the 30-second and 3-minute layers differ in job? What must a pitch keep that compression tempts you to drop? How do you explain your method without jargon, boundary-first?",
        "inquiry": "all positions (communication — Studio 10 revisit)",
        "srl_slot": "SRL slot 19 (randomly assigned at semester start)",
        "srl_focus": "Puzzle: the colleague's 30-second pitch sounds cleaner than their locked poster — and somewhere in the compression the limitation vanished and the claim quietly grew. Which words did it?",
        "claim_permitted": "\"In my sample, X was associated with Y — spoken exactly as the poster says it, boundary in the same breath, compressed but never upgraded.\"",
        "claim_not_permitted": "\"X causes Y\" said aloud at the poster when the poster only claims association (the excited-mouth upgrade); a pitch that drops the limitation is not a shorter version, it is a different claim.",
        "rdss_reading": "Required EDR|AI: research-pitches (first read); research-posters revisited. No new RDSS — the pitch layers are built boundary-first from your locked preliminary poster.",
        "cb_reading": "",
        "other_material": "nb12 student notebook (pitch and defense rehearsal) §1–2 (Colab); project/conference/presentation_plan_protocol.md; the colleague's Week-11 poster artifact (unscored continuation); M11 brief on Brightspace",
        "provenance": "crosswalk M11 + BOOK_STATIONS adapt-and-defend revisit + presentation_plan_protocol.md | S10 defense-rehearsal unit | boundary-first 30-sec + 3-min pitch layers + outsider test + unscored colleague continuation beat | adapted",
        "concepts": "pitch architecture (hook, claim, evidence, boundary, invitation); the 30-second hook vs the 3-minute walk; boundary-first construction; audience adaptation and the outsider test; explaining method without jargon; compression-never-inflation; the adaptation-loss rule",
        "python_r_dependency": "none",
        "dataset_simulation": "each student's own locked preliminary poster (+ the reused colleague S10 artifact)",
        "minute_dynamic": "0–9 SRL-led research puzzle: the lead plays the colleague's polished 30-second pitch against their locked poster and the room hunts the vanished limitation — the unscored continuation of the Week-11 audit; 9–31 guided AI research-partner investigation: build your two pitch layers boundary-first with AI as a rehearsal partner — the 30-second hook and the 3-minute walk — then have AI flag every sentence that upgrades a claim or hides behind jargon, and test the short layer on an outsider's ear; 31–43 human verification + instructor formalization: you check each AI flag against your poster's claim boundary yourself (AI proposes, you verify), and the instructor formalizes the pitch architecture — hook, claim, evidence, boundary, invitation — and the compression-never-inflation rule; 43–50 decision & defense: log the delivery decisions and their verification in the ledger and write the Claim Ticket.",
        "hands_on_activity": "Build and deliver both pitch layers boundary-first, catch a partner's spoken claim-upgrades and jargon, and open the M11 rehearsal record.",
        "practice": "📝 nb12 practice: compress one evidence block into a single spoken sentence at two lengths without inflating the claim; rewrite one jargon sentence in plain words a stranger outside your field would follow.",
        "discussion_prompt": "Where in a classmate's pitch did a technical word do real work, and where was it a wall a visitor could not climb?",
        "project_connection": "M11 (defense-ready presentation package — poster edition v2) begins: the two pitch layers and the rehearsal record are its first components, all sized to the poster you locked at M10.",
        "milestone_developed": "M11 — Defense-ready presentation package, Book Milestone 10 v2 (kickoff — Monday exception)",
        "milestone_work_time": "15 min (scripting the two pitch layers)",
        "milestone_presentation_review": "partner delivery rounds with upgrade-and-jargon flagging",
        "student_prep": "Locked M10 poster internalized; headline claim sayable cold; claim boundary at hand.",
        "student_artifact": "Two drafted pitch layers with the boundary sentence marked + rehearsal-record opening + partner feedback",
        "exit_ticket": "Claim Ticket #32: my boundary sentence, exactly as I will say it out loud.",
        "homework_next_milestone": "Rehearse both layers aloud on someone outside the course and log what they missed. Lecture 2 builds the harder half of the defense — the five hardest fair questions, spoken uncertainty, and defend-or-concede.",
        "instructor_prep": "Rehearse the well-said / inflated pitch demo pair; stage the colleague pitch fragment (reused S10 artifact, key private); print the pitch-architecture templates; stage the M11 brief on Brightspace.",
        "risks_contingency": "Stage fright surfaces → the two-attempt structure makes everyone's first delivery officially a draft, and solo rehearsal is offered in office hours.",
    },
    # ------------------------------------------------------------------ M33
    {
        "meeting": 33, "date": "2026-11-11", "day": "Wed", "modality": "in-person",
        "unit": "Week 12 — Studio 10: Pitch and defense rehearsal",
        "title": "Pitch and defense II: the five hardest fair questions, spoken uncertainty, and defend-or-concede",
        "driving_question": "Can you say what your study cannot show — and answer the hardest fair question — without either bluffing or apologizing your findings away?",
        "secondary_questions": "What does an honest 'I don't know' contain? When do you defend and when do you concede? What goes on the unanswered-question agenda — and why is that agenda itself evidence?",
        "inquiry": "all positions (communication — Studio 10 revisit)",
        "srl_slot": "SRL slot 20 (randomly assigned at semester start)",
        "srl_focus": "Puzzle: a visitor asks the colleague 'so does it CAUSE it?' about a poster that only claims association — what is the one sentence that stays honest and still keeps the visitor interested?",
        "claim_permitted": "\"I don't know — but here is what I do know that bears on it, and here is how one would find out.\"",
        "claim_not_permitted": "Bluffing an answer you do not have — the one move that can destroy a presenter's credibility on the spot.",
        "rdss_reading": "Required EDR|AI: difficult-questions (first read); poster-criticism revisited. No new RDSS — bring your uncertainty line and your poster's claim boundary.",
        "cb_reading": "",
        "other_material": "nb12 student notebook (pitch and defense rehearsal) §3–4 (Colab); project/conference/uncertainty_limitations_protocol.md; project/conference/hard_questions_protocol.md; the colleague's poster artifact (unscored continuation); M11 brief on Brightspace",
        "provenance": "uncertainty_limitations_protocol.md + hard_questions_protocol.md + BOOK_STATIONS adapt-and-defend step 3 | S10 defense-rehearsal unit | ULN move + five-hardest-fair-questions bank + defend-or-concede record + unanswered-question agenda | adapted",
        "concepts": "the five hard-question types (method, alternative explanation, so-what, generalization, AI-use); the uncertainty-limitations-next-step (ULN) move; the honest-don't-know formula; defend-vs-concede judgment; the unanswered-question agenda (questions you cannot answer are your next studio's agenda); separating evidence from speculation",
        "python_r_dependency": "none",
        "dataset_simulation": "each student's own findings, spoken (+ the reused colleague S10 artifact)",
        "minute_dynamic": "0–7 SRL-led retrieval & challenge: the lead fires the causal question at the colleague's deliberately noncausal poster (the unscored continuation audit) and the room drafts the one sentence that stays honest and keeps the visitor interested; 7–30 intensive applied AI laboratory: build your five-hardest-fair-questions bank (one per type) with AI generating hostile-but-fair versions you did not think of, draft the ULN paragraph and the honest-don't-know answer for the worst one, mark each bank entry defend or concede, then deliver your ULN to two partners in rotation; 30–38 peer defense + adversarial questioning: sit a 3-minute hot seat drawn from your bank plus surprises while classmates probe, defending from the ledger or conceding cleanly; 38–42 SRL synthesis + instructor accuracy lock: the lead states the room's conclusion and its uncertainty, and the instructor corrects any claim that survived challenge but is wrong before it can enter a ledger; 42–50 transfer + ledger + Claim Ticket: write the unanswered-question agenda from what the hot seat exposed, log the AI-use decision and its verification, and write the ticket.",
        "hands_on_activity": "Survive a 3-minute hot seat on your five-question bank, delivering the ULN move, at least one honest 'I don't know', and at least one clean concession.",
        "practice": "📝 nb12 practice: convert three apology-spiral sentences into ULN form; for one causal question aimed at a noncausal finding, write the two-sentence honest reply.",
        "discussion_prompt": "Which classmate's hot-seat save impressed you most, and what exactly did they do to turn a stumble into a grounded answer?",
        "project_connection": "M11 completes its intellectual armor: the pitch layers plus the question bank, ULN statement, defend-or-concede record, and unanswered-question agenda are the package you carry to the Expo.",
        "milestone_developed": "M11 — Defense-ready presentation package, Book Milestone 10 v2 (dev; question bank + ULN + defend-or-concede record added)",
        "milestone_work_time": "15 min (bank-building + ULN drafting)",
        "milestone_presentation_review": "hot-seat rounds + ULN partner rounds with strength-not-apology scoring",
        "student_prep": "Pitch layers rehearsed from Lecture 1; findings and their limits at hand.",
        "student_artifact": "Five-question bank with defend-or-concede calls + ULN paragraph + unanswered-question agenda + hot-seat performance",
        "exit_ticket": "Claim Ticket #33: the question I most fear at the Expo, and my first sentence in reply.",
        "homework_next_milestone": "Finish M11 (both pitch layers + question bank + ULN statement + rehearsal record) for Friday's studio, where the mock poster symposium drills it and M11 is due that night.",
        "instructor_prep": "Surprise-question deck per project; three ULN demos including a null finding; the colleague poster fragment staged; timer for the hot seats.",
        "risks_contingency": "A hot seat runs hot emotionally → the instructor becomes questioner-of-record and slows the cadence; the drill's purpose, safety through practice, is named aloud.",
    },
    # ------------------------------------------------------------------ M34
    {
        "meeting": 34, "date": "2026-11-13", "day": "Fri", "modality": "in-person",
        "unit": "Week 12 — Studio 10: Pitch and defense rehearsal",
        "title": "Studio Friday — the mock poster symposium: the defense-ready package under live fire, M11 due",
        "driving_question": "Can your whole defense-ready package survive a room of strangers rotating through your poster — and is it ready to submit tonight?",
        "secondary_questions": "Does the 3-minute walk land inside time? Do the pitch layers, the ULN, and the question bank hold together under real traffic? What is still soft before the Expo (Tuesday)?",
        "inquiry": "all positions (communication — studio)",
        "srl_slot": "",
        "srl_focus": "",
        "claim_permitted": "\"Every claim I spoke at my station matched what my poster shows — I compressed, I never upgraded.\"",
        "claim_not_permitted": "\"I'll figure out the hard questions live at the Expo\" (the symposium is the rehearsal that makes that unnecessary).",
        "rdss_reading": "(no new reading — studio Friday; bring your poster, both pitch layers, and your question bank)",
        "cb_reading": "",
        "other_material": "week12 quiz; nb12 student notebook (pitch and defense rehearsal) §5 symposium + visitor role cards (Colab); project/conference/dress_rehearsal_protocol.md (station-round format); M11 due tonight; M12 brief on Brightspace",
        "provenance": "presentation_plan_protocol.md + hard_questions_protocol.md + symposium protocol | S10 defense-rehearsal unit | mock symposium station rounds with visitor role cards as the studio work block | adapted",
        "concepts": "the mock poster symposium; station-round format; the visitor role card (the five question types spread across visits); critical-but-kind feedback; delivery under live traffic; the rehearsal record as a graded artifact",
        "python_r_dependency": "none",
        "dataset_simulation": "each student's own poster and package",
        "minute_dynamic": "0–10 weekly topic quiz: five multiple-choice questions on the week's topic, answered solo on paper and handed in; 10–15 research stand-up: one line each — the claim your package is built to defend and the one delivery move you are still unsure of; 15–45 milestone kickoff + symposium rounds: the instructor presents the M12 conference-reflection-and-defense-revision brief (present at the Expo on Tuesday, evaluate at least three colleagues' posters, then revise the claim or its defense from what the public asks), then the MOCK SYMPOSIUM runs as the work block — stations go live in rotation, presenters deliver the 30-second and 3-minute layers while everyone else works the visitor role card across the five question types; 45–50 revise, ledger, submit + Claim Ticket: lock the package and rehearsal record, log the verification, submit M11 tonight, and write the ticket.",
        "hands_on_activity": "Stand your poster through live symposium rounds and visit others as a critical-but-kind stranger, working all five question types across your visits.",
        "practice": "📝 (embedded) the visitor role card: ask at least one method, one alternative-explanation, one so-what, one generalization, and one AI-use question across your visits.",
        "discussion_prompt": "Which classmate's station made you stay longer than you meant to, and what specifically kept you there?",
        "project_connection": "M11 submits tonight; the package you drilled today is exactly what you carry to the Expo (Tuesday), where M12 begins its public test.",
        "milestone_developed": "M11 — Defense-ready presentation package, Book Milestone 10 v2 (worked + due); M12 — Conference reflection and defense revision, Book Milestone 10 v3 (kickoff)",
        "milestone_work_time": "30 min studio block (symposium rounds + bank revision)",
        "milestone_presentation_review": "the mock symposium IS the presentation/review",
        "student_prep": "M11 drafted from the week: both pitch layers, question bank, ULN statement, rehearsal record.",
        "student_artifact": "Revised package + symposium performance + submitted M11",
        "exit_ticket": "Claim Ticket #34: the one delivery move I will do differently at the Expo because of today.",
        "homework_next_milestone": "Submit M11 tonight, 11:59 PM. Monday is the final dress rehearsal; the Expo follows on Tuesday — carry a coding sheet and capture every question you are asked.",
        "instructor_prep": "Room set as stations; visitor role cards printed; timer; M12 brief staged on Brightspace; confirm Expo logistics to communicate.",
        "risks_contingency": "A poster's print is not ready → present full-screen today and trigger the backup print run so it is in hand before the Expo (Tuesday).",
    },
    # ------------------------------------------------------------------ M35
    {
        "meeting": 35, "date": "2026-11-16", "day": "Mon", "modality": "in-person",
        "unit": "Week 13 — Studio 10: Public test at the Expo + reflection",
        "title": "Public test week: the full dress rehearsal and the Expo capture plan",
        "driving_question": "The Expo is tomorrow. Is every piece — poster, pitch layers, question bank, logistics, and the coding sheet you will carry — actually ready for the public test?",
        "secondary_questions": "Does the 3-minute walk land inside time? What must be locked before tomorrow: location, call time, materials, backup file? What will you capture at the Expo so Friday's reflection has real data — and how will you tell criticism of your evidence from criticism of your presentation?",
        "inquiry": "all positions (communication — Studio 10 public test)",
        "srl_slot": "SRL slot 21 (randomly assigned at semester start)",
        "srl_focus": "Puzzle: the colleague's poster took a public criticism that sounds devastating — read it twice: does it touch the evidence, or only the presentation? What would each verdict change?",
        "claim_permitted": "\"Readiness audited: rehearsed twice inside time, question bank drilled, logistics confirmed, coding sheet in hand and pre-tagged.\"",
        "claim_not_permitted": "\"I'll wing it tomorrow\" (rehearsal is the difference between nerves and panic); \"that criticism destroyed the project\" before sorting whether it touched the evidence at all.",
        "rdss_reading": "Revisit-only week (no new lesson): research-posters, poster-criticism, research-pitches, difficult-questions — bring the pitch layers and the bank cold.",
        "cb_reading": "",
        "other_material": "nb13 student notebook (public test + reflection) §1 readiness audit + visitor role card (Colab); project/conference/dress_rehearsal_protocol.md; project/conference/conference_reflection_protocol.md (the capture method); audience-coding sheet; the colleague's criticized poster (unscored continuation); M12 brief on Brightspace",
        "provenance": "dress_rehearsal_protocol.md + conference_reflection_protocol.md capture method + colleague continuation | S10 public-test unit | full-dress station simulation + readiness audit + Expo capture plan + evidence-vs-presentation sort | adapted",
        "concepts": "full-dress simulation; readiness auditing; the visitor role card; capturing audience questions as data (the coding sheet, pre-tagged claims-vs-communication); the evidence-vs-presentation sort; logistics discipline; professional conference interaction",
        "python_r_dependency": "none",
        "dataset_simulation": "each student's own complete conference package (+ the reused colleague S10 artifact)",
        "minute_dynamic": "0–9 SRL-led research puzzle: the lead reads the persuasive-sounding public criticism of the colleague's poster (the unscored continuation beat) and the room sorts it — evidence or presentation — naming what each verdict would change in the claim or its defense; 9–31 guided full dress-run rotation: two station rounds where posters go live in turn while everyone else plus the instructor rotate as conference visitors, exercising the 30-second layer, the 3-minute walk, hard questions from the bank, and the ULN moment under time; 31–43 human verification + instructor formalization: sign the readiness audit (rehearsed / drilled / logistics / materials), and the instructor formalizes the Expo capture plan — the coding sheet each presenter carries to log every question in the moment, pre-tagged claims-vs-communication; 43–50 decision & defense: confirm call time and logistics, log the readiness decision in the ledger, and write the Claim Ticket.",
        "hands_on_activity": "Stand your poster through a full dress-run round, visit others with the five-type role card, sort one public criticism as evidence-or-presentation, and sign your readiness audit.",
        "practice": "📝 nb13 practice: fill the readiness audit honestly (an unchecked box is tonight's task, not a failure); write the one-line coding-sheet format you will use tomorrow, with its claims-vs-communication tag.",
        "discussion_prompt": "One thing you saw a classmate do in the dress run that you are stealing for the Expo tomorrow?",
        "project_connection": "M12 begins its public test: the readiness audit is the last gate before the Expo (Tuesday), and the pre-tagged coding sheet you leave with captures the audience data M12's reflection and defense revision need.",
        "milestone_developed": "M12 — Conference reflection and defense revision, Book Milestone 10 v3 (dev; readiness audit + Expo capture plan)",
        "milestone_work_time": "22 min (full dress-run rotation) + 4 min (readiness audit)",
        "milestone_presentation_review": "the full dress-run rotation IS the presentation/review",
        "student_prep": "M11 submitted; poster ready (printed or presentable); both pitch layers and question bank cold.",
        "student_artifact": "Signed readiness audit + dress-run performance + prepared pre-tagged coding sheet",
        "exit_ticket": "Claim Ticket #35: the one thing I will do differently at the Expo because of today's dress run.",
        "homework_next_milestone": "The Expo is tomorrow (Tuesday): present, and evaluate at least three colleagues' posters on the structured criticism forms. Carry your coding sheet and capture every question you are asked. There is no class Wednesday; Friday's studio is the structured reflection.",
        "instructor_prep": "Room set as stations; visitor role cards; audience-coding sheets and structured poster-criticism forms printed; the colleague criticism fragment staged (key private); confirm and communicate the Expo call time; M12 brief staged.",
        "risks_contingency": "A poster's print failed → present full-screen in the dress run today and resolve the emergency print before the Expo (Tuesday); the backup plan is pre-arranged.",
    },
    # ------------------------------------------------------------------ M36
    {
        "meeting": 36, "date": "2026-11-20", "day": "Fri", "modality": "in-person",
        "unit": "Week 13 — Studio 10: Public test at the Expo + reflection",
        "title": "Studio Friday — conference reflection: Expo questions become data, the defense revises, M12 due",
        "driving_question": "What did strangers' questions at the Expo reveal about your project that friends' questions never could — and which revision does that evidence license: the claim, or its defense?",
        "secondary_questions": "Which questions recurred? Was the most repeated one about your claims or your clarity? Which revision does the tally license — the claim, the defense, or neither? How honest are your self-evaluation and your portfolio of the three posters you evaluated?",
        "inquiry": "all positions (reflection, applied to your own project)",
        "srl_slot": "",
        "srl_focus": "",
        "claim_permitted": "\"The most repeated question at my poster was about my [claims / communication] — the count says so, not my mood — and here is the revision it licenses.\"",
        "claim_not_permitted": "\"People liked it, so my findings held up\" (applause measures your communication, not the truth of your claims).",
        "rdss_reading": "(no new reading — studio Friday; bring your Expo coding sheet and your three completed poster-criticism forms)",
        "cb_reading": "",
        "other_material": "week13 quiz; nb13 student notebook (public test + reflection) §2–3 reflection tally (Colab); project/conference/conference_reflection_protocol.md; M12 due tonight; M13 brief + the anonymized replication packages on Brightspace",
        "provenance": "conference_reflection_protocol.md + crosswalk M12 (adapt-and-defend revisit + release-next-cycle practice) | S10 reflection unit | audience-question coding + defense revision + criticism portfolio + M13 exchange kickoff | adapted",
        "concepts": "feedback as data; the claims-vs-communication split; recurring-question analysis; the licensed revision (claim vs defense vs neither); self-evaluation; the poster-criticism portfolio (three posters, structured); the release-practice note; the anonymized replication-package exchange",
        "python_r_dependency": "none (a provided tally cell if wanted)",
        "dataset_simulation": "each student's collected Expo questions + the three posters they evaluated",
        "minute_dynamic": "0–10 weekly topic quiz: five multiple-choice questions on the week's topic, answered solo on paper and handed in; 10–15 research stand-up: the single most surprising moment at your poster, in one line each; 15–45 milestone kickoff + reflection sprint: the instructor kicks off M13 by handing out the ANONYMIZED replication packages for the Thanksgiving async exchange (with the privacy and no-author-help rules), then the reflection runs as the work block — code every Expo question into the tally (type, target: claims vs communication, recurrence), find your pattern, decide the revision the evidence licenses to the claim or its defense (poster edition v3, publicly tested), assemble the criticism portfolio from the three posters you evaluated, and jot the release-practice note on what the public test taught you about release readiness; 45–50 revise, ledger, submit + Claim Ticket: write the honest reflection paragraph, submit M12 tonight, and write the ticket.",
        "hands_on_activity": "Code your Expo questions like data, find the recurring pattern, decide the licensed revision to your claim or its defense, and assemble your three-poster criticism portfolio.",
        "practice": "📝 nb13 practice: classify six received questions as claims-signal, communication-signal, or noise; name the one that recurred and the revision (if any) its repetition licenses.",
        "discussion_prompt": "What question did you get at the Expo that none of our hot seats predicted, and why did we miss it?",
        "project_connection": "M12 submits tonight (reflection + defense revision + portfolio, with the Expo presentation graded); M13 launches now — over break you cold-run and red-team a classmate's anonymized package.",
        "milestone_developed": "M12 — Conference reflection and defense revision, Book Milestone 10 v3 (worked + due); M13 — Replication and red-team report, Book Milestone 11 practice (kickoff; anonymized packages exchanged)",
        "milestone_work_time": "30 min studio block (coding + revision decision + portfolio assembly)",
        "milestone_presentation_review": "story round + partner tally-pattern read",
        "student_prep": "Expo presented; every question captured on the coding sheet; three poster-criticism forms completed at the Expo.",
        "student_artifact": "Coded question tally + licensed-revision decision + criticism portfolio + release-practice note (submitted as M12) + assigned replication package",
        "exit_ticket": "Claim Ticket #36: the most repeated question at my poster, and whether it challenged my evidence or my clarity.",
        "homework_next_milestone": "Submit M12 tonight, 11:59 PM. Monday is asynchronous (Thanksgiving week): the peer cold-run and red-team module on the anonymized package assigned today; the report is due Sunday night.",
        "instructor_prep": "Own Expo observation notes per student; tally template checked; anonymize, clear, and assign the replication packages; M13 brief staged on Brightspace.",
        "risks_contingency": "A student missed the Expo for a documented reason → the make-up presentation path runs and the reflection uses dress-run data meanwhile. Post-conference deflation → the story round names it as every researcher's post-conference dip.",
    },
    # ------------------------------------------------------------------ M37
    {
        "meeting": 37, "date": "2026-11-23", "day": "Mon", "modality": "async-online",
        "unit": "Week 14 — Studio 11: Async peer cold run + red-team",
        "title": "ASYNC — Peer cold run and red-team: rebuild a stranger's findings, then hand back the repairs",
        "driving_question": "Hand yourself a classmate's package: can you rebuild the headline number and its uncertainty from the materials alone — and where does it quietly not hold?",
        "secondary_questions": "Does the package run in a recreated environment? Can you trace the data and code lineage? Do the claims match what the computation actually shows? Which questions did you have to ask the author — and why is each one a missing line of documentation?",
        "inquiry": "all positions (Studio 11 practice — cold run + red-team of a peer's project)",
        "srl_slot": "",
        "srl_focus": "",
        "claim_permitted": "\"I cold-ran the package without the author's help, reproduced the headline number and its uncertainty, and here are the three weaknesses I ranked by how much they threaten the claim.\"",
        "claim_not_permitted": "\"It ran, so it's fine\" (a clean run is not agreement between claims and computation) — and \"independently reproduced\" said of any run the author assisted.",
        "rdss_reading": "Required EDR|AI: replication-reproduction (first read) — the module is self-contained; this is Studio 11 PRACTICE, preceding your own package's version 1.",
        "cb_reading": "",
        "other_material": "nb14 student notebook — fully self-contained async module (Colab); project/final_dossier/reproducibility_audit_protocol.md; the assigned anonymized replication package + the shared calibration package; GenAI Studio 'Reproducibility Auditor' role (genai.rcac.purdue.edu); async discussion board; M13 due Sunday night; M14 brief posted on Brightspace",
        "provenance": "reproducibility_audit_protocol.md + GenAI Studio Reproducibility Auditor touchpoint + crosswalk M13 (reproduce-and-package practice) | S11 practice unit | privacy intake + cold reproduction + red-team + repair handoff | adapted",
        "concepts": "the peer cold run (practice, not checkpoint — precedes your package's v1); the privacy/intake check; environment recreation; restart-and-run-all; data and code lineage; reproducing the uncertainty, not only the point estimate; reproduction vs independent verification; hidden assumptions and AI-related weaknesses; the undocumented-question log; the repair handoff (triaged by threat to the claim)",
        "python_r_dependency": "pandas/numpy (execute the peer's package end to end); scikit-learn if the package uses it",
        "dataset_simulation": "a classmate's anonymized replication package (+ the shared calibration package as the worked example)",
        "minute_dynamic": "ASYNC (~50 min self-paced, no live meeting): 0–6 module orientation + privacy/intake check — confirm the assigned package is cleared and identity-stripped, then skim the shared calibration package as the worked example of what a good handoff looks like; 6–20 cold reproduction — recreate the environment from its record, restart-and-run-all, trace the data and code lineage, and try to rebuild the headline number AND its uncertainty from the materials alone, logging every break and every question you would have to ask the author; 20–32 red-team audit — check the claims against what the computation actually shows, probe one alternative specification, and surface the hidden assumptions and AI-related weaknesses behind the illusion of completeness; 32–42 REQUIRED GenAI Studio pass — run the package summary through the 'Reproducibility Auditor' role, then verify its findings yourself and log the pass in your AI Research Ledger (the role proposes, you confirm — and a run the author assisted is never 'independent'); 42–48 write the repair handoff — prioritized recommendations ranked by threat to the claim, not by ease of fixing, plus the undocumented-question log the author will need next week; 48–50 (async board) post the single weakness you ranked most threatening and reply to one classmate.",
        "hands_on_activity": "Cold-run a classmate's anonymized package without author help, reproduce the headline number and its uncertainty, red-team it, and write the repair handoff the author will work from.",
        "practice": "📝 nb14 practice: for one sample package, list three ways a clean run can still hide a broken claim, then rank them by threat.",
        "discussion_prompt": "(async board) The weakness you ranked most threatening in your assigned package: post it, and reply to one classmate with a check that would confirm or dissolve theirs.",
        "project_connection": "M13 is Studio 11 practice on a peer's work — the cold run your own package faces next week, when M14 turns the repair handoff you WRITE into the repair handoff you RECEIVE.",
        "milestone_developed": "M13 — Replication and red-team report, Book Milestone 11 practice — peer cold-run preceding v1 (worked + due Sunday night); M14 — Research note v1 and reusable package, Book Milestone 9 v2 + Book Milestone 11 v1 (kickoff; brief posted with the module)",
        "milestone_work_time": "the whole module is milestone work (~50 min self-paced)",
        "milestone_presentation_review": "async board: most-threatening-weakness post + one reply",
        "student_prep": "M12 submitted; the assigned anonymized package downloaded; GenAI Studio access confirmed.",
        "student_artifact": "Cold-run reproduction log (number + uncertainty) + red-team audit + GenAI Studio Auditor pass (verified, ledgered) + repair handoff with undocumented-question log",
        "exit_ticket": "(embedded) Claim Ticket #37: the weakness that most threatens my assigned package's headline claim, and the check that would settle it.",
        "homework_next_milestone": "Happy Thanksgiving. Submit M13 by Sunday night, 11:59 PM. Class resumes in person next Monday with the note-revision unit (M14, posted today): your Expo tally and the handoff you receive become the evidence for note v1.",
        "instructor_prep": "Anonymize and assign packages so no one audits their own; verify each package runs unattended; confirm the GenAI Studio Reproducibility Auditor role is live; stage the shared calibration package; seed the discussion board; holiday-proof the Sunday deadline in Brightspace.",
        "risks_contingency": "Holiday-week attrition → the module is doable in one sitting, the deadline is Sunday, and a mid-week progress-checkpoint reminder goes out. A package will not run at all → that failure, documented with the exact break, IS valid cold-run evidence and belongs in the handoff.",
    },
    # ------------------------------------------------------------------ M38
    {
        "meeting": 38, "date": "2026-11-30", "day": "Mon", "modality": "in-person",
        "unit": "Week 15 — Studios 9 + 11: Research note v1 + reusable package",
        "title": "Note v1 I: adjudicate the public test and the cold run, then revise the bounded note",
        "driving_question": "The public asked, and a stranger ran your code. Which criticisms change your claim, which change only its defense — and what does the revised note now say?",
        "secondary_questions": "How do you adjudicate feedback without capitulating to it? What goes in the note change log? What does claim-evidence table v2 add? Why do the course's 'research note v1' and the book's Milestone 9 'version 2' name the same artifact?",
        "inquiry": "all positions (communication — Studio 9 revisit)",
        "srl_slot": "SRL slot 22 (randomly assigned at semester start)",
        "srl_focus": "Puzzle: a public criticism sounds serious — repeated, confident, specific — yet changes nothing the claim licenses. What is the honest response that is neither capitulation nor dismissal?",
        "claim_permitted": "\"I adjudicated every captured criticism and cold-run finding: this one changed my claim, this one changed my defense, this one changed nothing — and my change log says why.\"",
        "claim_not_permitted": "\"I addressed all feedback\" meaning every criticism produced a revision (adjudication is judgment, not compliance — and un-adjudicated criticism is not addressed either).",
        "rdss_reading": "Revisits for the note revision: results-to-claims, claim-evidence-tables, poster-to-note, ai-disclosure. No new lesson today — the evidence for revision is your Expo tally and the cold-run handoff you received.",
        "cb_reading": "",
        "other_material": "nb15 student notebook (note revision + reusable package) §1–2 (Colab); project/final_dossier/research_brief_template.md; your M12 tally + the M13 repair handoff you received; M14 brief on Brightspace",
        "provenance": "crosswalk M14 (write-bound-disclose revisit) + conference_reflection_protocol.md outputs | S9 revisit unit | feedback adjudication + note change log + claim-evidence table v2 + naming bridge | fresh",
        "concepts": "feedback adjudication (accept, rebut, or bound); the note change log; claim-evidence table v2; the bounded-note revision; the naming bridge (course research note v1 = Book Milestone 9 version 2, the post-conference bounded note); criticism as evidence about the claim vs about its communication",
        "python_r_dependency": "none (verified outputs consulted, not re-run)",
        "dataset_simulation": "each student's own Expo tally, received cold-run handoff, and note v0",
        "minute_dynamic": "0–9 SRL-led research puzzle: the lead reads one serious-sounding public criticism that does not change the claim license and the room drafts the honest response that neither capitulates nor dismisses; 9–31 guided AI research-partner investigation: adjudicate your own captured feedback with AI as devil's advocate — for each Expo question and each cold-run finding, decide accept, rebut, or bound, then have AI argue the other side of your two hardest calls before you commit; 31–43 human verification + instructor formalization: you verify that every accepted change traces to evidence and every rebuttal is argued, not felt (AI proposes, you decide), and the instructor formalizes the change log, claim-evidence table v2, and the naming bridge — the note you revise to course v1 is the book's Milestone 9 version 2; 43–50 decision & defense: log the adjudication decisions and their verification in the ledger and write the Claim Ticket.",
        "hands_on_activity": "Adjudicate every captured criticism and cold-run finding into accept / rebut / bound, then open the note change log and claim-evidence table v2.",
        "practice": "📝 nb15 practice: classify four criticisms as claim-changing, defense-changing, or non-binding, and write the change-log line for one of each.",
        "discussion_prompt": "Which criticism did a classmate rebut that you would have accepted, and whose adjudication had the better evidence?",
        "project_connection": "M14's note half advances: the adjudication table and change log become research note v1 (Book Milestone 9 v2), due at Friday's studio.",
        "milestone_developed": "M14 — Research note v1 and reusable package, Book Milestone 9 v2 (dev; feedback adjudication + note change log)",
        "milestone_work_time": "15 min (adjudication + change-log drafting)",
        "milestone_presentation_review": "none (lecture day; the adjudication runs inside the investigation block)",
        "student_prep": "M13 submitted; Expo tally and the repair handoff you received in hand; note v0 open.",
        "student_artifact": "Adjudication table (accept / rebut / bound) + note change log opened + claim-evidence table v2 started",
        "exit_ticket": "Claim Ticket #38: the one criticism that changed my claim — or the hardest one I rebutted, and on what evidence.",
        "homework_next_milestone": "Extend the revision toward note v1. Lecture 2 turns to the package: repairing what the cold run exposed and assembling reusable package v1.",
        "instructor_prep": "Route each student's received repair handoff before class; a worked accept/rebut/bound example triple; M14 brief staged on Brightspace.",
        "risks_contingency": "A student received a harsh or thin cold-run report → the adjudication frame treats both identically (findings are evidence, not verdicts) and the instructor moderates calibration; a report that arrived late → adjudicate the Expo tally today and the handoff at Wednesday's lab.",
    },
    # ------------------------------------------------------------------ M39
    {
        "meeting": 39, "date": "2026-12-02", "day": "Wed", "modality": "in-person",
        "unit": "Week 15 — Studios 9 + 11: Research note v1 + reusable package",
        "title": "Package v1: repair what the cold run exposed and assemble the reusable package",
        "driving_question": "A stranger ran your code and had to ask you questions. Can you repair the package so the next stranger never has to?",
        "secondary_questions": "What belongs in the README and the data-access recipe? What makes an environment record sufficient? Which licence and permissions travel with the package? What does the second clean run prove that the first could not?",
        "inquiry": "all positions (reproducibility — Studio 11 checkpoint)",
        "srl_slot": "SRL slot 23 (randomly assigned at semester start)",
        "srl_focus": "Puzzle: the colleague's package ran for its cold runner — after one question to the author. One question. Why does that single question demote the run, and which missing line caused it?",
        "claim_permitted": "\"My package carries data or its access recipe, code, environment, README, and licence — and a second clean run passed with no author question.\"",
        "claim_not_permitted": "\"It runs for me\" — or a package whose cold run needed the author in the room (a run the author assisted is never independent).",
        "rdss_reading": "Required EDR|AI: research-packages (first read); replication-reproduction revisited. Bring the repair handoff you received.",
        "cb_reading": "",
        "other_material": "nb15 student notebook (note revision + reusable package) §3–4 (Colab); project/final_dossier/reproducibility_audit_protocol.md (package anatomy); the colleague's cold-run fragment (unscored continuation); M14 due Friday; M15 brief on Brightspace",
        "provenance": "reproducibility_audit_protocol.md package anatomy + crosswalk M14 (reproduce-and-package checkpoint) + colleague continuation | S11 checkpoint unit | cold-run repair + package assembly + second clean run | adapted",
        "concepts": "the reusable package (data or its access recipe, code, environment, README, licence); repair as documentation (every author question is a missing line); the second clean run; permissions set what can be shared; solo-proxy honesty ('external cold run pending'); package v1 = Book Milestone 11 version 1",
        "python_r_dependency": "own package repair + restart-and-run-all (the second clean run)",
        "dataset_simulation": "each student's own package and received handoff (+ the reused colleague S11 artifact)",
        "minute_dynamic": "0–7 SRL-led retrieval & challenge: the lead shows the colleague's cold run that needed exactly one author question (the unscored continuation beat) and the room finds the missing documentation line that caused it; 7–30 intensive applied AI laboratory: repair your own package from the handoff you received — fix what the cold run exposed, write the README and access recipe with AI drafting and you verifying every instruction against the actual files, complete the environment record and the licence/permissions line — then run the second clean run with restart-and-run-all; 30–38 peer defense + adversarial questioning: a partner probes your package choices — why this licence, why this access recipe, what a stranger still cannot do without you; 38–42 SRL synthesis + instructor accuracy lock: the lead states the room's conclusion and its uncertainty, and the instructor corrects any claim that survived challenge but is wrong before it can enter a ledger; 42–50 transfer + ledger + Claim Ticket: log the repair decisions and the second-run result, and write the ticket.",
        "hands_on_activity": "Repair your package from the cold-run handoff, assemble the five package components, and pass a second clean run.",
        "practice": "📝 nb15 practice: convert three author-questions from a cold-run log into the exact README lines that would have prevented them.",
        "discussion_prompt": "Which README line in your package did you only write because a stranger stumbled, and why did you not see the gap yourself?",
        "project_connection": "M14's package half advances: reusable package v1 (Book Milestone 11 v1) joins note v1 for Friday's studio, where M14 is due.",
        "milestone_developed": "M14 — Research note v1 and reusable package, Book Milestone 11 v1 (dev; cold-run repair + package assembly)",
        "milestone_work_time": "15 min (repair + assembly) + the second clean run",
        "milestone_presentation_review": "partner package-probe rounds",
        "student_prep": "Adjudication and change log from Lecture 1; the repair handoff you received in hand; project notebook runnable.",
        "student_artifact": "Repaired package (data or access recipe, code, environment, README, licence) + second-clean-run log",
        "exit_ticket": "Claim Ticket #39: the documentation line I added that I am most sure the next stranger needs.",
        "homework_next_milestone": "Finish note v1 and package v1 for Friday's studio, where M14 is due and M15 (release audit, final chapter, and AI-management portfolio) kicks off.",
        "instructor_prep": "Stage the colleague cold-run fragment (reused S11 artifact, key private); the package-anatomy checklist; M15 brief staged on Brightspace.",
        "risks_contingency": "The second clean run fails in class → the break is logged as package evidence and the fix routes to Friday's studio consults; an access-restricted dataset → the access recipe replaces the data and says exactly who can obtain it and how.",
    },
    # ------------------------------------------------------------------ M40
    {
        "meeting": 40, "date": "2026-12-04", "day": "Fri", "modality": "in-person",
        "unit": "Week 15 — Studios 9 + 11: Research note v1 + reusable package",
        "title": "Studio Friday — table read and package check: note v1 + package v1, M14 due, M15 launched",
        "driving_question": "Does the revised note do justice to the public test — and is the package one a stranger could run with no one to ask?",
        "secondary_questions": "Where does the note still overclaim, underexplain, or lose the reader? Does the package pass a partner's cold check? What does M15 — the release audit, final chapter, and AI-management portfolio — ask of you next week?",
        "inquiry": "all positions (communication + reproducibility — studio)",
        "srl_slot": "",
        "srl_focus": "",
        "claim_permitted": "\"Every claim in note v1 traces to my ledger, and my package ran for a partner who had no one to ask.\"",
        "claim_not_permitted": "\"It runs for me\" offered as reproducibility no stranger ever exercised.",
        "rdss_reading": "(no new reading — studio Friday; bring your revised note and assembled package)",
        "cb_reading": "",
        "other_material": "week15 quiz; nb15 student notebook (note revision + reusable package) §5 table read (Colab); project/final_dossier/research_brief_template.md (the table-read margin-note procedure); M14 due tonight; M15 brief on Brightspace",
        "provenance": "research_brief_template.md table-read procedure + reproducibility_audit_protocol.md | S9+S11 closing unit | note table read + partner cold check as the studio work block + M15 kickoff + defense-order draw | adapted",
        "concepts": "the table read with two-question margin notes; ledger-traceable prose; the partner cold check on the package; avoiding inflated contributions; the defense-order draw",
        "python_r_dependency": "partner opens your package cold (README first, restart-and-run-all)",
        "dataset_simulation": "each student's own note v1 and package v1",
        "minute_dynamic": "0–10 weekly topic quiz: five multiple-choice questions on the week's topic, answered solo on paper and handed in; 10–15 research stand-up: your note's sharpest revision and the claim you are least sure survives, one line each; 15–45 milestone kickoff + table read: the instructor presents the M15 brief (release audit, final chapter, and AI-management portfolio — TERMINAL, due next Friday) and draws the Evidence-Defense order for next week, then the TABLE READ runs as the work block — each note passes left, three minutes per read, a two-question margin note (sharpest revision, weakest claim) on each, full rotation — while package pairs run a quick cold check (open the README, follow it, note the first question you would have to ask the author); 45–50 revise, ledger, submit + Claim Ticket: revise from the margin notes, submit M14 tonight, and write the ticket.",
        "hands_on_activity": "Run the full-rotation table read with margin notes, and cold-check a partner's package before signing that it ran with no author question.",
        "practice": "📝 nb15 practice: for one sample note sentence, trace it to a ledger row or catch that it cannot be traced.",
        "discussion_prompt": "Which classmate's note taught you a compression or framing move, and what exactly was it?",
        "project_connection": "M14 submits tonight; note v1 and package v1 become the body the release audit interrogates next week, and the final chapter (M15) expands.",
        "milestone_developed": "M14 — Research note v1 and reusable package, Book Milestone 9 v2 + Book Milestone 11 v1 (worked + due); M15 — Release audit, final chapter, and AI-management portfolio, Book Milestone 12 v1 (kickoff — TERMINAL, no revision window)",
        "milestone_work_time": "30 min studio block (table read + partner cold check + revision)",
        "milestone_presentation_review": "table-read margin notes (all-read-all) + partner cold check",
        "student_prep": "Note v1 polished; package v1 assembled with its second-clean-run log.",
        "student_artifact": "Margin-annotated note + partner cold-check log + revision + submitted M14",
        "exit_ticket": "Claim Ticket #40: the claim a margin note flagged as weakest, and how I resized it.",
        "homework_next_milestone": "Submit M14 tonight, 11:59 PM. Monday opens the terminal week: is the package still reproducible, does the release audit pass, and is the dossier complete?",
        "instructor_prep": "Margin-note slips; an annotated exemplar note; defense order-draw slips; confirm partner cold-check pairings; M15 brief staged on Brightspace.",
        "risks_contingency": "A package will not run for the partner → the exact break is logged as reproducibility evidence and fixed in a consult; the note table read proceeds regardless.",
    },
    # ------------------------------------------------------------------ M41
    {
        "meeting": 41, "date": "2026-12-07", "day": "Mon", "modality": "in-person",
        "unit": "Week 16 — Studio 12: Release and direct the next cycle",
        "title": "Release I: the stale-run test, the five-part release audit, and the dossier",
        "driving_question": "One sentence changed since your last cold run. Is that run now stale — and would your work pass the audit that decides whether it may leave your hands?",
        "secondary_questions": "What makes a cold run stale? What do the five audit parts check — permissions, disclosure, reproducibility, claim boundaries, promises to participants? What belongs in the final dossier, and what is still missing from yours?",
        "inquiry": "all positions (release — Studio 12)",
        "srl_slot": "SRL slot 24 (randomly assigned at semester start)",
        "srl_focus": "Puzzle: one sentence in the note changed after the last cold run — a wording fix, the author says. Is the run stale? Find the rule that decides, and what being wrong would cost.",
        "claim_permitted": "\"Nothing moved since my last cold run — or something did, and I reran before calling the work release-ready.\"",
        "claim_not_permitted": "\"The package passed its cold run\" said of a package that changed since that run (a stale run verifies the past, not the release).",
        "rdss_reading": "Required EDR|AI: final-portfolio and managing-ai-agents (first read). Bring the M14 package and every ledger you have kept.",
        "cb_reading": "",
        "other_material": "nb16 student notebook (release and next cycle) §1–2 release audit + dossier manifest (Colab); project/final_dossier/evidence_defense_protocol.md; the course AI Research Ledger and claim ledger; M15 brief on Brightspace",
        "provenance": "BOOK_STATIONS release-next-cycle steps 1–3 + crosswalk M15 | S12 release unit | stale-run rule + five-part release audit + dossier manifest | fresh",
        "concepts": "the stale-run rule (any change to the package — a number, a claim, the data, the code, the environment record, or the instructions — makes the last cold run stale); the five-part release audit (permissions, disclosure, reproducibility, claim boundaries, promises to participants); the dossier manifest (contract versions, evidence registry, permissions, measurement, analysis and claim ledgers, AI ledger, artifacts, package, revision history); release as a decision, not a deadline",
        "python_r_dependency": "own package rerun (restart-and-run-all) if the stale-run test demands it",
        "dataset_simulation": "each student's own package, ledgers, and dossier components",
        "minute_dynamic": "0–9 SRL-led research puzzle: the lead presents the one-changed-sentence case and the room derives the stale-run rule — which kinds of change invalidate a cold run, what rerunning costs, and what releasing stale would cost instead; 9–31 guided AI research-partner investigation: run the stale-run test on your own package (list every change since the Studio-11 cold run, then decide rerun-or-stand), and walk the five-part release audit with AI as checklist interrogator — permissions, disclosure, reproducibility, claim boundaries, promises to participants — collecting every gap it flags for YOUR verification; 31–43 human verification + instructor formalization: you confirm or dismiss each flagged gap against your own records (AI proposes, you verify), and the instructor formalizes the stale-run rule, the five audit parts, and the dossier manifest; 43–50 decision & defense: record the rerun decision and audit result in the ledger and write the Claim Ticket.",
        "hands_on_activity": "Run the stale-run test and the five-part release audit on your own package, and open the dossier manifest with every component present or named as missing.",
        "practice": "📝 nb16 practice: for five changes to a project (a wording fix, a new figure, a data correction, a seed change, a README edit), rule each stale or not-stale and say why.",
        "discussion_prompt": "Which audit part would your project fail today, and what is the smallest honest repair before Friday?",
        "project_connection": "M15 begins in earnest: the rerun decision, the audit record, and the dossier manifest are its first components; the final chapter and AI-management portfolio build on them through the week.",
        "milestone_developed": "M15 — Release audit, final chapter, and AI-management portfolio, Book Milestone 12 v1 (dev; stale-run test + release audit + dossier manifest — TERMINAL Friday)",
        "milestone_work_time": "22 min (stale-run test + audit walk)",
        "milestone_presentation_review": "none (lecture day; the audit runs inside the investigation block)",
        "student_prep": "M14 submitted; package, note, and all ledgers at hand; defense order known.",
        "student_artifact": "Stale-run decision + five-part audit record + dossier manifest v0",
        "exit_ticket": "Claim Ticket #41: my stale-run verdict, and the audit part I am least sure my project passes.",
        "homework_next_milestone": "Close the audit gaps and extend the final chapter. Lecture 2 confronts your AI helpers directly — conflicting outputs, false consensus, the stopping rule — and stages the first defenses.",
        "instructor_prep": "The one-changed-sentence demo case; audit checklists printed; the dossier-manifest template; confirm the defense order is posted.",
        "risks_contingency": "A stale-run test demands a rerun that cannot finish in class → the rerun is queued as tonight's task and the audit proceeds on the rest; a failed audit part is a finding — the repair, not concealment, is the deliverable.",
    },
    # ------------------------------------------------------------------ M42
    {
        "meeting": 42, "date": "2026-12-09", "day": "Wed", "modality": "in-person",
        "unit": "Week 16 — Studio 12: Release and direct the next cycle",
        "title": "Release II: conflicting agents, false consensus, the stopping rule — and the first defenses",
        "driving_question": "Four AI reviewers agree your chapter is ready. Is that four confirmations or one blind spot shared four ways — and when do you overrule them all and stop?",
        "secondary_questions": "How do you wire worker–critic roles without inheriting their shared blind spots? What makes agreement false consensus (correlated errors)? What is a stopping rule stated as a decision — and which decisions should never be automated at all?",
        "inquiry": "all positions (synthesis — AI-workflow management + defense)",
        "srl_slot": "SRL slot 25 (randomly assigned at semester start)",
        "srl_focus": "Puzzle: four agreeing agents praise the same chapter — and share the same blind spot. What structural fact about how they were built predicts they fail together, and what check exposes it?",
        "claim_permitted": "\"Where my AI roles conflicted, I made the call and can defend it; where they agreed, I checked the agreement was not one error repeated — and my stopping rule is stated as a decision.\"",
        "claim_not_permitted": "\"All the agents agreed, so it must be right\" (correlated errors manufacture false consensus, and consensus is not verification).",
        "rdss_reading": "Required EDR|AI: conflicting-agents (first read); managing-ai-agents continues. Bring your chapter draft and your three weakest claim-ledger rows.",
        "cb_reading": "",
        "other_material": "nb16 student notebook (release and next cycle) §3–4 (Colab); GenAI Studio sequential-workflow roles (genai.rcac.purdue.edu, Colab API or UI); project/final_dossier/evidence_defense_protocol.md (defense format + cross-examination norms); the drawn defense order; M15 due Friday",
        "provenance": "GenAI Studio sequential-workflow + evidence_defense_protocol.md + BOOK_STATIONS release-next-cycle steps 4–5 | S12 release unit | worker–critic wiring + false-consensus check + stopping rule + defense staging (first defenses) | adapted",
        "concepts": "worker–critic wiring; agent specialization and its blind-spot cost; reconciling conflicting outputs; correlated errors and false consensus; escalation to human judgment and the override on record; the stopping rule stated as a decision; decisions that should never be automated; the next-study agenda; the Evidence Defense format (compressed staging + cross-examination)",
        "python_r_dependency": "GenAI Studio roles via the API or UI + the provided seeded reviewer-simulation cells (SEED = 464)",
        "dataset_simulation": "each student's own chapter draft + a seeded correlated-vs-diverse reviewer simulation (SEED = 464)",
        "minute_dynamic": "0–7 SRL-led retrieval & challenge: the lead shows four agreeing AI reviews of one chapter and the room hunts the shared blind spot, then predicts what a differently built reviewer would catch; 7–30 intensive applied AI laboratory: wire your worker–critic roles against your own chapter with GenAI Studio, run them to the point of conflict, reconcile the disagreements yourself, test each agreement for false consensus against the seeded correlated-vs-diverse reviewer simulation (SEED = 464), then write your stopping rule as a decision plus the list of decisions you refuse to automate; 30–38 peer defense + adversarial questioning: the first Evidence Defenses run in compressed staging form (a tightened defense + rapid cross-examination), every non-defender asking at least one ledger-grounded question; 38–42 SRL synthesis + instructor accuracy lock: the lead states the room's conclusion and its uncertainty, and the instructor corrects any claim that survived challenge but is wrong before it can enter a ledger; 42–50 transfer + ledger + Claim Ticket: log the escalations, overrides, and stopping rule in the AI-management portfolio, draft the next-study agenda, and write the ticket.",
        "hands_on_activity": "Run your roles to conflict, catch one false consensus with the seeded simulation, write your stopping rule as a decision, and either defend (if staged today) or cross-examine a classmate's defense.",
        "practice": "📝 nb16 practice: given three agreeing AI outputs and one dissent, decide whether the agreement is confirmation or correlated error, and name the check that decides.",
        "discussion_prompt": "When did you overrule every AI role at once today, and what did you know that they did not?",
        "project_connection": "M15 advances and the defenses begin: the conflict log, the override record, and the stopping rule are core portfolio entries, and the first defenders perform in the drawn order.",
        "milestone_developed": "M15 — Release audit, final chapter, and AI-management portfolio, Book Milestone 12 v1 (dev; stopping rule + first defenses — TERMINAL Friday)",
        "milestone_work_time": "23 min (conflict-reconciliation lab) + 8 min (first defenses)",
        "milestone_presentation_review": "first Evidence Defenses (compressed staging) + cross-examination",
        "student_prep": "Audit gaps closed; chapter advanced; three weakest ledger rows prepped; defense order known.",
        "student_artifact": "Conflict-reconciliation + false-consensus log + stopping rule + delivered defense or logged cross-examination",
        "exit_ticket": "Claim Ticket #42: my stopping rule in one sentence — why here, and not one more check.",
        "homework_next_milestone": "Finish the final chapter, the AI-management portfolio, and the dossier. The remaining defenses and the release ceremony are Friday, when M15 is due — TERMINAL, no revision window.",
        "instructor_prep": "Defense rubrics per defender; timer; the cross-examination norms card; GenAI Studio roles live; the seeded reviewer simulation tested; confirm the drawn order.",
        "risks_contingency": "Five full-length defenses do not fit the two meetings → compressed staging splits them across today and Friday, and any defense needing full length gets an office-hours overflow slot the rubric notes; GenAI Studio API friction → the UI path and the provided cells are the fallback, and the reconciliation logic is graded, not the plumbing.",
    },
    # ------------------------------------------------------------------ M43
    {
        "meeting": 43, "date": "2026-12-11", "day": "Fri", "modality": "in-person",
        "unit": "Week 16 — Studio 12: Release and direct the next cycle",
        "title": "Studio Friday (terminal) — the final defenses and the release ceremony, M15 due",
        "driving_question": "You began with a curiosity and end with a released, defended, reproducible body of work. Does the evidence hold, is the run fresh, and is it in?",
        "secondary_questions": "Do the remaining defenses survive cross-examination? Is the dossier complete and every ledger closed as a record, not a summary? Can you say your stopping rule aloud — and what should the next study ask?",
        "inquiry": "all positions (synthesis)",
        "srl_slot": "",
        "srl_focus": "",
        "claim_permitted": "\"My release audit passed, my last cold run is not stale, my stopping rule is stated as a decision, and I can defend every claim from a verified ledger.\"",
        "claim_not_permitted": "\"The AI wrote my chapter\" (you directed, verified, and own it — or you did not, and the defense shows which).",
        "rdss_reading": "(no new reading — terminal studio; RDSS ch. 24 'Epilogue' offered as an optional send-off, not required; book.declaredesign.org)",
        "cb_reading": "",
        "other_material": "week16 quiz; nb16 student notebook (release and next cycle) §5 synthesis (Colab); project/final_dossier/evidence_defense_protocol.md (final defenses + the release checklist); course-reflection survey; M15 due tonight",
        "provenance": "evidence_defense_protocol.md + BOOK_STATIONS release-next-cycle close | S12 terminal unit | remaining Evidence Defenses + release ceremony as the terminal studio work block | adapted",
        "concepts": "the Evidence Defense under cross-examination; the release ceremony; the closed dossier and closed ledgers (complete records, not summaries); the AI-management portfolio (what was automated, escalated, and overridden); the stopping rule said aloud; the next-study agenda (a research cycle ends by declaring the next one); number-to-cell traceability; verification as a habit that outlasts the course",
        "python_r_dependency": "none (defenders may open the package live if probed)",
        "dataset_simulation": "each student's own chapter, dossier, ledgers, and AI-management portfolio",
        "minute_dynamic": "0–10 weekly topic quiz: five multiple-choice questions on the week's topic, answered solo on paper and handed in; 10–15 research stand-up: the AI decision you are proudest of overruling, one line each; 15–45 milestone kickoff + defense rounds: the instructor runs the release checklist one last time (stale-run status, the five audit parts, the dossier manifest), then the REMAINING EVIDENCE DEFENSES run as the work block in the drawn order (compressed staging so all five defenders fit across the two meetings), every non-defender asking at least one ledger-grounded question, and each defender closing with the stopping rule said aloud and the next-study agenda in one sentence; 45–50 revise, ledger, submit + Claim Ticket: submit M15 and confirm it on screen, take the reflection survey, and write the final Claim Ticket.",
        "hands_on_activity": "Deliver or cross-examine the final defenses, run a last stale-run and traceability spot-check on your own chapter, and release: submit M15.",
        "practice": "📝 (retrospective) the exit self-assessment: classify, match, bound, verify, release — rate yourself at the start of the semester versus now.",
        "discussion_prompt": "What claim did you believe at the start of the semester that you would now demand evidence for, and what evidence would satisfy you?",
        "project_connection": "M15 — the release audit, final chapter, closed dossier, and AI-management portfolio — is submitted; the semester's complete, defended, reproducible artifact leaves your hands pointing at its successor.",
        "milestone_developed": "M15 — Release audit, final chapter, and AI-management portfolio, Book Milestone 12 v1 (worked + due TONIGHT — TERMINAL, no revision window)",
        "milestone_work_time": "30 min studio block (final defenses + release ceremony)",
        "milestone_presentation_review": "the remaining Evidence Defenses ARE the presentation/review",
        "student_prep": "Chapter, dossier, and AI-management portfolio complete; package cold run fresh (not stale); ready to defend or cross-examine.",
        "student_artifact": "Delivered defense or logged cross-examination + submitted M15 + exit self-assessment + reflection survey",
        "exit_ticket": "Claim Ticket #43 (the last): one claim I will carry carefully for the rest of my life, and the evidence I hold it on.",
        "homework_next_milestone": "None. It is done. The next-study agenda you wrote is where the cycle reopens, whenever you choose. (Grades follow the posted rubric timeline.)",
        "instructor_prep": "Rubrics per remaining defender; the overflow slot in reserve; the strongest-defenses synthesis list; survey link live; submission mechanics confirmed; celebration logistics.",
        "risks_contingency": "A chapter misses the ceremony → the tonight deadline governs and the published late policy applies; a defense needs the full length → the office-hours overflow slot absorbs it before the deadline; a last-minute stale run → release with the rerun queued and DECLARED, never silently stale.",
    },
]
