#!/usr/bin/env python3
"""build_book_toc.py — the EN book TOC, generated from the manifest (D38).

D38 made the twelve Studios the book's twelve navigational parts: each
studio's generated page opens its part and the studio's lessons follow it,
in (studio rank, lesson rank) order. This generator owns the `chapters:`
block of book/_quarto.yml so the TOC can never disagree with
planning/BOOK_ARCHITECTURE.yml — the last hand-maintained ordering source
closes (Phase-2 critique, migration step 5).

The six former parts survive as non-navigational arcs (see the manifest's
`parts:` list and the "How this book is organized" page); they no longer
appear in the TOC.

    .venv/bin/python scripts/build_book_toc.py            # write
    .venv/bin/python scripts/build_book_toc.py --check    # CI: fresh?

NOTE: this generator deliberately does NOT call require_lock() — the
validator's own TOC check compares against this module's output, so
requiring the lock here would deadlock every TOC migration.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "scripts"))
from book_manifest import active_lessons, load_architecture  # noqa: E402

QUARTO_YML = REPO / "book" / "_quarto.yml"

# Front-of-book pages before the studios, in order.
FRONT = [
    "index.qmd",
    "author.qmd",
    "part1-research-with-ai/part1-overview.qmd",  # "How this book is organized"
]


def studio_page_rel(st: dict) -> str:
    return f"studios/studio{st['rank']:02d}-{st['id']}.qmd"


def render_chapters_block(arch: dict | None = None) -> str:
    """The full `  chapters:` block (manifest order), ending with a newline."""
    arch = arch or load_architecture()
    lessons = active_lessons(arch)
    by_station: dict[str, list[dict]] = {}
    for l in lessons:
        by_station.setdefault(l["station"], []).append(l)
    lines = [
        "  chapters:",
        "    # ---- generated by scripts/build_book_toc.py from",
        "    # ---- planning/BOOK_ARCHITECTURE.yml (D38) — edit the manifest",
        "    # ---- and rerun the generator; never hand-edit this block",
    ]
    for page in FRONT:
        lines.append(f"    - {page}")
    for st in sorted(arch["stations"], key=lambda s: s["rank"]):
        lines.append(f"    - part: {studio_page_rel(st)}")
        lines.append("      chapters:")
        for l in by_station.get(st["id"], []):   # already rank-ordered
            lines.append(f"        - {l['source']}")
    return "\n".join(lines) + "\n"


def render_file() -> str:
    text = QUARTO_YML.read_text()
    m = re.search(r"^  chapters:\n(?:.*\n)*?(?=^  appendices:)", text, re.M)
    if not m:
        sys.exit("✗ book/_quarto.yml: could not locate the chapters block "
                 "(expected `  chapters:` ... `  appendices:`)")
    return text[:m.start()] + render_chapters_block() + text[m.end():]


def main() -> int:
    check = "--check" in sys.argv
    new = render_file()
    if QUARTO_YML.read_text() == new:
        print("✓ book/_quarto.yml TOC is fresh")
        return 0
    if check:
        print("✗ book/_quarto.yml TOC is STALE — run scripts/build_book_toc.py")
        return 1
    QUARTO_YML.write_text(new)
    print("✓ book/_quarto.yml TOC regenerated from the manifest")
    return 0


if __name__ == "__main__":
    sys.exit(main())
