#!/usr/bin/env python3
"""build_meeting_schedule.py — serialize the 44×32 meeting schedule.

Reads the structured meeting data in scripts/schedule_data/ (authored from
planning/COURSE_MASTER_PLAN.md), validates it against the verified calendar
backbone (planning/CALENDAR_BACKBONE.csv, produced by validate_calendar.py),
and writes:

    planning/MEETING_SCHEDULE.csv   — 44 rows × 32 columns (brief §8)
    planning/MEETING_SCHEDULE.md    — the same content as readable per-meeting blocks

Run:  python3 scripts/build_meeting_schedule.py
Exit is non-zero if any invariant fails (row count, column set, date/day/modality
mismatch with the backbone, empty required fields), so it can gate commits.
"""
from __future__ import annotations

import csv
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "scripts"))

from schedule_data import COLUMNS, MEETINGS  # noqa: E402

BACKBONE = REPO / "planning" / "CALENDAR_BACKBONE.csv"
OUT_CSV = REPO / "planning" / "MEETING_SCHEDULE.csv"
OUT_MD = REPO / "planning" / "MEETING_SCHEDULE.md"

# Fields allowed to be empty (e.g., CB reading is optional by design).
OPTIONAL_EMPTY = {"cb_reading"}


def fail(msg: str) -> None:
    print(f"✗ {msg}")
    sys.exit(1)


def main() -> None:
    # --- validate against the backbone -------------------------------------
    with open(BACKBONE, newline="") as f:
        backbone = {int(r["meeting"]): r for r in csv.DictReader(f)}

    if len(MEETINGS) != 44:
        fail(f"expected 44 meetings, got {len(MEETINGS)}")
    if len(backbone) != 44:
        fail(f"backbone has {len(backbone)} rows, expected 44")

    for i, m in enumerate(MEETINGS, start=1):
        missing = [c for c in COLUMNS if c not in m]
        extra = [k for k in m if k not in COLUMNS]
        if missing:
            fail(f"meeting {i}: missing fields {missing}")
        if extra:
            fail(f"meeting {i}: unknown fields {extra}")
        if m["meeting"] != i:
            fail(f"row {i} carries meeting number {m['meeting']}")
        b = backbone[i]
        for k in ("date", "day", "modality"):
            if str(m[k]) != b[k]:
                fail(f"meeting {i}: {k} {m[k]!r} != backbone {b[k]!r}")
        for c in COLUMNS:
            if c not in OPTIONAL_EMPTY and str(m[c]).strip() == "":
                fail(f"meeting {i}: required field {c!r} is empty")

    # --- write CSV ----------------------------------------------------------
    with open(OUT_CSV, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=COLUMNS)
        w.writeheader()
        for m in MEETINGS:
            w.writerow({c: m[c] for c in COLUMNS})

    # --- write MD -----------------------------------------------------------
    labels = {
        "driving_question": "Driving question",
        "secondary_questions": "Secondary questions",
        "approach": "Approach",
        "claim_permitted": "Claim PERMITTED",
        "claim_not_permitted": "Claim NOT permitted",
        "rdss_reading": "RDSS reading",
        "cb_reading": "Calling Bullshit (optional)",
        "other_material": "Other material",
        "provenance": "Provenance",
        "concepts": "Concepts",
        "python_r_dependency": "Python dependency",
        "dataset_simulation": "Dataset / simulation",
        "minute_dynamic": "50-minute dynamic",
        "hands_on_activity": "Hands-on activity",
        "practice": "Practice",
        "discussion_prompt": "Discussion prompt",
        "project_connection": "Project connection",
        "milestone_developed": "Milestone developed",
        "milestone_work_time": "Milestone work time",
        "milestone_presentation_review": "Milestone presentation/review",
        "student_prep": "Student prep",
        "student_artifact": "Student artifact",
        "exit_ticket": "Exit ticket",
        "homework_next_milestone": "Homework / next milestone",
        "instructor_prep": "Instructor prep",
        "risks_contingency": "Risks / contingency",
    }

    lines = [
        "# HONR 46400 — Meeting Schedule (Fall 2026)",
        "",
        "Generated by `scripts/build_meeting_schedule.py` from `scripts/schedule_data/`.",
        "Machine-readable version: `planning/MEETING_SCHEDULE.csv` (44 rows × 32 columns).",
        "Dates verified against `planning/CALENDAR_BACKBONE.csv` (scripts/validate_calendar.py).",
        "",
    ]
    current_unit = None
    for m in MEETINGS:
        if m["unit"] != current_unit:
            current_unit = m["unit"]
            lines += [f"## {current_unit}", ""]
        lines += [
            f"### M{m['meeting']} — {m['day']} {m['date']} ({m['modality']}) — {m['title']}",
            "",
        ]
        for key, label in labels.items():
            val = str(m[key]).strip()
            if val:
                lines.append(f"- **{label}:** {val}")
        lines.append("")

    OUT_MD.write_text("\n".join(lines))

    n_async = sum(1 for m in MEETINGS if m["modality"] == "async-online")
    print(f"✓ {len(MEETINGS)} meetings × {len(COLUMNS)} columns validated against the backbone")
    print(f"✓ wrote {OUT_CSV.relative_to(REPO)}")
    print(f"✓ wrote {OUT_MD.relative_to(REPO)} ({n_async} async meetings)")


if __name__ == "__main__":
    main()
