#!/usr/bin/env python3
"""Build the standalone HONR 46400 course-schedule .docx.

A companion to scripts/build_syllabus_docx.py and a sibling of QM 47400's
scripts/build_schedule_docx.py, whose design this reproduces: landscape letter,
Purdue palette, a black header band in Old Gold, alternating week bands, a
heavier rule at each week boundary, shaded no-class rows, accent shading for the
marquee events, a repeating header row, a Final Project milestone table, and a
page footer.

QM474's version parses its own schedule.qmd, whose table is five columns. HONR's
schedule page is eight columns and is regenerated by a different script, so this
build takes its rows from the same place the syllabus .docx does - the shared
helpers in build_syllabus_docx - which keeps the two documents in agreement and
keeps both anchored to planning/MEETING_SCHEDULE.csv.

Run:  .venv/bin/python scripts/build_schedule_docx.py
"""
from __future__ import annotations

import sys
from datetime import date, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from docx import Document                                      # noqa: E402
from docx.enum.section import WD_ORIENT                        # noqa: E402
from docx.enum.table import WD_ALIGN_VERTICAL                  # noqa: E402
from docx.enum.text import WD_ALIGN_PARAGRAPH                  # noqa: E402
from docx.oxml import OxmlElement                              # noqa: E402
from docx.oxml.ns import qn                                    # noqa: E402
from docx.shared import Inches, Pt, RGBColor                   # noqa: E402

from build_syllabus_docx import (                              # noqa: E402
    MILESTONE_DUE, ROOT, build_schedule_rows, fmt_date)

OUT = (ROOT / "_syllabus" / "2026F"
       / "2026F_evidence_driven_research_HONR464_schedule.docx")

# ── Purdue palette (university-wide, not school-specific) ───────────────────
BLACK = "000000"
GOLD = RGBColor(0xCF, 0xB9, 0x91)      # Purdue Old Gold
BAND = "F7F5F1"                        # subtle warm band
NOCLASS = "EFEFEF"
ACCENT = "EFE7D6"                      # gold tint for the marquee events
GREY = RGBColor(0x76, 0x76, 0x76)
BROWN = RGBColor(0x8E, 0x76, 0x4C)
FONT = "Calibri"

TERM_START, TERM_END = date(2026, 8, 24), date(2026, 12, 11)
NO_CLASS_REASON = {
    "2026-09-07": "No class — Labor Day",
    "2026-10-12": "No class — October Break",
    "2026-11-18": "No class — the day after the Expo, to rest and catch up",
    "2026-11-25": "No class — Thanksgiving Break",
    "2026-11-27": "No class — Thanksgiving Break",
}

MILESTONE_TITLE = {
    1: "Curiosity committed and the research problem",
    2: "Your rules and your question",
    3: "Verified evidence and contribution map",
    4: "Research Contract v0 and permission determination",
    5: "Pathway declaration and mandated contrast (Contract v1)",
    6: "Data and measurement governance",
    7: "First reproducible analysis",
    8: "Robustness audit",
    9: "Bounded research note and claim-evidence table",
    10: "Venue contract and the publication-ready artifact",
    11: "Poster first draft",
    12: "Peer review submission",
    13: "Final poster lock (TERMINAL — no revision window)",
    14: "Go-public package: presentation plan and invitation",
    15: "Conference reflection",
    16: "Reproducible package and the peer cold run",
    17: "Release audit, final research chapter, and AI-management portfolio "
        "(TERMINAL — no revision window)",
}


# ── docx helpers (same techniques as QM474's generator) ─────────────────────
def shade(cell, hexcolor):
    el = OxmlElement("w:shd")
    el.set(qn("w:val"), "clear")
    el.set(qn("w:color"), "auto")
    el.set(qn("w:fill"), hexcolor)
    cell._tc.get_or_add_tcPr().append(el)


def set_cell_borders(cell, **kw):
    tcPr = cell._tc.get_or_add_tcPr()
    borders = tcPr.find(qn("w:tcBorders"))
    if borders is None:
        borders = OxmlElement("w:tcBorders")
        tcPr.append(borders)
    for edge, spec in kw.items():
        e = borders.find(qn("w:" + edge))
        if e is None:
            e = OxmlElement("w:" + edge)
            borders.append(e)
        for k, v in spec.items():
            e.set(qn("w:" + k), str(v))


def repeat_header(row):
    el = OxmlElement("w:tblHeader")
    el.set(qn("w:val"), "true")
    row._tr.get_or_add_trPr().append(el)


def cant_split(row):
    row._tr.get_or_add_trPr().append(OxmlElement("w:cantSplit"))


def set_table_cell_margins(table, top=60, start=90, bottom=60, end=90):
    mar = OxmlElement("w:tblCellMar")
    for name, val in (("top", top), ("start", start),
                      ("bottom", bottom), ("end", end)):
        n = OxmlElement("w:" + name)
        n.set(qn("w:w"), str(val))
        n.set(qn("w:type"), "dxa")
        mar.append(n)
    table._tbl.tblPr.append(mar)


def style_run(run, size=9, bold=False, italic=False, color=None):
    run.font.name = FONT
    run.font.size = Pt(size)
    run.bold = bold
    run.italic = italic
    if color is not None:
        run.font.color.rgb = color
    rPr = run._element.get_or_add_rPr()
    rFonts = rPr.find(qn("w:rFonts"))
    if rFonts is None:
        rFonts = OxmlElement("w:rFonts")
        rPr.append(rFonts)
    for a in ("w:ascii", "w:hAnsi", "w:cs", "w:eastAsia"):
        rFonts.set(qn(a), FONT)
    return run


def add_hyperlink(par, url, text, size=8):
    """A real external hyperlink.

    The run is created through python-docx's API and only then moved inside the
    w:hyperlink wrapper. Hand-building w:rPr risks an out-of-order child
    sequence, which makes Word prompt to repair the file.
    """
    r_id = par.part.relate_to(
        url,
        "http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink",
        is_external=True)
    run = par.add_run(text)
    style_run(run, size, color=RGBColor(0x1F, 0x4E, 0x79))
    run.font.underline = True
    link = OxmlElement("w:hyperlink")
    link.set(qn("r:id"), r_id)
    par._p.remove(run._element)
    link.append(run._element)
    par._p.append(link)


TWIPS_PER_INCH = 1440


def set_col_widths(table, fractions, total_inches=10.0):
    """Write real column widths.

    NOTE: `cell.width = ...` is a no-op in this python-docx version - it emits
    no w:tcW at all, leaving Word to use the tblGrid's equal columns. (QM474's
    schedule generator has the same latent bug, so its Topic column renders at
    20% instead of the 42% its WIDTHS list intends.) Writing tblW, the tblGrid,
    and every cell's tcW directly is what actually takes effect.
    """
    assert abs(sum(fractions) - 1.0) < 1e-9, fractions
    total = int(total_inches * TWIPS_PER_INCH)
    cols = [int(total * f) for f in fractions]
    cols[-1] = total - sum(cols[:-1])          # absorb rounding

    tblPr = table._tbl.tblPr
    for old in tblPr.findall(qn("w:tblW")):
        tblPr.remove(old)
    tblW = OxmlElement("w:tblW")
    tblW.set(qn("w:w"), str(total))
    tblW.set(qn("w:type"), "dxa")
    tblPr.append(tblW)

    grid = table._tbl.find(qn("w:tblGrid"))
    for gc, w in zip(grid.findall(qn("w:gridCol")), cols):
        gc.set(qn("w:w"), str(w))

    for row in table.rows:
        for cell, w in zip(row.cells, cols):
            tcPr = cell._tc.get_or_add_tcPr()
            for old in tcPr.findall(qn("w:tcW")):
                tcPr.remove(old)
            tcW = OxmlElement("w:tcW")
            tcW.set(qn("w:w"), str(w))
            tcW.set(qn("w:type"), "dxa")
            tcPr.append(tcW)


def tune(par, space_before=1, space_after=1, align=None):
    pf = par.paragraph_format
    pf.space_before = Pt(space_before)
    pf.space_after = Pt(space_after)
    pf.line_spacing = 1.0
    if align is not None:
        pf.alignment = align
    return par


def week_of_date(iso: str, rows) -> str:
    """The Wk label a no-class day belongs to: the week of the nearest meeting."""
    d = date.fromisoformat(iso)
    best, bestgap = "", 999
    for r in rows:
        gap = abs((date.fromisoformat(r["iso"]) - d).days)
        if gap < bestgap:
            best, bestgap = r["wk"], gap
    return best


def all_rows():
    """Meetings plus the term's no-class MWF days, in date order.

    The no-class days are DERIVED - every Monday, Wednesday, and Friday between
    the first and last meeting that the schedule does not cover - rather than
    typed from memory, so the printed schedule cannot disagree with the calendar.
    """
    rows = build_schedule_rows()
    covered = {r["iso"] for r in rows}
    d = TERM_START
    while d <= TERM_END:
        iso = d.isoformat()
        if d.weekday() in (0, 2, 4) and iso not in covered:
            reason = NO_CLASS_REASON.get(iso)
            if reason is None:
                raise SystemExit(
                    f"✗ {iso} is an uncovered class day with no recorded reason; "
                    f"add it to NO_CLASS_REASON or fix MEETING_SCHEDULE.csv")
            rows.append({"wk": "", "date": fmt_date(iso), "topic": reason,
                         "nb": "—", "nb_url": None, "note": "",
                         "iso": iso, "noclass": True})
        d += timedelta(days=1)
    rows.sort(key=lambda r: (r["iso"], r["topic"].startswith("PURDUE")))
    for r in rows:
        r.setdefault("noclass", False)
        if not r["wk"]:
            r["wk"] = week_of_date(r["iso"], build_schedule_rows())
    return rows


def main():
    rows = all_rows()
    doc = Document()

    st = doc.styles["Normal"]
    st.font.name = FONT
    st.font.size = Pt(10)
    st.element.rPr.rFonts.set(qn("w:eastAsia"), FONT)

    sec = doc.sections[0]
    sec.orientation = WD_ORIENT.LANDSCAPE
    sec.page_width, sec.page_height = Inches(11), Inches(8.5)
    sec.left_margin = sec.right_margin = Inches(0.5)
    sec.top_margin = Inches(0.45)
    sec.bottom_margin = Inches(0.45)

    # ── title block ─────────────────────────────────────────────────────────
    p = tune(doc.add_paragraph(), 0, 0)
    style_run(p.add_run("HONR 46400 · Evidence-Driven Research"), 20, bold=True)
    p = tune(doc.add_paragraph(), 1, 0)
    style_run(p.add_run("Course Schedule · Fall 2026"), 13, bold=True, color=BROWN)
    p = tune(doc.add_paragraph(), 2, 8)
    style_run(p.add_run(
        "John Martinson Honors College, Purdue University   ·   "
        "Professor Davi Moreira   ·   Section 002, Monday / Wednesday / Friday, "
        "1:30–2:20 p.m., HCRS-1054   ·   August 24 – December 11, 2026"),
        9, color=GREY)

    # ── main schedule table ─────────────────────────────────────────────────
    widths = [0.05, 0.105, 0.42, 0.125, 0.30]
    assert abs(sum(widths) - 1.0) < 1e-9
    header = ["Wk", "Date", "Topic", "Notebook", "Assessment / Notes"]

    tbl = doc.add_table(rows=1, cols=5)
    tbl.style = "Table Grid"
    tbl.autofit = False
    tbl.allow_autofit = False
    set_table_cell_margins(tbl)

    hdr = tbl.rows[0]
    repeat_header(hdr)
    cant_split(hdr)
    for i, label in enumerate(header):
        cell = hdr.cells[i]
        cell.vertical_alignment = WD_ALIGN_VERTICAL.CENTER
        shade(cell, BLACK)
        par = tune(cell.paragraphs[0], 3, 3,
                   WD_ALIGN_PARAGRAPH.CENTER if i in (0, 3)
                   else WD_ALIGN_PARAGRAPH.LEFT)
        style_run(par.add_run(label), 9.5, bold=True, color=GOLD)

    prev_wk = None
    for r in rows:
        row = tbl.add_row()
        cant_split(row)
        marquee = r["topic"].startswith("PURDUE") or "TERMINAL" in r["note"]
        band = r["wk"].isdigit() and int(r["wk"]) % 2 == 0
        fill = (ACCENT if marquee
                else NOCLASS if r["noclass"]
                else BAND if band else None)
        new_week = r["wk"] != prev_wk

        for i, raw in enumerate((r["wk"], r["date"], r["topic"], r["nb"],
                                 r["note"])):
            cell = row.cells[i]
            cell.vertical_alignment = WD_ALIGN_VERTICAL.TOP
            if fill:
                shade(cell, fill)
            if new_week:
                set_cell_borders(cell, top={"val": "single", "sz": 12,
                                            "color": "BFB39A"})
            par = tune(cell.paragraphs[0], 2, 2,
                       WD_ALIGN_PARAGRAPH.CENTER if i in (0, 3)
                       else WD_ALIGN_PARAGRAPH.LEFT)
            if i == 3:
                if r["nb_url"]:
                    style_run(par.add_run(r["nb"].split()[0]), 9.5, bold=True)
                    par.add_run().add_break()
                    add_hyperlink(par, r["nb_url"], "Open in Colab", size=8)
                else:
                    style_run(par.add_run("—"), 9, color=GREY)
            elif r["noclass"]:
                style_run(par.add_run(raw), 9, italic=(i == 2), color=GREY)
            else:
                style_run(par.add_run(raw), 9,
                          bold=(marquee and i in (1, 4)))
        prev_wk = r["wk"]

    set_col_widths(tbl, widths)

    # ── Final Project milestone table ───────────────────────────────────────
    p = tune(doc.add_paragraph(), 14, 2)
    style_run(p.add_run("Final Project Milestones"), 13, bold=True)
    p = tune(doc.add_paragraph(), 0, 6)
    style_run(p.add_run(
        "The seventeen milestones are the Milestone Deliverables item of the "
        "Final Project. Friday milestones are submitted in the studio; M11 is "
        "due at class on a Wednesday, and M13 and M15 fall on Sundays at "
        "11:59 PM. The final poster lock is pinned to Sun Nov 8, nine days "
        "before the conference and shared with QM 47400's print run. M13 and "
        "M17 are terminal: no revision window."), 9, color=GREY)

    m_tbl = doc.add_table(rows=1, cols=3)
    m_tbl.style = "Table Grid"
    m_tbl.autofit = False
    m_tbl.allow_autofit = False
    set_table_cell_margins(m_tbl)
    m_widths = [0.08, 0.62, 0.30]

    mh = m_tbl.rows[0]
    repeat_header(mh)
    cant_split(mh)
    for i, label in enumerate(("#", "Milestone", "Due")):
        cell = mh.cells[i]
        cell.vertical_alignment = WD_ALIGN_VERTICAL.CENTER
        shade(cell, BLACK)
        par = tune(cell.paragraphs[0], 3, 3,
                   WD_ALIGN_PARAGRAPH.CENTER if i == 0
                   else WD_ALIGN_PARAGRAPH.LEFT)
        style_run(par.add_run(label), 9.5, bold=True, color=GOLD)

    entries = [(f"M{n}", MILESTONE_TITLE[n], fmt_date(MILESTONE_DUE[n]))
               for n in sorted(MILESTONE_TITLE)]
    entries.insert(13, ("—", "Purdue Fall Undergraduate Research Expo "
                             "(required poster presentation)", "Tue Nov 17"))
    for idx, (num, name, due) in enumerate(entries):
        row = m_tbl.add_row()
        cant_split(row)
        key = num == "—" or "TERMINAL" in name
        for i, raw in enumerate((num, name, due)):
            cell = row.cells[i]
            cell.vertical_alignment = WD_ALIGN_VERTICAL.TOP
            if key:
                shade(cell, ACCENT)
            elif idx % 2 == 0:
                shade(cell, BAND)
            par = tune(cell.paragraphs[0], 2, 2,
                       WD_ALIGN_PARAGRAPH.CENTER if i == 0
                       else WD_ALIGN_PARAGRAPH.LEFT)
            style_run(par.add_run(raw), 9, bold=key)
    set_col_widths(m_tbl, m_widths)

    p = tune(doc.add_paragraph(), 10, 0)
    style_run(p.add_run(
        "Subject to change. While I will try to adhere to the course schedule "
        "as much as possible, I also want to adapt to your learning pace and "
        "style; the syllabus and course plan may change during the term. The "
        "official source of record is the course Brightspace page."),
        8.5, italic=True, color=GREY)

    # ── footer with page numbers ────────────────────────────────────────────
    fp = sec.footer.paragraphs[0]
    fp.alignment = WD_ALIGN_PARAGRAPH.CENTER
    style_run(fp.add_run("HONR 46400 · Evidence-Driven Research · Fall 2026 "
                         "· Page "), 8, color=GREY)
    fld = OxmlElement("w:fldSimple")
    fld.set(qn("w:instr"), "PAGE")
    fp._p.append(fld)
    style_run(fp.add_run(" of "), 8, color=GREY)
    fld = OxmlElement("w:fldSimple")
    fld.set(qn("w:instr"), "NUMPAGES")
    fp._p.append(fld)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    doc.save(OUT)
    meetings = sum(1 for r in rows if not r["noclass"])
    noclass = sum(1 for r in rows if r["noclass"])
    print(f"✓ {OUT.relative_to(ROOT)}")
    print(f"  {meetings} sessions + {noclass} no-class days = {len(rows)} rows; "
          f"{len(entries)} milestone entries")


if __name__ == "__main__":
    main()
